### ISSUE TITLE
Is it possible to capture a route parameter which contains slashes?

### ISSUE THREAD

**Issue by barrucadu** [haskell-servant/servant#1000]
I'm trying to translate a Ruby application into Servant for my own learning, and the Ruby application makes use of routes like `/api/content(/*path_without_root)`.  That `path_without_root` parameter is an arbitrary path, containing slashes.

I have this Servant route: `"api" :> "content" :> Capture "path" String :> Get '[JSON] ()`, which matches `/api/content/foo`, but doesn't match `/api/content/foo/bar`.

Is it possible to capture a route parameter which contains slashes?

**Comment by alpmestan** [comment]
Would [`CaptureAll`](https://hackage.haskell.org/package/servant-0.14/docs/Servant-API-Capture.html#t:CaptureAll) work for your use case? You would do something like:

``` haskell
type API = "api" :> "content" :> CaptureAll "path" Text :> Get '[JSON] Foo
```

and the corresponding handler (respectively client) would get a `[Text]` argument in this case, containing the rest of the path after "content". For `/api/content/foo` you'd get `["foo"]`, for `/api/content/foo/bar` you'd get ["foo", "bar"], etc. Of course you cannot use another static string or `Capture` after this one, for a given endpoint's description. Something that would allow that is discussed in https://github.com/haskell-servant/servant/issues/962 but we don't have an implementation.

**Comment by barrucadu** [comment]
I think `CaptureAll` is just what I need, thanks
