### ISSUE TITLE
Is there a way to generate client functions that return a raw Response?

### ISSUE THREAD

**Issue by neongreen** [haskell-servant/servant#1004]
With servant-client, I can generate functions like these:

```
postNewBook :: Book -> ClientM Book
getAllBooks :: ClientM [Book]
(getAllBooks :<|> postNewBook) = client myApi
```

However, I want to use those functions in a testsuite, and I need to get status codes back and optionally raw data. So, I want the generated functions to be more low-level and give me back more than just the response body. For instance:

```
postNewBook :: Book -> ClientM Response         -- or GenResponse Book
getAllBooks :: ClientM [Book]                   -- or GenResponse [Book]
(getAllBooks :<|> postNewBook) = clientRaw myApi
```

Of course, getting all the metadata and the raw body *and* the parsed response would be even better.

Is there a way to get what I want? Or a good reason why servant-client doesn't support this?

**Comment by alpmestan** [comment]
You could I suppose write a type family that turns all the `Get`s, `Post`s, etc (all `Verb`s) into `Raw`s. A client for a Raw endpoint returns the raw `Response`. But then you basically "forget" that the response body should be a `Book` or `[Book]`. So this probably would require some new code in servant-client-core.

**Comment by alpmestan** [comment]
@neongreen I suspect you can actually achieve this "out of the box" with `Servant.Client.Free`, see [this new cookbook recipe](https://haskell-servant.readthedocs.io/en/latest/cookbook/using-free-client/UsingFreeClient.html).

**Comment by alpmestan** [comment]
Did you get a chance to try out this approach?

**Comment by neongreen** [comment]
Nope, sorry. I get how to use it, but manually making requests and handling branches of `ClientF` seems a bit too DIY and not worth it for our usecase (just six endpoints) anyway.

**Comment by alpmestan** [comment]
Right, even though I think you can get away with very very little boilerplate here. Anyway, feel free to reopen later if you're not satisfied with your current solution.
