### ISSUE TITLE
How to "lift" serveDirectoryFileServer to custom monad?

### ISSUE THREAD

**Issue by saurabhnanda** [haskell-servant/servant#1012]
I've been struggling to compose a set of routes, which are in `AppM`, with the static/raw file-server provided by servant. The new `hoistServer` function is structured in such a way that all the routes passed to it should be in the same monad. Therefore, how do I "lift" a static-server to my custom `AppM` monad.

Here's my attempt, which doesn't type-check -- https://gist.github.com/saurabhnanda/99f5f471427c8b50f438ca8775f76220

**Comment by phadej** [comment]
you got your `Proxy`-ies wrong:

```haskell
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE DataKinds, TypeOperators #-}
module AppServer2 where

import Servant.Server as Servant
import Network.Wai
import Data.Proxy
import Servant.API
import Servant.Server.StaticFiles

newtype AppM a = AppM (Servant.Handler a)

type API = "lambda" :> "assets" :> Raw

appmToServantM :: forall a. AppM a  -> Servant.Handler a
appmToServantM appm = undefined

staticFileServer :: ServerT API AppM
staticFileServer = serveDirectoryFileServer "dist"

-- Note: Those take API as a proxy, not a (ServerT API AppM)
app :: Application
app = serve (Proxy :: Proxy API) $ hoistServer (Proxy :: Proxy API) appmToServantM staticFileServer
```

**Comment by saurabhnanda** [comment]
Thanks a lot! This works. And I feel like kicking myself for making such a mistake 😞

**Comment by phadej** [comment]
@saurabhnanda no worries, blackouts and freezes happen to everyone.
