### ISSUE TITLE
Questions about the safe-links API based off of servant-generic

### ISSUE THREAD

**Issue by saurabhnanda** [haskell-servant/servant#1013]
I'm trying to implement "safe links" in my app after upgrading to servant-0.14.x, which has merged servant-generic. I'm following https://haskell-servant.readthedocs.io/en/stable/cookbook/generic/Generic.html

After defining `links` as under...

```
links :: Routes (AsLink Link)
links = allFieldLinks
```

...here's how I am generating links to embed into server-generated HTML:

```
linkURI ((rGetFlexiPayment links) (PK fid))
```

Here's what I'm wondering:

- Why does the safe-link function return a `Link` value, and not a `URI` value directly? What kind of processing is possible on a `Link` value that is not possible on a `URI` value? Is there any way to get functions that directly generate `URI`s instead of `Link`s?
- Why does the generated URI not have a preceding forward-slash (`/`)? Here's what I'm seeing:

    ```
    ghci> show $ linkURI ((rGetFlexiPayment links) (PK 10))
    "lambda/plugins/flexipayment/admin/bookings/10"
    ```

- Is there an existing function that can generate safe-link functions via TH, so that the following is possible? (If not, is a PR to add this functionality acceptable?)

    ```
    $(generateSafeLinks ''Routes)
    
    -- can be used as:
    rGetFlexiPayment (PK 10)
   ```

**Comment by saurabhnanda** [comment]
Last point is related to https://github.com/alpmestan/servant/issues/17

**Comment by alpmestan** [comment]
Right, this old QuasiQuote was a fun little experiment by jkarni but it didn't really stand the test of time and I think Julian just thought it wasn't worth keeping around at some point.

Regarding your actual problem:

> Why does the safe-link function return a Link value, and not a URI value directly? What kind of processing is possible on a Link value that is not possible on a URI value? Is there any way to get functions that directly generate URIs instead of Links?

The answer to this lies in [the haddocks for the `Link` data type](https://hackage.haskell.org/package/servant-0.14.1/docs/Servant-Links.html#t:Link): _A safe link datatype. The only way of constructing a Link is using safeLink, which means any Link is guaranteed to be part of the mentioned API._

An URI you could get from anywhere, but a `Link` is just always going to be valid. Always.

> Why does the generated URI not have a preceding forward-slash (/)?

Well, some people want it, some people don't, and it's in a way easier to add it than remove it. It's quite trivial to specify your own little "postprocessing" of links to automate this though. There's `safeLink'` and `allLinks'` which let you specify a function `Link -> a` to be applied to all "final" links generated by the `safeLink` machinery. You could use this to add your missing `/`s, convert `Link` to some other `URI` type than the one we support out of the box, and all sorts of things I haven't thought about.

> Is there an existing function that can generate safe-link functions via TH, so that the following is possible? (If not, is a PR to add this functionality acceptable?)

No we don't have that. However, given that we already have this functionality without TH, why would you be interested in a solution that does use TH?

**Comment by phadej** [comment]
Note the [allFieldsLinks'](http://hackage.haskell.org/package/servant-0.14.1/docs/Servant-Links.html#v:allFieldLinks')

```haskell
allFieldLinks' :: ... => (Link -> a) -> routes (AsLink a)
```

If through your application you use `URI`, you can use `allFieldLinks' linkURI`. If you happen to use `lucid`, use [`safeLink_`](http://hackage.haskell.org/package/servant-lucid-0.8.1/docs/Lucid-Servant.html#v:linkHref_) (and its variants) from `servant-lucid` (then you'll get an `Attribute`).

Forward slash is omitted because in general the "baseurl" also may or may not end with a slash too, so *not* having it at the other end makes concatenating simpler (if both had slashes, than we'd need to remove one - now we only need be careful to add one if needed  - that's what `servant-lucid` does).

I think the TH case is unneeded if you use allFieldLinks' and `RecordWildCards`, I haven't tried though.

**Comment by saurabhnanda** [comment]
I've run into another issue. I'm writing a bunch of routes for an existing Rails app which serves user-uploaded images (basically the popular Paperclip gem).

Once you upload a photo, the file is saved in the following directory:

```
system/images/<chunk1>/<chunk2>/<chunk3>/<fingerprint>/<photo-style>/<filename>
```

where

- chunk1, chunk2, chunk3 are are prepared by converting the photo's primary key into a zero-padded string of 9-chars and splitting it into chunks of 3. For example:
  - 4567 will be (000, 004, 567)
- fingerprint is the md5sum of the image, which is stored in the DB when the file is uploaded
- photo-style can be configured by the programmer. Paperclip processes the original image into each of these styles and stores resulting images in different folders.

I want to have a function to which I pass the following tuple - `(PhotoId, Filename, Fingerprint, Style)` and I get the final path/URL. I tried the following...

```
data Routes route = Rouates
  {
    rDbPhoo :: route :- "system" :> "images" :> Capture "photoEssentials" (PhotoId, Filename, Fingerprint, Style) :> Get '[Text] ()
  } deriving (Generic)

instance ToHttpApiData (PhotoEssentials, Photo.Style) where
  toUrlPiece (PK photoId, fname, fprint, style_) =
    T.intercalate "/" $ buildChunks ++ [fprint, toText style_, fname]
    where
      buildChunks = (chunksOf 3 $ toS $ leftPadZeros $ show photoId)
      leftPadZeros s = (Prelude.replicate (9 - (Prelude.length s)) '0') ++ s

links :: Routes (AsLink URI)
links = allFieldLinks' linkURI
```

... but end-up with a URL-encoded version of the path, i.e...

```
ghci> (rDbPhoo links) (PK 30, "test.jpg", "3489379734324", Logo)
system/images/000%2F000%2F030%2F3489379734324%2Flogo%2Ftest.jpg
```

I tried defining the `toEncodedUrlPiece` function from the `ToHttpApiData` type-class, but even that didn't help.

How can I do this via the interface provided by servant-client?

**Comment by phadej** [comment]
### RecordWildCards

```haskell
λ *Main> :t routesLinks  -- was created by allFieldLinks
routesLinks :: Routes (AsLink Link)
λ *Main> :set -XRecordWildCards 
λ *Main> Routes {..} = routesLinks 
λ *Main> :t _get
_get :: Int -> Link
```

### Not using allFieldLinks at all

```haskell
fieldHref_
    :: ( HasLink endpoint, IsElem endpoint (ToServantApi routes)
       , GenericServant routes AsApi
       )
    => (routes AsApi -> endpoint)
    -> MkLink endpoint Attribute
fieldHref_ = fieldLink' linkAbsHref_
```

This is not in `servant-lucid` as there are too much options (absolute, relative some other baseurl)

then your lucid markup would look like

```haskell
p_ $ a_ [ fieldHref_ myRoute param1 param2 ] "link text"
```

**Comment by phadej** [comment]
About another issue: one issue per GH issue. Won't answer here.

**Comment by alpmestan** [comment]
@saurabhnanda Does this answer your questions?

**Comment by saurabhnanda** [comment]
@phadej @alpmestan I believe it does. I have gone on another tangent wrt Haddocks and will come back to this shortly. Closing this issue till then. I will reopen if I have any more questions.

Thanks for the help!

**Comment by saurabhnanda** [comment]
Okay, I'm back to this problem now. 

Not completely convinced with the design decision related to the following ..

>> Why does the generated URI not have a preceding forward-slash (/)?

> Well, some people want it, some people don't, and it's in a way easier to add it than remove it. It's quite trivial to specify your own little "postprocessing" of links to automate this though. There's safeLink' and allLinks' which let you specify a function Link -> a to be applied to all "final" links generated by the safeLink machinery. You could use this to add your missing /s, convert Link to some other URI type than the one we support out of the box, and all sorts of things I haven't thought about.

Implementing a custom function to replace `linkURI` is definitely possible, as such:

```
links :: Routes (AsLink URI)
links = allFieldLinks' myLinkURI
```

... but please consider the **default** behaviour of `linkURI` function, where it doesn't add the preceding `/`. Here's my reasoning to why this is probably not correct:

- `linkURI` returns a [`URI`](https://www.stackage.org/haddock/lts-12.1/servant-0.14.1/Servant-Links.html#t:URI), which is documented as such:

![screenshot 2018-09-10 17 18 21](https://user-images.githubusercontent.com/28369/45295789-8bdd1100-b51d-11e8-9a65-427773d0a3b9.png)

- it **expects** the `uriPath` to have a preceding slash.  
- it **doesn't expect the** `uriAuthority` to have a trailing slash.
- So, the default `linkURI` seems to be constructing malformed `URI` values.
- if one wanted to re-use the code already written in `linkURI`, one is forced to modify the `uriAuthority` **and** the `uriPath` fields, instead of simply doing something like:

```
links :: Routes (AsLink URI)
links = allFieldLinks' (\x -> (linkURI x) { uriAuthority = "www.mydomain.com" })
```

Again, I'll reiterate, given the flexibility that the API provides, I can write whatever I want. Just wanted to add my 2-cents about the **default** behaviour of the API.

**Comment by phadej** [comment]
```haskell
λ Network.URI> uriPath <$> parseURI "http://example.com"
Just ""
```

An example is not a spec. Without proper specification (i.e. spelled out *Invariants* or better `check` / `validate`function), it's only a *spec*ulation :)

**Comment by phadej** [comment]
I think @alpmestan answered the question. (to add, why not `URI`: because we don't know host, port nor scheme)
