### ISSUE TITLE
Generic + Nested records

### ISSUE THREAD

**Issue by mitchellwrosen** [haskell-servant/servant#1015]
Hello! I'd like some advice on how to write a nested record suitable for a servant servant and client. Is it possible? Here's what I've discovered so far.

Preamble.

```haskell
{-# LANGUAGE DataKinds, DeriveGeneric, TypeOperators #-}

import Servant
import Servant.API.Generic
import Servant.Client
import Servant.Client.Generic
import Servant.Server.Generic
```

Outer API type: has a route, plus a nested API type (Inner).

```haskell
data Outer route = Outer
  { outer :: route :- Get '[JSON] ()
  , inner :: route :- ToServant Inner AsApi
  } deriving Generic
```

Inner API type with a couple routes.

```haskell
data Inner route = Inner
  { foo :: route :- Get '[JSON] ()
  , bar :: route :- Get '[JSON] ()
  } deriving Generic
```

Generating a server works, but note we have to call `genericServer` on the inner record as well. It would be great to only have to call this once.

```haskell
outerServer :: ToServant Outer AsServer
outerServer =
  genericServer Outer
    { outer = pure ()
    , inner = genericServer Inner
        { foo = pure ()
        , bar = pure ()
        }
    }
```

Generating a client does not work so well. I have to match the inner client with `:<|>`, which means reverse-engineering the nesting that `genericClient` makes.

```haskell
callOuter :: ClientM ()
callInnerFoo :: ClientM ()
callInnerBar :: ClientM ()
Outer
  { outer = callOuter
  , inner = callInnerFoo :<|> callInnerBar
  } = genericClient
```

Unfortunately this nested record type (my first attempt) does not work.

```haskell
data Outer route = Outer
  { outer :: route :- Get '[JSON] ()
  , inner :: Inner route
  } deriving Generic
```

With this we can generate a nice server (note: only call to `genericServer`).

```haskell
outerServer :: ToServant Outer AsServer
outerServer =
  genericServer Outer
    { outer = pure ()
    , inner = Inner
        { foo = pure ()
        , bar = pure ()
        }
    }
```

However, I'm unable to call `genericClient` at this type due to the equality constraints.

```haskell
callOuter :: ClientM ()
Outer callOuter _ = genericClient
```
```haskell
    • Couldn't match type ‘Client ClientM (Inner AsApi)’
                     with ‘Inner (AsClientT ClientM)’
        arising from a use of ‘genericClient’
    • In the expression: genericClient
      In a pattern binding: Outer callOuter _ = genericClient
   |
64 | Outer callOuter _ = genericClient
   |                     ^^^^^^^^^^^^^
```

**Comment by alpmestan** [comment]
IIRC @domenkozar and I figured this out a few months back. Domen, any chance you still have some code/gist/etc around?

**Comment by alpmestan** [comment]
Thanks! :)

@mitchellwrosen For reference, the records that specify the endpoints that the clients linked to above target are [here](https://github.com/cachix/cachix/blob/master/cachix-api/src/Cachix/Api.hs).

**Comment by alpmestan** [comment]
Should we leave this open, as a reminder that there's still a bit of boilerplate needed? Might be nice to document it on readthedocs (in the cookbook recipe I suppose) too.

**Comment by seanhess** [comment]
Does anyone have an example of how to do this for servant-server? The linked example only shows a client.

**Comment by mitchellwrosen** [comment]
@seanhess Yeah, see my original comment (though there might be a better way).

```haskell
outerServer :: ToServant Outer AsServer
outerServer =
  genericServer Outer
    { outer = pure ()
    , inner = Inner
        { foo = pure ()
        , bar = pure ()
        }
    }
```

**Comment by alpmestan** [comment]
@mitchellwrosen @domenkozar Would either of you perhaps be interested in augmenting the cookbook recipe about the records+generic based approach, to document how nesting should be handled?

**Comment by seanhess** [comment]
Thanks @mitchellwrosen, hi @alpmestan! 

I’ve managed to follow your example to get a value of ToServant Outer (AsServerT AppM) — where AppM is my monad stack, but I’m still struggling to get serve / hoistServer to work. 

It looks like the Proxy should be Proxy (Outer routes) right? 

What should these lines look like? It used to be working for a non generic API. 

serve (Proxy :: ?) $ hoistServer (Proxy :: ?) nt outer 

Where outer is ToServant Outer (AsServerT AppM) and nt is my natural transformation function. 

Sorry for the formatting I’m on my phone. And thanks! A working example with generics and ServerT would be amazing

**Comment by alpmestan** [comment]
Does the following work?

``` haskell
type API = ToServant Outer AsApi
...
serve (Proxy :: Proxy API) $ hoistServer (Proxy :: Proxy API) nt outer
```

?

The idea is that we have different ways to traverse the records and collect the information we want on each endpoint. One per way to interpret APIs. `AsApi` instructs that `ToServant` type level computation to look at the `Outer` record and compile all the "endpoint types" into a single equivalent API type, expressed using `:<|>` to join the different endpoints together.

**Comment by seanhess** [comment]
That works, and makes sense, thank you @alpmestan!

Here's a working example for anyone arriving here later (missing imports and function bodies, but it should be enough). 

```


data BaseApi route = BaseApi
    { _info ::     route :- Get '[JSON] Text
    , _accounts :: route :- "accounts" :> ToServantApi AccountsApi -- Get '[JSON] Text
    } deriving (Generic)





data AccountsApi route = AccountsApi
    { _all :: route :- Get '[JSON] [Account]
    , _post :: route :- ReqBody '[JSON] AccountInfo :> Post '[JSON] Account
    , _get :: route :- Capture "id" Text :> Get '[JSON] Account
    , _put :: route :- Capture "id" Text :> ReqBody '[JSON] AccountInfo :> Put '[JSON] Account
    } deriving (Generic)

accountsApi :: ToServant AccountsApi (AsServerT AppM)
accountsApi = genericServerT AccountsApi
    { _all  = undefined
    , _post = undefined
    , _get  = undefined
    , _put  = \i a -> runState $ saveAccount i a
    }


baseApi :: ToServant BaseApi (AsServerT AppM)
baseApi = genericServerT BaseApi
    { _info = pure "hello"
    , _accounts = accountsApi
    }


type AppM = ReaderT AppState Handler


nt :: AppState -> AppM a -> Handler a
nt s x = runReaderT x s


baseApi :: ToServant BaseApi (AsServerT AppM)
baseApi = genericServerT BaseApi
    { _info = asks appMessage
    , _accounts = accountsApi
    }


apiProxy :: Proxy (ToServant BaseApi AsApi)
apiProxy = Proxy


application :: AppState -> Application
application st = do
    serve apiProxy $ hoistServer apiProxy (nt st) baseApi

```

**Comment by phadej** [comment]
These should be really added to the cookbook, don't leave it here buried in the comments.

**Comment by gelisam** [comment]
The ViewPattern trick described [above](https://github.com/haskell-servant/servant/issues/1015#issuecomment-407468389)  by my colleague @mitchellwrosen only works when `Inner` is directly inside `Outer`. For example, if there is a `Capture` in between, like this:

```haskell
data Outer route = Outer
  { outer :: route :- Get '[JSON] ()
  , inner :: route :- Capture "x" Int :> ToServant Inner AsApi
  } deriving Generic
```

Then one might hope that `callInnerFoo` and `callInnerBar` will now take an extra `Int` argument:

```haskell
callOuter :: ClientM ()
callInnerFoo :: Int -> ClientM ()
callInnerBar :: Int -> ClientM ()
Outer
  { outer = callOuter
  , inner =
      fromServant @_ @(AsClientT ClientM) ->
        Inner
          { foo = callInnerFoo
          , bar = callInnerBar
          }
  } = genericClient
```

Unfortunately we instead get a type error, because `inner (genericClient @Outer)` now has type `Capture "id" Int :> ToServant Inner AsApi`, not `ToServant Inner AsApi`, and thus we cannot use `fromServant @Inner @(AsClientT ClientM)` to transform it into an `Inner (AsClientT ClientM)`.

Instead of that trick, I've had a much better experience using my other colleague @asivitz's variant of @divarvel's [blog post](https://blog.clement.delafargue.name/posts/2019-09-10-a-new-tale-of-servant-clients.html), like this:

```haskell
-- Given a client for a (ToServantApi record) and a field of that record,
-- get a client for the part of the API inside that field
(//) :: ((mode ~ AsClientT m), GenericServant record mode)
     => ToServant record mode
     -> (record mode -> a)
     -> a
client // field = field (fromServant client)
infixl 1 //

-- Fill-in a parameter, e.g. a Capture
(/:) :: (a -> b -> c)
     -> b
     -> a -> c
(/:) = flip
infixl 2 /:

type OuterClient = Client ClientM (ToServantApi Outer)
type InnerClient = Client ClientM (ToServantApi Inner)

outerClient :: OuterClient
outerClient = client (genericApi (Proxy @Outer))

innerClient :: OuterClient -> Int -> InnerClient
innerClient client x = client // inner /: x

callOuter :: OuterClient -> ClientM ()
callOuter client = client // outer

callInnerFoo :: OuterClient -> Int -> ClientM ()
callInnerFoo client x = client // inner /: x // foo

callInnerBar :: OuterClient -> Int -> ClientM ()
callInnerBar client x = client // inner /: x // bar
```

So if something should be added to the cookbook, that's the trick I recommend adding! Better yet, how about including `(//)` and `(/:)` in servant-client itself?

**Comment by tchoutri** [comment]
@gelisam As of 0.19, these two helpers have been integrated in the Servant API https://github.com/haskell-servant/servant/blob/cdd7c34add589fccd52d59047c1a0a8578a3b5f0/servant/CHANGELOG.md?q=%22(%2F%3A)%22#019

**Comment by arianvp** [comment]
Can we close this?

**Comment by alpmestan** [comment]
Yes, I think we all agree that we have a pretty satisfactory solution to this problem now.
