### ISSUE TITLE
How to emit a "url piece" that already has forward-slashes in it?

### ISSUE THREAD

**Issue by saurabhnanda** [haskell-servant/servant#1016]
Following up from https://github.com/haskell-servant/servant/issues/1013#issuecomment-407251814

I'm writing a bunch of routes for an existing Rails app which serves user-uploaded images (basically the popular Paperclip gem).

Once you upload a photo, the file is saved in the following directory:

```
system/images/<chunk1>/<chunk2>/<chunk3>/<fingerprint>/<photo-style>/<filename>
```

where

- chunk1, chunk2, chunk3 are are prepared by converting the photo's primary key into a zero-padded string of 9-chars and splitting it into chunks of 3. For example:
  - 4567 will be (000, 004, 567)
- fingerprint is the md5sum of the image, which is stored in the DB when the file is uploaded
- photo-style can be configured by the programmer. Paperclip processes the original image into each of these styles and stores resulting images in different folders.

I want to have a function to which I pass the following tuple - `(PhotoId, Filename, Fingerprint, Style)` and I get the final path/URL. I tried the following...

```
data Routes route = Rouates
  {
    rDbPhoo :: route :- "system" :> "images" :> Capture "photoEssentials" (PhotoId, Filename, Fingerprint, Style) :> Get '[Text] ()
  } deriving (Generic)

instance ToHttpApiData (PhotoEssentials, Photo.Style) where
  toUrlPiece (PK photoId, fname, fprint, style_) =
    T.intercalate "/" $ buildChunks ++ [fprint, toText style_, fname]
    where
      buildChunks = (chunksOf 3 $ toS $ leftPadZeros $ show photoId)
      leftPadZeros s = (Prelude.replicate (9 - (Prelude.length s)) '0') ++ s

links :: Routes (AsLink URI)
links = allFieldLinks' linkURI
```

... but end-up with a URL-encoded version of the path, i.e...

```
ghci> (rDbPhoo links) (PK 30, "test.jpg", "3489379734324", Logo)
system/images/000%2F000%2F030%2F3489379734324%2Flogo%2Ftest.jpg
```

I tried defining the `toEncodedUrlPiece` function from the `ToHttpApiData` type-class, but even that didn't help.

How can I do this via the interface provided by servant-client?

**Comment by saurabhnanda** [comment]
Thanks for the quick reply @phadej 

What is the difference between `toUrlPiece` and `toEncodedUrlPiece`? I was under the impression that the latter is an "unsafe" version of the former (where it believes that the programmer has already taken care of URL-encoding the link).

**Comment by phadej** [comment]
Yes, you can **abuse** `toEncodedUrlPiece`, but then you are on your own> and you cannot parse (i.e. reuse API type) that URL back if you'd need to redo rails app with Haskell+servant. I do not recommend that approach.

If chunks count is fixed i.e. 3, I'd just admit it and write the API as that, and then do mangling in "user-land". It's not as elegant as you'd wish, but it's way more honest.
