### ISSUE TITLE
Decoupling servant-server from IO

### ISSUE THREAD

**Issue by ababkin** [haskell-servant/servant#1023]
I am building a distributed client-server app which I'd like to test in a non-`IO` setting (with the likes of https://hackage.haskell.org/package/dejafu). This will involve simulation of the network. The recent addition of `servant-client-core` works well for this, but the `servant-server` is unfortunately still hard-coupled to `IO`. 
I was curious whether anyone considered separating out the abstract server? (i.e. not based around a `wai` `Application` but something more abstract like a `Monad` that supports certain operations necessary for the servant server)

**Comment by phadej** [comment]
I personally would like to separate what's we can from `servant-server` (e.g. `Router`), to help `servant-snap`. That would help building new server interpretations. But it's far from my top on my priority list.

**Comment by ababkin** [comment]
I can contribute to this (since this is a blocker for my project anyway). I just want to make sure that I'll be working in the right direction to keep the effort concerted, so appreciate any pointers.

**Comment by phadej** [comment]
@ababkin I'm not sure what's your goal.

You use `servant-client-core` to make "pure" servant *client*, so you need a servant *server* as `Request -> Either ServantErr Response`, preferebly with `Request` and `Response` similar to ones in `servant-client-core`?

Just to be very clear: why you need a `servant` in between, why you don't test the functions you use to
implement handlers directly? You can `hoistServer` your application monad into `Handler`, and similarly `hoistClient` the `servant-client` into your application monad too. I.e. why you want to "integrate" through superficial Servant abstraction, and not directly?

**Comment by jkarni** [comment]
To some extent, `Wai` *is* the abstract server, and you can implement a different one than `Warp` and use that (though that of course depends on your use-case, which like @phadej I too would be curious to know more about). 

Is the main concern the IO performed by the handlers themselves, rather than the server/framework?

**Comment by alpmestan** [comment]
I started work on this a week or two ago, not by a lot but I can put it up somewhere one of these days and raise some discussion points.

**Comment by ababkin** [comment]
@phadej - you are right that I could do it all in the `servant-client-core`'s `Request -> Either ServantErr Response` and this is kind of what I currently do, but my eventual goal is to test _all_ the concurrency in a network of nodes (that communicate with each other) to expose any kind of concurrency non-determinism or deadlocks. For this I'll need to modify the server (`servant-server` and `wai`/ `warp`) to run in `MonadConc`[0] and not in `IO` (and simulate the transport layer in same monad as well). 

[0] https://docs.barrucadu.co.uk/concurrency/Control-Monad-Conc-Class.html

**Comment by phadej** [comment]
@ababkin I see, but why you cannot test the concurrency by wrapping handlers directly, what's the concrete benefit of also wrapping servant, *a middleman*, too? More concretely, say we have very simple single endpoint API nodes use to communicate with each other:

```haskell
type API = ReqBody '[JSON] ProtoReq :> Post '[JSON] ProtoRes

api :: Proxy API
api = Proxy
```

we can impelement it with

```haskell
hoistServer api toHandler handler where
    toHandler :: App x -> Handler x
    toHandler = ...

handler :: ProtoReq -> App ProtoRes
```

Now, `servant-server` and `servant-client` interpretations are "real world glue". But to simulate the fleet of nodes we can use non-servant specific `handler`:

```haskell
newtype TestApp a = TestApp (ConcT App a)

concHandler :: ProtoReq -> TestApp ProtoRes
concHandler  = TestApp . ... . handler

-- bunch of examples / properties working with @concHandler@.
-- Or the `App` can be instance of `MonadConc` directly.
```

---

That's how I'd test that my *business logic* is concurrency bug free. As said, I don't see what's the benefit of having `servant` being in the middle helps. I don't think you'll discover any new class of concurrency bugs there. All concurrency in `servant-server` comes from `warp`, so if you are very concerned, you'll need to have `warp` in the loop anyway.

**Comment by ababkin** [comment]
thanks @phadej - I'm still learning `servant` so the above definitely helps. This is how I'm implementing things currently:
https://github.com/ababkin/distest/blob/master/src/Hl/Node/Servant/Test/Client.hs#L44-L69
It is a bit painful to dispatch different requests this way, which is why I wanted a corresponding `servant-server` handlers for this. 
You have a point though that `servant` is a non-concurrent glue, and therefore there is not much point including it into the testing loop. And indeed all the server concurrency is inside `warp`, so that will be my `IO`-decoupling target for sure. 
I will try to do it the way you suggest.

**Comment by alpmestan** [comment]
So perhaps we can rename this issue, to make it really about the general problem of testing/emulatng/etc handlers? Seems like the backend-independent router stuffs I got started on might deserve their own issue, if there isn't one already. I also agree with @phadej that in my experience it's a lot easier to just work with what you really need (the handlers) without bringing in anything else. It's only going to make everything more complex for pretty much no gain.

**Comment by ababkin** [comment]
@jkarni - well, the concern is the hard coupling of the server side to `IO` (`warp` and `wai`). My handlers are already `IO`-free.

**Comment by ababkin** [comment]
@alpmestan - we could rename the issue, but it's not just handlers, it's the concurrency inside `warp` (or another concrete server impl that I can use) that I want to include into the `dejafu` test loop. Since if I just pretend there is no concurrency in the server in the tests (by stubbing it out somehow), the concurrency scheduling caused by `warp` during the runtime may interact negatively with the already tested concurrency inside the business logic, rendering the entire test incomplete (and the great part about `dejafu` is its completeness guarantees).

**Comment by ababkin** [comment]
@phadej - perhaps I wasn't entirely clear
```
newtype TestApp a = TestApp (ConcT App a)

concHandler :: ProtoReq -> TestApp ProtoRes
concHandler  = TestApp . ... . handler

-- bunch of examples / properties working with @concHandler@.
-- Or the `App` can be instance of `MonadConc` directly.
```
Perhaps I'm still missing something, but this makes sense only if I want to conc-test the handler _in isolation_.
My ambition however is not even testing of interaction of conc business logic and of all the handlers that may have conc in them on a single node. It is to test the interaction of all conc parts of a network (i.e. across all nodes) - basically make a whole network (and simulated transport layer) run in `MonadConc` as one whole (i.e. so `dejafu` can mess around with scheduling of the whole thing while looking for conc inconsistencies - simulating different execution schedulings of all the node's components + non-deterministic delays/packet-drops of the network and their impact on the network's concurrent behavior).

Currently my client side is taken care of: 
I make my client endpoints here:

https://github.com/ababkin/distest/blob/bfef63fa79866b8813bacf114f95071dd07bd1a3/src/Hl/Network/Interpreter/Test.hs#L79

then client-side call them here:

https://github.com/ababkin/distest/blob/bfef63fa79866b8813bacf114f95071dd07bd1a3/src/Hl/Network/Interpreter/Test.hs#L46

currently I dispatch them here, and call the handler directly: https://github.com/ababkin/distest/blob/bfef63fa79866b8813bacf114f95071dd07bd1a3/src/Hl/Node/Servant/Test/Client.hs#L45

But I want these calls to turn into some (on-the-wire) representation instead (simulating what happens in real `IO` impls), which will percolate through a simulated transport layer (could be a simple channel for starters) to finally reach a concurrent server that will dispatch the call using `servant-server` and call an appropriate handler - all while keeping _everything_ in `MonadConc`

if I short-circuit and simply call a handler here instead of making the endpoint `servant-client` call as above, I'll bypass the simulated transport layer and the concurrent server in this test, which is far from ideal for my case.

**Comment by phadej** [comment]
@ababkin you are on the right track. You don't need `servant`, as it's a part of "transport" i.e. way node communicate. Similarly you don't need `warp`. HTTP servers to the first approximation are:

```haskell
server = forever $ do
  (request, sender) <- acceptRequst
  fork $ handle request >>= sendTo sender
```

**Comment by ababkin** [comment]
yep, and thats more or less exactly how I'm approximating it right now. Thanks a lot for the help, this will get me going.
