### ISSUE TITLE
Add Tags combinator

### ISSUE THREAD

**Issue by nakaji-dayo** [haskell-servant/servant#1031]
I propose Tags combinator.
Like the Summary and Description combinator, this is useful for servant-swagger.
Swagger tags: https://swagger.io/docs/specification/2-0/grouping-operations-with-tags/

Can this be added to the main repo?
I can send PR.

**Comment by alpmestan** [comment]
@phadej Thoughts?

**Comment by phadej** [comment]
Well, indeed we have `Summary` and `Description`. But `Tags` IMHO start to be too swagger-y (and arbitrary).

I don't really know.

**Comment by domenkozar** [comment]
It's currently possible to do this via http://hackage.haskell.org/package/servant-swagger-1.1.5/docs/Servant-Swagger.html#g:3

**Comment by alpmestan** [comment]
@nakaji-dayo See the previous comment. That should cover your needs, right?

**Comment by domenkozar** [comment]
we can close this as duplicate of https://github.com/haskell-servant/servant-swagger/issues/73
