### ISSUE TITLE
Composing ServerT monad

### ISSUE THREAD

**Issue by farnoy** [haskell-servant/servant#104]
Hi, I'm trying to do something like this:

```type Handler layout a = ReaderT Env (ServerT layout (EitherT ServantErr IO)) a```

Motivation: I want to enhance the Server monad with some environment and helpers. Specifically, I want an easier access to the database and websocket broadcast channel, to use it like this:

```
fromDb f = do
  env <- ask
  withResource (db env) $ runDbConn f

announce msg = do
  env <- ask
  return . atomically . writeTQueue (queue env) $ msg

server :: Handler Api
server =  do
          c <- fromDb $ project ChannelConstructor CondEmpty
          announce "test message"
          return $ T.unlines $ fmap channelName c
```

I'm running into some issues though, the error is:
```
    The second argument of ‘ReaderT’ should have kind ‘* -> *’,
      but ‘ServerT layout (EitherT ServantErr IO)’ has kind ‘*’
    In the type ‘ReaderT Env (ServerT layout (EitherT ServantErr IO)) a’
    In the type declaration for ‘Handler’
```

I've recently read <http://catamorph.de/documents/Transformers.pdf> and wanted to enhance my context with more goodies. Can you point me in the right direction?

**Comment by jkarni** [comment]
Sure. The tutorial has a [section](http://haskell-servant.github.io/tutorial/server.html#using-another-monad-for-your-handlers) on using different monads. The basic idea is to get from the monad you want to (ultimately) `EitherT ServantErr IO`, via natural transformations. E.g., if you don't need the EitherT, you can do:

```
type Handler api = ServerT api (ReaderT Env IO)

server :: Handler Api

myEnter :: Env -> (ReaderT Env IO :~> EitherT ServantErr IO)
myEnter env = Nat $ liftIO (runReaderT env)

main = ... serve myProxy (enter (myEnter myEnv) server) ...
```
(I haven't tested this out, but imagine it's roughly correct.)
Though you can also stack transformers further, and then change `myEnter` accordingly. There are some [utilities](http://hackage.haskell.org/package/servant-server-0.4.0/docs/Servant-Server-Internal-Enter.html) for natural transformations. Try to get something of type `a :~> EitherT ServantErr IO`, where `a` is the monad stack you want to use. 

If you get stuck, let us know!

(Note that you should probably never stack monads over `ServerT` - instead, just use the entire monad stack you're interested in as it's second argument.)

**Comment by farnoy** [comment]
I struggled for a bit, but I've got it to work, thank you!

**Comment by jkarni** [comment]
Great! Let us know (or send a PR to the hakyll branch of the [website repo](https://github.com/haskell-servant/haskell-servant.github.io/blob/hakyll/tutorial/server.md), or even to this repo if you think the haddocks are at fault) if you know how we could make the documentation better.
