### ISSUE TITLE
CONTRIBUTION doesn't mention how to build the docs

### ISSUE THREAD

**Issue by k-bx** [haskell-servant/servant#1057]
Doing the `stack test` doesn't seem to build the docs, which is slightly inconvenient, since I can't really check if I got them right without Travis.

Would be a nice addition.

**Comment by alpmestan** [comment]
Right, we use sphinx for this, see [this file](https://github.com/haskell-servant/servant/blob/master/doc/building-the-docs) for some instructions.

I guess it wouldn't hurt to have the contributing document mention this indeed.

Note that if you're a nix enthusiast, `nix/shell.nix` can also provision the whole sphinx business.

**Comment by vcunat** [comment]
BTW, with new sphinx the documentation won't build unless you remove a line from config:
https://github.com/haskell-servant/servant/blob/4b247ee801/doc/conf.py#L170

**Comment by phadej** [comment]
That's why we have

> https://github.com/haskell-servant/servant/blob/master/doc/requirements.txt

**Comment by vcunat** [comment]
I see, though `==1.7.5` seems a bit strict requirement to me personally.  This way one would end up keeping a dozen versions in each distribution.  Docs built fine with 1.7.9 for us and it's a simple one-liner for 1.8.3, but if you prefer it this way...

**Comment by phadej** [comment]
I use virtualenv (as well as readthedocs) and https://github.com/haskell-servant/servant/blob/master/doc/building-the-docs mentions it. Seems we don't have `html` target in `Makefile` though. Cannot check what's up now. That needs fix indeed.

Pipenv isn't supported on readthedocs based on https://github.com/rtfd/readthedocs.org/issues/3181

Unfortunately I don't know the current best practicies of development in Python, but I'm pretty sure that relying on global installations is not one. (And IIRC there aren't anything like cabal's dependency solver, so sticking to pinned versions (which work) is the best approach). 

I'd like to read more about Python development practicies though.

**Comment by phadej** [comment]
Actually `make html` works, that `Makefile` is smart.

Anyway, `building-the-docs` describes how to build docs, and `CONTRIBUTION.md` could point to it.

Adding to CI is a bonus of course, it would be nice if [`haskell-ci`](https://github.com/haskell-ci/haskell-ci) could include needed parts from configuration (so we don't need to edit `.travis.yml` manually).

**Comment by vcunat** [comment]
For reference, I actually use `nix` wherever I can, and regression in the nixos.org build farm is what lead me here.  I didn't want to mention that specifically, but I see I'm not the first nixer in this thread.  With nix we technically _can_ have many versions of packages, but we're trying to restrict that, so I just patched that single line in the nixpkgs official repo...

**Comment by phadej** [comment]
Wait, does nixpkgs include/build servant's doc/ tutorial or what? Or how the failure there lead you, @vcunat here?

**Comment by phadej** [comment]
@vcunat that's very nice :+1:

**Comment by domenkozar** [comment]
I used to do Python, so I made https://github.com/haskell-servant/servant/pull/1124

**Comment by domenkozar** [comment]
Can be closed, fixed.

**Comment by k-bx** [comment]
Thanks!

**Comment by k-bx** [comment]
Forgot one essential point: does it check the code in docs compiles well? If not – we should mention that in README imo @domenkozar

**Comment by alpmestan** [comment]
We do check that the tutorial + cookbook recipes compile, in CI.
