### ISSUE TITLE
Can't create the nested API example in the docs, "Expected kind ‘* -> *’, but ‘API’ has kind ‘*’"

### ISSUE THREAD

**Issue by tolgap** [haskell-servant/servant#1060]
So I'm trying to build a nested API, *with* token based authentication. I have the types ready for each individual REST API endpoint, all that's left is combining the 6 different REST routes, into a singular api client.

For this, I am trying to use the example in `servant-client-core` docs for `ClientLike`:

https://www.stackage.org/haddock/lts-11.12/servant-client-core-0.13.0.1/Servant-Client-Core-Reexport.html#t:ClientLike

So this part:

```haskell
type API1
    = "foo" :> Capture "x" Int :> Get '[JSON] Int
 :<|> "bar" :> QueryParam "a" Char :> Post '[JSON] String

type API2
    = "baz" :> QueryParam "c" Char :> Post '[JSON] ()

type API = API1 :<|> API2

data APIClient = APIClient
  { getFoo  :: Int -> ClientM Int
  , postBar :: Maybe Char -> ClientM String
  , postBaz :: Maybe Char -> ClientM ()
  } deriving GHC.Generic

instance Generics.SOP.Generic APIClient
instance (Client API ~ client) => ClientLike client APIClient -- <----- ERROR IS HERE

mkAPIClient :: APIClient
mkAPIClient = mkClient (client (Proxy :: Proxy API))
```

But I am presented with this error:

```
 Main.hs    54  18 error           error:
     • Expected kind ‘* -> *’, but ‘API’ has kind ‘*’
     • In the first argument of ‘Client’, namely ‘API’
       In the first argument of ‘~’, namely ‘Client API’
       In the instance declaration for ‘ClientLike client APIClient’ (intero)
 Main.hs    54  46 error           error:
     • Expecting one more argument to ‘client’
       Expected a type, but ‘client’ has kind ‘* -> *’
     • In the first argument of ‘ClientLike’, namely ‘client’
       In the instance declaration for ‘ClientLike client APIClient’ (intero)
```

How is it that I can't compile the example given in the docs? It's copy pasted directly from Stackage. I hope I can get some help as I've been struggling to get this working for days now 😓. Thanks.

**Comment by alpmestan** [comment]
I recommend directly following this recipe: https://haskell-servant.readthedocs.io/en/latest/cookbook/generic/Generic.html#client (the link points to the client part). Have you seen it before? This is the usual way to get records of client functions, using servant-client, not servant-client-core (which only contains http client lib independent things).

Feel free to create a new issue earlier next time, we're always happy to explain things and improve our docs. :-)

**Comment by tolgap** [comment]
Hi @alpmestan . Thanks for the response. I'm trying to apply your advice and updated to LTS-12.14 so I could use servant-0.14 with Generics. I think the cookbook and the examples are helpful for small scenarios but for it doesn't quite answer my question (as I'm not really the most knowledgable in Haskell).

Right now, by reading the cookbook examples, I have no idea how to do a nested API example with `Servant.API.Generic`. My eventual goal is to combine 5 REST endpoints into a single Client API which is protected by a Basic Bearer token.

Say we have:

```
data Routes1 route = Routes1 { _get1 :: route :- "something" } deriving Generic
data Routes2 route = Routes2 { _get2 :: route :- "else" } deriving Generic
```

I eventually want to end up with 1 data type that combines both those routes, with a basic authentication applied to them at the top level. Could you explain it to me by applying this to the example I gave above (`Routes1` and `Routes2`)? I would really appreciate it!

**Comment by alpmestan** [comment]
Long story short, you have to do some intermediate calls to help out servant's record machinery.

You can see an example + some discussion at https://github.com/haskell-servant/servant/issues/1015. Please ask any question you may have here :-)

**Comment by tolgap** [comment]
If anyone runs into this issue and is struggling with creating nested APIs. I figured things out together with @domenkozar 's Cachix repository. Here's my project implementing 7 APIs into a single API:
https://github.com/paramander/mollie-api-haskell/blob/c504528a1137872cf78f67f89ec6b5669a5a0ce4/src/Mollie/API.hs

**Comment by alpmestan** [comment]
Thanks for leaving a link to your solution!

**Comment by patrickmn** [comment]
How did you do auth at the top with nested records?
