### ISSUE TITLE
Provide a template

### ISSUE THREAD

**Issue by Sir4ur0n** [haskell-servant/servant#1065]
Now that https://github.com/commercialhaskell/stack/issues/4039 is released in Stack 1.9.1, it would be nice to provide Stack templates in this repo.
Maybe start again from https://github.com/commercialhaskell/stack-templates/blob/master/servant.hsfiles and fix it (I think it's broken and not up-to-date)?

**Proposals:**
- A template with a single, minimalistic API. This could contain more or less the result of the [A first example](https://haskell-servant.readthedocs.io/en/stable/tutorial/Server.html#a-first-example) section of the tutorial.
- A production-grade template with several APIs showing the full potential of Servant, including code organization (import API types and handlers from several modules), API Swagger documentation, etc. Maybe even some tests? I'm not sure about this part. Basically, something that I can create using `stack new foobar github:haskell-servant/servant-on-steroids`, build, exec, and just see what can be built/done with Servant in a fraction of minute. Then the curious can start toying with the code, the others will read carefully the documentation. Each its own pace/learning style.

**Comment by alpmestan** [comment]
I certainly wouldn't mind shipping templates in the repo, if that makes the life of stack users (especially beginners) easier. I agree that it would be nice to have a very simple one, and then possibly incrementally fancier ones that set up clients, tests, logging, auth, etc. Are you volunteering to add this @Sir4ur0n? :-)

**Comment by Sir4ur0n** [comment]
I don't mind proposing the simple template (I definitely don't know enough Servant fu for the complete one). However I'm waiting for https://github.com/commercialhaskell/stack/issues/4344 to befixed first 😞

**Comment by alpmestan** [comment]
OK, feel free to use this issue to track anything related to servant stack templates.

**Comment by Sir4ur0n** [comment]
No sooner than 5 months later, here it is 😄 Sorry I had completely forgotten about it, then yesterday a coworker struggled with Servant (because he used the old template) and I remembered ^^'
