### ISSUE TITLE
hlint parse error on Headers declaration

### ISSUE THREAD

**Issue by rnons** [haskell-servant/servant#107]
I have some code like this

```
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE OverloadedStrings #-}
import Servant
import Data.Text (Text)
import Network.Wai.Handler.Warp (run)

type Api = "download" :> Get '[PlainText] (Headers '[Header "Connection-Disposition" String] Text)

getDownloadH = return $ addHeader "attachment;" "Hello world!"

apiProxy :: Proxy Api
apiProxy = Proxy

apiServer :: Server Api
apiServer = getDownloadH

main :: IO ()
main = do
    run 3000 $ serve apiProxy $ apiServer
```

And hlint complains that 

```
sample.hs:8:60: Warning: Parse error: "Connection-Disposition"
Found:
    import Network.Wai.Handler.Warp (run)

  > type Api = "download" :> Get '[PlainText] (Headers '[Header "Connection-Disposition" String] Text)

    getDownloadH = return $ addHeader "attachment;" "Hello world!"


1 suggestion
```

With this parse error, hlint failed to catch the redundant do in the main function.
Do you have any suggestions, or should I report this to the hlint project?

**Comment by jkarni** [comment]
The bug is with `haskell-src-exts` rather than `hlint` itself - I believe [this](https://github.com/haskell-suite/haskell-src-exts/issues/219) is the relevant ticket.

**Comment by jkarni** [comment]
Closing since it doesn't seem like there's anything else we can do, but feel free to reopen or continue commenting if you feel otherwise, or have other questions.
