### ISSUE TITLE
Allow QuickCheck-2.11.*

### ISSUE THREAD

**Issue by domenkozar** [haskell-servant/servant#1083]
From https://github.com/commercialhaskell/stackage/issues/3949 it seems quite a lot libraries haven't upgraded yet, is there a good reason to bump QuickCheck to 2.12?

**Comment by phadej** [comment]
That issue doesn't seem to be updated in two months since it was created. There are some packages with my name on it; i'm pretty sure that most of them allow QuickCheck-2.12 as I updated many during GHC-8.6 migrations.

**Comment by domenkozar** [comment]
Let's see at https://github.com/commercialhaskell/stackage/pull/4139
