### ISSUE TITLE
Example value for ParamSchema

### ISSUE THREAD

**Issue by cdupont** [haskell-servant/servant#1093]
I'd like to add an example value for a ParamSchema, to be able to see it in Swagger-UI.
For example for a Schema, I added an example:

```
instance ToSchema Foo where
   declareNamedSchema proxy = genericDeclareNamedSchema defaultSchemaOptions proxy
         & mapped.schema.example ?~ toJSON defaultFoo
```

The example value "defaultFoo" will render in Swagger for the body of a request. But for a URL parameter, how to get the example?

**Comment by cdupont** [comment]
It seems that `ParamSchema` doesn't have an "example" field: http://hackage.haskell.org/package/swagger2-2.3.1/docs/Data-Swagger-Internal.html#t:ParamSchema

**Comment by phadej** [comment]
Please open the issue in the https://github.com/GetShopTV/swagger2 repository, this is not related to `servant`
