### ISSUE TITLE
is there a way to point on servant-server 0.15 ?

### ISSUE THREAD

**Issue by nhenin** [haskell-servant/servant#1096]
I would like to use the version 0.15 instead of the the one available on the last LTS (12.22), usually I'm adding this in stack.yaml :
```
extra-deps :
  - git: git@github.com:haskell-servant/servant.git
    commit: e3e5d2b23057c2c3409e5e210b613527baf3b77d 
```
But you use multiple projects in the same repo so it does not work :-(  : 
`The current entry points to /Users/nhenin/dev/gsdFlow/.stack-work/downloaded/6krbU6UwORFF/ but no .cabal or package.yaml file could be found there.`

Do you know how I could use it ?

**Comment by arianvp** [comment]
```
extra-deps :
  - git: git@github.com:haskell-servant/servant.git
    commit: e3e5d2b23057c2c3409e5e210b613527baf3b77d
    subdirs:
      - servant
      - servant-server
      - servant-client
      # Etcetera
```

Is what you're looking for. See the stack documentation:  https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md#extra-deps
