### ISSUE TITLE
Bug in `decodedAs`?

### ISSUE THREAD

**Issue by edsko** [haskell-servant/servant#1097]
In `Servant.Client.Core.Internal.RunClient`, we find

```haskell
decodedAs :: forall ct a m. (MimeUnrender ct a, RunClient m)
  => Response -> Proxy ct -> m a
decodedAs response contentType = do
  responseContentType <- checkContentTypeHeader response
  unless (any (matches responseContentType) accept) $
    throwServantError $ UnsupportedContentType responseContentType response
  case mimeUnrender contentType $ responseBody response of
    Left err -> throwServantError $ DecodeFailure (T.pack err) response
    Right val -> return val
  where
    accept = toList $ contentTypes contentType
```

I think the line

```
  unless (any (matches responseContentType) accept) $
```

is wrong. The documentation for [`matches`](https://www.stackage.org/haddock/lts-10.3/http-media-0.7.1.1/Network-HTTP-Media.html#v:matches) reads

> This relation must be a total order, where more specific terms on the left can produce a match, but a less specific term on the left can never produce a match. For instance, when matching against media types it is important that if the client asks for a general type then we can choose a more specific offering from the server, but if a client asks for a specific type and the server only offers a more general form, then we cannot generalise. In this case, the server types will be the left argument, and the client types the right.

Here however the client type is given on the _left_ instead. 

The result is that for a client that accepts a HTML response (`accept` will be `[text/html;charset=utf-8]`) but a server that returns a content-type of `text/html`, the response is rejected as `UnsupportedContentType`.

**Comment by phadej** [comment]
the server types are the left argument, aren'т тhey?

**Comment by edsko** [comment]
Hello again @phadej :D Uh, well, the roles are reversed here I think. `responseContentType` is the specific content type returned by the server; `matches` is the list of content types that we can accept. As the docs say: "a less specific term on the left can never produce a match". Here the server returns something unspecific `text/html`, and we specify something quite specific (`text/html;charset=utf-8`), and hence it doesn't match.

**Comment by phadej** [comment]
hmm. For `JSON` we do have also non specific `application/json`, don't we have the same for `HTML`? 

Maybe we don't, but OTOH, i'd rather require you to write own `HTML`, which has charset-less media-type. Non setting the charset for html endpoints is asking for troubles.

```php
header('Content-Type: text/html; charset=utf-8');
```

is like the first thing people do in their PHP scripts, so browsers don't need to guess...

**Comment by edsko** [comment]
I don't control the endpoint, I am writing a client, not a server :)

And no, we don't:

```
*QuerySFZD.API.Ours Network.HTTP.Media Data.Foldable> toList $ contentTypes (Proxy @HTML)
[text/html;charset=utf-8]
```

**Comment by phadej** [comment]
Thanks, these will probably fail with old `base`, but i'll just drop the support for pre GHC-8.0. ie no need to fix those

**Comment by phadej** [comment]
new versions of `servant-lucid` and `servant-blaze` released
