### ISSUE TITLE
Catching Application Errors and redirect with err500

### ISSUE THREAD

**Issue by nhenin** [haskell-servant/servant#1112]
Hi, here is the following code  : 

```
import qualified Pipes as P
import qualified Pipes.Prelude as P.Prelude
streamCommand :: WorkspaceId -> Handler (P.Producer (Persisted GsdCommand) IO ())
streamCommand workspaceId =
        handleInternalError $ return $ redirectGsdErrorToServantError $ toPipes $ GsdMonitoring.streamCommand eventStoreSettings workspaceId
       where
         redirectGsdErrorToServantError:: P.Producer (Either SomeException (Persisted GsdCommand)) IO () -> P.Producer (Persisted GsdCommand) IO ()
         redirectGsdErrorToServantError producer = producer P.>-> (P.Prelude.mapM (\item -> case item of
               Right persistedItem -> return persistedItem
               Left (SomeException e) -> throwError $ userError $ show e))

handleInternalError :: Handler a -> Handler a
handleInternalError = handleAny throwEx
             where
               throwEx e = throwError $ err500 {errBody = "The following server exception occured: " <> (cs $ show e)}
```
I would like to redirect my Left SomeException into a custom err500... I'm using the streaming version of the server... (my example is not working...I can't redirect these IO Exceptions ..)

Thanks for your help :-)

**Comment by phadej** [comment]
Is this somehow related to streaming?

If you start stream output, there's no way to change HTTP status (it's already sent)?

> Catch IO Exceptions with ExceptT as explained in their docs

Sorry, I don't follow; which docs?

**Comment by nhenin** [comment]
I think I'm triggering IO Exception and not exception through the ExcepT Transformer Monad... I was referring about t docs about [Control-Monad-Except](http://hackage.haskell.org/package/mtl-2.2.2/docs/Control-Monad-Except.html)'s doc which is saying the following :  

> "Please do not confuse ExceptT and throwError with Exception / SomeException and catch, respectively. The latter are for exceptions built into GHC, by default, and are mostly used from within the IO monad. They do not interact with the "exceptions" in this package at all. This package allows you to define a new kind of exception control mechanism which does not necessarily need your code to be placed in the IO monad.
> 
> In short, all "catching" mechanisms in this library will be unable to catch exceptions thrown by functions in the Control.Exception module, and vice-versa."

In the example above my call `GsdMonitoring.streamCommand eventStoreSettings workspaceId` is safe (Either SomeException a). I'm using another streaming library than pipe which is why you are seeing toPipes in front . 

So either It returns the item or it returns an Error (e.g `Left ConnectionClosed` when the database microservice used by `streamCommand` is down). 

when I put the database microservice down, my errors are not encapsulated in a ServantErr and sent to the client. 

I think that an IO Exception is thrown in the dedicated thread and it kills it (showing a message in the console like this  : `user error (Terminated "Connection closed"))`

I don't know if it is the way I'm using the Handler with the Pipe...

**Comment by phadej** [comment]
If you start streaming response to a client (e.g. even a single item), you cannot "return 500" anymore. Is this what you are trying to do?

In any case, your code seems complicated, can you minimize the example to highlight what you are trying to do, how the code behaves, and how you want it to behave. StackOverflow has good guidelines about asking questions:

https://stackoverflow.com/help/how-to-ask

**Comment by nhenin** [comment]
I don't think we need to see code actually... what I would like to do is having a way to notify the client that the upstream failed. Basically propagating the shutdown of the stream over http (your stack server + client).

**Comment by phadej** [comment]
> Basically propagating the shutdown of the stream over http 

That's something which  HTTP (and therefore `servant`) doesn't specify (provide respectively). In other words, it have to be built into your applications somehow.

You should think this problem at HTTP level. What kind of response you'll generate when say 3 commands come through, but then `GsdMonitoring.streamCommand` fails.

**Comment by nhenin** [comment]
I'm going toward having safe pipelines... By propagating the items in a structure like Either SomeError Item, each time you receive a SomeError, it closes the stream naturally... It add some complexity along the pipeline though, since I have an additional layer to handle... but that's the best solution I have in mind so far... Thank you for your help, and my apologies for dumping that "with a lack of context" code  :-) . I think we can close that ticket....
