### ISSUE TITLE
QueryParams does not accept param[0]=a&param[1]=b

### ISSUE THREAD

**Issue by marcosh** [haskell-servant/servant#1125]
I have an API endpoint which uses `QueryParams`.

It works fine if I use it as `/enpoint?param[]=a&param[]=b`, but it does not recognise the query parameters if the request is `/endpoint?param[0]=a&param[1]=b`.

I would expect to obtain the same query string parameters using the two calls above.

Am I missing something, maybe a parameter somewhere?

**Comment by phadej** [comment]
This isn't supported.

It's tricky, what should happen if `/endpoint?param[1]=a` is supplied? I suspect both *failing* and making some kind of sparse list are desirable properties.

For now, I'd recommend to write your own `QueryParams` variant, and let's keep built-in `QueryParams` simple.

**Comment by marcosh** [comment]
Thanks for the quick feedback and the explanation. I guess I'll close the issue then
