### ISSUE TITLE
How to help servant decode custom values from incoming POST request?

### ISSUE THREAD

**Issue by omefire** [haskell-servant/servant#1126]
If I have an API like this:
``` type API = "createReminder" :> ReqBody '[JSON] Reminder :> Post '[JSON] Reminder ```

- How do I make sure that servant can correctly decode and construct Reminder values from the incoming POST request ?
- What typeclass should I implement?

**Comment by phadej** [comment]
[`FromJSON`](http://hackage.haskell.org/package/aeson-1.4.2.0/docs/Data-Aeson-Types.html#t:FromJSON)

**Comment by omefire** [comment]
@phadej Thanks!

**Comment by omefire** [comment]
@phadej Thanks!
