### ISSUE TITLE
What is the best practice to redirect to another page with login processing?

### ISSUE THREAD

**Issue by falsandtru** [haskell-servant/servant#1150]
Redirecting to the thank you page is important to prevent the double submit problem. Could you provide the official solution?

**Comment by phadej** [comment]
The `throwError err302 { ... }` is the best we have at the moment, AFAIK.

**Comment by falsandtru** [comment]
Looks like I have to add a header to the succeeded response. How can I redirect the request with the following processing?

```hs
return $ applyCookies NoContent
```

https://github.com/haskell-servant/servant-auth

**Comment by falsandtru** [comment]
@phadej To define and use `Redirection` response type instead of `NoContent` may be a smart solution.

**Comment by MasseRelex** [comment]
There is also a stackoverflow answer related to this: https://stackoverflow.com/questions/46789241/redirections-in-servant and this [gist](https://gist.github.com/alpmestan/757094ecf9401f85c5ba367ca20b8900)

Basically something like this (lots have been redacted)

``` haskell
type PostRedirect (code :: Nat) loc = Verb 'POST code '[JSON] (Headers '[Header "Location" loc) NoContent)

type API = Capture "q" String :> PostRedirect 301 String

server :: Server API
server query = redirect ("https://example.com/" ++ query)
```

**Comment by alpmestan** [comment]
This indeed works if you want to redirect if everything goes well. When you want to do conditional redirects and what not it becomes trickier and you pretty much need to resort to the `throwError err30x [...]` approach, for now.

**Comment by falsandtru** [comment]
Looks like your solution can't be applied to cookie application. Could you show me an example working with authentication? I'm trying to refactor the official example(https://github.com/haskell-servant/servant/issues/1150#issuecomment-471804907) but `redirect` function can't seem to be possible to use for that example.

**Comment by falsandtru** [comment]
I resolve as follows:

```hs
login :: CookieSettings -> JWTSettings -> Login -> Handler (Headers '[ Header "Location" String
                                                                     , Header "Set-Cookie" SetCookie
                                                                     , Header "Set-Cookie" SetCookie]
                                                                    NoContent)
login cookieSettings jwtSettings Login { name, token } = do
   mApplyCookies <- liftIO $ acceptLogin cookieSettings jwtSettings User { name, email = "" }
   case mApplyCookies of
     Nothing           -> throwError err401
     Just applyCookies -> return $ (addHeader "" (applyCookies NoContent) :: Headers '[Header "Location" String, Header "Set-Cookie" SetCookie, Header "Set-Cookie" SetCookie] NoContent)
```

I'll try to use this. Thanks for your help.
