### ISSUE TITLE
Help migrating complex app

### ISSUE THREAD

**Issue by k-bx** [haskell-servant/servant#1151]
Hi. I have a big app that I'd like to migrate from servant 0.14 to a more recent one. It is currently using a mix of generic-style API with some old-style one, combining them together via different techniques.

I've re-created a somewhat stripped-down version of the app, it's buildable via `stack build` and should fully present you with the problem. It's 154 lines long: https://github.com/k-bx/servant-generic-hoist/blob/master/old/src/Main.hs

The biggest problem is the combination of old-style and new-style code like this:

```haskell
completeServer :: Env -> Manager -> Server API
completeServer env mgr =
  handlerServer env :<|> toServant srvStatic :<|>
  swaggerSchemaUIServer swaggerDoc :<|>
  Tagged (legacy mgr)
```

You can see this code combining the swagger-ui library base code with some legacy API and new generic-based one. It uses `handlerServer` which is defined like this:

```haskell
handlerServer :: Env -> ToServant (AdServerAPI AsServer)
handlerServer env = enter appToHandler (toServant server)
  where
    appToHandler :: AppM :~> Handler
    appToHandler = runReaderTNat env
```

I wasn't able to redefine it via new api (not using `enter`).

Not sure if it helps, but I've also created a `new` directory, containing a somewhat similar code base which has some code bootstrapped already https://github.com/k-bx/servant-generic-hoist/blob/master/new/src/Main.hs It's buildable via `stack build` as well, uses latest Stackage snapshot (with more recent servant).

Thank you!

**Comment by k-bx** [comment]
After thinking about it, I've added the `old-migrating` directory. It's a copy of `old`, but with attempt to migrate it to new servant. It fails to build with:

```
/home/kb/workspace/servant-generic-hoist/old-migrating/src/Main.hs:97:3: error:
    • Couldn't match type ‘"foo" :> Get '[PlainText] Text’
                     with ‘Handler Text’
      Expected type: Handler Text
        Actual type: ToServantApi AdServerAPI
    • In the first argument of ‘(:<|>)’, namely ‘handlerServer env’
      In the expression:
        handlerServer env
          :<|>
            toServant srvStatic
              :<|> swaggerSchemaUIServer swaggerDoc :<|> Tagged (legacy mgr)
      In an equation for ‘completeServer’:
          completeServer env mgr
            = handlerServer env
                :<|>
                  toServant srvStatic
                    :<|> swaggerSchemaUIServer swaggerDoc :<|> Tagged (legacy mgr)
   |
97 |   handlerServer env :<|> toServant srvStatic :<|>
   |   ^^^^^^^^^^^^^^^^^

/home/kb/workspace/servant-generic-hoist/old-migrating/src/Main.hs:110:21: error:
    • Couldn't match type ‘Handler Text’
                     with ‘"foo" :> Get '[PlainText] Text’
        arising from a functional dependency between:
          constraint ‘Enter
                        (ReaderT Env Handler Text)
                        AppM
                        Handler
                        ("foo" :> Get '[PlainText] Text)’
            arising from a use of ‘enter’
          instance ‘Enter (m a) m n (n a)’ at <no location info>
    • In the expression: enter appToHandler (toServant server)
      In an equation for ‘handlerServer’:
          handlerServer env
            = enter appToHandler (toServant server)
            where
                appToHandler :: AppM :~> Handler
                appToHandler = runReaderTNat env
    |
110 | handlerServer env = enter appToHandler (toServant server)
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by k-bx** [comment]
I think I did it. See https://github.com/k-bx/servant-generic-hoist/commit/8432fd575b67dd30bad09c34fd838100257e9343

**Comment by alpmestan** [comment]
Congrats =)

Sorry for the silence, I was away in the past few days.

**Comment by k-bx** [comment]
@alpmestan no problem, I'm actually happy about how things turned out. Generic-based method turned out to be way simpler than I thought, and now I have a somewhat full understanding of how it works :)
