### ISSUE TITLE
Adding an endpoint to serve static files to a pre-existing servant web service

### ISSUE THREAD

**Issue by omefire** [haskell-servant/servant#1153]
I have created a web service that exposes some REST API, but now I want to add another one to serve static files. However, I don't know how to get started.

Here is the code I want to extend: https://github.com/omefire/trello-reminders-server/blob/master/app/Main.hs

**Comment by alpmestan** [comment]
If your existing API's API type is called `ExistingAPI`, with handlers named `existingServer :: Server ExistingAPI`, then you can do:

``` haskell
type NewAPI = ExistingAPI :<|> "files" :> Raw

newServer :: Server NewAPI
newServer = existingServer :<|> serveDirectoryWebApp "./www"
```

More file serving functions available at: https://hackage.haskell.org/package/servant-server-0.16/docs/Servant-Server-StaticFiles.html

**Comment by omefire** [comment]
Thanks a lot! this was helpful. @alpmestan

**Comment by alpmestan** [comment]
Feel free to close when your problem is solved, or to come back with other questions if you can't get what you want to work.
