### ISSUE TITLE
Capture + Lenient?

### ISSUE THREAD

**Issue by neongreen** [haskell-servant/servant#1155]
I have an endpoint that looks like `/Users/v2/<uuid>`. I would like to use `Capture "id" UUID` in my API types (for documentation purposes), but when the UUID is unparseable, I want the API user to get 401, not 404. It would be nice if I could say `Capture' [Lenient] "id" UUID` and then get an `Either Text UUID` in my handler and deal with it myself.

Does that make sense?

**Comment by phadej** [comment]
It does.

**Comment by neongreen** [comment]
Alright, I'll do a PR.
