### ISSUE TITLE
Warp.setOnException doesn't work properly with warp-tls

### ISSUE THREAD

**Issue by k-bx** [haskell-servant/servant#1180]
I noticed that my app doesn't log a `setOnException` handler properly. I've somewhat bisected the problem into a reproducible self-containing repo. Initially I thought that the problem is in `warp-tls` itself, but it seems that it's not.

There's a repo with two projects: one servant-based and another is purely wai. Here's how the pure-wai one works:

Main.hs: https://github.com/k-bx/servant-custommonad-logging/blob/master/waitls-onexception-bug/src/Main.hs

```
$ curl --insecure -i https://localhost:8000/hello
```

Log you see:

```
Error: caught an exception: Erroring out
CallStack (from HasCallStack):
  error, called at src/Main.hs:33:22 in main:Main. Call stack: CallStack (from HasCallStack):
  onExceptionAct, called at src/Main.hs:37:29 in main:Main
```

Now, same thing in servant doesn't produce any output. Main.hs: https://github.com/k-bx/servant-custommonad-logging/blob/master/webapp/src/Main.hs

It works fine with non-tls warp, just uncomment the line:

```haskell
  -- WarpTLS.runTLS tlsSettings warpSettings app
  Warp.runSettings warpSettings app
```

And logging will work with servant (need to call curl like this):

```
$ curl -i localhost:8000/api/error-out
```

Didn't dig further than that yet.

**Comment by k-bx** [comment]
Sorry, my bad! The problem was that I was calling `respond (error ...)` when testing pure WAI stuff, but should've just called `error ...`, now it reproduces in pure warl-tls.

**Comment by k-bx** [comment]
Continuing in https://github.com/yesodweb/wai/issues/746

**Comment by alpmestan** [comment]
No problem :-)
