### ISSUE TITLE
We should use semantic versioning to release

### ISSUE THREAD

**Issue by unhappychoice** [haskell-servant/servant#1196]
Currently, almost every package management tools (like `stack` or `cabal`) and developers expect libraries to use [semantic versioning](https://semver.org), I think. 

So, if there's breaking changes in a release, we should update the major version although there's many breaking changes in the past minor releases.

**Comment by fizruk** [comment]
I think we adhere to [Package Versioning Policy](https://www.haskell.org/haskellwiki/Package_versioning_policy) (a.k.a PVP).
But @phadej can correct me as he has been doing releases for quite a while now :)

**Comment by unhappychoice** [comment]
Sorry that I don't know there's PVP existing :bow:
So, this issue is not the point and I just close this :+1:

**Comment by alpmestan** [comment]
Indeed, we do follow the PVP, and so do many other packages on Hackage, including many of servant's dependencies, and it's been working quite well.
