### ISSUE TITLE
Vote: Naming convention for content-type-aware combinators

### ISSUE THREAD

**Issue by alpmestan** [haskell-servant/servant#12]
Hi folks,

There's been a decent amount of work on all the servant libraries since the 0.2 release, among which is a clean and extensible support for content-types.

Most of the discussion so far about this resides [here](https://github.com/haskell-servant/servant-server/pull/13).

We're basically wondering what you, users and fellow servant developers, would prefer:

1) Keep `Get`, `Post` and friends as the names for the JSON-only endpoints, and have the combinators that take the list of supported content types be named with a final prime (`'`), as in `Get'`, `Post'`, etc. This would probably have the benefit of not breaking any existing code.
2) The reverse: have `Get`, `Post` and friends be the combinators that take a type level list of supported content types, and have `Get'`, `Post'` etc be the simple JSON-only versions.
3) Some other naming convention..?

The discussion linked above contains "sample code" to give you an idea of what each would look like.

Please express your vote in a comment to this issue here, and within a week or two we'll see what naming convention is preferred and we'll just go with that one.

Thanks in advance folks.

**Comment by jkarni** [comment]
:+1:  for (2) (possibly without actually providing `Get'` etc., since client code can do that itself.

**Comment by christian-marie** [comment]
(2) Without providing ```Get'``` because it hides something that I believe is important, and not very difficult to grasp. Get [JSON]' makes it obvious to the user how to provide alternate content types. 

Type aliases for relatively simple things like this are, in my experience, a hindrance to new users.

**Comment by tvh** [comment]
I like 2. Also preferably without the extra type synonym.

**Comment by thsutton** [comment]
I like 2; and I would prefer not providing Get', etc.

**Comment by soenkehahn** [comment]
I like 2, without `Get'`, etc. (after changing my mind a few times).

**Comment by seubert** [comment]
I also waffled on this a bit but I think 2 is best in the long run. It gives a sensible pseudo-default but also contains powerful flexibility.

**Comment by mf59816** [comment]
not sure if this poll has long been closed, but I am also in favor of 2.

**Comment by alpmestan** [comment]
It's not closed, it's only been open for 4 days, but I'm tempted to say we can close it already given the votes we got so far =)

**Comment by alpmestan** [comment]
Alright, unless someone has a sensible objection, we'll consider this vote closed. We'll provide content-types aware combinators named `Get`, `Post` and so on **without** their JSON-only counterparts.

Thanks for taking the time to vote everyone :+1:
