### ISSUE TITLE
import jsForAPI docs

### ISSUE THREAD

**Issue by bwo** [haskell-servant/servant#121]
it seems as if this should work:

```haskell
type StaticAPI = "static" :> Raw
type TagsAPI = "pagetags" :> ReqBody '[PlainText] T.Text :> Post '[JSON] ApiResponse

type API = StaticAPI :<|> TagsAPI

data ApiResponse -- blah blah

server' :: Server TagsAPI
server' = undefined -- blah blah
api' :: Proxy TagsAPI
api' = Proxy

apijs = jsForAPI api'
```

But it doesn't:

```
src/Main.hs:123:9:
    Couldn't match type ‘'False’ with ‘'True’
    In the expression: jsForAPI api'
    In an equation for ‘apijs’: apijs = jsForAPI api'
```

The documentation doesn't really indicate what has to be the case for this to work.

**Comment by christian-marie** [comment]
Hmmn. That's a terrible error message. I'll see if I can get that not unifying as opposed to trying to match 'True and 'False.

From there, we can work out what's actually wrong, but, at an absolute glance I suspect it's may be related to posting PlainText, which may or may not be supported in this context.

I agree that it should work, or at least provide an error message that makes sense.

**Comment by bwo** [comment]
Yeah, I worked it out eventually, it looks like only JSON is supported.

**Comment by christian-marie** [comment]
On Sun, Jun 14, 2015 at 06:43:35PM -0700, bwo wrote:
> Yeah, I worked it out eventually, it looks like only JSON is supported.

This is worth documenting, by the way.

Is there some piece of documentation that you've read along the way where we
could have told you about this limitation?

I still think the type family here can be cleaned up, and is worth doing.

**Comment by bwo** [comment]
I had been going by the tutorial, so I would think that http://haskell-servant.github.io/tutorial/javascript.html is a good place for it. 

[This](https://github.com/haskell-servant/servant-jquery/blob/master/src/Servant/JQuery/Internal.hs#L241) appears to be the only instance for `HasJQ` for `Post`s.

**Comment by alpmestan** [comment]
Yeah for now we just support JSON. I would gladly take any patches that lets one configure which content type to get the data under. =) I just wanted a quick solution to get javascript functions for free and have never bothered investigating anything beyond my needs. I don't really know how we would go about handling various others, with jquery/JS.

**Comment by tfausak** [comment]
For what it's worth, I hit this same problem. Luckily I found this issue, otherwise I would've been mystified. Adding something to the documentation that says the `Servant.JQuery` module only supports JSON would be nice.

**Comment by alpmestan** [comment]
Ideally, someone with enough javascript-fu could help us lift that restriction, so that we don't even have to mention it =) For now yeah, we should probably leave a note about this somewhere in the haddocks.

**Comment by codedmart** [comment]
What all would we want to support ideally?

**Comment by alpmestan** [comment]
Maybe the coffee hasn't kicked in yet, but I can't parse this sentence. Did you mean to ask about all the things missing that we would like to have in *servant-js*?

**Comment by codedmart** [comment]
@alpmestan Or my coffee ran out. I was referring to "*module only supports JSON*". I thought we were talking about supporting other content-types. So I was asking ideally which content-types would we want to support ideally.

**Comment by alpmestan** [comment]
Oh. Yeah, we are talking about supporting other content-types. At the very least the ones shipped in the core servant packages (that includes HTML, even though our HTML content types live in their own packages -- *servant-blaze*, *servant-lucid* and *servant-ede*), ideally with a decent way to extend that to user-defined content types. That, along with @freezeboy's recent work, would make *servant-js* a really fine JS client library.

**Comment by christian-marie** [comment]
Has anyone really been far even as decided to use even go want to do look more like?

Also, I'm no longer looking into the type error sucking. Did anyone else have an opinion on True ~ False being a not particularly useful type error?

**Comment by jkarni** [comment]
@christian-marie Removing `True ~ False` in type functions was a good idea before, and very likely still is.

**Comment by soenkehahn** [comment]
See also: #339.

**Comment by fizruk** [comment]
Is this issue still relevant?

**Comment by codedmart** [comment]
@fizruk I can't confirm for sure, but based on some of the tests and changes I would feel like it is not relevant anymore.

**Comment by jkarni** [comment]
https://github.com/haskell-servant/servant/blob/master/servant-foreign/src/Servant/Foreign/Internal.hs#L123 -- I guess we could still improve this by removing that line (or by having it be a more informative error).

**Comment by fizruk** [comment]
@jkarni removed in 1304b17bc2290cccee10642cc22fe098c7ada8bd.
