### ISSUE TITLE
Is it okay to use servant-0.15 for a client and servant-0.16 for a server?

### ISSUE THREAD

**Issue by chshersh** [haskell-servant/servant#1210]
**History:** I have a project that uses `servant-0.15`, and for some reasons not related to `servant` it's not possible to upgrade it to a newer version. I'm using `servant-client` capabilities. At the same time, I would like to upgrade another project to `servant-0.16` which uses `servant-server` capabilities. Moreover, I have a library that provides custom servers and clients:

* https://github.com/holmusk/servant-hmac-auth

My question is: are there any unpredictable things I can expect from using different versions? I've checked the CHANGELOG, but maybe there's something left undocumented:

* http://hackage.haskell.org/package/servant-0.16.2/changelog

Maybe some additional headers are added automatically to request or anything else? I'm asking the package maintainers because I hope they have insights regarding various versions compatibility or have a similar experience :slightly_smiling_face:

**Comment by phadej** [comment]
Maybe.

Looking at https://github.com/haskell-servant/servant/blob/master/servant/CHANGELOG.md#016, we didn't change anything in `servant` itself, nor how client or server interpret APIs.

I'm 99% sure that all PRs are mentioned in the changelog (only 99% because it's not automated process).

**Comment by jkarni** [comment]
Closing this, but feel free to re-open if you feel like something is needed.
