### ISSUE TITLE
$.ajax should set content-type on post

### ISSUE THREAD

**Issue by bwo** [haskell-servant/servant#122]
if we're posting JSON, the content-type should be set explicitly to application/json.

**Comment by alpmestan** [comment]
Sorry for leaving this without an answer. We might want to fix that in the next bugfix release. @christian-marie does that sound doable?

**Comment by christian-marie** [comment]
It does indeed. I'm going to be rather busy this weekend is all. I'll make some time on Sunday to look into this and cherry-pick some other fixes.

**Comment by christian-marie** [comment]
OK so this would take me a while and require threading extra information into the AjaxReq data type, at a first glance. I won't be doing this. If anyone wants to get a PR in very quickly we can include it?

**Comment by bwo** [comment]
that is somewhat surprising, since as it stands `servant-jquery` will generate a javascript function that, IME, can't actually be used with servant, making it somewhat less than useful, and there's apparently enough information to know to call `JSON.stringify`: https://github.com/haskell-servant/servant/blob/master/servant-jquery/src/Servant/JQuery.hs#L68 (or rather, it's assumed that one will want to do that, even though one might be POSTing some other way---but if the assumption is made partly, why not make it all the way?).

**Comment by bwo** [comment]
And the only POST that's `HasJQ` is one using JSON: https://github.com/haskell-servant/servant/blob/master/servant-jquery/src/Servant/JQuery/Internal.hs#L242

**Comment by christian-marie** [comment]
You're correct. I was working on the assumption that servant-jquery supports content types other than JSON, which it does not.

I'll put a quick PR together, but I don't use this particular library or do any javascript myself. Someone will have to verify it's OK.

**Comment by christian-marie** [comment]
Please review @bwo

**Comment by bwo** [comment]
I made a different PR:  https://github.com/haskell-servant/servant/pull/149 since that seemed the easier way to describe the changes, though as I said there I'm also inexpert. I would think that setting a content-type regardless of method or whether a body is present is not correct, though.
