### ISSUE TITLE
Versionning policy for servant packages

### ISSUE THREAD

**Issue by alpmestan** [haskell-servant/servant#123]
Hi everyone,

While it hasn't been much of a preoccupation up until now, we probably should have a discussion and settle down on a clear and principled versionning policy for the core servant packages as well as the "auxiliary ones".

I'm bringing this up because of the following situation.

I recently wrote [servant-ede](http://hackage.haskell.org/package/servant-ede) to use the [ede](http://hackage.haskell.org/package/ede) templating engine with servant, only for HTML although the engine doesn't care what the content type of the text it processes is. I released it as 0.4, so that it was in sync with servant.

After some time, someone contacted me to figure out whether we could generalize the code there a bit to support arbitrary content types, just like *ede*, which I wanted to do at some point anyway but this made me think and discuss about this to find the best solution. We found a quite good one (see [here] for the curious) but it'll require introducing breaking changes, which suggests the next version should be 0.5, to be used with servant-* 0.4.x.x. It's a bit annoying.

Similarly, if one of the core servant packages introduces a breaking change (such as the new routing stuffs in **master**), that prompts the question of whether we should make a major version bump on all other **core** servant packages?

My personal opinion on this is that auxiliary packages should try, when possible, to stay in sync with the core packages, but shouldn't influence versionning of core packages (the ones in the servant repo). However, if a core package requires a major version bump, I'd say we bump the other core packages too. 

As usual, let's hear all the arguments and collectively decide on a policy that we can just stick to later, down the road.

**Comment by jkarni** [comment]
Supposing we decide `servant-ede` isn't a core package and doesn't get to cause bumps on other core packages, I guess it shouldn't even try to be in sync with the core packages.

**Comment by jkarni** [comment]
@alpmestan can we close and say we ourselves won't try to match core package versions (and everyone else can of course do whatever they want)?

**Comment by alpmestan** [comment]
Sounds good.
