### ISSUE TITLE
Why is the repo behind Hackage?

### ISSUE THREAD

**Issue by fosskers** [haskell-servant/servant#1260]
Hackage advertises `servant-0.16.2`, but `master` here only has `0.16`. Has someone forgotten to push some commits?

**Comment by fosskers** [comment]
And this module is very strange:
http://hackage.haskell.org/package/servant-0.16.2/src/src/Servant/API/Verbs.hs

It's completely missing the definition of the `NoContentVerb` type.

**Comment by phadej** [comment]
See `0.16` branch. I haven't bumped any versions in `master`.

**Comment by fosskers** [comment]
Thanks.
