### ISSUE TITLE
Foreach fails with ConnectionClosed

### ISSUE THREAD

**Issue by sashasashasasha151** [haskell-servant/servant#1265]
Trying to rewrite old behaviour
```haskell
onStreamItem
  :: MonadUnliftIO m
  => ResultStream a -> (Either String a -> m ()) -> m ()
onStreamItem (ResultStream k) onItem = withRunInIO $ \runM ->
  k $ \getResult ->
    let loop = do
          r <- getResult
          case r of
            Nothing -> pure ()
            Just x  -> runM (onItem x) >> loop
    in loop
```

With new version  streaming refactoring
```haskell
onStreamItem
  :: (MonadUnliftIO m, Show a)
  => SourceIO a -> (a -> m ()) -> m ()
onStreamItem stream onItem = withRunInIO $ \runM ->
  foreach fail (runM . onItem) stream
```

But get ConnectionClosed error

**Comment by phadej** [comment]
Hard to say what happens. You can use [`SourceT.readFile`](https://hackage.haskell.org/package/servant-0.16.2/docs/Servant-Types-SourceT.html#v:readFile) to mimimize the example, as the `withFile` inside that `readFile` is similar to `withResponse` `servant-client` uses (e.g.).

Without that it's hard to guess anything.

**Comment by sashasashasasha151** [comment]
Probably should've told you, that it works fine when stream has elements, but in the end it fails\
Looks like it close connection after some period of time

**Comment by phadej** [comment]
Same should apply if you `readFile` an empty file.

**Comment by sashasashasasha151** [comment]
Any thoughts how can I fix it?

**Comment by phadej** [comment]
> Without the example I can run, I'd rather not guess what might be the cause.

**Comment by kirelagin** [comment]
Looks like the problem on our side was due the `SourceIO` value leaking outside `withClientM`. 🙄
Maybe tag it with a phantom variable?

**Comment by phadej** [comment]
It wouldn't work. You just to be careful as with all `with*` methods, is it `withFile`, `withResponse` (`http-client`) or `withClientM`.

```haskell
foo = do
    -- reader :: IO String
    reader <- withFile "file.txt" $ \hdl ->
        return (hGetContents hdl)

    -- leaked! To prevent this with phantom variable trick,
    -- one would need to parametrise "everything"
    -- with that phantom type.
    reader

    -- The ST s is different, as there aren't resources
    -- which are freed at the end of runST. It would break similarly
    -- if all created references would be "destroyed" / invalidated.
    -- That won't be that useful.
```
