### ISSUE TITLE
servant-docs: pretty-printing content

### ISSUE THREAD

**Issue by mf59816** [haskell-servant/servant#127]
The content in the servant documentation is printed out with `MimeRender`, which is intentionallly whitespace-free.  In documentation, we would like to call pretty-printing variants of the underlying functions, though.

I think I have a work-around for this that works reasonably well: https://github.com/liqd/thentos/issues/155

I am opening this ticket to express that this should be fixed in servant-docs propertly.  As something close to my work-around, I could see a patch that provides an extra function

```haskell
docs' :: HasDocs layout => [(M.MimeType, ByteString -> ByteString)] -> Proxy layout -> API
```

That allows people to pass their own pretty-printers explicitly.  If you would like me to I am happy to provide a pull request, but this is clearly not in the spirit of servant.  Perhaps you have a better idea?

**Comment by alpmestan** [comment]
Another thing you could do is define a `PrettyJSON` content type that uses `aeson-pretty` or something to encode values in a human-friendly JSON format. You can then substitute `PrettyJSON` for `JSON` in your API type (programmatically -- with a type families -- would be the best option I think) and use *that* API type to generate your docs.

``` haskell
data PrettyJSON

instance Accept PrettyJSON where
  accept _ = "application" // "json"

instance ToJSON a => MimeRender PrettyJSON a where
  mimeRender _ val = encodePretty val

type family Prettify api :: *
-- define it so that it looks for Get, Post, etc but also ReqBody, and replaces
-- any occurence of "JSON" by "PrettyJSON" in the content type lists.

prettified :: Proxy api -> Proxy (Prettify api)
prettified Proxy = Proxy

prettyDocs :: Proxy api -> API
prettyDocs = docsFor . prettified
```

**Comment by jkarni** [comment]
I like both suggested approaches quite a bit.

**Comment by jkarni** [comment]
Done in #289 .

**Comment by tfc** [comment]
Hey there,

i got this to work with `docs` and `docsWithIntros`, but not with `docsWith` where i also provide extrainfos etc.: The compiler does then complain that it can't match the `JSON` with the `PrettyJSON` part.
I am not educated enough about type families etc., is there a fix/workaround for that?

**Comment by alpmestan** [comment]
@tfc Is there any chance you could reproduce your problem on a self-contained example? Or share a link to the code in question if it's publicly available?

**Comment by tfc** [comment]
@alpmestan i figured it out an hour ago.

My extra infos needed to look like this: (Added `Pretty` everywhere and needed to include `Servant.Docs.Internal.Pretty (Pretty(..))`)

```haskell
extra :: ExtraInfo (Pretty MyApi)
extra =
    let synopsisFor proxy summary = extraInfo proxy $
            defAction & notes <>~ [DocNote "Synopsis" [summary]]
    in synopsisFor (Proxy :: Proxy (Pretty Foo)) "Description Foo"
    <> synopsisFor (Proxy :: Proxy (Pretty Bar)) "Description Bar"
```

It would have helped me if such change was suggested by the documentation, but i think that i just didn't think of this earlier was just my lack of experience with servant.

**Comment by alpmestan** [comment]
Ha, glad to hear you figured it out, and thanks for leaving a trace.

Note that we're always happy to receive documentation PRs, whether they touch the tutorial or the haddocks. If you have an idea of how the current docs can be improved to prevent the confusion you had, we'd be delighted to review the patch. :-)
