### ISSUE TITLE
Lack of documentation for genericServerT prevents its correct use and its understanding

### ISSUE THREAD

**Issue by Kleidukos** [haskell-servant/servant#1278]
To this day, [genericServerT](https://hackage.haskell.org/package/servant-server-0.17/docs/Servant-Server-Generic.html#v:genericServerT) suffers from a lack of documentation, explanation of its differences from `genericServer`, and example usages.

This being combined to the rather obtuse type signatures one can find in Servant codebases, Haskell developers who are new to the framework or even to codebases using it are easily lost.

cc @alpmestan

**Comment by phadej** [comment]
```haskell
genericServer  :: GenericServant routes  AsServer     => routes  AsServer     -> ToServant routes  AsServer
genericServerT :: GenericServant routes (AsServerT m) => routes (AsServerT m) -> ToServant routes (AsServerT m)
```

I don't really know what one could write about `genericServerT` except the

> Transform record of endpoints into a `ServerT m`.

Where `genericServer` is documented as 

> Transform record of endpoints into a `Server`.

---

An example usage is in https://docs.servant.dev/en/stable/cookbook/generic/Generic.html#using-generics-together-with-a-custom-monad

**Comment by Kleidukos** [comment]
@phadej It may be not much but still significantly better than nothing. :)
Linking or including the example usage would be quite an improvement as well.
Do you wish me to make a PR in that direction?

**Comment by phadej** [comment]
I really have no opinion, if you think you know how to improve the docs, please make a PR.

**Comment by Kleidukos** [comment]
Closed by https://github.com/haskell-servant/servant/pull/1279
