### ISSUE TITLE
Link for 'QueryParam sym v' asks for a value of type 'v' instead of 'Maybe v'

### ISSUE THREAD

**Issue by alpmestan** [haskell-servant/servant#129]
From `Servant.Utils.Link`:

``` haskell
instance (KnownSymbol sym, ToText v, HasLink sub)
    => HasLink (QueryParam sym v :> sub) where
    type MkLink (QueryParam sym v :> sub) = v -> MkLink sub
```

Shouldn't that be

``` haskell
type MkLink (QueryParam sym v :> sub) = Maybe v -> MkLink sub
```

We may very well want to link to the endpoint/page without specifying any value for a query param, which is not possible with the current instance.

**Comment by jkarni** [comment]
yup.

**Comment by alpmestan** [comment]
But this is a breaking change so that will only go in 0.5 I guess?
