### ISSUE TITLE
Custom types in API

### ISSUE THREAD

**Issue by ip1981** [haskell-servant/servant#1296]
I could not find anything related, except maybe the #766.

So here is what I'd like to have (at least for the client):

```haskell
data MyType = Foo Int | Bar String | Zzzz Int Int
-- and the URLs like "/example?foo=1" or "/example?bar=qwerty" or "/example?z1=1&z2=2"
type API = "example" :> MyType :> Get '[ JSON] Int
...

clientFunction :: MyType ->  ClientM Int
...
```

What classes/types families should I implement?

**Comment by ericnething** [comment]
You'll want to define instances for `ToHttpApiData` and `FromHttpApiData`. https://hackage.haskell.org/package/servant-0.17/docs/Servant-API.html#t:ToHttpApiData

**Comment by dmjio** [comment]
@ip1981 you'll need to implement `HasClient api => HasClient (MyType :> api)`, you can most likely copy the existing code for `QueryParam` and modify it slightly for your data type. See https://github.com/haskell-servant/servant/blob/master/servant-client-core/src/Servant/Client/Core/HasClient.hs#L432

**Comment by ip1981** [comment]
Yes, that was it. For future references, there is similar question: https://github.com/haskell-servant/servant/issues/884

And my solution: https://github.com/ip1981/openweathermap/commit/27b29703a46bcde319961c2b52d38da3513a1da8
