### ISSUE TITLE
New maintainers need github / hackage ownership.

### ISSUE THREAD

**Issue by fisx** [haskell-servant/servant#1313]
@arianvp and @fisx have offered to take over maintainership of the servant project, and we've already added our first repo towards the end of [zurihac](https://github.com/haskell-servant/servant/issues/1299) (thanks @domenkozar !).

Now we would need ownership status here on github and hackage in order to be able to do our job.

Currently, @alpmestan @domenkozar @fizruk @jkarni @soenkehahn are listed as owners.

as soon as this is resolved, we can get busy releasing and announcing servant-uverb!  :)

**Comment by fisx** [comment]
(Also, i'm curious as to who feels actively responsible for servant?  I know that @fizruk and @arianvp and I do.  Anybody else?)

**Comment by fizruk** [comment]
@fisx @arianvp I have updated your role on GitHub.

**Comment by fizruk** [comment]
On Hackage I do not have maintainership of packages except `servant-swagger`, so someone else should help with that :)

**Comment by dmjio** [comment]
I'm a maintainer too, can you update my role as well @fizruk ?

**Comment by fizruk** [comment]
@dmjio of course, done!

**Comment by fisx** [comment]
I just invited @Taneb (welcome!), who re-wrote servant-uverb with me last week-end, and wants to help with https://github.com/haskell-servant/servant/pull/1314.

Are there any rules in that I should follow when inviting people to the project?
