### ISSUE TITLE
servant-client-core bump base64-bytestring

### ISSUE THREAD

**Issue by arianvp** [haskell-servant/servant#1334]
```
 In the dependencies for servant-client-core-0.18:
     base64-bytestring-1.1.0.0 from stack configuration does not match
 >=1.0.0.1 && <1.1  (latest matching version is 1.0.0.3)
 servant-client-core will need a revision to support latest base64-bytestring

```

**Comment by arianvp** [comment]
@domenkozar where are you getting this error and with what stackage snapshot? We should probably update the stackage snapshot in stack.yaml  also I should probably sign us up for stackage build failures. I dont know much about stackage so if someone can guide me how to do that that'd be great =)

**Comment by domenkozar** [comment]
I'm testing following stack.yml on servant-auth repo:

```
resolver: nightly-2020-08-31
packages:
- servant-auth
- servant-auth-server
- servant-auth-client
- servant-auth-docs
- servant-auth-swagger
extra-deps: 
- servant-client-core-0.18
- servant-server-0.18
```

We'd need to add servant back to https://github.com/commercialhaskell/stackage/ (see merged PRs for example) and add it under your maintenance
