### ISSUE TITLE
Add servant back to stackage

### ISSUE THREAD

**Issue by arianvp** [haskell-servant/servant#1340]
https://github.com/commercialhaskell/stackage/blob/master/build-constraints.yaml#L1540

Now that everything builds with GHC 8.10 #1331 #1295 we should be able to re-add ourselves.

I do not know who controls that current mailing list that's in build-constraints. If the answer is that nobody does anymore than we should update it

**Comment by arianvp** [comment]
Probably needs https://github.com/haskell-servant/servant/issues/1334 too

**Comment by arianvp** [comment]
I asked around about the mailing list; but nobody responded. I suggest we create a new email address with the new maintainers; instead of trying to get hold of ownership of the old one.

**Comment by domenkozar** [comment]
I'd recommend https://github.com/haskell-servant/servant-auth/blob/master/.github/workflows/ci.yml

**Comment by arianvp** [comment]
Nice it seems a bit simpler than the haskell-ci stuff; which only seems to work with travis. I'll have a look

**Comment by domenkozar** [comment]
Yeah I find having CI abstraction in a releasable haskell package quite a feedback killer.

**Comment by serras** [comment]
I think with #1348 merged, you can now try to add it again to Stackage.

**Comment by maksbotan** [comment]
Done! Core packages, `servant-blaze`, `servant-multipart` and `servant-swagger-ui` are in nightly now: https://www.stackage.org/diff/nightly-2020-11-06/nightly-2020-11-08
