### ISSUE TITLE
Handler with resource (ala ResourceT) handling

### ISSUE THREAD

**Issue by andremarianiello** [haskell-servant/servant#1345]
I am currently in a situation when I and writing an endpoint handler that has an api like `Stream .... (SourceIO Thing)`, and this stream is infinite. It is designed to only terminate when the client leaves and the ClientConnectionIsClosed exception is thrown in streamHandler. However, I allocated resources in this endpoint handler that I want to free when the request thread dies, but looking at the existing code it seemed impossible. In an effort to make this possible, I created a new API type

```haskell

data WithResource a

instance (HasServer api ctx, HasContextEntry ctx (Acquire a)) => HasServer (WithResource a :> api) ctx where
  type ServerT (WithResource a :> api) m = (ReleaseKey, a) -> ServerT api m
  hoistServerWithContext _ pc nt s = hoistServerWithContext (Proxy @api) pc nt . s
  route _ ctx subserver = route (Proxy @api) ctx (subserver `addParameterCheck` foo)
    where
      foo :: DelayedIO (ReleaseKey, a)
      foo = DelayedIO $ lift $ allocateAcquire (getContextEntry ctx)
```

This allows me to run the server by providing an `Acquire a` in the context passed to `serveWithContext`, and safely use the `a` in my handler. This uses the ResourceT that already exists in the DelayedIO stack.

Is this the best way to do this? And if so, should I make a PR?

**Comment by andremarianiello** [comment]
This might help people suffering from https://github.com/haskell-servant/servant/issues/741 or https://github.com/haskell-servant/servant/issues/676

**Comment by andremarianiello** [comment]
Should this be a part of servant or should it be relegated to a separate library?

**Comment by alpmestan** [comment]
It is for sure a great candidate for a companion library. I wouldn't mind it being part of the core libs and covered in a tiny cookbook page or something, but have no strong opinion.

Thanks for sharing it here regardless of what's done with it.

(Sorry for not noticing this earlier)

**Comment by tchoutri** [comment]
I support the integration in the core library, and will condition my approval on the presence of a corresponding Cookbook :)
