### ISSUE TITLE
Redirecting from inside a handler

### ISSUE THREAD

**Issue by jhickner** [haskell-servant/servant#135]
I just thought I'd post this since it took me a while to figure out. Please comment if there's a better way to do this:

    import Control.Monad.Trans.Either

    redirect303 :: Monad m => ByteString -> EitherT ServantErr m a
    redirect303 url = left err303 { errHeaders = [("Location", url)] }

    -- then, inside your handler you can:
    redirect303 "/login"

**Comment by alpmestan** [comment]
Hello,

I've suggested the inclusion of a generic `Redirect` combinator [here](https://github.com/haskell-servant/servant/issues/117). Maybe that would be of interest to you too?

**Comment by jhickner** [comment]
Would you use that just like `Headers`? That would be great. How would you make it optional though? For instance how do you encode the idea that the route may return some JSON object or it may redirect?

**Comment by alpmestan** [comment]
Here's how it would be used:

``` haskell
"users" :> ReqBody '[FormUrlEncoded] User :> Redirect Post ViewUser UserAPI
-- where ViewUser is, e.g:
type ViewUser = "users" :> Capture "userid" UserId :> Get '[HTML] User
-- and UserAPI contains ViewUser
```

This would describe an endpoint reachable with **POST** requests, which when successful redirects you to a user profile. What you have to do for that is provide an URI (to be used as the value of the `Location` header) as the return value of your handler, and the only way to do that within servant is to use the [safe link module](https://hackage.haskell.org/package/servant-0.4.2/docs/Servant-Utils-Links.html).

Is that clearer now? Let me know if you want some more explanations or an actual complete example you can examine and toy around with.

**Comment by jkarni** [comment]
> How would you make it optional though? For instance how do you encode the idea that the route may return some JSON object or it may redirect?

@jhickner That's not (easily and neatly - i.e., without abusing `Left`) that easy with the current situation. That's a pretty general problem - HTTP status codes are currently *too* static (modulo `Left`). For now, I think your original approach might be best...

**Comment by jhickner** [comment]
The `Redirect` combinator wouldn't cover the use case that prompted this question, but it looks very useful in general. I think `Left` is the right approach or what I needed to do, which was redirect in case of error.

**Comment by jkarni** [comment]
Closing this since we already have an open issue for static redirects, and it seems we all agree `Left` is the right approach for dynamic ones. (Feel free to reopen if anyone disagrees.)
