### ISSUE TITLE
IO functions in Servant

### ISSUE THREAD

**Issue by shubham1172** [haskell-servant/servant#1352]
So I want to use the current timestamp inside an API handler, and this is how I ideally get time in an IO context
```haskell
import Data.Time.Clock.POSIX
getTime :: Integral b => IO b
getTime = round `fmap` getPOSIXTime 
```
What is the idiomatic way of doing IO in this situation? I really want to avoid using `unsafePerformIO`!

**Comment by fisx** [comment]
Yes, please don't use `unsafePerformIO`!  No need for an issue, though, [it's all in the docs :)](https://docs.servant.dev/en/stable/tutorial/Server.html#performing-io)

**Comment by shubham1172** [comment]
Thanks @fisx!!
