### ISSUE TITLE
Remove travis and migrate to Github Actions

### ISSUE THREAD

**Issue by arianvp** [haskell-servant/servant#1353]
Travis is dropping support for OSS projects. I have no budget to pay them.

**Comment by fisx** [comment]
not saying we shouldn't, but: https://bugs.chromium.org/p/project-zero/issues/detail?id=2070&can=2&q=&colspec=ID%20Type%20Status%20Priority%20Milestone%20Owner%20Summary&cells=ids

**Comment by arianvp** [comment]
https://github.com/haskell-CI/haskell-ci/pull/416 has landed. This should make our lives a lot easier as we do not have to rewrite our CI from scratch but can keep using the existing CI files!!

**Comment by gdeest** [comment]
Fixed by #1402 .
