### ISSUE TITLE
UVerb doesn't understand Headers

### ISSUE THREAD

**Issue by intolerable** [haskell-servant/servant#1373]
`Headers` types can't be included in UVerb unions as there's no equivalent to the `HasServer (Verb meth st cts (Headers h a))` instance for UVerb.

**Comment by arianvp** [comment]
Thanks. This indeed seems to be an omission. I don't think it's too hard to add.

**Comment by arianvp** [comment]
@akshaymankar do you perhaps want to take a jab at this?

**Comment by the-dr-lazy** [comment]
I can work on this with some help from maintainers if it's available.

**Comment by the-dr-lazy** [comment]
What would be the ideal and possible representation? Is it possible to combine header-containing response with not header-container responses?

```hs
type Response
  = '[ Headers '[Header "Location" Text] (WithStatus 303 NoContent)
     , WithStatus 404 NoContent
     ]

type Route = UVerb 'POST '[JSON] Response
```
