### ISSUE TITLE
Gripes from porting oauth2 server to servant

### ISSUE THREAD

**Issue by christian-marie** [haskell-servant/servant#138]
This is a ticket that doesn't need any action.

It's to be a place where we note places of friction when using servant to do things that servant perhaps wasn't designed for (building an oauth server).

I think that some of these things are worth improving, and the flexibility is something we want.

The idea here is to get people talking productively as opposed to just getting annoyed and not mentioning it again.

**Comment by christian-marie** [comment]
Being able to handle decode failures explicitly would be nice, I'm not sure how this would look, yet, but it would save us from this weird hack:

https://github.com/anchor/oauth2-server/pull/74/files

**Comment by christian-marie** [comment]
Having static response headers would be useful too. It'd be nice if servant shipped with types that did things like always send: Cache-Control: no-store

**Comment by alpmestan** [comment]
> Being able to handle decode failures explicitly would be nice, I'm not sure how this would look, yet, but it would save us from this weird hack:
>
> https://github.com/anchor/oauth2-server/pull/74/files

I'm pretty sure you don't want the decoding failure to be handled explicitly all the time. I had to use `FormUrlEncoded` a couple of weeks ago, so I see what your needs are here. I definitely would like to somehow let room for specifying what to do when the decoding fails, because you typically want to say "you forgot to fill that field" -- I suppose this is what your PR is about too?

The point is, if we could say in the instance or somewhere what we want to do when the decoding fails (and how to generate a `Response` from that), that would solve my little grip with it. Yours too? If yes, maybe we could try and think of a way to accomplish that?

> Having static response headers would be useful too. It'd be nice if servant shipped with types that did things like always send: Cache-Control: no-store

You can do that with a very trivial middleware. That's one of the things I use them for. We are by the way thinking about a `Middleware` combinator to apply a middleware to just a part of an API.

**Comment by christian-marie** [comment]
Thanks for your input @alpmestan.

> The point is, if we could say in the instance or somewhere what we want to do when the decoding fails (and how to generate a `Response` from that), that would solve my little grip with it. Yours too? If yes, maybe we could try and think of a way to accomplish that?

Yes, I think we have similar needs there.

If we could attach an IO/any monadic action to that too, we would have all of the flexibility to do anything. Not so sure we need anything that drastic yet, though.

@thsutton, @tvh, do you think that simply generating a certain Response from the a decode failure fits our use case?

> > Having static response headers would be useful too. It'd be nice if servant shipped with types that did things like always send: Cache-Control: no-store

> You can do that with a very trivial middleware. That's one of the things I use them for. We are by the way thinking about a `Middleware` combinator to apply a middleware to just a part of an API.

That's a good point, although we only want to add the header for a few endpoints. Perhaps this shouldn't be part of our API type, it's more of an implementation detail I'd prefer to hide. I'll have to think about this more, perhaps all static headers do belong in middleware.

**Comment by alpmestan** [comment]
Regarding the last point, you can tell the middleware to only add the `Cache-Control` header for those endpoints, as long as you can restrain the endpoints as constraints on the request (e.g *the request path begins with "/users"*).

**Comment by jkarni** [comment]
> Being able to handle decode failures explicitly would be nice, I'm not sure how this would look, yet

This is a good point. I started playing around with unifying the errors from within the handlers and the combinators, and one idea that came out of that is that it'd be very easy to have combinators that modify failures. E.g.

       type API = Some400ToMyErr :> RestOfApi

with 

     instance ... Server Some400ToMyErr :> rest where
         type ... = Server rest
         route _ x = case x of 
             Left err | err `isSpecific400` -> <change err>
             ...

Also, it's looking like we need really need a middleware combinator...

**Comment by fizruk** [comment]
Is this issue still relevant?

**Comment by jkarni** [comment]
> Is this issue still relevant?

I think we should close it, and re-open more specific ones if they are still a problem.

**Comment by christian-marie** [comment]
This is ancient. It's relevance, debatable.
