### ISSUE TITLE
Use uri-bytestring instead of network-uri in next major?

### ISSUE THREAD

**Issue by christian-marie** [haskell-servant/servant#139]
How do we feel about me replacing all references of network-uri with uri-bytestring. I'm noticing some bytestring packing going on in production code where safeLink is being used, which I'd like to avoid.

It seems like a nicer API, too.

https://hackage.haskell.org/package/uri-bytestring-0.1.5/docs/URI-ByteString.html

**Comment by alpmestan** [comment]
Is it taking that much time? Anyway, I wouldn't mind it at all, as long as we have a good enough reason to give to the users. We're on a breaking change spree anyway =)

**Comment by christian-marie** [comment]
This isn't a performance change as much as "you should probably be using a bytestring anyway". It's also that uri-bytestring provides lenses and a nicer interface (in my opinion).

**Comment by christian-marie** [comment]
@oswynb as a user, did you have any particular reason why you liked this interface more?

**Comment by tvh** [comment]
`network-uri` has a few very weird invariants. https://github.com/haskell/network-uri/issues/2 and https://github.com/haskell/network-uri/issues/11 describe the most obvious ones.

**Comment by oswynb** [comment]
I like the clear distinction between relative/absolute URIs, the useful parse errors instead of just a Maybe and I do prefer ByteStrings over Strings as a general fact. Also agree with @tvh's refs.

**Comment by oswynb** [comment]
Hrmm, it seems that uri-bytestring doesn't support query flags nor array/matrix parameters. The network-uri has a ByteString for the Query whereas uri-bytestring has a Query type which is a list of (ByteString, ByteString) tuples which it forces into things of form ?foo=bar&baz=bar.

**Comment by tvh** [comment]
That is not quite true. A flag is basically a parameter without a value. That means the following are equivalent:

```
?foo=&baz=
?foo=&baz
?foo&baz
```

I haven't checked how uri-bytestring does it's rendering here though. The `FormUrlEncoded` stuff does this in it's parsing as well.

**Comment by mf59816** [comment]
I've implemented RelativeRefs in uri-bytestring and I'm interested in writing any other missing parts.

I expect flags to be easy (and welcome as a patch for uri-bytestring), but if I'm not mistaken, matrix parameters change their semantics depending on their position in the path.  I'm not sure how to implement that with a minimum of surprise for the other users.

One way I can think of is to replace the `ByteString`-typed paths in `URI` etc. with something like this:

```haskell
data Path = Path { fromPath :: ByteString } | MatrixPath { fromMatrixPath :: [Segment] }
data PathSegment = PathSegment ByteString | MatrixSegment ...
```

(I am not very familiar with matrix parameters, so I'm not sure if this makes any sense.)

**Comment by oswynb** [comment]
Matrix parameters are query parameters that fit within segments of a path and use ';' instead of ? and &

so baseurl/captureOne;m1=v1;m2=v2/captureTwo;m3=v3?q1=qv1

Maybe something similar to what Servant has now could work for uri-bytestring?

```haskell

data URI
  { uriScheme :: Scheme
  , uriAuthority :: Maybe Authority
  , uriPath :: Path
  , uriQuery :: [QueryParam]
  , uriFragment :: Maybe ByteString
  }

data QueryParam
  = QueryParam ByteString ByteString
  | QueryFlag ByteString

data MatrixParam = MatrixParam ByteString ByteString

type Path = [Segment]

data Segment = Segment ByteString [MatrixParam]

```

^ Something like that?

**Comment by mf59816** [comment]
Yes, that looks more coherent.

**Comment by mf59816** [comment]
(I've opened two uri-bytestring issues for these.)

**Comment by alpmestan** [comment]
Thanks, that's appreciated! `network-uri` being on life-support mode isn't exactly the ideal situation for us, so I would definitely approve a move to `uri-bytestring` once it has everything we need. Are other web libraries moving to it too by the way?

**Comment by fizruk** [comment]
Is this issue still relevant?

**Comment by jkarni** [comment]
If a PR comes along showing performance, it'd be welcome, but I think we can close. https://github.com/Soostone/uri-bytestring/issues/12 is still open.

**Comment by christian-marie** [comment]
On Wed, Jan 20, 2016 at 04:30:40AM -0800, Nickolay Kudasov wrote:
> Is this issue still relevant?

This issue was created well before Servant had a major revamp, so I think that
it can be closed.

**Comment by dbaynard** [comment]
Hello, I see this has been closed but @mrkkrp has just released `modern-uri`. It isn't clear to me why this issue is not still relevant; in my own code I've had to write shims between `network-uri` and `uri-bytestring` and while adding another option into the mix doesn't by itself help, if it becomes a maintained library that offers the features of `network-uri` with the (more useable, IMHO) interface of `uri-bytestring` I would recommend it for consideration.

**Comment by alpmestan** [comment]
Maybe we can give it a bit of time before switching over to it, assuming it becomes the go-to option?

**Comment by dbaynard** [comment]
Of course. It seemed from this thread there were some requirements for a uri library; this may be a good opportunity to have somebody implement some of them. There's a current r/haskell discussion.

**Comment by phadej** [comment]
`network-uri` is used in
- `servant-client` (I guess because `http-client` uses it?)
- `Servant.Utils.Links`, here we want something which is relatively cheap. It's easy to write `Link -> YourURI` function, if you want ot use something else.

In short, I don't see a need to change even in the long-term. In fact, we could even drop `network-uri` dependency from `Servant.Utils.Links` completely, and instead provide good enough API for consuming `Link`. (IIRC I use `Link` directly atm)

**Comment by dbaynard** [comment]
Oh, yes `Link` is great. I'd rather use that when interacting with servant than have to use a term level uri library.
