### ISSUE TITLE
Example in Servant.API.ContentTypes uses ReqBody with Get inappropriately

### ISSUE THREAD

**Issue by tysonzero** [haskell-servant/servant#1405]
```haskell
type MyEndpoint = ReqBody '[JSON, PlainText] Book :> Get '[JSON, PlainText] Book
```

This goes against the recommendations of the HTTP spec, and in practice frequently does not work.

**Comment by fisx** [comment]
Well, id *does* work if you implement it like this.  :)  But point taken, the examples should be standard-compliant.

If you submit a PR, it'll probably trivial enough that somebody will click *merge* soon.  Perhaps you can keep the body, and replace the `Get` with a `Put`?  Haven't checked the context.

**Comment by tysonzero** [comment]
Does it work?

I had something similar recently (what I really wanted was `QueryParamForm` but I had `ReqBody '[FormUrlEncoded]` instead) and I got 400 errors in safari.

Hmm `Put` seems a little weird semantically, but I suppose `Post` doesn't imply idempotency, so `Put` is a little closer in that regard.

**Comment by alpmestan** [comment]
Patch at #1429
