### ISSUE TITLE
Can't get result in tests

### ISSUE THREAD

**Issue by Sergey111991KV** [haskell-servant/servant#1425]
Hi Guys! I have some problem with spec tests and servant, for example:

type MyAPI = ProtectedWithJWT :> "request" :> ReqBody '[JSON] SomeParametres :> Post '[JSON] (Web.WebApiHttpResponse SomeEntity)

data WebApiHttpResponse res
  = FailedWebApiHttpResponse [WebApiHttpError]
  | SuccessfulWebApiHttpResponse res

When I start server - all good) I catch FailedWebApiHttpResponse [WebApiHttpError] or SuccessfulWebApiHttpResponse SomeEntity. But when I start e2e tests I have problem((  I catch SuccessfulWebApiHttpResponse SomeEntity or FailedWebApiHttpResponse [] - without any error. What could be the problem?

**Comment by alpmestan** [comment]
The description of your problem is a bit fuzzy here. Any chance you could expand a bit with perhaps a minimal reproducer for your issue?

**Comment by Sergey111991KV** [comment]
I solved this issue yesterday, but forgot to write it here. Sank you!)
