### ISSUE TITLE
allow http-api-data-0.4.3

### ISSUE THREAD

**Issue by juhp** [haskell-servant/servant#1428]
See commercialhaskell/stackage#5941

http-api-data-0.4.3 ([changelog](http://hackage.haskell.org/package/http-api-data-0.4.3/changelog)) (Nickolay Kudasov <nickolay.kudasov@gmail.com> @fizruk, Stackage upper bounds) is out of bounds for:
- [ ] servant-0.18.2 (>=0.4.1 && < 0.4.3). Haskell Servant <haskell-servant-maintainers@googlegroups.com>. @haskell-servant. Used by: library
- [ ] servant-server-0.18.2 (>=0.4.1 && < 0.4.3). Haskell Servant <haskell-servant-maintainers@googlegroups.com>. @haskell-servant. Used by: library

**Comment by tchoutri** [comment]
Fixed by #1409
