### ISSUE TITLE
Simplify serveWithContext ErrorFormatters constraint

### ISSUE THREAD

**Issue by brandon-leapyear** [haskell-servant/servant#1437]
`servant-server-0.18` added the `HasContextEntry (context .++ DefaultErrorFormatters) ErrorFormatters` constraint to `serveWithContext`, which is annoying to rewrite if one writes a helper function around `serveWithContext`.

It seems like this constraint is redundant if you just call `mkContextWithErrorFormatter` before passing the `context` to `route`.

**Comment by alpmestan** [comment]
@brandon-leapyear Do you have a suggestion to improve the experience of writing helpers around `serveWithContext`, or for giving a less cumbersome constraint there in the first place?

**Comment by brandon-leapyear** [comment]
hm it seems like my idea didn't work. i guess servant could provide a type alias, so it's at least not so cumbersome, like
```hs
type IsValidContext context =
  ( HasContextEntry (context .++ DefaultErrorFormatters) ErrorFormatters
  , ... -- in the future, could add other constraints needed, if more default context entries are added
  )
```

**Comment by alpmestan** [comment]
I find `IsValidContext` to be a bit too cryptic without conveying any illuminating information. `ServerContext`?

**Comment by brandon-leapyear** [comment]
yeah, `ServerContext` sounds good!
