### ISSUE TITLE
Improve serve functions

### ISSUE THREAD

**Issue by brandon-leapyear** [haskell-servant/servant#1438]
It'd be nice to have a helper for the common case (in my experience) of serving all routes in a custom monad, especially with a custom context. Currently, I do this with
```hs
app = serveRoutes @MyAPI myContext runMyMonad routes

serveRoutes ::
  forall api context m.
  HasServer api context =>
  Context context ->
  (forall x. m x -> Handler x) ->
  ServerT api m ->
  Application
serveRoutes ctx f routes =
  serveWithContext (Proxy @api) ctx $
    hoistServerWithContext (Proxy @api) (Proxy @context) f routes
```

This seems like a pretty general helper that can be exported upstream. I would think `servant-server` could expose an API like:
```hs
serve :: HasServer api '[] => Proxy api -> Server api -> Application
serve p = serveWithContextT p EmptyContext id

-- related: https://github.com/haskell-servant/servant/issues/1437
serveWithContext :: HasServer api context => Proxy api -> Context context -> Server api -> Application
serveWithContext p ctx = serveWithContextT p ctx id

serveWithContextT ::
  HasServer api context =>
  Proxy api ->
  Context context ->
  (forall x. m x -> Handler x) ->
  ServerT api m ->
  Application
```

It would also be nice if `serve` and `serveWithContext` used type applications instead of using proxies, but I'm not too hung up about that.

**Comment by alpmestan** [comment]
Hello.

Regarding your central suggestion, I definitely agree. I think we could perhaps even reuse the `Server`/`ServerT` naming convention (i.e the `T` suffix), and perhaps rename your `serveWith` to `serveWithContextT`? No strong opinion on that, just throwing it out there.

---

Regarding:

> It would also be nice if `serve` and `serveWithContext` used type applications instead of using proxies, but I'm not too hung up about that.

I'm not overly enthusiastic about this. Since `ServerT` is a non injective type family, am I mistaken in thinking that this would essentially force everyone to enable `AllowAmbiguousTypes`? Which is not something I'm delighted to be encouraging, even if it's pretty benign all things considered.

**Comment by brandon-leapyear** [comment]
> Regarding your central suggestion, I definitely agree. I think we could perhaps even reuse the `Server`/`ServerT` naming convention (i.e the `T` suffix), and perhaps rename your `serveWith` to `serveWithContextT`? No strong opinion on that, just throwing it out there.

Yeah, that sounds like a good idea. Updated the description

> am I mistaken in thinking that this would essentially force everyone to enable `AllowAmbiguousTypes`?

No, only the definition site (i.e. `Servant.Server`) needs to enable that. But it would force everyone to enable `TypeApplications` and call `serve` with type applications. But yeah, I'm not too tied to this; the only savings it gives is changing
```hs
serve (Proxy @MyApi) app
```
to
```hs
serve @MyApi app
```

**Comment by alpmestan** [comment]
@brandon-leapyear Would you like to write the `serveWithContextT` patch? :-)
