### ISSUE TITLE
Adding (//) and (/:) for Servant client composition

### ISSUE THREAD

**Issue by tchoutri** [haskell-servant/servant#1442]
(opened with the approval of @divarvel)

I would like to introduce two operators for client endpoint composition in Servant.Client.Generic

```haskell
(//)                                
  :: (m ~ AsClientT n)              
  => GenericServant routes m        
  => (a -> ToServant routes m)      
  -> (routes m -> b)                
  -> (a -> b)                       
f // f' = f >>> fromServant >>> f'  
                                    
(/:) :: (a -> b -> c) -> b -> a -> c
(/:) = flip                         
```
An example usage (taken from their [introductory article](https://blog.clement.delafargue.name/posts/2019-09-10-a-new-tale-of-servant-clients.html) is:

```haskell
withUser /: userId // putUser /: userData
```
This helps replacing usages of `fromServant` between each accessor, like this:

```haskell
withUser >>> ($ userId) >>> fromServant >>> putUser ($ userData)
```

I think this addition would greatly improve the user experience of using servant-client, and can testify that, having seen those combinators user in production, they bring value in readability.

cc @akhesaCaro @gdeest

**Comment by divarvel** [comment]
A very similar combinator is also super useful with `allFieldLinks` (ideally `//` should work both with links and clients, but the `AsClientT` / `AsLink` type equality constraint seems required for inference to work correctly.

```haskell
(///)
  :: m ~ AsLink n
  => GenericServant routes m
  => (a -> ToServant routes m)
  -> (routes m -> b)
  -> a -> b
f /// f' = f >>> fromServant >>> f'
```

**Comment by alpmestan** [comment]
Since the type signatures are not all that illuminating, nor are the operators, this would have to be illustrated with crystal clear examples in the haddocks and perhaps the cookbook recipe about generic-based servant. But I personally have absolutely no objection about bringing something like those combinators into servant. I guess this can be viewed as an alternative solution of sorts for #1315.

**Comment by divarvel** [comment]
they can be complementary actually. Even with #1315, having `//` as an alias for `>>>` improves readability as well.

**Comment by tchoutri** [comment]
@alpmestan 

> this would have to be illustrated with crystal clear examples in the haddocks and perhaps the cookbook recipe about generic-based servant. 

Yes absolutely. :)
