### ISSUE TITLE
More informative HasServer

### ISSUE THREAD

**Issue by oswynb** [haskell-servant/servant#145]
Instead of returning a Nothing regardless of mode of failure (decode failure, missing key, etc.) for Parameters, Headers, etc. use an Either to give pass more information to the server implementation and allow them to handle different cases differently.

I've written an example of what I'm thinking of using Strings, (https://github.com/haskell-servant/servant/compare/master...oswynb:wip-either) though I think maybe a sum type would be cleaner? Though this would have the disadvantage of things breaking when said sum type changes, and also requiring a lot of pattern matching on each constructor.

**Comment by jkarni** [comment]
Can you explain a little the use cases? The obvious one is returning more informative error messages from the handlers, but it sounds like maybe you have others in mind too?

**Comment by alpmestan** [comment]
What do you have in mind for the `Left` part of `Either`? To be honest, I feel perfectly good with `Nothing` as usualy it doesn't make a difference for me whether we couldn't decode the value or whetther the value wasn't there at all -- if however this is something that could benefit other people, it should definitely be considered. The obvious drawback being that's it would break a quite scary proportion of the servant code out there =)

**Comment by thsutton** [comment]
One reason we want it is that we need to return different errors depending on whether the value is missing or malformed in a few places in the OAuth2 server.

**Comment by alpmestan** [comment]
I could argue that you're giving a quite key role to the (e.g) header which can really be reflected with a proper combinator. But I won't -- I guess your suggestion is the right way to go, because the other way would be not to let you implement what you need, which is terrible. @jkarni ?

**Comment by jkarni** [comment]
I'm in favour of either `Either` or nothing at all (i.e., not even `Maybe`). Where we currently stand, there's not easy way to give more precise errors; if we moved to `Either` we'd pass the burden of sending those errors to the handlers. But we could also go with the "the combinator sends the error" approach, which might be pretty insofar as side-stepping it (i.e., handling errors yourself, or doing `Maybe` again) is as simple as having the type to be decoded into be either `Either` or `Maybe`.

(I think I like the second option better.)

**Comment by thsutton** [comment]
I'd be OK with a "no, add new combinators kthxbai" if it's not something that fits in your plans.

**Comment by jkarni** [comment]
@oswynb @thsutton  Speaking of which, as an ugly hack to get this working before there's a release with a nicer solution, you can already get the errors if you try decoding into an `Either` which always "succeeds" by keeping decoding errors on the `Left`, no? There'd be an unnecessary `Just` wrapping it, though...

**Comment by fizruk** [comment]
I believe this is closed by #218.
