### ISSUE TITLE
Retiring support for GHC 8.0, 8.2 and 8.4 versions

### ISSUE THREAD

**Issue by tchoutri** [haskell-servant/servant#1450]
In the optics of focusing our efforts on better maintenance and scarce resources, I would like to submit to vote that we drop support for the following versions of GHC:

* 8.0
* 8.2
* 8.4

I feel it would be premature to retire the 8.6 version, due to its mix of stability in the ecosystem and several hundred bugs fixed from the 8.4 series.

cc @haskell-servant/core

**Comment by tchoutri** [comment]
cc @haskell-servant/maintainers as well

**Comment by akhesaCaro** [comment]
Discussed in https://github.com/haskell-servant/servant/issues/1404

**Comment by alpmestan** [comment]
What does dropping support mean here? Removing the CI jobs for those GHC versions? Are we targeting some precise breakage that we don't want to worry about anymore?

IIRC we've got some recent PRs with failing jobs for 8.0 and 8.2, not sure if that's easy to address but given the little time we have to dedicate to such issues, I think I'm inclined to vote "yes" on this.

**Comment by theophile-scrive** [comment]
@alpmestan Yep, removing CI for those versions, not having to do CPP/Extraneous imports when it comes to Applicative or Semigroup, being certain we can recommend newer techniques when it comes to generics deriving, like DerivingVia, etc…

**Comment by akhesaCaro** [comment]
For instance (UVerb Cookbook), you can see how to exclude GHC versions in this PR 

https://github.com/haskell-servant/servant/pull/1407

**Comment by tchoutri** [comment]
@alpmestan Yep, removing CI for those versions, not having to do CPP/Extraneous imports when it comes to Applicative or Semigroup, being certain we can recommend newer techniques when it comes to generics deriving, like DerivingVia, etc.

**Comment by akhesaCaro** [comment]
For instance (UVerb Cookbook), you can see how to exclude GHC versions in this PR : #1407

**Comment by domenkozar** [comment]
Sounds good - I'll do the same for servant-auth.

**Comment by tchoutri** [comment]
@domenkozar Hi, thanks for the feedback. :)
The main blocker for this will be the move to a monorepo, but I'm glad that you agree with this plan

**Comment by akhesaCaro** [comment]
I am on it!

**ghcjs will be an issue in this matter** as long as it is build with GHC 8.4 on CI. 

To do otherwise, we will need the change the way we install the package on the CI. 
It seems recommended to use [reflex platform](https://github.com/reflex-frp/reflex-platform) , but it implies to install much more than just ghcjs. I am not very convince by the solution.

**Comment by akhesaCaro** [comment]
WIP : https://github.com/haskell-servant/servant/pull/1452

**Comment by akhesaCaro** [comment]
DONE
