### ISSUE TITLE
GHC 9.2.1 support

### ISSUE THREAD

**Issue by listx** [haskell-servant/servant#1491]
I was trying out [GHC 9.2.1](https://www.reddit.com/r/haskell/comments/qif499/announce_ghc_921_released/) with `servant-client`, and noticed that the [latest version of it (0.18.3)](https://hackage.haskell.org/package/servant-client-0.18.3) relies on `base < 4.16` (4.16 is shipped with GHC 9.2.1).

I noticed there are no existing open issues for GHC 9.2.1 support, so I'm opening this one.

**Comment by tchoutri** [comment]
This is currently being addressed in https://github.com/haskell-servant/servant/pull/1482

**Comment by listx** [comment]
> This is currently being addressed in #1482

I see, thanks for the pointer.

Nit: I would have left this issue open until that PR was closed/resolved so that other folks don't ask the same question.

**Comment by tchoutri** [comment]
Duly noted
