### ISSUE TITLE
Tutorial: entire tutorial listed under "Stack"

### ISSUE THREAD

**Issue by nickgirardo** [haskell-servant/servant#1495]
I went to read through the tutorial, and the table of contents only has two elements: cabal-install and stack.  Everything else is listed under stack.  This can be seen in the image below.  Note that I've opened the stack category but by default, all of the topics listed under it are collapsed

![image](https://user-images.githubusercontent.com/4015408/144653578-13531375-6a06-4f66-bedd-7bb7e20abfc7.png)

I'm not an expert with read-the-docs, but I assume that this is due to the table of contents falling below the stack header in the document (as seen below).  This might be solvable by moving the table of contents to the elsewhere in the document

![image](https://user-images.githubusercontent.com/4015408/144653992-707a5b0f-d211-4951-bd07-54bf4ef74432.png)

This issue made me initially miss the majority of the tutorial.  When I navigated to the page I only saw installation details.  The information which would have been helpful to me fell below the fold.  Missing the majority of the tutorial lead me to believe the tutorial was only for installation and that I wanted the cookbook for usage.  Going into the cookbook without having first read the tutorial was tricky.

An alternative solution to this might be putting all of the installation instructions (both cabal-install and stack) into an "Installation" category and the rest of the tutorial into a "Usage" category

**Comment by alpmestan** [comment]
This should be fixed by https://github.com/haskell-servant/servant/pull/1465
And it indeed is if you switch to another version at the bottom left of the page, e.g the 'latest' tag shows the correct hierarchy: https://docs.servant.dev/en/latest/

**Comment by nickgirardo** [comment]
Thanks for the heads up! That looks much better and would totally resolve my issues once it reaches stable.  Apologies for duplicating #1444

**Comment by alpmestan** [comment]
@nickgirardo No worries, thanks for caring about the docs :-)

Closing, since this has addressed.
