### ISSUE TITLE
Can't build servant-swagger

### ISSUE THREAD

**Issue by tfausak** [haskell-servant/servant#1507]
`servant-swagger`'s custom setup needs the `Cabal` library but doesn't list it in `setup-depends`:

https://github.com/haskell-servant/servant/blob/c388c5e82c3df5d8ae63b523fea012c23e37410a/servant-swagger/servant-swagger.cabal#L50-L53

This causes a build error:

```
/stack/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs:3:1: error:        
    Could not load module ‘Distribution.PackageDescription’        
    It is a member of the hidden package ‘Cabal-3.2.1.0’.        
    You can run ‘:set -package Cabal’ to expose it.  
    (Note: this unloads all the modules in the current scope.)        
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.        
  |        
3 | import Distribution.PackageDescription (PackageDescription, emptyHookedBuildInfo)        
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
```

The package description from the old repo correctly lists a dependency on `Cabal`:

https://github.com/haskell-servant/servant-swagger/blob/7ac475a40b4b95a50bc2094f9461c62bd7fbb1fd/servant-swagger.cabal#L50-L54

**Comment by gdeest** [comment]
I am looking into this. Interestingly, `servant-swagger` does build on servant CI without errors. Do you have any idea why it might be so ?

**Comment by gdeest** [comment]
OK the build fails with stack, but we didn't catch it because we forgot to add the project to `stack.yaml`.

**Comment by gdeest** [comment]
Actually the story is a tad more complex. Doctest documentation mentions that dependency on `Cabal` isn't needed if we only use `defaultMainWithDoctests`, which we do… conditionally, based on some CPP invocations.

**Comment by tfausak** [comment]
Thanks!
