### ISSUE TITLE
Generic ToSample

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#151]
We could (and should) provide a generic derivation of `ToSample`. @kosmikus' generic-sop shows how.

**Comment by alpmestan** [comment]
By relying on `Data.Default` for filling the values of the fields without user intervention?

**Comment by jkarni** [comment]
No, I was just thinking of actually using generics. We should also probably do that for `From/ToText`.

**Comment by alpmestan** [comment]
Yeah, but even with generics, you have to make up values of type `Int`, `String` or whatever is contained in the type you want a "sample" of. Generics would just let us mash up those values together into whatever type we're interested in.

**Comment by jkarni** [comment]
Ah, I see. Yeah, probably. On the one hand, `42` (or `1797`) is a better default `Int` (etc.) for samples than `0`. On the other, using standard classes is always better. So in all, I'd say that's a good idea.
