### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by ocharles** [haskell-servant/servant#1512]
Hi all,

Is there a plan to cut a new release? The main thing I'm interested in is having `aeson-2` support, and not needing a bunch of `source-repository-package` entries.

**Comment by tchoutri** [comment]
Hi Ollie! The TODO list for the next release is laid here: https://github.com/haskell-servant/servant/projects/2

As you can we're nearing the end. :)

**Comment by ocharles** [comment]
Oh, thank you! I'll close this and keep an eye on the project. Thank you very much for the speedy response, look forward to the next release!
