### ISSUE TITLE
https://www.servant.dev/ is down

### ISSUE THREAD

**Issue by visortelle** [haskell-servant/servant#1520]
<img width="437" alt="Screen Shot 2022-02-01 at 2 49 02 PM" src="https://user-images.githubusercontent.com/9302460/151980221-dfa8a5d1-3691-4b25-a21b-33d276c43cd9.png">

https://docs.servant.dev/en/stable/ works.

Probably it makes sense just to replace the link to the site in README.md

**Comment by arianvp** [comment]
I suppose this is the same as https://github.com/haskell-servant/servant/issues/1500 ? cc @domenkozar

**Comment by alpmestan** [comment]
Yes, this is the lovely github pages system in action. @tchoutri and @domenkozar are looking into this I think.

**Comment by visortelle** [comment]
OK. Then I'm closing the issue.
