### ISSUE TITLE
Persistent Keys

### ISSUE THREAD

**Issue by jhickner** [haskell-servant/servant#153]
I'm encoding persistent's database `Key`s directly in the URL, like so:

```haskell 
"user" :> Capture "id" UserId :> Get '[JSON] (Maybe (Entity User))
```
Persistent has a function `toSqlKey` with this signature that makes this possible:
```haskell
toSqlKey :: ToBackendKey SqlBackend record => Int64 -> Key record
```

So I end up with a bunch of instances that look like this:
```haskell
instance FromText SignalId where fromText = (toSqlKey <$>) . fromText
...
...
```

My question is, is there a way to define this once and for all for every key, using type inference to derive the correct `Key` instance from context? Would this be a useful addition to Servant core?

EDIT: I should note that my initial attempt results in a `Constraint is no smaller than the instance head` error:

```haskell
instance ToBackendKey SqlBackend a => FromText (Key a) where
    fromText = (toSqlKey <$>) . fromText
```

**Comment by alpmestan** [comment]
This would not be added to servant core, because that would introduce a dependency on *persistent* for everyone who uses *servant*. However, if there's any way to offer generic helpers for using servant and persistent together, this could all be put into a *servant-persistent* package or something.

**Comment by jkarni** [comment]
Closing since as Alp mentioned, we don't want a dependency on `persistent`
