### ISSUE TITLE
Let servant-jquery be more generic

### ISSUE THREAD

**Issue by freezeboy** [haskell-servant/servant#155]
Currently, servant-jquery is generating javascript code that depends on jquery library. With some frameworks, the AJAX part is included in another way (for example $http service in Angular) an using both could seem superfluous.

The main part of the library can be shared, and after some discussion with @alpmestan, it appeared that having specialized `generateJS` functions (optional with GeneratorOption support:

```haskell
-- Generates a function with XmlHttpRequest
generateVanillaJS :: VanillaJSOpts -> AjaxReq -> String
-- Generates an Angular Controller using $http provider
generateAngularJS :: AngularJSOpts -> AjaxReq -> String
-- Generates a function using the $.ajax function
generateJQueryJS :: JQueryJSOpts -> AjaxReq -> String
```
And once this foundation is built, one could add support for react, ember, etc...

I see multiple actions to resolve this issue:
1. Rename the generatejs function into Jquery
2. Define some basic options (function name prefix, ...)
3. Generalize the *HasJQ* instance into *HasJS* --> Requires to patch other libraries to support that change
4. Write other variants
5. Rename the package (one with all variants)

This is open for discussion, maybe I missed some problems

**Comment by alpmestan** [comment]
Yeah, the package should probably be renamed to *servant-javascript* if we make it target several javascript libraries. If you do the hard work of writing those different JS-generation functions, I would definitely feel like help wrapping up the PR by doing the renaming and reorganization of the code and what not.

One thing to keep in mind while we're at it: we might want to have @parsonsmatt somewhere near and solve #143 with him along the way, as this will be useful for *all* generators.

Kind of related: #38 #39 #121

Also, do you see an easy way to make arbitrary content types (JSON, HTML, PlainText, ...) supported by the javascript client libraries?

**Comment by freezeboy** [comment]
So I started to code, and I encounter one problem : 
```haskell
instance GenerateCode AjaxReq where
  jsFor = generateJS
```
I can't figure out how to let this instance use the variant we want, instead of always using the JQuery one.

As far as #143 is concerned, I can imagine to use the options to "translate" the method, for example:
GET => get
POST => save
PUT => update
...
but @parsonsmatt 's example still would work. I cannot find a solution in this case
Anyway theses naming problems should be dealt in the common part of the lib, not in each generator.

**Comment by jkarni** [comment]
We'd have to change the signature of `jsFor` - e.g.:
```
data JsDep = JQuery | Angular | Vanilla

class GenerateCode reqs where
   jsFor :: reqs -> JsDep -> String
```
Or some such. If we make the second argument of `jsFor` polymorphic, and it's type an argument to `GenerateCode`, and each of `JQuery`, `Angular`, etc. a type rather than a constructor, it'll be easily extensible to other elements besides the ones we provide, but that might not be that important in this case.

**Comment by freezeboy** [comment]
Ok this is acceptable for you, it's ok for me
By the way, it would only force version 0.5 to stick to this limitation (if I'm fast enough), newer version could improve the solution later

**Comment by jkarni** [comment]
I'm happy with the signature change. 
@freezeboy just as thought, I think API Blueprint (or Swagger?) use template files to generate code (rather than our string concatenation). No *need* to go that route, but keep it in mind if it's easier. (I was originally in favour of using expression types from `language-ecmascript`, but I now think that's just more work for very little gain.)

**Comment by parsonsmatt** [comment]
The idea that I have been thinking on would look something like this:

```haskell
generateClient :: ApiType -> ApiParser -> CodePrinter -> String
```

where `ApiParser` and `CodePrinter` are record types of functions which encapsulate the logic. The ApiParser would be responsible for language semantics stuff, so it'd have logic for handling name duplication (fine in Java, bad news in JS/Ruby), type names, etc. There would only need to be one ApiParser for a given target language.

CodePrinter would have logic around actually generating the code from the processed API type. It'd have stuff like "camelCase vs snake_case" for identifier names, what to put before and after the generated functions (module.exports declaration, IIFE, etc), the function name that invokes the AJAX request, etc. You'd have a CodePrinter for jQuery, Angular, React, etc.

Setting up the codegen as a pair of record types should make it pretty easy to extend in the future, but would be a lot more work up front. unfortunately I haven't had time to put much work into this :\

**Comment by alpmestan** [comment]
For the record, this is what I suggested in an email conversation with @freezeboy.

``` haskell
-- We change GenerateCode so that it takes an argument that specifies
-- the precise JS code gen strategy we want
class GenerateCode ajaxreqs where
  generateJSWith :: (AjaxReq -> String) -> ajaxreqs -> String

instance GenerateCode AjaxReq where
  generateJSWith gen req = gen req

instance GenerateCode rest => GenerateCode (AjaxReq :<|> rest) where
  generateJSWith gen (req :<|> rest) =
    concat [gen req, "\n", generateJSWith gen rest]

-- to be used with, say:
vanillaGen :: AjaxReq -> String
jqueryGen :: AjaxReq -> String
angularGen :: AjaxReq -> String
...

-- in that way:
generateJSWith vanillaGen
generateJSWith jqueryGen
generateJSWith angularGen

-- But thanks to partial application, we ccan have configurable
-- generators:
data VanillaJSOpts
data JQueryOpts
data AngularOpts

vanillaGen :: VanillaJSOpts -> AjaxReq -> String
jqueryGen :: JQueryOpts -> AjaxReq -> String
angularGen :: AngularOpts -> AjaxReq -> String
```

**Comment by jkarni** [comment]
:+1:

**Comment by freezeboy** [comment]
First of all: I'm a newbie:
@parsonsmatt I'd be happy to try the Parser / CodeGen stuff, I'm not sure to understand what is a *record types of functions which encapsulate the logic.*
@jkarni What do you call API Blueprint / Swagger ?

**Comment by parsonsmatt** [comment]
No worries! I'm a total noob also :)

A record type of functions would look something like:

```haskell
data ApiParser =
    { resolveNameCollisions :: [String] -> [String] 
    -- given a set of strings, make sure all generated function names are OK
    , typeAnnotations :: [(Type -> String)]
    -- write types appropriately for target language
    , -- etc...
    }
```

So, given some value of type ApiParser, you could do `let funcNames = (resolveNameCollisions apiParser) apiType`

**Comment by freezeboy** [comment]
Ok I got it, I sometimes forget a function is a value..

**Comment by freezeboy** [comment]
I don't know if you are familiar with Angularjs.
Now I do have some thing that compiles and passes the tests, but I kept the same logic: each endpoint is made available through it's own function.

Maybe it would be more clever to build a *$service* containing all the end points ?
The problem I see is that if all this is automatic it won't be very customizable, and I think it is easier to compose a *$service* from simple functions than decompose it into other services.

Do any of you have any idea on this ?

**Comment by alpmestan** [comment]
Or maybe don't make that choice for the user and make it configurable?

``` haskell
data AngularGenOpts = ToplevelFunctions | Service
```

If you need to make more things configurable, just make a record with such options in it.

**Comment by freezeboy** [comment]
Seems a good solution, now I need to implement a way to wrap all the function definitions inside some code...

**Comment by alpmestan** [comment]
Let us know when/if you need a hand at any point.

**Comment by freezeboy** [comment]
Ok I added the tag on my clone, but now I'm stuck to find the ideal entry point to the generation mecanism.

Il need to generate only once:
module.service(serviceName, .... {
   /// Here generate recursively all the functions like the previous functions did
});

But generateJS is both an entry point and a function used in the recursion if i understand correctly
I think I should not do it in an instance, but then, where ...

**Comment by alpmestan** [comment]
Worst case, you can just assume you'll get a list of `AjaxReq` and start from there? I'll then show you how you can easily get your hands on an `AjaxReq` list.

**Comment by freezeboy** [comment]
Sorry, I don't understand in which existing function we use a [AjaxReq]
I see function that traverse the url tree
do you mean add a public function doing more or less the same job that generateJS does, but adding a prelude / conclude parts depending on the options ?

**Comment by alpmestan** [comment]
I just meant to say that you can assume you'll get data in the right shape for you and start from there. If we need to go through some hoops to get the data in the right shape for your functions, I'll happily take care of that. So just pick whatever is convenient for you and we'll make sure the data arrives in that shape when necessary.
