### ISSUE TITLE
how to run servant-server from terminal

### ISSUE THREAD

**Issue by hududed** [haskell-servant/servant#1562]
I am fairly new to this, following the tutorial https://docs.servant.dev/en/stable/tutorial/Server.html?highlight=cabal%20run#a-first-example - how exactly do I run the servant server from the terminal? Is it from `cabal repl` ?

**Comment by tchoutri** [comment]
@hududed The entrypoint of your program in the `main` function, which you can either call from GHCi with `:main` (or simply `main`), or put in a module called `Main` (in a `Main.hs` file).
Then you need to have an `executable` stanza in your cabal file to tell cabal that you're producing an executable.

**Comment by hududed** [comment]
Ahh ok I see that there is already an example of `greet.hs` in `servant-server/example` - I ran `cabal run greet` from `servant-server` directory and it works - thanks!
