### ISSUE TITLE
How do I validate that swagger and json match for endpoints returning (Maybe a)?

### ISSUE THREAD

**Issue by adlaika** [haskell-servant/servant#1563]
Hi! I'm using swagger-servant's `validateEveryToJSON` to ensure that our swagger spec and `ToJSON` instances are in sync. Unfortunately, it fails whenever it encounters a Servant API type like this: 

```
  "merchants" :> Capture "id" MerchantId :> Get '[JSON] (Maybe Merchant)
```

...that is, one that returns a `Maybe a` type. 

The blurb under "Validating Maybe" [here](https://hackage.haskell.org/package/swagger2-2.8.2/docs/Data-Swagger-Schema-Validation.html) says: `Because Maybe a has the same schema as a, validation generally fails for null JSON`, but I would be surprised to learn that there's no way to validate the swagger/json instances for Servant endpoints returning `Maybe a`s, since that seems like a common pattern. Is there something I'm missing?

Thanks!

**Comment by gdeest** [comment]
According to the documentation you linked, it looks like your problem could be solved by altering the return type of the endpoint to something like this:

```haskell
newtype MerchantResponse = MerchantResponse { getMerchantResponse :: Maybe Merchant }
```

There doesn't seem to be a way to solve your problem without altering the response type.

If you want to try out `servant-openapi3`, good news though: `servant-swagger-ui` does support OpenAPI3.

https://hackage.haskell.org/package/servant-swagger-ui-0.3.5.4.5.0/docs/Servant-Swagger-UI.html

**Comment by adlaika** [comment]
Yeah, that's what I was afraid of--adjusting the return type means losing automatic 401 responses in the case of Nothing. Not the end of the world, but slightly annoying.

Totally missed that in the `servant-swagger-ui` docs--thanks!
