### ISSUE TITLE
Fallback route for serving a static directory

### ISSUE THREAD

**Issue by ollimandoliini** [haskell-servant/servant#1578]
In order for a single-page app's routing to work, requests to urls that don't have a matching file have to be routed to `index.html`. Then the url will be handled by the front-end code. Unless I'm totally mistaken, this is something that is not currently supported by `servant` out of the box but instead, I am using this custom handler:

```haskell
serveFrontEnd :: String -> ServerT Raw (AppT IO)
serveFrontEnd rootDirectory =
  serveDirectoryWith settingsWithFallback
  where
    settingsWithFallback = (defaultWebAppSettings rootDirectory) { ssLookupFile = lookup' }
    lookup' p = do
      f <- ssLookupFile (defaultWebAppSettings rootDirectory) p
      case f of
        LRFile   f' -> return $ LRFile f'
        LRFolder f' -> return $ LRFolder f'
        LRNotFound -> ssLookupFile (defaultWebAppSettings rootDirectory) [unsafeToPiece "index.html"]
```

I'm wondering if there is something I have overlooked? If this indeed isn't supported out of the box, is this something that could be included in `servant`s codebase? If so, I'd be happy to implement it.

**Comment by gdeest** [comment]
Indeed, this is not supported out-of-the-box. It is relatively easy to implement, but would still be valuable to end users as it is a fairly frequent use-case.

I am guessing the right place to open such a PR might not be this repository but https://github.com/yesodweb/wai as the `serveDirectory*` functions are provided by the `wai-app-static` package.

**Comment by tchoutri** [comment]
Yep, I use `wai-app-static` for this very usecase.

**Comment by ollimandoliini** [comment]
@tchoutri Do you mean you use it in a similar fashion as in my snippet?

**Comment by tchoutri** [comment]
@ollimandoliini only on the backend side. When supporting SPA, I use a dedicated reverse proxy like Nginx, for which the SPA workflow is well-documented: https://sdickinson.com/nginx-config-for-single-page-applications/

**Comment by ollimandoliini** [comment]
@tchoutri Thanks! That's what I usually do as well – on the other hand like the simple setup of having both backend and frontend in the same place.

I acknowledge that this is a bit off-topic but do you know what are the performance implications of serving the SPA through wai vs nginx?

**Comment by gdeest** [comment]
> I acknowledge that this is a bit off-topic but do you know what are the performance implications of serving the SPA through wai vs nginx?

I honestly don't know for sure, but I'd be surprised if `nginx` were slower than `wai-app-static`. But `wai-app-static` is easier to deploy, so I wouldn't worry until performance really becomes a problem if it satisfies your requirements.

**Comment by tchoutri** [comment]
@ollimandoliini While I don't have specific benchmarks to show you, I can assure you that Nginx
has the advantage of using `sendfile()`, and has been optimised for very efficient assets serving over many years.

**Comment by gdeest** [comment]
@tchoutri WAI has had support for `sendfile` since its early days, AFAICT: https://www.yesodweb.com/blog/2010/08/static-file-optimizations

**Comment by gdeest** [comment]
`warp` makes direct use of `sendFile`: https://github.com/yesodweb/wai/blob/052b875effb45fbf7fd3bb9123592fc5002c9763/warp/Network/Wai/Handler/Warp/SendFile.hs#L42

I'd be surprised if `ReponseFile` reponses did not make use of that functionality … ?

**Comment by tchoutri** [comment]
Ah yes I see it's using https://hackage.haskell.org/package/simple-sendfile. :)

**Comment by gdeest** [comment]
@ollimandoliini I am closing this issue as it doesn't seem strictly servant-related. Feel free to re-open if you disagree !
