### ISSUE TITLE
Is there support for `servant-docs` when using `NamedRoutes`?

### ISSUE THREAD

**Issue by ikervagyok** [haskell-servant/servant#1581]
Is there some way to use `servant-docs` when using the `NamedRoutes` approach for defining the APIs?

The (broken) minimal viable test I have done is:

```.haskell
data SimpleAPI mode = SimpleAPI {simpleAPI :: mode :- Raw}
  deriving (Generic)

proxySimpleAPI :: Proxy (NamedRoutes SimpleAPI)
proxySimpleAPI = Proxy

main = putStrLn $ markdown $ docs proxySimpleAPI
```

As a reference I've tried the traditional way of defining an API, which works as expected:
```.haskell
type SimpleAPI_ = Raw :<|> Raw

proxySimpleAPI_ :: Proxy SimpleAPI_
proxySimpleAPI_ = Proxy

main = putStrLn $ markdown $ docs proxySimpleAPI_
```

**Comment by gdeest** [comment]
> Is there some way to use servant-docs when using the NamedRoutes approach for defining the APIs?

Not yet ; it is missing the corresponding instance.

I just opened https://github.com/haskell-servant/servant/pull/1582 to fix this.
