### ISSUE TITLE
How to get/show/print Request before ClientM gets evaluated?

### ISSUE THREAD

**Issue by unclechu** [haskell-servant/servant#1594]
If I for instance want to debug or/and to log the request before it gets evaluated by `runClientM` how can I do this? How I could receive final `Request` from a `ClientM`?

It’s clear how to do this when making an HTTP server. You could just add a middleware for WAI. But I’m not sure how I can do this for client requests.

**Comment by arianvp** [comment]
Would [`managerModifyRequest`](https://hackage.haskell.org/package/http-client-0.7.11/docs/Network-HTTP-Client.html#v:managerModifyRequest) do the job for you?

**Comment by alpmestan** [comment]
A more flexible (but slightly more involved) alternative is described in [this cookbook](https://docs.servant.dev/en/stable/cookbook/using-free-client/UsingFreeClient.html).

**Comment by unclechu** [comment]
@arianvp hm... Almost but it doesn’t show HTTPS. I mean it shows this:

``` haskell
Request {
  host                 = "matrix.org"
  port                 = 80
  secure               = False
...
```

While it should be 443 and `secure` should be `True` I assume. Because I created the manager using `newTlsManagerWith`:

``` haskell
let
  managerSettings = HTTP.defaultManagerSettings
    { HTTP.managerResponseTimeout = responseTimeout
    , HTTP.managerModifyRequest = \req → do
        runInIO $ requestOptionsRequestLogger reqOpts req
        HTTP.managerModifyRequest HTTP.defaultManagerSettings req
    }
HTTP.newTlsManagerWith managerSettings
```

Am I missing something?

**Comment by unclechu** [comment]
Sorry, it seems there was no `https://` prefix in my `BaseUrl` and it was defaulting to plain HTTP.

**Comment by unclechu** [comment]
Both `managerModifyRequest` and Servant Client Free monad worked well, gave me the same result. `managerModifyRequest` works perfectly for the job, provides middleware-like API just for logging requests, ends with `IO`. For some reason I didn’t find it myself, probably confused Servant’s `Request` with HTTP’s `Request`.

**Comment by unclechu** [comment]
Also I had to use `Network.HTTP.Client.TLS.tlsManagerSettings` instead of `Network.HTTP.Client.defaultManagerSettings` in the piece of code I posted above.

**Comment by unclechu** [comment]
So the final `Manager` is built like this:

``` haskell
data RequestOptions = RequestOptions
  { requestOptionsTimeout ∷ Maybe T.Seconds
  -- ^ "Nothing" means default timeout value (30 seconds)
  , requestOptionsRequestLogger ∷ ∀m. ML.MonadLogger m ⇒ HTTP.Request → m ()
  }

...

tlsManager ← withRunInIO $ \runInIO →
  let
    managerSettings = HTTP.tlsManagerSettings
      { HTTP.managerResponseTimeout = responseTimeout
      , HTTP.managerModifyRequest = \req → do
          runInIO $ requestOptionsRequestLogger reqOpts req
          HTTP.managerModifyRequest HTTP.defaultManagerSettings req
      }
  in
    HTTP.newTlsManagerWith managerSettings
```
