### ISSUE TITLE
Ignored Cookies in RunStreamingClient

### ISSUE THREAD

**Issue by alt-romes** [haskell-servant/servant#1605]
Hello, today I came across an issue when developing an application using servant-client to generate a client for a streaming end-point.

The authentication for this endpoint is done through cookies.

Long story short, I wasn't being correctly authenticated when using the servant-client generated functions for accessing the streaming API, because the cookies I had set weren't being considered.

I traced the issue down to [`performWithStreamingRequest`](https://github.com/haskell-servant/servant/blob/f0e2316895ee5fda52ba9d5b2b7e10f8a80a9019/servant-client/src/Servant/Client/Internal/HttpClient/Streaming.hs#L175).

If you compare that function to the one directly above (`performRequest`) it's visibly noticeable that `performWithStreamingRequest` is not taking into consideration the cookie jar whatsoever (while `performRequest` is!)

I have a patch ready (I simply copied the cookie jar lines from the function above) and will link this from there.

It fixes my use case that required the cookie authentication + the streaming endpoint.

I'm left wondering if there's any particular reason for *not* taking the cookies into consideration.

Do let me know,
Thanks,
Rodrigo

**Comment by alt-romes** [comment]
Friendly bump! The PR is working and ready to merge ;-)

**Comment by ysangkok** [comment]
This is now released on Hackage and is visible in [the changelog for servant-client-0.20](https://hackage.haskell.org/package/servant-client-0.20/changelog#020).
