### ISSUE TITLE
Hackage home-page link is no longer valid for servant-auth

### ISSUE THREAD

**Issue by qwbarch** [haskell-servant/servant#1615]
The [servant-auth](https://hackage.haskell.org/package/servant-auth) and [servant-auth-server](https://hackage.haskell.org/package/servant-auth-server) packages have broken home-page urls on its respective hackage pages.  
Not a big issue, but it could be worth updating the hackage metadata to prevent any confusion?

**Comment by ysangkok** [comment]
I think this was fixed by #1548, could you please confirm?

**Comment by qwbarch** [comment]
It's indeed fixed, thanks!
