### ISSUE TITLE
Please document the change of `CaptureRouter`

### ISSUE THREAD

**Issue by swamp-agr** [haskell-servant/servant#1633]
[Here](https://github.com/haskell-servant/servant/commit/77b92d0d7d7913e8e3cf4d3b1ebd31d3923094f6) you introduced `CaptureHint` and modified the structure of `CaptureRouter`. Could you please document that change to make it clear what it is about and how to use it in other cases than `CaptureRouter []`?

**Comment by tchoutri** [comment]
@nbacquey Would you mind submitting an addition to the changelog and documentation? :)

**Comment by swamp-agr** [comment]
Cool, I even forget about that one. Thank you for looking into it. 👍
