### ISSUE TITLE
New hackage release for servant-docs to support lens 5.2

### ISSUE THREAD

**Issue by kostmo** [haskell-servant/servant#1636]
The upper bound for `lens` was bumped [here](https://github.com/haskell-servant/servant/pull/1607).  However, the `lens` bound for [`servant-docs` on Hackage is still `< 5.2`](https://hackage.haskell.org/package/servant-docs).

I believe a new `Hackage` release needs to be made for `servant-docs`.

**Comment by philderbeast** [comment]
Yes please. Preferable (when compiling `servant-pandoc` for example) to using `cabal.project/allow-newer`:

```
packages: .

allow-newer:
  servant-docs:lens
```

**Comment by ysangkok** [comment]
@alpmestan Would you be able to make a Hackage revision for this? Asking because I saw your name on https://hackage.haskell.org/package/servant-docs/maintainers/

**Comment by dhess** [comment]
Hi, this would be helpful for us as well, for the `mtl-2.3.1` support.

**Comment by ysangkok** [comment]
Hmm, looks like Alp isn't active recently, but seems like @arianvp is. Would you be able to bump this @arianvp? Hope I am not too obnoxious.

**Comment by alpmestan** [comment]
Hey,

Sorry for the delay. Published a revision that allows lens 5.2.

Cheers

**Comment by jonathanlking** [comment]
Piggy-backing on this issue, would it be possible to do update `servant-foreign` in the same way too please? 🙏 

The [servant-foreign.cabal](https://github.com/haskell-servant/servant/blob/master/servant-foreign/servant-foreign.cabal#LL55C7-L55C38) allows lens-5.2, but the [hackage package](https://hackage.haskell.org/package/servant-foreign) doesn't.

**Comment by alpmestan** [comment]
@jonathanlking Made a revision to the latest release for this as well.

**Comment by ysangkok** [comment]
Closing this as I think it has been addressed by the revision and by servant-0.20
