### ISSUE TITLE
Warp version bump

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#164]
3.1 is out (with HTTP 2!). See [stackage ticket](https://github.com/fpco/stackage/issues/703).

**Comment by alpmestan** [comment]
Is there any hope we could just have everything work with `warp >= 3.0 && <3.2` ?

**Comment by jkarni** [comment]
Let's see (#165) :)

**Comment by jkarni** [comment]
@codedmart investigated this and it seems to be fixed by https://github.com/yesodweb/wai/issues/406. Waiting on a release.

**Comment by jkarni** [comment]
(See also #170)

**Comment by jkarni** [comment]
Done in #165
