### ISSUE TITLE
UTF-8 should be uppercase

### ISSUE THREAD

**Issue by mgajda** [haskell-servant/servant#1650]
This is nicely explained in [MIME type documentation of Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#structure_of_a_mime_type:~:text=To%20specify%20a%20UTF%2D8%20text%20file%2C%20the%20MIME%20type%20text/plain%3Bcharset%3DUTF%2D8%20is%20used.), same as [for XML documents](https://blog.codingoutloud.com/2009/04/08/is-utf-8-case-sensitive-in-xml-declaration/#:~:text=Sometimes%20you'll%20see%20the,both%20variants%20are%20widely%20supported):

The charset is **case-sensitive** according to specs, and it is just poor implementations that force user agents to accept lowercase version.

Thus `servant` idea that all charsets are case insensitive is non-compliant.

**Comment by mgajda** [comment]
The only place that I see reporting that HTML character encodings are _not_ case sensitive: https://www.w3.org/TR/html4/charset.html#h-5.2.1:~:text=Names%20for%20character%20encodings%20are%20case%2Dinsensitive%2C%20so%20that%20for%20example%20%22SHIFT_JIS%22%2C%20%22Shift_JIS%22%2C%20and%20%22shift_jis%22%20are%20equivalent.

**Comment by mgajda** [comment]
At the same time, other parts of content type are case insensitive which is confusing.

**Comment by arianvp** [comment]
The MDM docs are wrong. the MIME-Type RFC (RFC 2046) is really clear about this and Servant's implementation is compliant

https://datatracker.ietf.org/doc/html/rfc2046#section-4.1.2
>    Unlike some other parameter values, the values of **the charset
   parameter are NOT case sensitive.**  The default character set, which
   must be assumed in the absence of a charset parameter, is US-ASCII.

**Comment by arianvp** [comment]
We can still make it upper-case if that "looks" nicer; but we should keep the type a case-insensitive string. Want to open a PR for that?

**Comment by arianvp** [comment]
I will close this issue but feel free to send a PR with the nit
