### ISSUE TITLE
servant-client doesn't handle multiple Set-Cookie headers correctly

### ISSUE THREAD

**Issue by dgaw** [haskell-servant/servant#1665]
`servant-client` seems to concatenate all `Set-Cookie` headers instead of treating them as separate values.

The problem most likely is related to the handling of multiple headers with the same name.

I've added a test to the test suite in order to demonstrate this: https://github.com/dgaw/servant/commit/7b4a39f1e80092c9d1ac918dc3d2b323a0f8a855

Here is the result:
```
Failures:

  test/Servant/SuccessSpec.hs:157:37: 
  1) Servant.Success.Servant.SuccessSpec Returns multiple Set-Cookie headers appropriately
       expected: [("Set-Cookie","cookie1"),("Set-Cookie","cookie2")]
        but got: [("Set-Cookie","cookie1\ncookie2"),("Set-Cookie","cookie1\ncookie2")]
```

**Comment by tchoutri** [comment]
oh no
