### ISSUE TITLE
haddock documentation link in readme is broken

### ISSUE THREAD

**Issue by yellowbean** [haskell-servant/servant#1669]
read me link:  https://github.com/haskell-servant/servant/tree/master/servant-swagger

![image](https://user-images.githubusercontent.com/1008321/228143730-611ca4d3-28e7-4f41-8cba-97a57e757772.png)

**Comment by Taneb** [comment]
Thanks for pointing this out! I've made a PR #1670 to fix this link

**Comment by tchoutri** [comment]
fixed by #1670
