### ISSUE TITLE
Can the lastest servant-auth be released?

### ISSUE THREAD

**Issue by guaraqe** [haskell-servant/servant#1671]
It contains the fix for NamedRoutes, but this is currently not available on Hackage, that would be very useful.

**Comment by ysangkok** [comment]
The source changes needed for ghc-9.6 compatibility are also not on Hackage:

* #1627 

So I think it would be best to just release a new version of all packages. I don't think one-offs are done anyway.

**Comment by ysangkok** [comment]
A release would address the following Stackage issues:

* commercialhaskell/stackage/issues/6909
* commercialhaskell/stackage/issues/6910
* commercialhaskell/stackage/issues/6923
* commercialhaskell/stackage/issues/6926

**Comment by guaraqe** [comment]
Ok, it seems releasing just a package is complicated. For now it is working for me by using it directly from GH and jailbreaking the dependencies. I will wait for the next release then.

**Comment by ysangkok** [comment]
@guaraqe You shouldn't need to jailbreak if you use the latest master commit. If you do, we should fix that on master.

**Comment by ysangkok** [comment]
@guaraqe We made a release of servant-0.20, but it didn't include servant-auth. We made [a revision](https://hackage.haskell.org/package/servant-auth-0.4.1.0/revisions/) to bump some bounds, but it sounds like you wanted a source release. Could you please point me to the changes in servant-auth that are not released yet?
