### ISSUE TITLE
Modify the way servant-js generates function names

### ISSUE THREAD

**Issue by freezeboy** [haskell-servant/servant#169]
I had an idea and would prefer to discuss it before writing it. Maybe it can then help to remove the #143 issue.

currently, the function name is generated this way:

```haskell
data MyAPI = "root" :> "sub" :> Get ...
```
gives:
```javascript
var getsubroot = function() {...}
```

and the function name is imediately a String.

The changes I would like to do are:
 1. keep the method at the begining, but reverse the remaining part
 2. buid an array of strings to keep the "parts" easy to find and transform

So with previous example...
```haskell
["get", "root", "sub"]
```

I then consider the functionRenamer from servant-js's default implementation is concat
we can then provide helper functions to change its behavior:

```haskell
camelCaseFunctionName :: [String] -> String
camelCaseFunctionName arr = head arr : $ map capitalize $  tail arr

snakeCaseFunctionName :: [String] -> String
snakeCaseFunctionName arr = intercalate "_" arr
```

We can even imagine to transform the method name with some function like
```haskell
crudMethodName :: String -> String
crudMethodName method = case method of
          "post" -> "create"
          "get" -> "retreive" -- or fetch
          "put" -> "update"
          otherwise -> method
```

**Comment by alpmestan** [comment]
Sounds good, could be handy to get that in for the next release. Since we're breaking things anyway, let's change that too. I can see how such a design could lift some weight off of our shoulders for having a "smart function naming heuristic", which is a good thing. We can afford to only make it "smart enough" for most cases. =)

**Comment by alpmestan** [comment]
Done in #171.
