### ISSUE TITLE
servant-auth-server: Too strict bounds on lens-aeson

### ISSUE THREAD

**Issue by sternenseemann** [haskell-servant/servant#1703]
Requests `lens-aeson >=1.0.2 && <1.2`, but also works with lens-aeson-1.2.2 according to my testing.

**Comment by arianvp** [comment]
Please open a PR

**Comment by ysangkok** [comment]
servant-auth-server-0.4.8.0 was released with this bound bumped. See [cabal file](https://hackage.haskell.org/package/servant-auth-server-0.4.8.0/src/servant-auth-server.cabal). Closing as completed.
