### ISSUE TITLE
Get '[JSON] does not imply a header Accept: application/json

### ISSUE THREAD

**Issue by alt-romes** [haskell-servant/servant#1715]
I am using servant-client to request JSON information from the hackage API, but it turns out that specifying '[JSON] in the Get request will not add a header `Accept: application/json` to the Request, even though `requestAccept` seems to have the correct application types.

Here's a reproducer:
```haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
module Main where

import GHC.Generics
import Data.Proxy
import Data.Aeson
import Servant.API
import Network.HTTP.Client (newManager, defaultManagerSettings, requestHeaders)
import Servant.Client

data Package
  = Package
    { packageName :: String
    , downloads :: Int
    }
    deriving stock Show
    deriving stock Generic
    deriving anyclass FromJSON

type API = "top" :> Get '[JSON] [Package]

getTop :: ClientM [Package]
getTop = client (Proxy @API)

main :: IO ()
main = do
  manager' <- newManager defaultManagerSettings
  let clientEnv = mkClientEnv manager' (BaseUrl Http "hackage.haskell.org" 80 "packages")
  res <- runClientM getTop (clientEnv{makeClientRequest = \b r -> makeClientRequest clientEnv b r >>=
                                                            \r' -> return r'{requestHeaders = [("Accept", "application/json")]}})
  case res of
    Left err -> putStrLn $ "Error: " ++ show err
    Right packages -> print packages
```
with `build-depends: base, servant, servant-client, aeson, http-client`

## Expected behaviour

I was expecting the `Accept: application/json` to be automatically added to the request, since I'm using a `Get` request and `JSON` as the decoding format.

**Comment by tchoutri** [comment]
Ah, how quaint! I'll toy with your code and hit httpbin.org to see where it fails.

**Comment by tchoutri** [comment]
Hmm I'm not seeing anything explicitly wrong in this result:

```json
{
  "headers": {
    "Accept": "application/json;charset=utf-8,application/json", 
    "Accept-Encoding": "gzip", 
    "Host": "httpbin.org", 
    "X-Amzn-Trace-Id": "Root=1-660c6e2c-75bb6dfc08b3f13056f4c4d0"
  }
}
```

**Comment by tchoutri** [comment]
@alt-romes In my personal experience, hackage-sever is more often faulty than servant-client. If you can trace the requests as they are understood and processed by hackage-server and show that it's `servant-client`'s fault I'd be more than happy to reopen, but in this case it might be a case of bad behaviour from the server.

**Comment by tchoutri** [comment]
Coming back to this, it appears that Hackage Server is overly compliant and will not process correctly requests with a MIME type that includes a charset encoding. See 
https://github.com/haskell/hackage-server/issues/839.

Maybe it makes indeed sense for Servant's `JSON` not to specify the charset. Sorry for the premature closing of the issue @alt-romes.
