### ISSUE TITLE
Export a function of type `IO (Either ServerError a) -> Handler a` from `Servant.Server`

### ISSUE THREAD

**Issue by danidiaz** [haskell-servant/servant#1732]
Currently we have `runHandler :: Handler a -> IO (Either ServerError a)`, and it would be good to have a function going in the other direction.

Of course, it's easy to lift an `IO a` to `Handler a` using `liftIO` but, unless I'm mistaken, going from `IO (Either ServerError a)` to a `Handler` requires a dependeny on `transformers` and importing the `ExceptT` constructor.

Instead of a special-purpose function, re-exporting the `ExceptT` constructor could be another solution.

**Comment by ysangkok** [comment]
Sounds fairly innocent, I'd review a PR for this. But `transformers` is such a popular package, I am not sure I fully understand why one would avoid it. Is it just because it's cumbersome for something you think is something Servant should have out of the box?

**Comment by danidiaz** [comment]
For small enough cases, I do like to use `Servant` without `tranformers` and `mtl`. I just stay in the `IO` monad and lift the result to `Handler` at the last minute. I guess you could call it "simple Servant" 😆 

I've just realised that I already can write a function `IO (Either ServerError a) -> Handler a` without those dependencies, because [`throwError`](https://hackage.haskell.org/package/servant-server-0.20/docs/Servant.html#v:throwError) is re-exported by the `Servant` module. Still, I believe having an explicit inverse to [`runHandler`](https://hackage.haskell.org/package/servant-server-0.20/docs/Servant-Server.html#v:runHandler) could make sense.

**Comment by tchoutri** [comment]
@danidiaz Are you happy with the PR? If yes, I'll let you close this ticket. :)
