### ISSUE TITLE
Client functions with BaseUrl param

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#174]
Right now the `BaseUrl` can only be provided to the `client` function itself, not to the returned functions. This makes varying the URL significantly harder.

(We previously had it this way, but the `BaseUrl` param would come in random argument positions, which was significantly worse)

**Comment by tfausak** [comment]
:+1:

**Comment by jkarni** [comment]
I started writing a typeclass to distribute the `BaseUrl` (see [here](http://lpaste.net/137511)). Some issue came up, but I don't quite remember the details (the lpaste doesn't even typecheck, I think, but I can't find the fixed up version). The idea is this though:

```
clifn1 base = let (c :<|> _rest) = client api base in c
```
Gets the *first* client function in the desired format (i.e., with an explicit `BaseUrl` argument). We want a type class that recurses down the API accumulating such functions. 

The typeclass approach might not be the only one, it's just what I intuitively reach for in servant-related code.

**Comment by legrostdg** [comment]
I just found this one while I wanted to add command-line based configuration of the BaseUrl port to my client... It would be nice to be able to do so easily!

**Comment by jtdaugherty** [comment]
I'll chime in and add that this is pretty painful for me, too.  Having to bind the URL early with `client` makes it hard to write a module that exports the client API functions.  I think that it would be nice to be able to do something like this:
```
data MyAPIRecord = API { endpoint1 :: ..., endpoint2 :: ... }

mkAPI :: BaseUrl -> MyAPIRecord
mkAPI = ... (in terms of client)
```
That would make it possible to configure the API nicely, package up all the endpoint functions in one unit that I can pass around, avoid top-level bindings with missing type signatures (that I have to add myself), etc.

**Comment by jkarni** [comment]
I think we could do something similar with the `safeLink` machinery. Though `client` takes a `BaseUrl` for the argument API, the argument API can be a subset (even a single endpoint) of the entire API. E.g.:

```
endpoint1 :: BaseUrl -> ExceptT ServantError IO User
endpoint1 = client (Proxy :: Proxy ("user" :> Get '[JSON] User)) 

etc.
```

**Comment by fizruk** [comment]
@jtdaugherty I use exactly this approach at work, which I explain in https://github.com/haskell-servant/servant/issues/335#issuecomment-172300487. I am not sure what you mean by *"it would be nice to be able to do something like this"* — it's already possible, just requires a few more lines than with top-level bindings.

**Comment by jtdaugherty** [comment]
@fizruk - yeah, I've used that same approach. But in my case the record type has enough fields that the pattern match required to assign them all (i.e. the long chain of `foo :<|> bar :<|> ...`) is unpleasant.  I think what I have in mind is something like what `lens` does for generating lenses for record fields where a template haskell directive makes you a record type by inspecting your API.

**Comment by fizruk** [comment]
@jkarni can this be closed in favour of #344?

**Comment by jkarni** [comment]
Closing (done in #599 )

**Comment by soenkehahn** [comment]
Does #599 really solve this? As I understand it enables us to use `enter` to make this happen, but maybe we should provide the natural transformation to do this. Or even a `client` variant that does this. Or at least some documentation how this is supposed to work. Or am I missing something in #599?

**Comment by soenkehahn** [comment]
cc: @amarpotghan
