### ISSUE TITLE
servant-server: Revise `warp <3.5` on Hackage?

### ISSUE THREAD

**Issue by JackKelly-Bellroy** [haskell-servant/servant#1754]
We are successfully using `allow-newer: servant-server:warp` internally, and I see the latest `servant-server.cabal` has `warp <3.5`. Could we please have a metadata revision on Hackage to allow this?

**Comment by maksbotan** [comment]
Done in https://github.com/commercialhaskell/stackage/issues/7287#issuecomment-2116245107, please re-open if I missed something.
