### ISSUE TITLE
Prepare servant-quickcheck 1.0 release

### ISSUE THREAD

**Issue by maksbotan** [haskell-servant/servant#1757]
Hi @tchoutri @fisx.

Looks like servant-quickcheck was not uploaded to Hackage since 2020. Moreover, there is 0.10.0.0 release on Hackage that is did not exist at any point in time in this repo, not sure how is that possible.

Can you please verify that current version in the repository, 1.0.0.0, is ready for Hackage release?

**Comment by tchoutri** [comment]
No idea who uploaded 0.0.10.0.
0.1.0.0 needs a last PR to fix the cabal file and then should be good.
