### ISSUE TITLE
Client functions with Manager param

### ISSUE THREAD

**Issue by aemxdp** [haskell-servant/servant#176]
I'd like to open a discussion for allowing custom connection manager for servant-client. Currently there is an [internal global manager](https://github.com/haskell-servant/servant/blob/master/servant-client/src/Servant/Common/Req.hs#L133) established via unsafePerformIO which is used for everything. My guess it's for convenience. I'd like to propose at least allowing to specify Manager for `client` function, but would be even better to be able to specify it per function as #174 asks for BaseUrl.

**Comment by alpmestan** [comment]
I think we're at a point where we need to think about #174 and this issue together. It would be pretty neat to find a way to be able to specify whether we want the `BaseUrl` argument per-function or not, and whether we want one global manager or if the functions should expect one. That looks a bit tricky because depending on the choice, the types of the client functions are quite serious impacted. But definitely a good idea though!

I'll start thinking about this but if anyone has an idea, I'm all ears =)

**Comment by aemxdp** [comment]
One idea is to have two mutually-exclusive interfaces like Servant.Client (per function) and Servant.Client.Simple (per `client` call), I definitely saw this approach before, but can't remember where exactly. Of course there are downsides: it will make maintenance harder and may require some code duplication. But maybe such interfaces here can share most things (simply by re-exporting from some Servant.Client.Shared) but each will have its own implementation of `client` and some definition-closing combinators like Get, Post, Put ... Raw.

**Comment by aemxdp** [comment]
Another idea is to try using some typelevel magic to implement such operator:
```haskell
supply x (f1 :<|> f2 :<|> ... :<|> fN) = f1 x :<|> f2 x :<|> ... :<|> fN x
```
Then existing combinators can be changed to always expect baseurl and manager parameters, but at the `client` call site there are many choices: to call just `client` and get flexible parameterized functions, or to call something like `supply (baseurl, manager) . client` and get simple convenient functions.

**Comment by alpmestan** [comment]
Something like this?

``` haskell
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE FunctionalDependencies #-}
import Servant.API
import Servant.Client

-- f' is what we get when supplying an 'a'
-- to f
class Supply a f f' | a f -> f' where
  supply :: a -> f -> f'

instance Supply a (a -> b) b where
  supply a f = f a

instance (Supply a serv1 serv1', Supply a serv2 serv2')
      => Supply a (serv1 :<|> serv2) (serv1' :<|> serv2') where
  supply a (f1 :<|> f2) = supply a f1 :<|> supply a f2

main :: IO ()
main = do
  let (a :<|> b) = supply (5 :: Int) (f1 :<|> f2)
  print a
  print b

  where f1 :: Int -> String
        f1 i = show i ++ "?!"

        f2 :: Int -> Int
        f2 i = i ^ 2
```

**Comment by aemxdp** [comment]
@alpmestan 
Yes, like this, but it seems it's possible without UndecidableInstances. Here's associated types implementation which assumes (:<|>) is applied in right-associated way:
```Haskell
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MultiParamTypeClasses #-}

import Servant.API
import Servant.Client

class Supply a f where
    type Supplied a f
    supply :: a -> f -> Supplied a f

instance Supply a (a -> r) where
    type Supplied a (a -> r) = r
    supply a f = f a

instance Supply a rest => Supply a ((a -> r) :<|> rest) where
    type Supplied a ((a -> r) :<|> rest) = r :<|> Supplied a rest
    supply a (f :<|> rest) = f a :<|> supply a rest

main :: IO ()
main = do
  let (a :<|> b :<|> c) = supply (5 :: Int) (f1 :<|> f2 :<|> f3)
  print a
  print b
  print c

  where f1 :: Int -> String
        f1 i = show i ++ "?!"

        f2 :: Int -> Int
        f2 i = i ^ 2

        f3 :: Int -> Int
        f3 i = i `mod` 2
```

**Comment by alpmestan** [comment]
Does it work with:

``` haskell
type API = "users" :> UserAPI
          :<|> "products" :> ProductAPI

type UserAPI = "a" :> Get '[JSON] Int
                  :<|> "b" :> Get '[JSON] Int

type ProductAPI = "c" :> Get '[JSON] Int
                      :<|>  "d" :> Get '[JSON] Int
```

and corresponding dummy servers?

**Comment by aemxdp** [comment]
Whoops, I'm actually new to servant and somehow missed the ability to share prefix from tutorials, that's neat! Changing second instance to something more like your initial one seems to work fine:
```Haskell
instance (Supply a lhs, Supply a rhs) => Supply a (lhs :<|> rhs) where
    type Supplied a (lhs :<|> rhs) = Supplied a lhs :<|> Supplied a rhs
    supply a (lhs :<|> rhs) = supply a lhs :<|> supply a rhs

type API = "users"    :> UserAPI
      :<|> "products" :> ProductAPI

type UserAPI = "a" :> QueryParam "id" String :> Get '[JSON] Int
          :<|> "b" :> QueryParam "id" String :> Get '[JSON] Int

type ProductAPI = "c" :> QueryParam "id" String :> Get '[JSON] Int
             :<|> "d" :> QueryParam "id" String :> Get '[JSON] Int

(a :<|> b) :<|> (c :<|> d) =
    supply (Just "12345") $
    client (Proxy :: Proxy API) $
        BaseUrl Https "my-api.com" 8081
```

**Comment by alpmestan** [comment]
Yes, that's probably what I'd like to go for then! Not needing undecidable instances is always good, even though we can't really do without in some other places I think.

**Comment by tfausak** [comment]
I just want to chime in to say that I'm very eager for a fix to both this issue and #174. What can I do to help?

**Comment by jkarni** [comment]
@tfausak I'm in favour of just passing `Manager` as a param rather than `unsafePerformIO`-ing one. @alpmestan, what do you think?

If so, then threading the `Manager` as we thread `BaseUrl` would work (and shouldn't be much work). Perhaps if we do that we would like to apply the same solution we come up with for #174 to `Manager` as well, but it'd be best to discuss that there.

**Comment by tfausak** [comment]
I think passing around a manager is fine. And I agree that it sounds like the solution to this will be similar to #174. 

One thing I've grown to like is passing around `Request -> IO Response` instead of just a manager. That allows you to inject "middleware" like logging. It also makes testing a lot easier since you can inject custom responses. So you may consider doing that.

**Comment by alpmestan** [comment]
I too wouldn't mind passing a `Manager` and `BaseUrl` around, as long as we provide a function or something to do it "the easy way", with one `Manager` and `BaseUrl` supplied to it that would then be "distributed" automatically for me to each client function.
