### ISSUE TITLE
servant-auth doesn't build with new js backend

### ISSUE THREAD

**Issue by tysonzero** [haskell-servant/servant#1764]
This is due to the `jose` -> `crypton`/`memory` -> `basement` dependency chain with `basement` being the package that actually fails due to its usage of `GHC.IntWord64`.

I bring up the issue here though because I think it may be rather hard to get that chain to build with the js backend in the near future, so I was curious if there was a possibility of making the dependency chain a little lighter for the shared `servant-auth` library.

A heavier dependency chain on `servant-auth-server` is much less of a problem due to building a backend server with the js library being presumably a lot less desirable.

**Comment by ysangkok** [comment]
Given that jose is still maintained, and offers a fine API, wouldn't it make more sense to report the issue there? The community should migrate off of Crypton since nobody wants to maintain the underlying libraries.

**Comment by tysonzero** [comment]
I filed an issue there, but that may be harder than removing the dependency on it, since it doesn't seem like `servant-auth` itself needs to do much cryptography, since it's just the api layer, unlike `servant-auth-server`.

**Comment by ysangkok** [comment]
Thank you, I will close this issue and I think we can't be keeping track of all the dependencies that aren't compatible with the JavaScript backend. There are probably more, since many Haskell libraries are backed by C code.
