### ISSUE TITLE
Please edit the Hackage metadata (or upload a new version)

### ISSUE THREAD

**Issue by erikd** [haskell-servant/servant#1773]
The version on [Hackage](https://hackage.haskell.org/package/servant-server) of `servant-server` does not compile with `ghc-9.10` (the upper bound on `base` says `< 4.20`) but the version here in the repo does.

Same for the `servant` package,

**Comment by tchoutri** [comment]
On it, thanks

**Comment by tchoutri** [comment]
Yes it is planned. :)

**Comment by tchoutri** [comment]
@erikd the revisions have been made, can you try them?

**Comment by erikd** [comment]
I checked earlier today and they still needed fixing, but the are fixed now. Thanks!

**Comment by tchoutri** [comment]
Thank you for your patience :bow:
