### ISSUE TITLE
possible regression in 0.20.2 affecting routing

### ISSUE THREAD

**Issue by jgraydus** [haskell-servant/servant#1780]
I've noticed a subtle change in behavior with the 0.20.2 release. Often when setting up new routes, I'll implement route handlers as `error "not implemented yet"` initially. Prior to 0.20.2 this worked fine.  Existing routes would still work and invoking the unimplemented route would result in the error, as expected. As of 0.20.2, the error is thrown no matter which route is invoked. I was able to reproduce with this minimal example:
```
module Main where

import Servant
import Network.Wai.Handler.Warp (run)

type Foo = "foo" :> Get '[JSON] ()

fooHandler :: Server Foo
fooHandler = pure ()

type Bar = "bar" :> Get '[JSON] ()

barHandler :: Server Bar
barHandler = error "not implemented yet"

type Api = Foo :<|> Bar

apiHandler :: Server Api
apiHandler = fooHandler :<|> barHandler

main :: IO ()
main = do
  putStrLn "starting server"
  run 8000 $ serve (Proxy @Api) apiHandler
```
I expect `/foo` to be successful and `/bar` to cause an error, but actually both routes result in the error being throw.
```
> curl http://localhost:8000/foo
not implemented yet
CallStack (from HasCallStack):
  error, called at src/Main.hs:14:14 in main:Main
```
I can work around the issue by adding some non-error value prior to the error. e.g.
```
barHandler = do
  pure ()
  error "not implemented yet"
```
I suspect something with the way routing is done is less lazy than it used to be, but I'll defer to the maintainers to determine whether this is a bug.

p.s. I love this library. Thanks!

**Comment by tchoutri** [comment]
Thanks a lot for this ticket!

**Comment by ysangkok** [comment]
Seems like this was introduced in #1750

**Comment by tchoutri** [comment]
Yep
