### ISSUE TITLE
GitHub repository description is misspelled

### ISSUE THREAD

**Issue by elldritch** [haskell-servant/servant#1793]
It should say `Servant` instead of `Servat`:

![1731551098](https://github.com/user-attachments/assets/4a03788b-c867-45d2-8bac-41ddaf8ac6ee)

This typo shows up in the repository preview in Google results:

![1731551154](https://github.com/user-attachments/assets/4e397a69-6b03-4581-9df8-1240d80face4)

**Comment by fisx** [comment]
fixed, thanks!
