### ISSUE TITLE
Set Content-Disposition to attachment;filename

### ISSUE THREAD

**Issue by rubenmoor** [haskell-servant/servant#181]
Is there a way to implement an `Accept` instance that produces the below `Content Disposition`?

    Content-Type: text/xml
    Content-Disposition: attachment;filename=\"My Text File.txt\"

Currently I have

    instance Accept XML where
      contentType _ = "text" // "xml" /: ("charset", "utf-8")
    
    instance MimeRender XML String where
      mimeRender _ val = BL.pack val

**Comment by jkarni** [comment]
Would returning `Content-Disposition` as an extra header (with [`addHeader`](http://haskell-servant.github.io/posts/2015-05-10-servant-0.4-released.html#response-headers)) suffice?

**Comment by jkarni** [comment]
@rubenmoor can you let us know if addHeader suffices for your needs, and if we can close this?

**Comment by rubenmoor** [comment]
Yes, thank you. `addHeader` will suffice.

2015-08-13 13:27 GMT+02:00 Julian Arni <notifications@github.com>:
