### ISSUE TITLE
Discover (sub) APIs and the corresponding handlers under a directory (TH?)

### ISSUE THREAD

**Issue by alpmestan** [haskell-servant/servant#187]
While talking with *jsidfofo* on IRC, who would like to write handlers and the corresponding routes "at the same time", i.e have them visually close to one anoher, we had the idea of a (probably TH-powered) thing that could scan some directory for API types and the corresponding request handlers, and automatically write the "big API type" that `:<|>`'s together all the ones it would have discovered, doing the same with the request handlers.

I know close to nothing about TH but maybe it could be of help here? An alternative approach could be to write something akin to Simon's *hspec-discover*.

**Comment by jkarni** [comment]
How would we choose the order (w.r.t. `:<|>`) of the sub-apis?

**Comment by alpmestan** [comment]
Very good question. Alphabetically comes to mind, but that wouldn't work. And there's this last spot for `Raw` that we use for serving static files: where would we put it in a standard way so that we know we would have to list it last in the big, complete API type? And also make it optional...

Yeah, a lot of unanswered questions. But it might be nice though, I could benefit from it on a few large apps I have worked on.

**Comment by jkarni** [comment]
If no solutions come up re: ordering with `:<|>`, should I close?

**Comment by alpmestan** [comment]
For now yeah, I guess.
