### ISSUE TITLE
autogenerated javascript can have invalid identifier

### ISSUE THREAD

**Issue by berdario** [haskell-servant/servant#191]
If you have a route like

```
"preferred-hours" :> Get '[JSON] Int
```

servant-js will generate a function with name `getPreferred-hours`.

**Comment by alpmestan** [comment]
With the code currently in *master* (i.e in the upcoming 0.5 release), you can give a function that "modifies" names. Take a look [here](https://github.com/haskell-servant/servant/blob/master/servant-js/src/Servant/JS/Internal.hs#L32). So you can just specify a function that watches for "preferred-hours" and gives a custom, valid name, and just leaves all other names as they are. Is that a satisfactory solution for you?

**Comment by freezeboy** [comment]
What if we split url portions when we generate the segments ? this would then generate:

```haskell
usingConcat: preferredhours
usingCamel: preferredHours
usingSnake: preferred_hours
```

**Comment by alpmestan** [comment]
What should we split on, aside from `-`? Sounds a bit arbitrary but if you have a suggestion that works well enough in practice, I'm all ears.

**Comment by berdario** [comment]
I think we should just split using something like this regexp when matching over (example in Python):

    >>> re.split('[^\w]', 'a_-a\U00010330b\u180ec')
    ['a_', 'a𐌰b', 'c']

I can write a patch for this, as soon as I'll have time (which means that someone else might want to do it earlier... )

**Comment by jkarni** [comment]
[Here](https://mathiasbynens.be/notes/javascript-identifiers) is a description of valid identifiers in JS. The simplest thing that might work is to just strip invalid ones, and prefix an underscore if the result is a reserved keyword. This doesn't allow camel/snake casing, but the advantage of keeping it simple is that it'd also be predictable.

**Comment by freezeboy** [comment]
@jkarni why do you say this doesn't allow camel/snake case ? instead of stripping invalid chars we just split into pieces before joining them using the camel/snake function ?

**Comment by jkarni** [comment]
@freezeboy I was wrong. 

Anyone know what's the status on this? It feels like a lot of changes that are relevant have happened since.

**Comment by freezeboy** [comment]
I haven't touched it since that day, but I think we can insert some "sanitizing" on each part of the function name before giving the list to the camel/snake/transforming function if you still think bad things can happen

**Comment by berdario** [comment]
I'm having a look at the code, I found some weird changes

https://github.com/haskell-servant/servant/commit/f6ee02eb917f231899de6a744e01026babc3472b

https://github.com/haskell-servant/servant/blob/cda3161/servant-foreign/src/Servant/Foreign/Internal.hs#L320

These seems to be ad-hoc changes, done in a non-appropriate place (`-` would be a valid identifier character for a lisp, for example... and thus should belong in servant-js, not servant-foreign)

And the `toValidFunctionName` function has apparently always been used to only filter variable names for headers

https://github.com/haskell-servant/servant/commit/b59a62e01207ade90b4795e04ebad5476cf8a9ec

Hopefully I'll get something working by the end of the day
