### ISSUE TITLE
Getting Started link on Hackage is broken.

### ISSUE THREAD

**Issue by seanparsons** [haskell-servant/servant#192]
The link to the Getting Started page listed here doesn't work:
https://hackage.haskell.org/package/servant-server

**Comment by alpmestan** [comment]
Where is the getting started page referenced on this page? It only appears in the description for versions of servant-server prior to 0.4, doesn't it?

**Comment by seanparsons** [comment]
In the "Getting Started" section...

**Comment by alpmestan** [comment]
Oh, sorry, I had not scrolled down to the README on that page, so did not see what you were talking about. I'll release a new minor version of servant-server today that has a README with the right link. Thanks for the report!

**Comment by alpmestan** [comment]
[Fixed](https://hackage.haskell.org/package/servant-server).
