### ISSUE TITLE
Serve static HTML page with blaze-html

### ISSUE THREAD

**Issue by yemi** [haskell-servant/servant#195]
I'm still pretty new to both Haskell and Servant so this is probably something really straightforward, but I haven't found out how to do it.

Basically what i want is to use an API with a single endpoint like this:

``` haskell
type API = "/" :> Raw
```

and the server _something_ like this:

``` haskell
server :: Server API
server = return $ h1 "hello world"
```

where `h1` comes from `blaze-html`

Whats the best way to do something like this in servant?

**Comment by BartAdv** [comment]
How about: https://hackage.haskell.org/package/servant-blaze ?

**Comment by alpmestan** [comment]
It's also mentionned [in the tutorial](https://haskell-servant.github.io/tutorial/server.html#case-studies-servant-blaze-and-servant-lucid) (explains how it works and shows an example). There's [this](https://github.com/haskell-servant/servant/blob/master/servant-examples/tutorial/T4.hs) which shows an example with Lucid, this is almost the same with blaze. Let us know if that answers your question, in which case feel free to close the issue.

**Comment by yemi** [comment]
Maybe im misunderstanding this, but doesnt the tutorial only show how you use html based on a data type `person` for example? What i want is just a plain html file served by servant and templated in blaze-html?

**Comment by echatav** [comment]
A static page correponds to a unit type. Does this help?

```
module Page where

import Network.Wai
import Network.Wai.Handler.Warp
import Servant
import Servant.HTML.Blaze
import Text.Blaze.Html5 hiding (main)

data Page = Page

instance ToMarkup Page where
  toMarkup Page = h1 "hello world"

type API = Get '[HTML] Page

api :: Proxy API
api = Proxy

server :: Server API
server = return Page

app :: Application
app = serve api server

main :: IO ()
main = run 8080 app
```

**Comment by BartAdv** [comment]
Question is, why you need templating for static page. Just HTML file served
from disk won't do? For this you would use
https://hackage.haskell.org/package/servant-server-0.4.0/docs/Servant-Utils-StaticFiles.html
.

But if you want to build page with blaze for whatever reason, then remember
there is nothing servant specific about Raw - its just WAI Application.

**Comment by yemi** [comment]
Thanks @echatav for the snippet, that helped. 

And @BartAdv, no big reason, I just wanted to try this out without using any static html files and do all templating in blaze. Thanks for the explanation, everything works as intended now :) :+1:

**Comment by alpmestan** [comment]
@yemi It's very simple if you don't want to serve a type. Just make your endpoint `Get '[HTML] Html`, where `Html` is [the one from this module](https://hackage.haskell.org/package/blaze-html-0.8.0.2/docs/Text-Blaze-Html.html#t:Html). There **is** a `MimeRender` instance that allows you to return some `Html` (i.e some arbitrary *blaze-html* html code / entire page) along with the `HTML` content type.

``` haskell
type API = "mypage" :> Get '[HTML] Html

api :: Proxy API
api = Proxy

server :: Server API
server = return page

  where page :: Html -- the Html from blaze
             page = p "hello"

app :: Application
app = serve api server

main :: IO ()
main = run 8080 app
```

Something like this with the proper imports and the `OverloadedStrings` extension should work.

**Comment by yemi** [comment]
Cool, thanks @alpmestan
