### ISSUE TITLE
415 falls through

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#197]
type Api = "hi" :> ReqBody '[JSON] Int :> X
                :<|> Raw

In the above API, a request to "hi" with a body content-type of `text/plain` (or none at all) will fall through to the `Raw` endpoint. This is internally consistent with the general servant behaviour, but likely to be very surprising. I think it makes more sense to just always return 415.

**Comment by alpmestan** [comment]
So, we change the semantics of `:<|>`?

**Comment by jkarni** [comment]
I think we can just change the semantics of content-type mismatch.

**Comment by kosmikus** [comment]
I disagree with this proposed change. The current behaviour is the only behaviour that makes sense to me. How else would I modularly (i.e., separately) specify two handlers for the same endpoint for different body content types?

**Comment by alpmestan** [comment]
Just posted a comment in #214 that explains many things among which this issue. Hoping to get all the eyes and brains we can there to find a nice and solid solution to this whole thing with routing and combining "routing results" and the problems it causes.

**Comment by jkarni** [comment]
> How else would I modularly (i.e., separately) specify two handlers for the same endpoint for different body content types?

Fair point, but it also seems to favour underlying elegance (at the cost of practicality) a little too much. Being able to have separate handlers for different content-types is neat, but I don't see an obvious use, especially since in my opinion *content-type should not affect behaviour*. If an endpoint can handle JSON and XML request bodies, it *should not* return an `Int` and a `String` in each case, but rather always the same datatype. And in practice I'd imagine being bitten by routing continuing is a much more common issue than wanting that form of modularity.

**Comment by jkarni** [comment]
Closed in #218 .
