### ISSUE TITLE
Servant with persistent/IO

### ISSUE THREAD

**Issue by rubenmoor** [haskell-servant/servant#20]
Hello,

I can't figure out based on the example code, how to use servant with `persistent`. Instead of returning something like `Greet` (s. example), I have an IO action (because I access a database). Has someone done something like that? Is there an example? All help is appreciated!

**Comment by alpmestan** [comment]
The code for any hander is, for now (this may change in future versions but hasn't changed yet), running in `EitherT (Int, String) IO a`. So basically, it all boils down to this: do you have a way to run your *persistent* code by getting the result in `IO`? I assume this is possible, in which case you just have to use `liftIO`. Let us know if this is still not helpful/clear to you, in which case I can take a closer look at how one can mix *persistent* and *servant*.

**Comment by rubenmoor** [comment]
Awesome! `liftIO` just did the trick! Haskell is still magic to me :dancers:  ;)
