### ISSUE TITLE
Allow for paths in BaseUrl

### ISSUE THREAD

**Issue by tfausak** [haskell-servant/servant#203]
I like being able to generate clients with `Servant.Client.client`. However I wish that I could add a path to my `Servant.Common.BaseUrl`. For example, let's say I have this API:

``` hs
type API = "widgets" :> Get '[JSON] [Widget]
```

I would like to be able to create clients that could consume that API at `example.com` and `example.org/api/v1`. 

- `http://example.com/widgets`
- `http://example.org/api/v1/widgets`

I can create `BaseUrl` values that have paths, but the client ignores them.

``` hs
host = BaseUrl Http "example.org/api/v1" 80
                                ^^^^^^^ - This part is ignored.
```

**Comment by alpmestan** [comment]
We probably have to change *servant-client* a bit to make your change happen. It's however a quite simple one to make. Would you like to take a stab at it? Otherwise I'll get around to it, but not in the upcoming days.

**Comment by tfausak** [comment]
Sure, I'll see what I can do.
