### ISSUE TITLE
Converting to raw should not alter behaviour

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#209]
When writing a `Middleware` combinator, I noticed it was not possible to do the obvious thing, which is to convert the sub-api to an `Application` and then apply the middleware. This is because the http errors that come out of `Raw` are not treated in the same way as framework errors. Relatedly, user-sent errors (with `Left errXXX`) are also not treated in the same way as framework errors. They all should. 

This solves more than the middleware issue; it also fixes the currently quite crazy issues with `Raw` (e.g. having `Raw` be the first, top-level combinator makes everything else in the API be ignored.

**Comment by alpmestan** [comment]
Fixing this would be great!

**Comment by fizruk** [comment]
What's the status of this? Has this been fixed already? If not, can you elaborate on the problem?

**Comment by jkarni** [comment]
As mentioned [here](https://github.com/haskell-servant/servant/issues/108#issuecomment-173187131), I don't think this will be possible.
