### ISSUE TITLE
ToSample grievances

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#211]
The two args for `ToSample` are necessary internally, but there should be a different class that just has one, so it's simple to implement, with an instance for it against the underlying `ToSample`. 

Moreover some basic instances (`()`, `ToSample a a => ToSample [a] [a]`, `ToSample a, ToSample b => ToSample (a, b)`) are missing.

(See also #151)

**Comment by fizruk** [comment]
Why does `ToSample` need two arguments internally?

**Comment by jkarni** [comment]
@fizruk sorry for taking so long to respond. The reason is that in *one* case (`ResponseHeaders`) the datatype we get and the datatype we need a sample for are different. So the first argument is `ResponseHeaders hdrs a` and the second is `a`.

**Comment by jkarni** [comment]
I took a look at having two separate classes, and don't think it'll work due to ambiguity issues. Closing since the rest of this task has been done in #227 .

**Comment by fizruk** [comment]
Okay, but I can't see do we need `ToSample` instance for `Headers ls a` anyway: it is not used anywhere in the code (unless you consider nested `Headers ls (Headers ls' a)`, which should not happen AFAICT).

I have just removed the second argument from `ToSample` together with `ToSample (Headers ls a)` instance, built and run tests and everything looks fine.

So is there any problem I don't see?

**Comment by jkarni** [comment]
>I have just removed the second argument from ToSample together with ToSample (Headers ls a) instance, built and run tests and everything looks fine.
> So is there any problem I don't see?

Missing tests :).

You can have an endpoint such as `EitherT ... (Headers ls a)`, and we want to be able to provide a sample response. But the sample response (body) should be an `a`, not a `Headers ls a`. So the reasoning was we'd have the second param to indicate the sample type in that case would be an `a`. It doesn't need to show up in the code, though.

One option would be to have a single param, and then `ToSample a => ToSample (Headers ls a)`. But of course then we need `ToJSON a => ToJSON (Headers ls a)`. That's not bad, but the idea is that we can have samples in other content-types extensibly, so users declaring a new content-type would have to do something similar (for `ToXML` or whatever). It still might be a better idea.

Does that make sense? Any thoughts?

**Comment by fizruk** [comment]
> You can have an endpoint such as `EitherT ... (Headers ls a)`...

Sorry, I don't understand what you mean by this. Do you mean something like

```haskell
type TestApi1 = Get '[JSON, PlainText] (Headers '[Header "Location" String] Int)
```

Because it works just fine!
The reason is that we don't use `ToSample (Headers ls a)`, but rather pattern match against `Headers` in `HasDocs` instances like this:

```haskell
instance
#if MIN_VERSION_base(4,8,0)
         {-# OVERLAPPING #-}
#endif
        (ToSample a, IsNonEmpty cts, AllMimeRender cts a, SupportedTypes cts
         , AllHeaderSamples ls , GetHeaders (HList ls) )
    => HasDocs (Delete cts (Headers ls a)) where
  ...
```

**Comment by jkarni** [comment]
Ugh, my mistake (and a pretty terrible one since I wrote both those parts of the code in the same commit!). You're absolutely right. Want to remove the extra param, or should I?
