### ISSUE TITLE
Examples file names are not very descriptive 

### ISSUE THREAD

**Issue by octopuscabbage** [haskell-servant/servant#212]
The filenames in the examples folder are not very descriptive of what they are examples of. Even though they correspond to the tutorial it's more helpful if they are named clearly for referencing later.

**Comment by alpmestan** [comment]
Are you talking about the `T1`, `T2` etc modules? Or all of the examples from the *servant-examples* pkg?

**Comment by octopuscabbage** [comment]
Yeah mostly the T1, T2 etc modules. Like I said they are useful to glance back on if one couldn't quite remember the syntax of something that can't as easily be answered by hackage (Plus I've found that hackage isn't great at documenting the type of stuff that's hard to remember in servant)

**Comment by alpmestan** [comment]
Hmm. The names I can think of wouldn't be "super-helpful", but of course still more descriptive than `T1`, `T2`, etc. If you have any suggestion for the module names, I'm all ears!

**Comment by fizruk** [comment]
Superseded by #342.
