### ISSUE TITLE
Use path-pieces package?

### ISSUE THREAD

**Issue by fizruk** [haskell-servant/servant#213]
Is there any reason not to use [`path-pieces`](http://hackage.haskell.org/package/path-pieces) package instead of [`Servant.Common.Text`](http://hackage.haskell.org/package/servant-0.4.4.2/docs/Servant-Common-Text.html)?

I am currently using `persistent` with `servant` and have to manually define instances like this for almost every entity I have (the `PathPiece` instances are provided automatically by `mkPersist`):

```haskell
instance FromText (Key User) where
  fromText = fromPathPiece

instance ToText (Key User) where
  toText = toPathPiece
```

Also, we might use `MultiPathPiece` class for a corresponding combinator (to capture the rest of the path).

**Comment by arianvp** [comment]
Seems like a pretty sane idea to me.  I like it.

**Comment by fizruk** [comment]
@arianvp yes, with `UndecidableInstances` it is possible. I still think we should not have multiple classes for the same thing.

**Comment by alpmestan** [comment]
Have you seen [this discussion](https://github.com/haskell-servant/servant/issues/137) ?

**Comment by jkarni** [comment]
I'd be okay with @gregwebs suggestion (last comment on #137).

**Comment by fizruk** [comment]
Sorry for that.

I have created an issue in the `path-pieces` repository, asking to apply @gregwebs's suggestions directly to `path-pieces`.

**Comment by alpmestan** [comment]
@fizruk FWIW, I quite like your suggestion in the *path-pieces* issue and would agree to change servant to use that instead of our `FromText`/`ToText` classes I think.
