### ISSUE TITLE
broken nix script (`update-nix-files.sh`)

### ISSUE THREAD

**Issue by soenkehahn** [haskell-servant/servant#216]
Currently `update-nix-files.sh` seems to be broken. Do we have someone that uses these scripts regularly? If not I'd be in favor of removing the files.

**Comment by jkarni** [comment]
Broken how? @codedmart at least uses nix, and it'd be nice to support development with nix, cabal and stack (if it's not too much of a maintenance overhead).

**Comment by codedmart** [comment]
@soenkehahn I guess it should be noted that I use unstable channel or master from nixpkgs. I am in favor of removing individual nix files from each folder but keeping this so users can generate their nix files. I can fix it up to work with the current stable nixpkgs channel and unstable/master.

**Comment by aycanirican** [comment]
@codedmart why don't you use here document style embedding? Ex:

cat < EOF > $SHELLNIX
  .. here goes shell.nix content ..
EOF

**Comment by jkarni** [comment]
Fixed in #217 (though if anyone wants to refactor it into here docs, that'd be welcome!)

**Comment by soenkehahn** [comment]
@codedmart: I don't use the nix scripts so I don't really have an opinion on unstable vs. stable or having nix expressions in subfolders or not. I just wanted to make sure we don't have a broken script in the repo. (Which was fixed by #217.)
