### ISSUE TITLE
406 errors for Left

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#219]
We don't actually throw a 406 if the Accept header can't be matched, but the handler throws a left. In fact, we run the entire handler before checking whether we can fulfil the `Accept` header. This should be fixed.

**Comment by jkarni** [comment]
While directly fixing this isn't hard, it does bring up a different issue. If we check whether we should return 406 before running the handler, that doesn't give an opportunity for 415s to surface from the ReqBody combinator, so if both the Content-Type and the Accept header can't be handler/matched, the Accept header is the one that will raise the error (whereas my opinion, and that of [http-decision-diagram](https://raw.githubusercontent.com/for-GET/http-decision-diagram/master/httpdd.png), is that it should be the other way around).

**Comment by kosmikus** [comment]
Ok, this issue is related to the problem I mentioned in my review of #218 that I'd like to delay `Capture` processing, but @jkarni understandably objected that it currently prioritized "Bad Method" over 404, which is undesirable.

**Comment by kosmikus** [comment]
@jkarni Is this still open?

**Comment by jkarni** [comment]
Nope!
