### ISSUE TITLE
Parse error: POST route with String in request body

### ISSUE THREAD

**Issue by rubenmoor** [haskell-servant/servant#22]
Hello,
when I try to build a root that expects a simple String in the request body (rather than a Haskell data instance) like so:

type Api =
    ...
    :<|>    "item" :> "create" :> ReqBody (String) :> Post ()

I always get the rather generic error response

    Invalid JSON in request body: Failed reading: satisfy

This is regardless of what I tried:

    "asdf"
    asdf
    \"asdf\"

It never made it through the servant Json parsing to my actual handler (where "asdf" would likely cause another runtime error).

Am I missing something?

(The idea behind the String in the request body is, btw, to use digestive functors for validation. If anyone else has input on how to combine servant with digestive-functors, I'm all ears!)

**Comment by thsutton** [comment]
@rubenmoor A string is not a valid JSON document, so the parser fails (with a very bad message). The top level of a valid JSON document must be:

- an object `{ ... }`; or
- an array `[ ... ]`.

You could make a `newtype` wrapper for your string with a FromJSON and ToJSON instances that wrap it in an array constructor. Alternatively, the next release will support alternative formats in addition to JSON.

**Comment by rubenmoor** [comment]
Got it!

I've seen the discussion about alternative formats. I guess I would simply need a "raw" format that passes on the request body to the handler *as is*. Is there a way to check out the most recent code that already has this feature?
The master branch did not work with servant-server 0.2.4 because of missing QQ. Do the current master branches of servant-server and core work together? Would it make sense to use these atm?

**Comment by jkarni** [comment]
yes, servant master and servant-server master should work together. We will likely also soon cut a release candidate branch for both of those that will work together

**Comment by jkarni** [comment]
Closing, but feel free to comment if you feel like I shouldn't have

**Comment by rubenmoor** [comment]
Thank you!
