### ISSUE TITLE
Use ExceptT instead of EitherT

### ISSUE THREAD

**Issue by int-index** [haskell-servant/servant#220]
Drop the `either` dependency and use `ExceptT` from `transformers` instead.

**Comment by alpmestan** [comment]
Any particular argument to motivate this change?

Note that with any API, you can have your request handlers be computations in *any monad you want*. This is covered [here](https://haskell-servant.github.io/tutorial/server.html#using-another-monad-for-your-handlers) in the tutorial. This means you could write your handlers using `ExceptT` instead of `EitherT`.

However, if you're suggesting we drop the `either` package (hence breaking a lot of servant apps), I'd be curious to know why and to hear any strong argument in favor of that.

**Comment by int-index** [comment]
> Any particular argument to motivate this change?

Any particular argument to use `EitherT` in the first place? The package has no purpose since the introduction of `ExceptT`, and the original author [seems to be in favor of gradual migration to `ExceptT`](https://www.reddit.com/r/haskell/comments/3ded39/why_cant_we_have_an_eithert_in_transformers/ct4mnk1):

> With 7.10+, we can finally start to see some migration to `ExceptT` and in theory the `either` package can start to dissolve over time as more and more code can finally start to use `transformers` to get `ExceptT` rather than either for `EitherT`.

My only argument against `EitherT` is code duplication. We now have `ExceptT`, why both? This is *morally right* to drop the `either` package.

> hence breaking a lot of servant apps

The breakage won't be silent, and it's fixable by `%s/EitherT/ExceptT/g`, so why not?

**Comment by kosmikus** [comment]
I'm mildly in favour of this. Yes, it is a somewhat arbitrary change, but since `ExceptT` is now there and provided directly by `mtl`, it seems somewhat strange to depend on the `either` package for no added functionality. We're still in a phase where we occasionally make breaking changes between servant releases, and this one has a clear upgrade path.

**Comment by alpmestan** [comment]
@int-index Alright, I missed this post indeed. Given this context, your suggestion makes a lot more sense =)

Feeling like submitting a PR for that? If not I'll take care of it in the upcoming weeks.

**Comment by s9gf4ult** [comment]
Vote for @int-index proposal also.

**Comment by int-index** [comment]
> Feeling like submitting a PR for that?

Sure.

**Comment by k-bx** [comment]
+1 on this. Let me also remind, that `errors` library switched its focus to ExceptT also: https://github.com/Gabriel439/Haskell-Errors-Library/issues/32

**Comment by jkarni** [comment]
There was some previous discussion on this in #91. We would lose compatibility with 7.8, no? If so, I'm distinctly -1 on it.

**Comment by k-bx** [comment]
@jkarni I'm not sure I follow why it wouldn't work on 7.8. Maybe http://hackage.haskell.org/package/transformers-compat would help?

**Comment by christian-marie** [comment]
If anyone cares from a practical standpoint, I'm pretty sure that you can coerce between these two (Data.Coerce).

From a migration perspective, is moving to ExceptT in the next major feasible with -compat packages?

**Comment by k-bx** [comment]
@christian-marie yes, you can check for base version and require transformers-compat in case if it's ghc <= 7.8, that should do the job

**Comment by kosmikus** [comment]
@k-bx I don't think you have to conditionally depend on transformers-compat. You should be able to just depend on it, and it should then work with ghc-7.8 and ghc-7.10.

**Comment by christian-marie** [comment]
OK I vote that, then.

transformers-compat on the next major release, with a change to ExceptT.

**Comment by dmjio** [comment]
+1

**Comment by jkarni** [comment]
I'm still not sure about this. Would 7.8 users be able to user `errors` at all?

**Comment by k-bx** [comment]
@jkarni yes, `errors` of branch 1.x uses EitherT, and `errors` of branch 2.x uses ExceptT, users of 7.8 are able to either use errors < 2 (if they need it with EitherT), or install transformers-compat to be able to use errors >= 2 and use it with ExceptT.

**Comment by int-index** [comment]
@jkarni First of all, `transformers` are *not* bound to the compiler (though they are shipped with it). It is entirely possible to have `7.8` with latest `transformers`!

Some users, however, experience problems when they try to upgrade to newer `transformers`, and to help them there is the `transformers-compat` package. It uses CPP magic to check if the user is using old `transformers`, and if he does, then the missing definitions are added.

Compiler version is not a concern in this case, at all.

**Comment by jkarni** [comment]
@int-index thanks for clarifying. One more question. If `transformers-compat` provides its own `ExceptT` (rather than the `transformers >= 0.4` one), then that won't work with `errors`, since `errors` uses the `transformers` `ExceptT` -- is that correct?

**Comment by dredozubov** [comment]
I'm also in a favor of this change +1

**Comment by int-index** [comment]
@jkarni That's incorrect, because definitions from `transformers-compat` are exported only if the user is on old `transformers`. Such users can't install latest `errors` at all.

**Comment by k-bx** [comment]
@jkarni both new transformers and transformers-compat provide `Control.Monad.Trans.Except` module, so it's quite hard (you'd need to use "package imports" language extension for explicit import from some package) to even know where it comes from.

**Comment by jkarni** [comment]
@int-index ok, my worry was just that some group of people (with `transformers < 0.4`) were no longer going to be able to use `errors` with `servant` after this change. You're right that it won't be for the reason I mentioned, but this is still true, no? I don't mean to suggest that's enough to rule out this change - I just want to get a clearer sense for the consequences.

@k-bx unless you're using a library that uses one of them.

**Comment by k-bx** [comment]
@jkarni correct, hopefully there isn't one

**Comment by int-index** [comment]
@jkarni This is correct, users of `transformers < 0.4` are forced to use `errors < 2.0`, which depend on `either`. One way to solve this is to ask @Gabriel439 to release `errors` that use the same `transformers-compat`-based approach.

**Comment by Gabriel439** [comment]
Alright, `errors-2.0.1` is up on Hackage and now uses `transformers-compat` to support a wider range of `transformers` versions.  Thanks to @int-index for the pull request!

**Comment by KenseiMaedhros** [comment]
Servant Tutorial Documentat does not reflect this change. I'll add a work task for myself to update it after I  have this API up and running. :)

**Comment by phadej** [comment]
@KenseiMaedhros: what tutorial are you reading? E.g. http://haskell-servant.readthedocs.io/en/stable/tutorial/Server.html uses ExcepT

**Comment by KenseiMaedhros** [comment]
That tutorial's "Combining APIs" portion.

At the point of my writing that comment, the "Combining APIs" portion was using EitherT. When resolving another issue, I noticed the "latest" documentation had it in. 

As I browse the tutorial site, I now can find no reference to EitherT anywhere, on any branch. Perhaps Google led me to an older version of the site somehow, in any case, no documentation updates needed.

**Comment by int-index** [comment]
Your browser probably had a cached version of the page.

**Comment by KenseiMaedhros** [comment]
That might be it. :) 

A couple hours after I posted that comment, I got my combined API up and DB connection working. Fastest and most enjoyable server work I've ever done. You guys have an amazing piece of software here.
