### ISSUE TITLE
question : Is there already a template engine for servant

### ISSUE THREAD

**Issue by rwobben** [haskell-servant/servant#222]
Hello, 

Im now learning Haskell and when I have finisched CIS194 and the NICTA I love to make a ecommerce site with Haskell. I like to do this with Servant but I cannot find out if there is a template engine so I can display mu html templatet at the user.

**Comment by BartAdv** [comment]
http://haskell-servant.github.io/tutorial/server.html#case-studies-servant-blaze-and-servant-lucid

**Comment by rwobben** [comment]
Thanks, I think I will stick with the blaze-html because on lucid I cannot find much info and tutorials.

**Comment by alpmestan** [comment]
Aside from -blaze and -lucid, there's a module for using [ede](http://hackage.haskell.org/package/ede) with servant, called [servant-ede](http://hackage.haskell.org/package/servant-ede).

If you want/need a package for another library, get in touch with me and we'll fix that =)

**Comment by rwobben** [comment]
oke, Is there some tutorial where I can learn ede. Expecially how to convert thigs like html

**Comment by alpmestan** [comment]
@rwobben There's an example in the docs of *servant-ede*, [on this page](https://hackage.haskell.org/package/servant-ede-0.5.1/docs/Servant-EDE.html). That shows a basic example of EDE template + how to integrate it with *servant*. The complete code lives [here](https://github.com/alpmestan/servant-ede/tree/master/example).

Now, regarding the template language/library itself, *ede*, I learned about all the constructs [here](https://hackage.haskell.org/package/ede-0.2.8.2/docs/Text-EDE.html#g:11) (from that point in the page until the bottom, the author basically explains all the syntax constructs the templating language has). If you have any question or want to help write a mini tutorial for *servant-ede* or something, let me know!

**Comment by rwobben** [comment]
Oke, the complete code makes a lot clear to me.
As I said im a super beginner and at the moment Im very busy to learn Haskell. So at the moment no time to help with servant. But maybe in the future.

**Comment by alpmestan** [comment]
No worries, good luck and enjoy the ride!

**Comment by rwobben** [comment]
Thanks, I hope it wo't take long to do the CIS and the NICTA course.
