### ISSUE TITLE
import Servant / import Servant.API

### ISSUE THREAD

**Issue by Profpatsch** [haskell-servant/servant#223]
import Servant

seems to not work any more,

    import Servant.API

does.

The tutorial & documentation should be updated.

**Comment by alpmestan** [comment]
`import Servant.API` refers to a module in *servant*. It reexports all the combinators that you can use to describe APIs.

`import Servant` refers to a module in *servant-server*, the package that for server-side things. It reexports everything from `Servant.API` along with most of the things from the *servant-server* package.

The idea is that if you are only going to describe an API type, without any server-related thing, you can import the former. If you just want to import one module to define and run a webapp with servant, `Servant` is the one you're looking for. It's the starting point for anyone writing a *servant* app, you import this and don't worry about where the names come from, everything you'll need is in scope.

**Comment by alpmestan** [comment]
Hence, my guess is that you forgot to add *servant-server* to your dependency list...?

**Comment by Profpatsch** [comment]
You are right, I confused the two. Thanks!

**Comment by alpmestan** [comment]
No worries =)
