### ISSUE TITLE
Extract most of Servant.JS.Internal to make a reusable module for generating client in other languages.

### ISSUE THREAD

**Issue by dredozubov** [haskell-servant/servant#229]
I have an urge to make servant-ruby to make my life a little bit easier. To reduce duplication and to make writing of similar libraries as easy as possible, we can extract common types and helpers from Servant.JS.Internal. I guess we can parameterize `HasJS` as well to make it reusable(i haven't given it much thought, but i think we can make it work). Something like servant-generator will do. Would really like to hear your thoughts on this matter.

**Comment by dredozubov** [comment]
@jkarni pointed to me that there are https://hackage.haskell.org/package/lackey and https://github.com/parsonsmatt/servant-ruby and we still make it nicer by consolidating these libraries and extracting common parts. I guess we should start with a list of existing libraries?

**Comment by alpmestan** [comment]
Hello,

That's a great idea! I think the code in `servant-js` can be a good start (or the code in `lackey` maybe? I just know my way around *servant-js* for now but I suspect both packages are quite similar), as there's a clear distinction between the two phases: "compile all the information you need to produce client functions" and "output some code in JS based on the data you compiled".

[`Servant.JS.Internal`](https://github.com/haskell-servant/servant/blob/master/servant-js/src/Servant/JS/Internal.hs) has the code for the first phase mentionned above, whereas all the other files sitting next to it provide "code generators" for various JS libraries, all corresponding to the second phase.

I think we basically can extract this module into a `servant-foreign` package that would provide "phase 1" and have *servant-js* and friends directly start with "phase 2".

AFAIK, the only client packages on hackage aside from *servant-client* (which is quite different as it directly targets haskell) are [servant-js](http://hackage.haskell.org/package/servant-js) and [lackey](http://hackage.haskell.org/package/lackey). The folks at Anchor Hosting did start working on a [servant-purescript](https://github.com/anchor/servant-purescript) package as well, but I don't know how far along this work got.

Factoring out "phase 1" into a package that everyone can use will certainly halve the amount of work needed to provide client function generation. @dredozubov Do you feel like giving this a try?

**Comment by dredozubov** [comment]
@alpmestan Sure, i'd like to do that in my spare time. I looked at `servant-js` yesterday and i believe most of it can be extracted(with exception of `toValidFunctionName` and maybe something else language-specific), so i agree with this course of action.

I guess we'll need some `HasForeign language` typeclass to provide some ad-hoc implementations for language identifiers and such.

**Comment by alpmestan** [comment]
I don't think so...? What if `servant-foreign` (or whatever we end up calling it) just provides the ADTs that carry data about APIs, along with a class and instances to convert API types to values of those ADTs ?

Then every package can just use that, offer configuration options specific to the target language and what not. Thoughts?

**Comment by jkarni** [comment]
Done in #232
