### ISSUE TITLE
Example for FormUrlEncoded endpoint

### ISSUE THREAD

**Issue by rubenmoor** [haskell-servant/servant#236]
Is there an example on how to implement a `FormUrlEncoded` endpoint in Servant?

I'm trying to build plain, old HTML forms (using digestive-functors and blaze) and want Servant to handle `GET` and `POST`. For digestive functors I need to build an [Env m](http://hackage.haskell.org/package/digestive-functors-0.8.0.0/docs/Text-Digestive-Types.html#t:Env) and I'm looking for a good starting point.

Atm I don't even understand what the consequences of the `FormUrlEncoded`-contenttype are, as in here:

    type Api = "contract" :> "create" :> ReqBody '[FormUrlEncoded] ContractData :> Post '[HTML] Html

**Comment by fizruk** [comment]
Have you looked at [`ToFormUrlEncoded`/`FromFormUrlEncoded`](https://hackage.haskell.org/package/servant-0.4.4.3/docs/Servant-API-ContentTypes.html#t:FromFormUrlEncoded) classes in `Servant.API.ContentTypes`?

If you're making a server, you just need to implement `instance FromFormUrlEncoded ContractData` to be able to handle incoming forms.

**Comment by fizruk** [comment]
Also documentation on [`FormUrlEncoded`](https://hackage.haskell.org/package/servant-0.4.4.3/docs/Servant-API-ContentTypes.html#t:FormUrlEncoded) tell you that it uses `application/x-www-form-urlencoded` content type.

**Comment by alpmestan** [comment]
Here's a minimal example of using `FormUrlEncoded`.

``` haskell
import Data.Aeson

type API = "login" :> ReqBody '[FormUrlEncoded] User :> Post '[JSON] Login

data Login = LoggedIn | NotLoggedIn
  deriving (Eq, Show)

instance ToJSON Login where
  toJSON = toJSON . show

data User = User
  { email :: Text
  , password :: Text
  } deriving (Eq, Show)

instance FromFormUrlEncoded User where
  fromFormUrlEncoded inputs =
    User <$> lkp "email" <*> lkp "password"

    where lkp input_label = case lookup input_label inputs of
                 Nothing -> Left $ "label " <> input_label <> " not found"
                 Just v    -> Right v

server :: Server API
server usr =
  if email usr == "admin@admin.com" && password usr == "1234"
  then return LoggedIn
  else return NotLoggedIn
```

Now, as you can see, in the `FromFormUrlEncoded` instance I don't do any fancy validation here. `inputs` is a list of all inputs pairs (input_name, input_value), of type `[(Text, Text)]`, which I'm pretty sure most validation libraries will happily let you work with. I however don't use any of them but would be glad to help you figure out how to wire those to this `FromFormUrlEncoded` class :)

**Comment by rubenmoor** [comment]
Great, thanks! I'll be able to take it from here.

**Comment by alpmestan** [comment]
Feel free to use this issue to ask questions, if you get stuck further down the road.

**Comment by jkarni** [comment]
I think it'd be very useful to have an example of using `digestive-functors` with servant though. @rubenmoor if you end up doing that, please consider adding an example to `servant-examples`!

**Comment by rubenmoor** [comment]
@jkarni will sure do!

**Comment by alpmestan** [comment]
Can we consider this issue solved/closed?

**Comment by rubenmoor** [comment]
Closed, in my opinion. I'll get back later with my solution and open questions regarding the combination of Servant with digestive-functors.

**Comment by alpmestan** [comment]
Yeah, definitely. Just open an issue about this when you manage to make both play well together :)
