### ISSUE TITLE
Combinator for capturing all remaining segments

### ISSUE THREAD

**Issue by jml** [haskell-servant/servant#257]
It'd be nice to have a combinator for capturing all remaining segments in a URL, say for serving some sort of filesystem-like interface. 

It's easy enough to write such a combinator. Here's one I wrote with the help of @alpmestan: 

```haskell
data CaptureAll (sym :: Symbol) deriving (Typeable)

instance (KnownSymbol capture, HasServer sublayout)
         => HasServer (CaptureAll capture :> sublayout) where

  type ServerT (CaptureAll capture :> sublayout) m = [Text] -> ServerT sublayout m

  route Proxy subserver request respond =
    let request' = request { pathInfo = [] }
        segments = processedPathInfo request
    in
    route (Proxy :: Proxy sublayout) (subserver segments) request' respond
```

However, AFAICT, it's not possible to write a `HasLink` instance, which means one can't make safe links for the API.

**Comment by ggreif** [comment]
You can probably use `DataKinds` and (type-level list of) `Symbol`s to get type-safety back a bit.

**Comment by fizruk** [comment]
I think it would make sense to make `CaptureAll` a bit more general (as `Capture` is):

```haskell
data CaptureAll (sym : Symbol) a deriving (Typeable)
```

The `HasLink` instance seems to be rather straightforward, except if I miss something:

```haskell
instance (ToHttpApiData v, HasLink sub)
    => HasLink (CaptureAll sym v :> sub) where
    type MkLink (CaptureAll sym v :> sub) = [v] -> MkLink sub
    toLink _ l vs =
        toLink (Proxy :: Proxy sub) $
            foldr (addSegment . escape . unpack . toUrlPiece) l vs
```

**Comment by jml** [comment]
Yes. It's merely that `HasLink` is only possible if you have access to private functions like `addSegment`.

What would be the advantage of the generality? How would you define a specialization?

**Comment by alpmestan** [comment]
``` haskell
type CaptureAllText = CaptureAll "blah" Text
```

One question though: what is the `Symbol` good for here?

**Comment by jml** [comment]
Probably nothing. I cargo-culted it from `Capture`.

Would `CaptureAllText` lead to a handler function that takes `[Text]`? I guess I can think of use cases for wanting something other than `Text` there. 

If we were going for full usefulness, there'd be a way to specify how to turn the list of captured URL pieces into a single value.

**Comment by fizruk** [comment]
`Symbol` should be used for documentation. Just like `Capture` uses it for that only purpose.
E.g. it could be displayed like this:

```
/static/*path
```

`CaptureAll "blah" a` will lead to a handler that takes `[a]`, so you can use any type with `FromHttpApiData` instance.


> a way to specify how to turn the list of captured URL pieces into a single value

I don't see why you might need this. Can you give an example where it might be useful to get something different from `[a]` for a list of URL pieces?

**Comment by fizruk** [comment]
@jml BTW, it is possible to define `HasLink` for `CaptureAll` without using private functions.
You'll need a fair amount of type hackery though:

```haskell
data Captured (sym :: Symbol) (t :: Symbol)

instance (KnownSymbol t, HasLink sub) => HasLink (Captured sym t :> sub) where
  type MkLink (Captured sym t :> sub) = MkLink sub
  toLink _ l = toLink (Proxy :: Proxy (Capture sym String :> sub)) l (symbolVal (Proxy :: Proxy t))

data SomeHasLink sub = forall l. (HasLink l, MkLink sub ~ MkLink l) => SomeHasLink (Proxy l)

toLinkAll :: forall sym v sub. (ToHttpApiData v, HasLink sub) => [v] -> Proxy (CaptureAll sym v :> sub) -> SomeHasLink sub
toLinkAll []     _ = SomeHasLink (Proxy :: Proxy sub)
toLinkAll (x:xs) p =
  case toLinkAll xs p of
    SomeHasLink pl -> case someSymbolVal (unpack (toUrlPiece x)) of
      SomeSymbol ps -> SomeHasLink (f pl ps)
  where
    f :: Proxy l -> Proxy s -> Proxy (Captured sym s :> l)
    f _ _ = Proxy

instance (ToHttpApiData v, HasLink sub)
    => HasLink (CaptureAll sym v :> sub) where
    type MkLink (CaptureAll sym v :> sub) = [v] -> MkLink sub
    toLink p l vs = case toLinkAll vs p of
      SomeHasLink p -> toLink p l
```

**Comment by jml** [comment]
Basically, when you want to do some extra translation / validation that can only be done on the aggregation of captured pieces.

Some combinations of valid pieces might be invalid. Or perhaps the order of the captured pieces is irrelevant, so they are sorted before being passed to the handler.

I admit these aren't strong use cases, and could be done by the handler. But then why can't the handler convert `[Text]` to `[Int]` or whatever, for the imagined use case of supporting general `FromHttpApiData` rather than only `[Text]`? What's the reason for drawing the line of generality at one place and not the other? 

Genuinely curious. Any level of support that has been described on this ticket would be fine by me.

**Comment by fizruk** [comment]
`path-pieces` has `PathMultiPiece` class which allows you to define this sort of validation, but I don't really know anyone using it for something except for `[a]`. This is why in `http-api-data` we have decided to just provide helpers for `[a]`.

I guess the reason this validation is not used in `PathMultiPiece` is that for filesystem-like paths one usually needs to perform some `IO` actions to know whether any given path is valid or not.

@alpmestan I can send a PR for this if you like.

Naming question: would `Captures` be better than `CaptureAll` (following `QueryParam`/`QueryParams`)?

**Comment by alpmestan** [comment]
Yeah, `Captures` sounds nicer. PR sounds good. For `data Captures sym a` then? I.e with the ability to convert to some `a` all the captured bits of text?

**Comment by fizruk** [comment]
`data Captures sym a` with the ability to convert all URL pieces to `[a]`.

**Comment by jml** [comment]
@fizruk Are you still intending to send a PR for this? If not, I might take a look at having a go myself. No promises though.

**Comment by fizruk** [comment]
@jml sorry, I got busy with other stuff, I won't touch this until weekend.
You should know, however, that I have tried to work on this and encountered a serious problem (admittedly, I should've reported right back).

Currently `servant-server`'s routing mechanism does not allow `Captures` to be implemented easily.
One straightforward solution might be to add a new constructor to [`Route'`](https://github.com/haskell-servant/servant/blob/master/servant-server/src/Servant/Server/Internal/Router.hs#L15-L26) (we need a constructor similar to `DynamicRouter` which should get all the remaining URL pieces).

Note, however, that this is some core stuff I know little about, so we probably need to ask @jkarni or @alpmestan whether this is an acceptable solution.

**Comment by jml** [comment]
@fizruk I'll wait until after this weekend then. :)

Can you explain why `Captures` can't be implemented easily? I'm currently using what I wrote in the OP (called `CaptureAll` there), and it seems to be working fine for us.

**Comment by fizruk** [comment]
@jml that code is invalid in `HEAD` because there are significant changes to the routing mechanism.
There is no longer a way to modify request arbitrary like you do by setting `pathInfo = []`.

**Comment by fizruk** [comment]
@jkarni with [current `Router'`](https://github.com/haskell-servant/servant/blob/master/servant-server/src/Servant/Server/Internal/Router.hs#L14-L26) this still seems impossible to implement. How would you like it to be changed? Options I see are:
- `DynamicAllRouter` similar to `DynamicRouter`, but consuming all the URL pieces left;
- `DynamicWithRequest` which would allow modifying `Request` arbitrarily (not just read from it).

**Comment by jkarni** [comment]
If we change `WithRequest` to:

```
    WithRequest   (Request -> (Request, Router))
```
We should be good, no?

**Comment by fizruk** [comment]
@jkarni yes, that would work. I can work on this then.

**Comment by jml** [comment]
Thanks for looking into this @fizruk. I was wondering, will the proposed fix make it possible to safely link to entities that have been defined using `CaptureAll`?

**Comment by fizruk** [comment]
@jml yes, see here https://github.com/haskell-servant/servant/pull/347/files#diff-8e010c13600c67feeac9666e44fb1fdfR294.
