### ISSUE TITLE
Support cli generation

### ISSUE THREAD

**Issue by alexanderkjeldaas** [haskell-servant/servant#264]
I'd like to be able to combine a servant API with some of the command line argument parser libraries, so both a client and a cli can be generated at the same time.

**Comment by alpmestan** [comment]
A CLI to query the API described by some servant API type? That would be very nice to have! Somewhat relatedly, there's [configifier](http://hackage.haskell.org/package/configifier) but it doesn't offer a bridge between servant and command line args, it just borrows the approach.

But that's definitely an interesting idea! Would you like to work on this? I can offer some guidance *if needed*.

**Comment by fisx** [comment]
Thanks for referencing configifier!  (-:  I would like to add that it's still alpha, but if anybody is interested in using it please submit issues.  I'm eager to get it in shape.  (-:

**Comment by zudov** [comment]
I've started working on this recently but didn't get very far yet.

**Comment by zudov** [comment]
Would try to put what I have in the public and hopefully we would make some progress.

**Comment by alpmestan** [comment]
Sure, that's the best way to get some more eyes/hands on this =)

**Comment by jkarni** [comment]
I like the idea!

**Comment by jkarni** [comment]
What more concretely would the CLI do?

**Comment by proger** [comment]
I imagine it as a `servant-client` that automatically gives you a CLI interface as well.

The first thing you do trying to test the API is use `curl` — but it would be a lot neater if there was a CLI tool that does all the boring stuff you type into `curl` for you.

A bonus hack would be smth like "copy as curl" in Chrome that generates a curl command you can share with your friends so they can all paste in their shells and enjoy servant together!

```
% stack build
built `myservice`
built `myclient`
% stack exec myclient --
myclient CLI servant :dance:

global options:
   --curl: generate a curl command line instead performing a request
   --safe: automatically redirects to https://www.youtube.com/watch?v=rsv96JK4Vx4 on badarg
   --unsafe: automatically redirects to https://www.youtube.com/watch?v=sTSA_sWGM44 on badarg

discovered apis:  (defaults to POST when <stdin> is non-empty, otherwise GET)
   images
     <id> [filters...]
   blogposts
     <id>
```

**Comment by fishtreesugar** [comment]
[mstksg/servant-cli](https://github.com/mstksg/servant-cli)

**Comment by alpmestan** [comment]
Right, I think we can safely consider this CLI interpretation taken care of at this point. Any objection to closing the issue?

**Comment by ocharles** [comment]
I am happily using `servant-cli` and think this can probably be closed.
