### ISSUE TITLE
Adopt servant-purescript

### ISSUE THREAD

**Issue by christian-marie** [haskell-servant/servant#268]
@fisx has just made servant-purescript compile with the latest changes: https://github.com/anchor/servant-purescript/pull/3

Anchor is no longer using purescript, and most of our original development team there has moved on.

This leads to my question: Do we wish to adopt this repository? I believe it's quite similar to (and based off) servant-js.

I don't think it utilizes servant-foreign yet, though. I haven't checked.

poke: @jkarni, @alpmestan, @soenkehahn, @kosmikus

**Comment by fisx** [comment]
actually it does use servant-foreign now.  it also generates code that compiles, but there is still open issues (see paf31's comment in the PR, but also remove or update the demos, and a bit more testing, camel-casing instead of flat-casing in some places, small things like that).  i could get these out of the way if it helps.

thanks @christian-marie for negotiating this!

**Comment by alpmestan** [comment]
Sounds good to me, once it's in a good enough shape (what @fisx listed above)! This is great news -- I'm glad *servant-purescript* is coming back to life.

**Comment by christian-marie** [comment]
Excellent. @fisx, could you please copy this into the servant codebase and do whatever you thought was important? We can then review and decide if it's ready.

**Comment by fisx** [comment]
Will do.  I'll ping this ticket and the PR over at anchor when I'm ready.  Thanks!

**Comment by fisx** [comment]
What should I put in here?

```cabal
author:              Anchor Engineering <engineering@anchor.com.au>
maintainer:          Anchor Engineering <engineering@anchor.com.au>
copyright:           2015 Anchor
```

**Comment by arianvp** [comment]
You'll have to keep the copyright and author information due to the MIT license afaik.  I think you can add your name to it to though. But I am not a lawyer so I hope someone from Anchor can back me on this.

**Comment by fisx** [comment]
I don't think MIT license is about the maintainership; we can fill in whoever feels responsible for keeping this in shape.  @alpmestan, would that be you?  Saw you in the maintainer attribute of servant-js.  (-:

**Comment by alpmestan** [comment]
Well, `Maintainer` would be whoever ends up taking care of this package. And `Author` would be *Anchor* + that person.

**Comment by christian-marie** [comment]
I think that the LICENSE file has to retain Geoffrey's name.

Maintianer could probably be set to the servant team, with the servant mailing list address.

You can certainly *add* names to the authorship. You can't exactly un-author something, though.

**Comment by fizruk** [comment]
As has been [decided on the `haskell-servant` mailing list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/haskell-servant/eHWiGBSn5nY/aj-DkyisDwAJ), `servant-purescript` should reside in a separate repo.

@fisx would you be able to move your work from #269 into `haskell-servant/servant-purescript` or your own repo? Let me know if you need any help with moving things around.

**Comment by jkarni** [comment]
https://github.com/haskell-servant/servant-purescript created.

**Comment by ctd** [comment]
Hi, is there any progress on this? I note that https://github.com/haskell-servant/servant-purescript is empty right now.

@anchor would like to remove our repo of servant-purescript since we are no longer developing or maintaining this software. We're happy to transfer ownership of our repo if that interests you.

**Comment by fisx** [comment]
sorry, we're currently not using it either (moved to digestive-functors, at least temporarily), so it's unlikely that i will work this into better shape any time soon.  any other volunteers?

(out of curiosity: is anchor moving away from servant + purescript?  or is it just that there are better ways to write client code in purescript than this package?)

**Comment by ctd** [comment]
@fisx anchor's movement is more related to broader internal changes that mean we aren't actively working with, or on, these projects at present; it has no bearing on the software itself.

**Comment by fisx** [comment]
@ctd thanks.  that's good to hear.

Perhaps we can move it to the repo that @jkarni created and mark it as 'looking for maintainer', then?  I'd be happy to hang around if anybody needs hints.  Would that be ok with the servant team?

**Comment by alpmestan** [comment]
Sounds good to me. We could even publish a little something (blog? mailing list? haskell-cafe@ ? /r/haskell?) to hunt for someone willing to give this package the love it deserves...?

**Comment by arianvp** [comment]
What is our current status on this? Do we want to proceed to 'adopt'? https://github.com/haskell-servant/servant-purescript is still empty at the moment @haskell-servant/maintainers

**Comment by soenkehahn** [comment]
I'd be in favor of removing the repo, since an empty repo is not very useful. Once someone puts some work into this we can just re-create it.

**Comment by soenkehahn** [comment]
I'd also be in favor of closing this issue, since interest in this seems to have vanished.

**Comment by alpmestan** [comment]
Well, either someone volunteers to make this happen, or we remove the repo until someone does, I guess?

**Comment by christian-marie** [comment]
Yep, this should be closed once the https://github.com/haskell-servant/servant repo is removed, or perhaps a README.md is placed there.

@ctd please feel free to transfer the https://github.com/anchor/servant-purescript repo (and any others you wished to retire) to https://github.com/WhereSoftwareGoesToDie, if you were going to destroy it otherwise. I have invited you as an owner.

It would be a shame for this not to be archived "live" somewhere, even if it is defunct.

**Comment by soenkehahn** [comment]
Since nothing happened since last week I'm going to delete `haskell-servant/servant-purescript` and close this issue.
