### ISSUE TITLE
Require a `Seg` type on bare symbols to represent constant URI segments

### ISSUE THREAD

**Issue by tel** [haskell-servant/servant#280]
Today the semantics of the API specs has that a bare symbol represents a constant segment in the API. I'd like to suggest that this causes issues for analysis of Servant APIs since there is no way for a type family to pattern match against a bare symbol.

On the other hand, if instead there were a type

    data Seg (segment :: Symbol)

and we wrote API descriptions like

    Seg "users" :> Capture "id" Int :> Get '[JSON] User

then it would become easier to totally analyze API descriptions at the type level. This would allow the construction of type families which analyze the whole API and augment it with metadata. For instance [a method for automatically constructing CORS response data from the existing API tree](https://github.com/haskell-servant/servant/issues/278#issuecomment-160851007).

I'm fairly sure that (a) this is a massive breaking change if introduced and (b) isn't really required to be introduced in the core library since everything is just open for extension, so there's not a lot of motivation to achieve such a change, but I'd like to hear about tradeoffs in this design or other ways to accomplish static whole-API analysis.

Thanks!

**Comment by tel** [comment]
Nevermind. I was just informed that one can write type families like

```haskell
type family X (a :: k)
type instance X (s :: Symbol) = ()
```

and therefore by matching on kind we can recover what's needed.

**Comment by alpmestan** [comment]
Yes, you found out why we went with bare `Symbol`s. =)
