### ISSUE TITLE
Is EitherT the right Monad for the server functions?

### ISSUE THREAD

**Issue by ondrap** [haskell-servant/servant#286]
According to https://www.fpcomplete.com/user/commercial/content/exceptions-best-practices 'It is almost always wrong to wrap an `ExceptT`, `EitherT`, or `ErrorT` around an `IO`-based transformer stack.' 

I have just found in my code a nice example:
````
getUser dbpool userid = runSqlPool dbpool $ maybe (lift $ left err404) return $ get userid
````

This is wrong, as the rollback in `runSqlPool` doesn't get called. I decided to convert all my server code completely to `IO` and use `enter` to convert back to `EitherT` - and throw exceptions as: `throwServant err404`. Is there any fundamental reason to use `EitherT` as opposed to `IO` with exceptions? It seems to me that IO would be a more sensible default, although I understand this would be quite a big API change.

**Comment by jkarni** [comment]
A lot of the options considered in the page you've linked aren't open to us, as we can't have typeclass constraints in associated type synonyms. So e.g.:

> it's also almost always a bad idea to have such a concrete transformer stack used in a public-facing API. It's usually better to express a function in terms of typeclass requirements, using mtl typeclasses as necessary.

The suggested option here just isn't possible. There *may* be ways around the typeclasses-in-ATS issue with existential newtype-wrapping, but that'd probably end up looking much less familiar to most programmers, and I don't yet know what it would look like.

Could you explain what you mean with the code sample? What is being rolled back (presumably `get`s don't need rollbacks)? I haven't ever used `persistent`, and am not at all familiar with it. That being said, it does seem to be the source of frequent woe when used with `servant`, and I'd love to understand those woes better so as to maybe try fixing them.

As for using `IO` exceptions - I myself certainly prefer the explicitness of `ExceptT`. I personally don't take it to mean (when used over `IO`) that the left case is the only exception that can be thrown. At the very least it's a good source of documentation (i.e., it's really obvious from the type you're expected to provide that `ServantErr/ServantError` is the way of returning an error response code). I also think I'd like the direction we move in to be *more* explicit about the possible errors - e.g., precisely which error http status codes may be thrown, if we could get something like Edsko's [Lightweight Checked Exceptions](http://www.well-typed.com/blog/2015/07/checked-exceptions/) involved. But I'd love to hear from other people too.

**Comment by 3noch** [comment]
I had the same reaction as @ondrap when I first read servant's API. Having both in- and out-of-band exceptions in the same stack seems like a tricky API to use, especially in light of the "best-practices" approach which shuns this. However, I can see this being OK in servant's case since it wants to provide a specific mechanism for specific HTTP return codes. In this case it does feel a lot like lightweight checked exceptions. I think as long as that distinction is made **very clear** in the documentation, things will go pretty well. E.g. "Any exception *not* delivered through ExceptT, will be translated as a fatal error, returning a 500 status code."

**Comment by ondrap** [comment]
The `runSqlConn` command is similar to STM's `atomically`, but it allows you to run IO code from inside via `liftIO`. It correctly handles exceptions thrown from the IO code. But when you run `lift $ left` from inside, you completely skip all finalizers (rollback or commit). Suppose, you could jump this way out of STM - things could break very easily. In my example I had only `get`(SELECT), but even in this case you could get long-running transactions, unnecessary locks on the tables etc. as the connection is not closed but reused later.

The other exceptions definitely can be thrown and it doesn't invalidate the code (only you get a 500 status code). So this is really more a documentation thing - it was nice to know just from the types how to return different error status. And the next thing I had to do was to change the base monad in order to avoid incorrect code.... The checked exceptions seem nice, I wonder how would it compose with persistent.

**Comment by dzhus** [comment]
While we're at it, I think ExceptT should be used instead of EitherT. Other packages are doing it and EitherT was there just because transformers didn't use to have ExceptT.

**Comment by jkarni** [comment]
@dzhus on master we've already updated it to `ExceptT`.

**Comment by jkarni** [comment]
@ondrap I'm still a little unclear on what's going on. I think I'd need to actually read through the persistent codebase (unless anyone knows of a place that describes this behaviour in more detail). I don't really see what problems would arise from using `ExceptT` with `STM` (except figuring out with which level of granularity with which to call `atomically`). If you have a self-contained example that demonstrates unexpected behaviour, that'd be very useful!

**Comment by ondrap** [comment]
This is the code for runSqlConn:

    runSqlConn :: MonadBaseControl IO m => SqlPersistT m a -> SqlBackend -> m a
    runSqlConn r conn = do
        let getter = getStmtConn conn
        liftBase $ connBegin conn getter
        x <- onException
                (runReaderT r conn)
                (liftBase $ connRollback conn getter)
        liftBase $ connCommit conn getter
        return x

This function guarantees that either rollback or commit get called. If you `lift $ left err404` out of the `r`, neither gets called. If you are using SQL pools, the connection probably gets returned to the pool and a different HTTP request gets this half-in-progress transaction. This is bad even when only `get` was done (as the next request can take quite a long time, so you end up with long-running transaction), but is flatly wrong if you do some work inside the transaction that you expect to be rolled back.

**Comment by alpmestan** [comment]
To give a short comment on this: I feel bad about the current `EitherT` (0.4) / `ExceptT` (master) handlers, but we haven't found a way to just allow "any monad that's powerful enough to do IO and allow some form of failure, letting us generate HTTP responses". This is an "open problem" so to speak, so if anyone's got some free time... =)

**Comment by 3noch** [comment]
Well you *could* just use `IO` and have a exception hierarchy for your needs.

**Comment by ondrap** [comment]
I am currently using this in `IO` (I am using `ReaderT` on top):

    import           Control.Exception.Lifted (throwIO)

    data ServantException = ServantException ServantErr deriving (Show)
    instance Exception ServantException

    throwServant :: MonadBase IO m => ServantErr -> m a
    throwServant = throwIO . ServantException

    rioToEither' :: ConnectionPool -> ReaderT ConnectionPool IO a -> EitherT ServantErr IO a
    rioToEither' cpool code =
      EitherT $ (Right <$> runReaderT code cpool)
         `catch` (\(ServantException err) -> return (Left err))

    rioToEither :: ConnectionPool -> ReaderT ConnectionPool IO :~> EitherT ServantErr IO
    rioToEither cpool = Nat (rioToEither' cpool)

    server = enter (rioToEither dbpool) (getDatabases :<|> createDb)

**Comment by jkarni** [comment]
@ondrap would providing that `Nat` in servant be sufficient? So far this still looks like a problem that's specific to the `servant`-`persistent` interaction. (And I'd even go as far as saying that this is maybe a bug in `runSqlConn` - there really isn't any guarantee that `connCommit` will run for any monad that has the expected signature.)

**Comment by jkarni** [comment]
@3noch any other advantages to switching to `IO` with our own exception hierarchy that you can think of (besides this particular `persistent` example)?

**Comment by 3noch** [comment]
@jkarni No.

**Comment by ondrap** [comment]
I'd say that this behaviour of monad transformers is *the* reason why they said it's best practice not to use `EitherT` on top of `IO`. On the other hand, one could argue that the inner function of `runSqlConn` should have been just `MonadIO` and not `MonadTrans`.

What about adding the `Nat` to `IO with exception` and 'ReaderT IO with exception', maybe as some kind of experimental module? What do others think?

**Comment by jkarni** [comment]
If we *were* to have exceptions for HTTP errors, wouldn't we thereby make it the case that nothing could be committed (via `runSqlPool`) from a handler that returns an HTTP error (without a lot of fancy footwork)? That doesn't seem right either. (This is also relevant for the `Nat`.)

Should we open an issue in `persistent`? It seems like it should be possible to move `connCommit` to a (lifted) `finally` when binding to `x` (possibly with some extra logic in case a commit after a rollback is undesirable).

**Comment by jkarni** [comment]
[Here's](https://gist.github.com/jkarni/ab02b5136aa762f904e1) what I was thinking. Kind of ugly, but seems to work

**Comment by ondrap** [comment]
There is a yesod-persistent package to help with integration with yesod; it might not be a bad idea to provide own `runSql` command that works well with `persistent` and `servant`.

As for how it should work - I think it shouldn't be tied only to `EitherT IO` as most people will switch it to some `ReaderT` anyway. But the question is if "commit-on-exception" is the desired behaviour. It seems to me that `get404` from the `yesod-persistent` does "rollback-on-exception" and at least in my programs that tends to be overwhelmingly the desired behaviour. And I didn't quite find a way how to do it, `finally` doesn't seem to be enough. This is the best I could come up with:

    (onException
            (do
                   res <- runReaderT r conn
                   liftBase $ connCommit conn getter
                   return res
             )
            (liftBase $ connRollback conn getter)) `finally` connRollback conn getter

untested - would probably work, but it's not nice.

**Comment by jkarni** [comment]
I opened an issue [here](https://github.com/yesodweb/persistent/issues/516).

**Comment by jkarni** [comment]
@ondrap does `runSqlConn` work with `ExceptT` now? I'm inclined to close this until we have a better picture of where we want to go.

**Comment by ondrap** [comment]
Seems to work OK, I think the solution is fine.
