### ISSUE TITLE
Create integration and regression tests for servant-js

### ISSUE THREAD

**Issue by arianvp** [haskell-servant/servant#288]
This is related to https://github.com/haskell-servant/servant/pull/287 and https://github.com/haskell-servant/servant/issues/285 

It would be fun to explore something like https://phantomjs.org/ to make sure that our generated code actually works.    At minimum we should pipe the generated JS through a linter to check if there are no syntax errors.

**Comment by alpmestan** [comment]
We only have one little test that parses the generated JS, [here](https://github.com/haskell-servant/servant/blob/master/servant-js/test/Servant/JSSpec.hs#L187). Augmenting it is a great idea though.

**Comment by jkarni** [comment]
`servant-js` no longer lives in this repo, so closing.
