### ISSUE TITLE
Bidirectionalization

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#29]
A lot of the lower-level functionality that is used to construct `HasServer` and `HasClient` instances (at least) are strongly related (often functions come in inverses). For example, getting a header and adding a header, or reading a body and returning a body. Writing functions for both is tedious and error-prone - not just for library maintainers, but also for users who might want to write a new combinator. This seems like a good candidate for availing ourselves of the bidirectionalization literature.

 Ideally, we should be able to write an instance of a single class, and `HasServer` and `HasClient` come for free from that instance. 

Please add any thoughts or ideas as a comment.

**Comment by alpmestan** [comment]
Do you have any paper, library or other types of resources in mind about this? I agree that some of that work could be factored out and also let us share names if the same type encodes both directions.

**Comment by jkarni** [comment]
http://www.janis-voigtlaender.eu/papers/BidirectionalizationForFree.pdf
http://www.informatik.uni-marburg.de/~rendel/unparse/
@christian-marie might have thoughts - he wrote https://github.com/anchor/roundtrip-aeson

**Comment by alpmestan** [comment]
This is all very interesting, thanks for the links. I think this is a great axis of improvement to consider after the upcoming the release.

**Comment by kosmikus** [comment]
Also lots of other packages, in particular https://hackage.haskell.org/package/JsonGrammar

**Comment by kosmikus** [comment]
This is accompanying code I've produced for an internal WT presentation on bidirectional parsing and pretty-printing, somewhat in the style of `boomerang` and `JsonGrammar`. Not overly documented, but perhaps helpful anyway: https://gist.github.com/kosmikus/fc589c83a5fe4517803c

**Comment by christian-marie** [comment]
I think that HasServer and HasClient are far enough removed from the "purity" of printer/parsers to wonder if such composition of smaller bidirectional parts are going to improve clarity, safety, maintainability and ease of use.

It certainly is an interesting prospect. I wonder if we would provide useful enough building blocks that it would be intuitive for a user to build upon this when defining their own HasServer/Client types.

I certainly see the idea here, but I wonder if there's actually any useful combinators to define that aren't just things we should export as part of the API?

If we're talking about utilizing such a technique for internal library use only, I'm dubious as to the improvement it brings. We still need to ensure that the "axiomatic" core bidirectional combinators are correct.

I wonder how small of a proven core we could build more useful combinators from. I think that's where our research should be initially directed. 

I'd suggest params to be as a place to start thinking about this. Perhaps matrix params, flags, query params and friends could all could all share one underlying parameter combinator with some "pure" isomorphisms bolted on top.

These isomorphisms would then be simpler to reason about and prove correct,  at the expense of possibly making extensibility more difficult for new users.

**Comment by christian-marie** [comment]
@thsutton also wrote roundtrip-aeson and may have further thoughts.

**Comment by jkarni** [comment]
For all the reasons @christian-marie mentioned, and because this sounds like a lot of work, I'm closing this. I don't object to someone else trying it.
