### ISSUE TITLE
IsSubList in Servant.Utils.Links may lead to loop in GHC type checker.

### ISSUE THREAD

**Issue by sopvop** [haskell-servant/servant#293]
As discussed in this ticked https://ghc.haskell.org/trac/ghc/ticket/11220#comment:6
the definition of IsSubList may lead to a type checker loop in GHC, and apparently is expected behaviour.

This happens if you specify content-type on method on link type, if said content-type is not present on method in Api type.

~~~~.haskell
type Api = "foo" :> Get '[JSON] ()

link = safeLink (Proxy :: Proxy Api) (Proxy :: Proxy ("foo" :> Get '[Bar] () ))
~~~~

**Comment by jkarni** [comment]
Fixed in #295 - thanks for the report and test case!
