### ISSUE TITLE
VanillaJS js generator doesn't handle "204 No content" answer from server

### ISSUE THREAD

**Issue by utdemir** [haskell-servant/servant#294]
When the server returns with "204 No content" (this happens when API is defined as `Get '[JSON] ()`), and therefore with an empty request body, the generated JS client tries to `JSON.parse('')` and gives syntax error.

Example:

```
{-# LANGUAGE DataKinds     #-}                                                                                                                                  
{-# LANGUAGE TypeOperators #-}                                                                                                                                  

module Main where                                                                                                                                               

--------------------------------------------------------------------------------                                                                                
import           Control.Monad.Trans.Class
import           Data.Proxy
import           Data.Text
import           Network.Wai.Handler.Warp
import           Servant
import           Servant.JS
--------------------------------------------------------------------------------                                                                                

type API = "print" :> Capture "num" Int :> Get '[JSON] ()

api :: Proxy API
api = Proxy

server :: Server API
server = lift . print

main :: IO ()
main = do
  putStrLn . unpack $ jsForAPI api vanillaJS
  run 2222 $ serve api server
```

On this case, server correctly returns "204 Not modified" without a response body, but the client fails:

![2015-12-16-115210_875x368_scrot](https://cloud.githubusercontent.com/assets/928084/11837739/77d59db2-a3eb-11e5-8e09-b31ee81a5a95.png)

**Comment by arianvp** [comment]
Good catch! I'll fix it.

**Comment by freezeboy** [comment]
While you're at it, maybe we could accept http status from 200 and 299 like in other places (I think servant-client) ?

Thank you

**Comment by arianvp** [comment]
If we read the HTTP RFC carefully. http://tools.ietf.org/search/rfc2616#section-7.2.1  then a HTTP Client should _ignore_  the content body (and `Content-Type`)  if a 204 is returned which we are clearly not doing. So I guess we should indeed fix the client generation code.

On the other hand. I kind of dislike `()` being a special case as it also has a Valid `ToJSON` instance.
Namely `encode () == "[]"`

  Why does servant return `204` in the first place?   I think it would be prettier to have a separate datatype in servant named `data NoContent = NoContent`  for returning `204`'s as I think `()` is a bit of a weird orphan instance.

**Comment by jkarni** [comment]
@arianvp I agree having a `NoContent` type for 204 is probably better than having `()`.
