### ISSUE TITLE
generate-nix-files.sh fails on NixOS because of /bin/bash

### ISSUE THREAD

**Issue by xor-xor** [haskell-servant/servant#300]
`generate-nix-files.sh` script uses `#!/bin/bash -`, which doesn't seem to be valid on NixOS (see RcppCore/RcppArmadillo#15 for relevant discussion). This also applies to other scripts in the same directory, but I'm deliberately mentioning only `generate-nix-files.sh`, as it is meant for Nix/NixOS exclusively.

**Comment by jkarni** [comment]
Can you check whether `#!/usr/bin/env bash` works on NixOS? Happy to switch all of them to use `env` if so.

**Comment by xor-xor** [comment]
Yes, it works. But there's one caveat - for some reason, you're spawning a login shell by providing `-` as an argument to `bash`, but it is not possible to pass any extra args to the commands executed via `env`.

In both cases though (i.e., login vs interactive shell), `generate-nix-files.sh` produces exactly the same `shell.nix` files.
