### ISSUE TITLE
X-Request-ID header usage

### ISSUE THREAD

**Issue by Xe** [haskell-servant/servant#302]
Hello,

I'm looking at using Servant in a project of mine and have been wondering how to have something automatically insert some random string as the client header `X-Request-ID` for easier correlation with log data. How would I do this?

**Comment by jkarni** [comment]
By "client header" do you mean response header? If so, [Middleware](https://hackage.haskell.org/package/wai-3.0.5.0/docs/Network-Wai.html#g:8) is likely the answer:

```
myIDGenerator :: IO Header
myIDGenerator = ...

m :: Middleware
m app req respond = app req $ \response -> do
    id' <- myIDGenerator
    respond $ modifyResponse (mapResponseHeaders (id' :) response)
```
(Haven't actually tried this!)

And then apply the middleware after getting an `Application` with `serve`, but before `run`-ing it.

Let me know if I misunderstood you or if you encounter problems.

**Comment by Xe** [comment]
Ah, perfect. This will do what I need. Thanks!
