### ISSUE TITLE
exceptions not logged with wai request logger middleware

### ISSUE THREAD

**Issue by mwotton** [haskell-servant/servant#303]
https://gist.github.com/mwotton/fa05eb3ea1b9c3a49a8f

using this code, I get no request logged.
if i switch to the wai app in the third file, the request is logged, then the exception is hit.
Any idea what might be going on here? I'm a bit stuck.

**Comment by christian-marie** [comment]
If I were to hazard a guess, I'd say that it's got to do with beginning to respond.

With the second example, you commit to writing a response and I'm not sure when it actually evaluates your errory response body. If it evaluates the error *after* it writes headers and such, we have a difference that could explain the lack of log. Does that make sense?

If that is the case, we could look at servant's behaviour and perhaps make this work.

**Comment by alpmestan** [comment]
What if you replace `throw ...` with `return undefined`?

**Comment by mwotton** [comment]
@alpmestan when i do that i do get the log. I can cut the wai example down to "application _ respond = respond undefined" and still get the log, so I don't think it's to do with sending headers. Maybe there should be a bracket in the wai logger?

**Comment by mwotton** [comment]
i think this is a wai middleware issue. Sorry for the noise.

https://github.com/yesodweb/wai/issues/496
