### ISSUE TITLE
fix compilation warnings

### ISSUE THREAD

**Issue by soenkehahn** [haskell-servant/servant#313]
And enable `-Werror` on travis.

**Comment by jkarni** [comment]
My opinion is that we should wait for the next release of `aeson`, since currently we get spurious `MINIMAL` issues that would involve a decent amount of CPP to fix, and `master` of `aeson` already has a fix.

**Comment by soenkehahn** [comment]
Sounds good to me. (We keep this issue open?)

**Comment by jkarni** [comment]
(Yup.)

**Comment by jkarni** [comment]
Issue: https://github.com/bos/aeson/issues/290#issuecomment-165870352 . It's been merged, but not yet released.

**Comment by soenkehahn** [comment]
Done.
