### ISSUE TITLE
servant-comock

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#319]
We discussed this before, but now it seems like work may get started on it and it's a good idea to discuss progress and design.

We want something like `servant-mock`, but instead of generating an `Arbitrary` *server*, generates a (set of) `Arbitrary` *clients*. That is, it queries all the endpoints with random arguments. A simple use-case is testing that two servers have the same behaviour.

My thoughts for how to implement this: use servant-client to get a (`:<|>`-separated) list of client functions. Write a function that takes an n-arry function where all the arguments are instances of `Arbitrary` and which gets the returns type of the function. Apply this function recursively to the list of client functions, comparing the two results to make sure they match.

*EDIT*: another use-case: much easier load-testing across one's entire API.

**Comment by jkarni** [comment]
@soenkehahn can I assign you?

**Comment by jkarni** [comment]
[quickcheck-properties](https://hackage.haskell.org/package/quickcheck-properties-0.1/docs/Test-QuickCheck-Property-Common.html) has an `Equalable` that does roughly what we want. We only need to add `Equalable` instances for `Equalable a => EitherT ServantErr IO a` and for `Equalable a, Equalable b => Equalable (a :<|> b)`. This may well be under 100 lines of code, all told.

**Comment by soenkehahn** [comment]
Not sure whether I will be able to look into this, so please no assignment yet. But yes, this could be very handy.

**Comment by jkarni** [comment]
I'll do it - looks fairly trivial.

**Comment by jkarni** [comment]
Development happening in the `jkarni/servant-comock` branch.

**Comment by jkarni** [comment]
Seems to be working already! Need some `Arbitrary` instances, and a decent `Eq` for `ServantError`, but it should be ready soon.

**Comment by alpmestan** [comment]
Do we have a better name than `comock`? I'm not sure people will figure out what it is for from the name.

**Comment by jkarni** [comment]
I don't (there's `servant-mock-client`, but I prefer `comock`). Open to suggestions though.
(Note however that testing that two applications are the same is not the only functionality I have planned - it may also come to include load testing and other things.)

**Comment by alpmestan** [comment]
I'm not fond of using `co` when it's only dual "by analogy" and not in a strict mathematical sense. Maybe something like `servant-random-client`/`servant-client-random` or smth else in that spirit? We basically want a name for a package that can generate requests to an API with random values for the "input parameters" of the endpoint.

**Comment by fizruk** [comment]
Since `Arbitrary` is at use, perhaps `servant-arbitrary`/`servant-arbitrary-client`/`servant-client-arbitrary`?
Or `servant-QuickCheck` variants?

**Comment by soenkehahn** [comment]
I like `servant-client-arbitrary`.

**Comment by jkarni** [comment]
Cool, let's go with that. It's a pretty accurate description.

There is a very close relationship to `servant-mock` which would be lost, though. Is renaming `servant-mock` to `servant-server-arbitrary` a good idea? (I myself like `servant-mock`.)

**Comment by alpmestan** [comment]
I like `servant-mock` as well, because "mock" in this context is a very well understood word by the webdev community. I agree that losing the close relationship to mock is unfortunate but maybe the clear name for the client equivalent makes up for it?

**Comment by aaronlevin** [comment]
what about renaming both:
- `servant-server-mock`
- `servant-client-mock`

this preserves the relationship while being clearer about the semantics.

**Comment by codedmart** [comment]
I like @aaronlevin suggestion :+1:.

**Comment by soenkehahn** [comment]
:+1:

**Comment by jkarni** [comment]
Sounds good to me.

**Comment by alpmestan** [comment]
I like it as well!

**Comment by fizruk** [comment]
:+1:

**Comment by dmjio** [comment]
:+1:

**Comment by dredozubov** [comment]
i'm with @aaronlevin

**Comment by jkarni** [comment]
This is now https://github.com/haskell-servant/servant-quickcheck
