### ISSUE TITLE
Servant.Server.Internal.Enter isn't really an "internal" module.

### ISSUE THREAD

**Issue by tphyahoo** [haskell-servant/servant#322]
per

http://stackoverflow.com/questions/9190638/how-why-and-when-to-use-the-internal-modules-pattern

which I think is a fairly mainstream view, internal modules are for implementation details that are not exposed in the public API.

I think this is not the case for the function 

enter

at least, which is recommended for use by 

http://haskell-servant.github.io/tutorial/server.html#using-another-monad-for-your-handlers

and the documentation has the feel of a public facing module.

So, perhaps this should be renamed something other than Internal, or the public bits of it should be moved into another module.

**Comment by alpmestan** [comment]
I think this is a very good suggestion. I'm not fond of the current `Enter` solution but until we find something better, we probably want 1/ to export it from `Servant.Server` just like the rest of the package and 2/ to have it live under `Servant.Server.Enter`.

**Comment by jkarni** [comment]
I agree with `1`, but would prefer to move things towards `Internal` modules (with re-exports) rather than away from them.

**Comment by jkarni** [comment]
Done in https://github.com/haskell-servant/servant/commit/bdf6d9aa4815c1705bf2f27122f394498f6379f8
