### ISSUE TITLE
Endpoint description combinator

### ISSUE THREAD

**Issue by fizruk** [haskell-servant/servant#336]
I would like to discuss a specific description combinator for the endpoint.
#### Problem

Most parts of the API can get custom description via an instance of a type class (e.g. `ToParam` in `servant-docs` or `ToParamSchema` in `servant-swagger`).
The whole API details (description, contacts, version, etc.) can be easily filled in after the fact with `DocIntro` in `servant-docs` or `info` in `servant-swagger`.

The hard yet very important part is documenting the meaning of a particular endpoint.
Currently with both `servant-docs` and `servant-swagger` user has to write down the endpoint type to assign description to it. In practice this type is too long (even without `Proxy :: Proxy` prefix).

A description combinator that can be used in API type would solve this problem.
#### Solution

The combinator can be as simple as this:

``` haskell
data Description (desc :: Symbol)

type ResourceAPI = "resource" :>
    ( Description "Create a resource."
      :> ReqBody '[JSON] Resource :> Post '[] ()

 :<|> Description "Find resources by name."
      :> QueryParam "name" Text :> Get '[JSON] [Resource]
    )
```

For convenience, we can provide an infix alias (although this might be confusing with URL pieces):

``` haskell
type description :-- api = Description description :> api

type ResourceAPI = "resource" :>
    ( "Create a resource."
      :-- ReqBody '[JSON] Resource :> Post '[] ()

 :<|> "Find resources by name."
      :-- QueryParam "name" Text :> Get '[JSON] [Resource]
    )
```

Since multiline string literals in Haskell might seem a bit inconvenient:

``` haskell
type Endpoint = "resource" :> Capture "resource_id" ResourceId :>
     "Delete a resource. \
     \The resource will only be deleted if user has admin access."
 :-- Delete '[] ()
```

We can use multiple `Description`s instead:

``` haskell
type Endpoint = "resource" :> Capture "resource_id" ResourceId :>
     "Delete a resource."
 :-- "The resource will only be deleted if user has admin access."
 :-- Delete '[] ()
```

Now its odd that "comment" symbol `:--` shows one one line later than the actual comment line.
But we can fix this and URL pieces confusion with changed semantics for `:--`:

``` haskell
data Description (desc :: Symbol)
type Dsc = Description

-- :-- needs to bind tighter than :>
type api :-- description = api :> Description more

type Endpoint = "resource" :> Capture "resource_id" ResourceId :>
 :-- "Delete a resource."
 :-- "The resource will only be deleted if user has admin access."
 :> Delete '[] ()

type ResourceAPI = "resource" :>
    ( Dsc "Create a resource."
      :-- "Only creates a resource if it does not exist."
      :> ReqBody '[JSON] Resource :> Post '[] ()

 :<|> Dsc "Find resources by name."
      :> QueryParam "name" Text :> Get '[JSON] [Resource]
    )
```

Now this looks almost like real comment lines!
Which actually can go to documentation!

What do you think?

**Comment by fisx** [comment]
I am doing something in the same direction in configifier, and always thought that the servant approach is nicer because it keeps the documentation separate and doesn't clutter and complicate the specification type.

You took it a lot further though, and now I like it much better.

What if you move the comment operator to the end of the line instead?  Notation is a bit unusual, but implementation more straight-forward (I think):

```haskell
type Endpoint = "resource" :> Capture "resource_id" ResourceId :>
     "Delete a resource."                                            --:
     "The resource will only be deleted if user has admin access."   --:
     Delete '[] ()
```

**Comment by fizruk** [comment]
Hmm, I should've checked the code. The "prefix" solution won't work because of associativity (`:>` is right associative, "prefix" `:--` is left associative).

Using `:--` at the end of line should work (although I like it less).

There are a few more alternatives to consider though, using type-level lists.

#### Interpret `[Symbol]` as docstrings

```haskell
type Endpoint = "resource" :> Capture "resource_id" ResourceId :>
     '[ "Delete a resource."
     ,  "The resource will only be deleted if user has admin access." ]
     :> Delete '[] ()
```

#### Use a separate combinator to indicate start of a description

This is a bit involved, but maybe implementation can be simplified.

```haskell
data DocStrings (xs :: [Symbol])

type Description = DocStrings '[]

type family docs :-- (line :: Symbol) where
  DocStrings xs :-- line = DocStrings (xs `Append` line)

type Endpoint = "resource" :> Capture "resource_id" ResourceId
     :> Description
     :-- "Delete a resource."
     :-- "The resource will only be deleted if user has admin access."
     :> Delete '[] ()
```

Despite the extra line with `:> Description`, I personally like this version.
(Still have to check the code though).

**Comment by JoshuaGross** [comment]
It would be great to have something like the above for API documentation, for sure. `servant-swagger` is already very helpful, and having it handle the `"description"` field by looking at `Description` as specified would be really great!

**Comment by rvion** [comment]
Would the idea of having an intermediary data type be interesting to explore ?

```haskell

data EndpointDoc

type Endpoint = "resource" :> Capture "resource_id" ResourceId
     :> Description EndpointDoc
     :> Delete '[] ()

-- so we can have both type level:
type instance toStrSym EndpointDoc = "blablablablabl"

-- and term level doc generation helpers
instance Description EndpointDoc where
   toStrDoc = ...
```

**Comment by phadej** [comment]
Can't `Description "foo" :>` instances for `HasServer`, `HasClient` etc. be added to `servant-swagger`, or why they should live in `servant`?

**Comment by rvion** [comment]
@phadej It could make sense to reuse description in other contexts, such as
 - js comment in servant-js, 
 - automatic http documentation via OPTIONS verb request (https://github.com/begriffs/postgrest#self-documentation, http://zacstewart.com/2012/04/14/http-options-method.html)

**Comment by phadej** [comment]
@rvion makes sense.

---

Also about intermediate type, I like the idea. That way one can share some documentation bits bitween different endpoints (as there might be multiple `Description`s.

```hs
class ToDescription d where
  toStrDoc :: Proxy d -> Text

instance KnownSymbol s => ToDescription s where
  toStrDoc = T.pack . symbolVal

data MyDoc
instance ToDescription MyDoc where
  toStrDoc _ = "my description"
```

**Comment by phadej** [comment]
`Description` is in servant-0.12
