### ISSUE TITLE
Update Copyright

### ISSUE THREAD

**Issue by fizruk** [haskell-servant/servant#337]
Currently we have this:

```
$ grep Copyright */LICENSE
servant-blaze/LICENSE:Copyright (c) 2015, Julian K. Arni
servant-cassava/LICENSE:Copyright (c) 2015, Julian K. Arni
servant-client/LICENSE:Copyright (c) 2014, Zalora South East Asia Pte Ltd
servant-docs/LICENSE:Copyright (c) 2014, Zalora South East Asia Pte Ltd
servant-examples/LICENSE:Copyright (c) 2015, Alp Mestanogullari
servant-foreign/LICENSE:Copyright (c) 2014, Zalora South East Asia Pte Ltd
servant-js/LICENSE:Copyright (c) 2014, Zalora South East Asia Pte Ltd
servant-lucid/LICENSE:Copyright (c) 2015, Julian K. Arni
servant-mock/LICENSE:Copyright (c) 2015, Alp Mestanogullari
servant-server/LICENSE:Copyright (c) 2014, Zalora South East Asia Pte Ltd
servant/LICENSE:Copyright (c) 2014, Zalora South East Asia Pte Ltd
```

I think we should at least update year with `-2016`.

Also, it might be good to change copyright owners to something like "Servant contributors" (like Stack does for example).

**Comment by jkarni** [comment]
I'm happy to have mine switched to `Servant contributors` (in fact I'd prefer that - mostly it is as it is because it was done automatically). As for the `Zalora` ones, I'm not sure they can be removed (and I don't think I'd want to either - it's a small way of saying thank you). But we should *add* `Servant Contributors` to them, I think.

**Comment by jkarni** [comment]
@alpmestan Are you okay with the above?

**Comment by alpmestan** [comment]
I definitely agree with you @jkarni (yes, it happens sometimes! =P) -- let's keep Zalora but append "Servant contributors" to it on all packages that were created under Zalora work. For the new ones, there's no question about it, I think we all just want "Servant contributors".

**Comment by jkarni** [comment]
I'm going to add `haskell-servant-maintainers@googlegroups.com` as the email, unless anyone objects.

**Comment by fizruk** [comment]
:+1:

**Comment by arianvp** [comment]
Sounds good

**Comment by jkarni** [comment]
@MaxOw are you okay with having the authors of `-foreign` changed to `Servant Contributors`?

**Comment by dredozubov** [comment]
I'm +1 on that.

**Comment by MaxOw** [comment]
Sure, no problem.
