### ISSUE TITLE
Use Read the Docs?

### ISSUE THREAD

**Issue by fizruk** [haskell-servant/servant#338]
I have started a branch ([fizruk/read-the-docs](https://github.com/haskell-servant/servant/tree/fizruk/read-the-docs)), organizing servant documenation for [readthedocs.org](https://readthedocs.org).

So far I've borrowed a config from Stack and put `README.md` and `CONTRIBUTING.md` links.
Here's how it looks: http://haskell-servant.readthedocs.org/en/fizruk-read-the-docs.

I find Read the Docs somewhat more convenient for documentation/tutorials than [haskell-servant.github.io](http://haskell-servant.github.io):
- it builds and updates automatically;
- it can serve multiple versions of documentation (so people can lookup documentation for `0.4` as well as for `HEAD`);
- it has search and better navigation.

Perhaps, [haskell-servant.github.io](http://haskell-servant.github.io) should only retain blog posts which do not exactly fit as documentation.

@jkarni, @alpmestan waiting for your approval to continue work on this.

**Comment by jkarni** [comment]
@soenkehahn is working on getting our tutorial etc. to be literate markdown ([here](https://github.com/haskell-servant/haskell-servant.github.io/pull/37), I believe it's pretty much done), so we can test that everything compiles. That's pretty useful, I think. Could we get that behaviour with RTD?

**Comment by fizruk** [comment]
@jkarni I don't see why not, we can simply use `.md` links to `.lhs` files (which are markdown literate haskell files IIUC).

**Comment by soenkehahn** [comment]
@fizruk: Sounds great. But yes, this should be coordinated with https://github.com/haskell-servant/haskell-servant.github.io/pull/37.

Is your plan to move the tutorial and other things from https://github.com/haskell-servant/haskell-servant.github.io (except the blog posts) into the `servant` repo, directory `doc` then?

**Comment by fizruk** [comment]
@soenkehahn yes, that would be the plan.

The idea is that tutorial and explanatory articles actually belong in servant repo, not servant's website:
- it should be in sync with the repo's content (at least at release points);
- it would really help to be able to review built documentation before the release;
- I think it would help servant's users to look at the documentation/tutorial relevant to their servant version (I don't expect everyone to migrate fast with every new version of servant).

Also, if we compile code in documentation together with the servant code itself, we would notice breakages in documentation early and it won't be such a daunting task to fix/update the docs.

**Comment by soenkehahn** [comment]
@fizruk: Sounds all very good to me.

I'll try to fix up the PR in `haskell-servant.github.io` soon. So that you can work from there.

**Comment by jkarni** [comment]
:+1: from me too.

**Comment by alpmestan** [comment]
:+1: from me as well.

**Comment by soenkehahn** [comment]
@fizruk: https://github.com/haskell-servant/haskell-servant.github.io/pull/37 is done and merged.

Another thing that came to mind is that this effort has to be coordinated with updating the tutorial/docs for `servant-0.5`.

**Comment by jkarni** [comment]
I did some work on this in https://github.com/haskell-servant/servant/tree/jkarni/merge-tutorial .

**Comment by soenkehahn** [comment]
There's this PR now: #355.

**Comment by jkarni** [comment]
Done in #355
