### ISSUE TITLE
Access to full Response body

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#34]
_From @tvh on March 13, 2015 6:14_

Sometimes it is necessary to inspect more about a response than just the body. Some services will return important information in the header. It would be nice to have a mechanism to do this.

One option would be to change the instance for `Raw`, such that it returns the Full response instead of just parts of it. This would also be in symmetry to the server, where you have full access to wai.

_Copied from original issue: haskell-servant/servant-client#16_

**Comment by jkarni** [comment]
:+1: on changing the instance for `Raw`. I guess we also need a `SetsHeader` combinator in `servant` - and then an instance for it in `servant-client`.

**Comment by jkarni** [comment]
_From @alpmestan on March 13, 2015 9:47_

+1 for `Raw`. Much less so for `SetsHeader` unless we really have no better solution: `SetsXXX` stuffs hardly compose unfortunately.

**Comment by fizruk** [comment]
@jkarni this issues seems outdated, can we close it?

**Comment by jkarni** [comment]
Agreed. You already get the full response.
