### ISSUE TITLE
Clean up servant-examples

### ISSUE THREAD

**Issue by fizruk** [haskell-servant/servant#342]
Currently `servant-examples` contains a few ad hoc and underdocumented examples (we should **explain** how examples work, not just showcase them):
- `auth-combinator` will soon be obsolete when auth mechanism is merged into servant;
- `hackage` example demonstrates integration with a part of a simple API while using `unsafePerformIO` and defining `uselessNumbers`;
- `include/overlapping-compat.h` is not used;
- `socket-io-chat` does not work out of the box (at least on my Mac) and has more JS/CSS code than Haskell (I think the former can be reduced significantly), also Haskell code can be improved;
- `tutorial` is heavily underdocumented for a tutorial;
- `wai-middleware` example only demonstrates the use of `logStdout` (which can be used in any other example).

I propose to:
- remove `auth-combinator` example or, alternatively, move it to `-contrib` packages;
- clean `hackage` example from bad code, make a realistic usage example;
- remove `include/`;
- fix and improve `socket-io-chat` example;
- replace/merge `tutorial` with the [one from `haskell-servant.github.io`](http://haskell-servant.github.io/tutorial/);
- remove `wai-middleware` and instead use logger middleware in other examples and/or tutorial;
- document everything (i.e. place explanatory and otherwise helpful comments in the code).

@haskell-servant/maintainers waiting for approval/discussion to move forward.

I would like this to be solved before #338. At least the tutorial part.

**Comment by soenkehahn** [comment]
All of your propositions seem very reasonable to me.

Regarding the tutorial: I was under the impression that the tutorial from http://haskell-servant.github.io references the code from `servant-examples/tutorial`. However there is no automatic check to make sure the two are still in sync -- even after https://github.com/haskell-servant/haskell-servant.github.io/pull/37. I like the idea of having the tutorial be self-contained compilable haskell files that don't refer to any external example files. So yes: replace `servant-examples/tutorial` with the one from `github.io` and remove the mentions to the old example files.

**Comment by codedmart** [comment]
@fizruk I agree with your proposals. I can fix `socket-io-chat` since I added that. The extra JS/CSS was just pulled from [here](https://github.com/ocharles/engine.io/tree/master/examples/chat/resources) but I can slim them down if you want.

**Comment by fizruk** [comment]
@codedmart yes, shrinking front-end code would be nice! Thanks!

**Comment by octopuscabbage** [comment]
+1, good job guys.

**Comment by jkarni** [comment]
We're removing `servant-examples` as part of #355, so closing.
