### ISSUE TITLE
Generate client types and functions with TH

### ISSUE THREAD

**Issue by fizruk** [haskell-servant/servant#344]
As brought up by @jtdaugherty in https://github.com/haskell-servant/servant/issues/174#issuecomment-172602367 it would be nice to have TH generation for Haskell client types and functions.

The idea is to translate this API:

``` haskell
type Bar = Value
type Foo = Value
type FooId = Int

type API
    = "bar" :> Get '[JSON] Bar
 :<|> "foo" :> Capture "foo_id" FooId :>
         ( "a" :> Get '[JSON] Foo
      :<|> "b" :> Get '[JSON] Foo )
```

into this client structures and functions:

``` haskell
data ApiClient = ApiClient
  { getBar :: ExceptT ServantError IO Bar
  , mkFooClient :: FooId -> FooClient
  }

data FooClient = FooClient
  { getFooA :: ExceptT ServantError IO Foo
  , getFooB :: ExceptT ServantError IO Foo
  }

mkClient :: BaseUrl -> ApiClient
mkClient baseurl = ApiClient{..}
  where
    apiClient = client (Proxy :: Proxy API) baseurl 
    getBar :<|> fooClient = client baseurl

    mkFooClient fooId = FooClient{..}
      where
        getFooA :<|> getFooB = fooClient fooId
```

The naming for the functions/types can be derived from URL pieces (e.g. `"foo"`, `"a"`, `"b"`).

**Comment by tdietert** [comment]
`apiClient = client (Proxy :: Proxy API) baseurl`
`getBar :<|> fooClient = client baseurl`

Is this a typo? How does client have type 
`client :: Proxy a -> BaseUrl -> ..
and
`client :: BaseUrl -> ..

And why is it being used twice. I feel like I understand what is happening here until I reach those lines. Please clarify?

**Comment by fizruk** [comment]
@tdietert I meant `getBar :<|> fooClient = apiClient`, of course!

**Comment by tdietert** [comment]
On that note, Servant 0.7 `client` function has type `HasClient layout => Proxy layout -> Client layout`, whereas the client function you use here takes a `BaseUrl`. I'm currently trying to use this approach to nest my API call that ALWAYS requires a `QueryParam "client_id" Text` combinator, no matter the endpoint. However, with the recent changes to servant-client, a `BaseUrl` and `Manager` must be passed to each client functions that queries and endpoint, instead of the baseurl being passed to the client function. Does this change the approach outlined above in any way? Thank you so much for your help :)

**Comment by fizruk** [comment]
Yeah, I've proposed this before `servant-0.7`.
Here's what we have with latest `servant` for our project:

```haskell
data ApiClient = ApiClient
  { getBar :: Manager -> BaseUrl -> ClientM Bar
  , mkFooClient :: FooId -> FooClient
  }

data FooClient = FooClient
  { getFooA :: Manager -> BaseUrl -> ClientM Foo
  , getFooB :: Manager -> BaseUrl -> ClientM Foo
  }

mkClient :: BaseUrl -> ApiClient
mkClient baseurl = ApiClient{..}
  where
    apiClient = client (Proxy :: Proxy API) 
    getBar :<|> fooClient = apiClient

    mkFooClient fooId = FooClient{..}
      where
        getFooA :<|> getFooB = fooClient fooId
```

**Comment by tdietert** [comment]
One last question, as I'm having a bit of trouble with the type system and understanding how it all fits together. Can you should me the definition of your API type? And, do you mean to pass a baseurl to the `mkClient` function; If so, why not a manager as well? I'm really struggling with this and keep getting the error:     
`No instance for (HasClient SoundcloudAPI)
      arising from a use of ‘client’
    In the expression: client soundcloudAPI`

So obviously something is not lined up properly. I'm about to just write out the endpoints without any nesting :(

**Comment by fizruk** [comment]
@tdietert ah, sorry, `mkClient` does not take `BaseUrl`, just remove that argument.

Here's [complete gist with the API](https://gist.github.com/fizruk/0e1b87d8a917d479f02ca5148861c9ae) (this time I tested, with `resolver: nightly-2016-07-19`).

Regarding the error you get — I can't tell much, since I am not sure what is the `SoundcloudAPI` you're dealing with.

**Comment by alpmestan** [comment]
If someone is willing to do this work, I definitely wouldn't mind having this in servant-client. While everyone's been happy to get client functions for free, many of us have been annoyed by how we pattern match our way to get them. It's cumbersome and this feature would make the problem go away for anyone willing to enable TH.

**Comment by jkarni** [comment]
#640 basically does this. Closing.
