### ISSUE TITLE
Allow external combinators to provide instances for Servant.Utils.Links

### ISSUE THREAD

**Issue by iand675** [haskell-servant/servant#352]
Servant.Utils.Links currently uses a closed type family for IsElem, so there's no way to extend it with new combinators. I wrote a session combinator that uses the `serversession` package, and the nature of the combinator is such that it doesn't affect how the links should be generated. It's a shame that I have to pick either auth or type-safe links and can't have both :)

**Comment by fizruk** [comment]
Actually, you can. You just add type instance to [`IsElem'`](http://hackage.haskell.org/package/servant-0.4.4.6/docs/Servant-Utils-Links.html#t:IsElem-39-).
While `IsElem` is a closed type family, it uses `IsElem'` **open** type family as a "catch all" handler.

**Comment by iand675** [comment]
Ah, perfect. Sorry for the noise!
