### ISSUE TITLE
Remove memoReqBody

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#356]
Currently `memoReqBody` keeps the entire request body in memory. This was originally there because, prior to @kosmikus 's work, we *had* to backtrack requests against the API. We decided to keep it there because it makes the semantics of `ReqBody` somewhat nicer and we weren't sure how things would play out, but I think by now everyone agrees having the request in memory is not acceptable.

I think this should mean that bad bodies are `FailFatal`, so that if two `ReqBody`s occur as in:

```
type API = ReqBody '[JSON] Int :> Post ..
          :<|> ReqBody '[JSON] Bool :> Post ...
```

The second one never gets tried.

**Comment by jkarni** [comment]
Relates to #271

**Comment by brendanhay** [comment]
:+1:
