### ISSUE TITLE
[tutorial] Make syntax highlighting work on readthedocs.

### ISSUE THREAD

**Issue by soenkehahn** [haskell-servant/servant#359]
In #355.

Syntax highlighting seems to break on `TypeOperators`.

@jkarni suggested that we may find a javascript solution.

**Comment by jkarni** [comment]
This issue should maybe be in `pygments` rather than here?

**Comment by soenkehahn** [comment]
This issue is about making the syntax highlighting work on the http://haskell-servant.readthedocs.org/. It might be solved by making it work in `pygments` or by switching to using something other then `pygments`.

**Comment by trevorriles** [comment]
I tried one of the unhighlighted sections from the readthedocs page and it highlighted ok using pygments demo site.

http://pygments.org/demo/4722547/

**Comment by trevorriles** [comment]
https://bitbucket.org/birkenfeld/pygments-main/issues/820/haskell-highlighting-promoted-types

This seems to be where the pygments parsing breaks, and theres already a ticket from 2012.

**Comment by teh** [comment]
I submitted https://bitbucket.org/birkenfeld/pygments-main/pull-requests/685/two-haskell-fixes/diff but I'm not sure how much pygments is supported these days.

**Comment by alpmestan** [comment]
Please keep us posted :)

**Comment by declension** [comment]
Noticed this too recently, but now seems like @teh's PR was merged :smile:

**Comment by teh** [comment]
readthedocs.io is still on 2.0 branch https://github.com/rtfd/readthedocs.org/blob/master/requirements/pip.txt#L8

If anyone has the time & energy to tackle that please do! Otherwise I'll have a go when I get around to it.

**Comment by declension** [comment]
@teh good point, thanks.

I've filed [issue #2720 there](https://github.com/rtfd/readthedocs.org/issues/2720), and have pushed [PR #2721](https://github.com/rtfd/readthedocs.org/pull/2721) to address this (hopefully...)

**Comment by declension** [comment]
Thanks for merging @phadej!

We should probably leave this story open until the external PR above, or equivalent, is merged (i.e. it works on Production RTD)

**Comment by phadej** [comment]
The highlighting seems to work in `latest` version: http://haskell-servant.readthedocs.io/en/latest/tutorial/ApiType.html

I don't know how to update where default, i.e. `stable` points to. @fizruk do you know? FWIW I made a RTD account.

**Comment by fizruk** [comment]
@phadej `latest` corresponds to `master` while `stable` to the lastest release (currently `v0.10`).
AFAIK we can't change this.

See http://docs.readthedocs.io/en/latest/versions.html for more info.

**Comment by phadej** [comment]
@fizruk I see. It make sense.

@declension I don't think it makes sense to track RTD issues here as well, when it will be resolved, it won't need any work from use (except maybe retrigger the builds, but they will anyway when we push / tag)

**Comment by declension** [comment]
@phadej cool, makes sense.
