### ISSUE TITLE
docs: Config: Mention that it's not meant to replace custom monad stacks and `enter`

### ISSUE THREAD

**Issue by soenkehahn** [haskell-servant/servant#361]
Some people asked (on irc) whether they could replace there `ReaderT MyCustomConfig` monad stack with the new Config mechanism. We should clarify that that's not what `Config` is for.

**Comment by fizruk** [comment]
How about renaming `Config` to `Context`?
`spock` people would recognize it then and it'll confuse people less.

Or, maybe to something else: `ServantConfig`, `APIConfig`?

**Comment by soenkehahn** [comment]
Actually I like `Context`. @jkarni, wdyt?

**Comment by aaronlevin** [comment]
:+1: on `Context`

**Comment by aaronlevin** [comment]
@soenkehahn it might be good to state in the docs, specifically, that `Context`/`Config` is mainly used for people writing `HasServer` instances (if that's not already stated).

**Comment by codedmart** [comment]
:+1: on `Context` as well.

**Comment by aaronlevin** [comment]
Also, not sure about this but it might be better to say: `InContext x context` as opposed to `HasContext x context` because there will always be some kind of `context`.

**Comment by soenkehahn** [comment]
I've created a PR for the renaming and clarification of what `Context` does: #401.

@aaronlevin: There's no `HasContext`. (I think that did exist but got removed.)

**Comment by soenkehahn** [comment]
Fixed through #401.
