### ISSUE TITLE
[tutorial] Set up webhooks for readthedocs

### ISSUE THREAD

**Issue by soenkehahn** [haskell-servant/servant#364]
This relates to #363.

**Comment by jkarni** [comment]
Done in #355

**Comment by soenkehahn** [comment]
Doesn't building the documentation still have to be manually triggered? We should have automatic builds for `master` triggered by pushes to github.

**Comment by jkarni** [comment]
No, I setup the webhook and it's now built automatically.

**Comment by soenkehahn** [comment]
Awesome!
