### ISSUE TITLE
Document How To Respond To Requests at "/"

### ISSUE THREAD

**Issue by m4dc4p** [haskell-servant/servant#365]
Spent the last hour trying to figure out how to serve "Raw" files from requests to the root directory. That is, requests to "http://foo.com/".

I tried `type FileAPI = "" :> Raw`, and then I used `serveDirectory` to respond to requests to the root URL. But my server always gave 404, even if the file was in the directory.

Reading through closed issues, I found #195, which had a signature similar to what I wanted. Based on the comment at  https://github.com/haskell-servant/servant/issues/195#issuecomment-132013000, I figured out the type I wanted was just `type FileAPI = Raw`.

Perhaps this is worth adding to the "tips & tricks" section, calling out in the tutorial, or maybe documenting with the `:>` data type?

**Comment by alpmestan** [comment]
You're right. This piece of information is only given implicitly at the moment, it can't hurt to make it louder and explicit.

**Comment by taakazazzz** [comment]
And if it wasn't "Raw" but `Get '[JSON] [Something]`,how would I do that?


    type PersonAPI = "" :> Get '[JSON] [Person] -- doesn't work
    type PersonAPI = "/" :> Get '[JSON] [Person] -- doesn't work

**Comment by soenkehahn** [comment]
Fixed in #553.
