### ISSUE TITLE
Question: Add table of contents?

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#37]
_From @paf31 on January 22, 2015 18:47_

Would you accept a PR to add a table of contents to the generated markdown?

I'm using servant for a medium sized project, and it would be nice if I could group docs into categories based on the tree of routes. I expect I would probably include a change in this PR to introduce a tree as an intermediate data structure.

Maybe we could even structure the markdown as a tree using nested lists, so that related routes appear in the same list. This would also allow me (later) to add a documentation string to every branch (subroute) in the tree.

Thanks.

_Copied from original issue: haskell-servant/servant-docs#8_

**Comment by jkarni** [comment]
_From @alpmestan on January 22, 2015 19:15_

Yes, that would definitely be a nice addition! Maybe the handier way to do that would be as a postprocessing step since the class instances are "local" (i.e they don't know if some other endpoint in the API shares the same shape/"root"). So once we have the [API](http://hackage.haskell.org/package/servant-docs-0.3/docs/Servant-Docs.html#t:API) value, we could group the endpoints "by common roots" recursively, in a tree. This would be much trickier to achieve at the type-level on the API type and is something @jkarni has started working on for other reasons, but it's not really ready yet and is tricky to get right.

**Comment by jkarni** [comment]
_From @mpickering on January 22, 2015 19:24_

It would be easy to generate a TOC using servant-pandoc with the correct pandoc flags.

**Comment by jkarni** [comment]
_From @alpmestan on January 22, 2015 19:28_

Even a smart one? Like:

- `/users`
    - **GET** ...     -- list all users
    - **POST** ...   -- add an user
    - `/:userid`
        - **GET** ...  -- view an user
        - **PUT** ...   -- update an user

? (which I think is what @paf31 wants to achieve)

**Comment by jkarni** [comment]
Hm, this is one advantage type-level URL trie-rewriting has over our (HEAD's) routing machinery: basically we'll have to re-implement everything for documentation, even though we already do something very similar f o

**Comment by fizruk** [comment]
@jkarni is this still relevant?

**Comment by jkarni** [comment]
If anyone wants to contribute a patch, it'd be welcome, but I think we can close.
