### ISSUE TITLE
Using Servant with custom monad: an example

### ISSUE THREAD

**Issue by rubenmoor** [haskell-servant/servant#370]
For your information: I put up an example that shows how we use servant in our projects.

Instead of running in `IO`, we use servant with the monad called "Diener". It has
* logging functionality
* a reader (among others: for database connections)
* its own errors
* convenience function for `lift`s

The monad along with a full example stack (warp - servant - persistent) can be found here:

https://github.com/themoritz/diener

**Comment by nrolland** [comment]
nice !

**Comment by phadej** [comment]
nice indeed!

**Comment by jkarni** [comment]
@rubenmoor please send a PR with a link to the example in [examples.md](https://github.com/haskell-servant/servant/blob/master/doc/examples.md)
