### ISSUE TITLE
Fix or remove GenerateList in servant-foreign

### ISSUE THREAD

**Issue by dredozubov** [haskell-servant/servant#373]
`GenerateList` is a convenience class, which makes possible transforming an API to the list of endpoints to make code generation easier. Currently it fails with an APIs like `"foo" :> (Endpoint1 :<|> Endpoint2)`.
I've made a test case to demonstrate this: https://github.com/dredozubov/servant/commit/b225daa9e0422a3f985fb8c65d35e22fde377adc (it fails with 2 != 4)

Before attempting to fix this i would like to clarify if this kind of APIs are officially supported and it makes sense to support these transformations thoughout all packages.

**Comment by dredozubov** [comment]
@jkarni @alpmestan can someone clarify?

**Comment by fizruk** [comment]
@dredozubov take a look at [`EndpointsList` in `servant-swagger`](https://github.com/haskell-servant/servant-swagger/blob/master/src/Servant/Swagger/Internal/TypeLevel/API.hs#L15).
I think it does what you want (and I am planning to move it to #345 when I have time)

**Comment by dredozubov** [comment]
@fizruk i propose we move it to the `Servant.API.TypeLevel`, then we'll be able to remove `servant-swagger` and `servant-foreign` versions

**Comment by fizruk** [comment]
@dredozubov I now see that [`GenerateList`](https://github.com/haskell-servant/servant/blob/master/servant-foreign/src/Servant/Foreign/Internal.hs#L314) is different from `EndpointsList`.

Also, why are you expecting 4 endpoints?

**Comment by dredozubov** [comment]
We've discussed it with @fizruk and it appears like i've been wrong here. I'm closing the issue.
