### ISSUE TITLE
Bump aeson version

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#374]
See https://github.com/fpco/stackage/issues/1211

**Comment by dredozubov** [comment]
Just a thought: should we wait until stackage lts will have `aeson-0.11`? stackage lts have `0.9.0.1`

**Comment by itteam** [comment]
@dredozubov `servant` is in stackage, so before `servant` bumps bounds nightly/lts won't have `aeson-0.11`...

**Comment by phadej** [comment]
@dredozubov `servant` is in stackage, so before `servant` bumps bounds nightly/lts won't have `aeson-0.11`...

**Comment by dredozubov** [comment]
@phadej oops! Yeah, you're right.

**Comment by soenkehahn** [comment]
Fixed on the branches `master` and `0.4` and released to hackage as `0.4.4.7`.
