### ISSUE TITLE
Get rid of code duplication in Servant.JS.Internal submodules

### ISSUE THREAD

**Issue by dredozubov** [haskell-servant/servant#377]
I believe it is a fairly reasonable thing to do and it looks pretty straightforward with the help of the test-suite.

**Comment by jkarni** [comment]
@dredozubov is this still relevant?

**Comment by dredozubov** [comment]
@jkarni i don't really use servant-js nowadays, so i'm probably not the best person to ask anymore. Also judging by the lack of feedback, it's safe to assume that no one really cares for this kind of improvement.

**Comment by soenkehahn** [comment]
Alright, closing.
