### ISSUE TITLE
Overlapping names

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#38]
_From @seanhess on April 16, 2015 17:44_

Servant is using the same name `getsources` for both `GET /sources` and `GET /sources/:id`. Is there some way it could figure out to call the second one `getsource`?

```
type Api = "sources" :> Get [Source] :<|> "sources" :> Capture "id" Text :> Get (Source)
```

_Copied from original issue: haskell-servant/servant-jquery#13_

**Comment by jkarni** [comment]
Great question. I'd suggest manually or automatically [0] changing the produced source code for now, but we'll keep this issue open and try to figure out a general way of preventing/resolving conflicting names.

[0] Something as simple as `sed  '0,/getsources(/! s/getsources(/getsourcesCapture(/' <file>` might work, even though it's pretty brittle.

**Comment by jkarni** [comment]
_From @alpmestan on April 19, 2015 8:37_

Unless anyone has a suggestion for an algorithm that can automatically generate decent names from our various combinators + static strings?

**Comment by seanhess** [comment]
What if you always add captures to the name?

    type Api = "sources" :> Get [Source] :<|> "sources" :> Capture "id" Text :> Get (Source)

    getSources()
    getSourcesId()

It's not as clear as `getSource` but it's way better than having them overlap. I would use it.

**Comment by alpmestan** [comment]
or `getSourcesById` maybe?

**Comment by jkarni** [comment]
That just pushes the problem elsewhere:

``` type Api = "sources[By]Id" :> Get [Source] :<|> "sources" :> Capture "id" Text :> Get (Source) ```

No purely local naming scheme can always work. 

I'd like to try to come up with some general approach to this type of problem. It's going to show up in other cases for `servant-jquery`, but also for any other future code-gen package.

**Comment by seanhess** [comment]
+1 `getSourcesById`. 

@jkarni True, but it's better than what we have now, isn't it?

**Comment by freezeboy** [comment]
Maybe we can close this one too, as master implements this solution ?

**Comment by jkarni** [comment]
@freezeboy yup. @seanhess thanks for the report, and let us know if you think this has been closed incorrectly.
