### ISSUE TITLE
Make compilable with GHC 8.0

### ISSUE THREAD

**Issue by phadej** [haskell-servant/servant#384]
Some of `servant-` packages' dependencies are already GHC8.0 ready, so the next release should either have restricted `base <4.9` or verified by other means to work with `GHC8.0`.

I edited (also) the last package metadata on Hackage: https://hackage.haskell.org/package/servant-0.4.4.6/revisions/

Related https://github.com/haskell-servant/servant/issues/374

**Comment by jkarni** [comment]
Done in #388 (and thanks a lot!)

**Comment by alpmestan** [comment]
Thanks @phadej !
