### ISSUE TITLE
Defining function rendering settings

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#39]
_From @rtrvrtg on January 22, 2015 1:2_

I was wondering if there are any plans to change the way that servant-jquery's Javascript wrapper functions get rendered. Currently, they're all rendered like so:

```javascript
function getsomething(onSuccess, onError) {
```

However, I was wondering if we could customise the `generateJS` method to support alternative rendering methods, such as functions as variables, the Javascript Module Pattern, CommonJS (which is the same as the current one but with the addition of an `exports` declaration), and Purescript-ready methods (which require a bunch of nested functions, one for each parameter).

The outcome is that we might be able to invoke, say,

```haskell
generateJS' (ModulePatternOutput "Foo.MySubmodule") getSomethingAjaxReq
```

and get

```javascript
Foo.MySubmodule.getsomething = function(onSuccess, onError){
...
```

I'm happy to undertake investigation into this and put together a PR for it, but I was wondering what your thoughts were on this.

_Copied from original issue: haskell-servant/servant-jquery#7_

**Comment by jkarni** [comment]
_From @alpmestan on January 22, 2015 1:9_

I wholeheartedly agree that this would be nice to have. The current implementation is the result of me putting together just what I needed at that time. We could definitely add an `Options` or `Settings` or `OutputFormat` type or something that would specify how we want the generated javascript to look like. I would just like however to keep the simple use case simple to write, so yeah we could have a `generateJS'` function next to the current one that supports fancy options, and have the current one be implemented in term of it using default settings to generate the same kind of JS code that we get now.

Does that sound good to you?

**Comment by jkarni** [comment]
_From @rtrvrtg on January 22, 2015 1:14_

Sounds good to me. If we need to provide a default setting, we can set it to be the current, simple output method.

**Comment by jkarni** [comment]
_From @alpmestan on January 22, 2015 1:19_

Perfect. Let me know if you need any help in working on this, although I don't have time to undertake it myself (alone) these days.

**Comment by jkarni** [comment]
_From @alpmestan on March 26, 2015 11:59_

@christian-marie Do you guys still want this to happen or can we close this ticket?

**Comment by christian-marie** [comment]
Sorry, missed this. @rtrvrtg is no longer working on this so I don't think it will get done.

I think we can close this but I'll hold out 'till someone who know more about the JS stuff to take a look at #143

**Comment by freezeboy** [comment]
#143 is now closed
