### ISSUE TITLE
Move Config into Router

### ISSUE THREAD

**Issue by fizruk** [haskell-servant/servant#392]
Currently we have:

``` haskell
route :: Proxy layout -> Config config -> Delayed (Server layout) -> Router
```

This makes it difficult or impossible to change `Config` for a sub API.
That might be useful for authentication combinators to put `UserId` into `Config`.

To solve this problem I think we can move `Config` from `route`'s signature into `Router`, adding one extra constructor to `Router'`:

``` haskell
type Router config = Router' config RouterApplication

data Router' config a where
  ...
  WithConfig :: (Config config -> Router subConfig) -> Router' config
```

The `route` method will then have this type:

``` haskell
route :: Proxy layout -> Delayed (Server layout) -> Router config
```

So far this is just a random thought, which probably deserves some investigation.

**Comment by soenkehahn** [comment]
If I understand you right, this is already possible: https://github.com/haskell-servant/servant/blob/master/servant-server/test/Servant/Server/UsingConfigSpec.hs#L81

**Comment by fizruk** [comment]
@soenkehahn unfortunately, that's only possible for static values. See how `InjectIntoConfig` injects a statically known `String`: https://github.com/haskell-servant/servant/blob/master/servant-server/test/Servant/Server/UsingConfigSpec/TestCombinators.hs#L56.

If I want to inject a result of an IO action (such as `UserId` obtained from database), I have no way to do that currently.

**Comment by soenkehahn** [comment]
Yes, you're right.

**Comment by jkarni** [comment]
This is an interesting idea. My opinion is that we should wait for a convincing use-case before implementing it, though.

**Comment by jkarni** [comment]
Closing until we have a concrete example of what problem this would solve.
