### ISSUE TITLE
problem aeson with the tutorial 

### ISSUE THREAD

**Issue by rwobben** [haskell-servant/servant#393]
Hello, 

IM trying to do the tutorial with the help of stack.

But I cannot solve this problem : 

/home/ubuntu/workspace/paytime/app/Main.hs:44:10:
    No instance for (ToJSON Day)
      arising from a use of ‘aeson-0.9.0.1:Data.Aeson.Types.Class.$gdmtoJSON’
    In the expression: aeson-0.9.0.1:Data.Aeson.Types.Class.$gdmtoJSON
    In an equation for ‘toJSON’:
        toJSON = aeson-0.9.0.1:Data.Aeson.Types.Class.$gdmtoJSON
    In the instance declaration for ‘ToJSON User’
Completed 98 action(s).

**Comment by aaronlevin** [comment]
Hi @rwobben,

Are you hitting this issue when cloning from `master`?

**Comment by aaronlevin** [comment]
Sorry, my question may have been unclear :) When you say "trying to do the tutorial with the help of stack" can you point to the current version of the tutorial you are using and any relevant stack files?

**Comment by rwobben** [comment]
NP, 

I did the page serving a api. 

I did copy the files from that page of the part a first example to my box and then do stack build. 
If you need it , I can make a github repo of how things are looking.

**Comment by phadej** [comment]
`aeson` provides `Day` instances only starting from `0.10.0.0` upwards.

**Comment by rwobben** [comment]
oops. and stack only ships 0.9 after the problems with 0.10. 
I hope this can be solved in a easy way

**Comment by phadej** [comment]
Stackage has `aeson-compat` backporting (at least) some missing instances (including `Day`).

**Comment by rwobben** [comment]
Thanks. chancing that and adding aeson-compat to the build depends did the trick.
