### ISSUE TITLE
Convenient way to set redirectCount?

### ISSUE THREAD

**Issue by gromakovsky** [haskell-servant/servant#394]
I'm writing a client (using `servant-client`) which queries a server with endpoint which results into `302` response (redirect). Derived function makes this redirect and results into `ServantError` if I call it. This error is `FailureResponse` with `responseStatus = 200`. In general it's very strange to see `FailureResponse` wih 200 status.

What I want to do is to be able to add some options like `redirectCount` to tune derived client functions. As I understand, currently derived functions simply inherit default behavior from `http-client` which is `to automatically perform up to 10 redirects (response codes 301, 302, 303, and 307), and to throw a StatusCodeException on all responses whose status are not in the 2xx range`. Is there any way to achieve this with `servant-0.4`?

**Comment by soenkehahn** [comment]
I don't see a way to achieve this with `0.4.*`. In `0.5` the function `client` has an additional `Manager` argument that allows to do what you want.

Sorry I can't help. Can I close this?

**Comment by gromakovsky** [comment]
Ok, thanks for reply, will wait for `0.5` version and will temporarily use `wreq` for this particular request.

Yes, I think you can close.

**Comment by matthewleon** [comment]
Not sure what the protocol is for closed Issues, but I think this belongs here.

It seems that `redirectCount` is an attribute of the `Request` itself rather than the `Manager`: https://hackage.haskell.org/package/http-client-0.5.7.0/docs/src/Network-HTTP-Client-Types.html#redirectCount.

Could `servant-client` provide a convenient way to patch settings on the emitted `Request` objects?

**Comment by alpmestan** [comment]
@matthewleon The protocol is that people should feel free to ask questions and what not, even on closed issues. `Request` indeed embeds a redirect count field (which I think is a bit odd, but anyways) and `Manager` comes with a function for modifying `Request`s on the fly before sending them: `managerModifyRequest`, which should allow you to set the `redirectCount` that you want, possibly depending on the target of the request or some other criteria. Unless I'm overlooking something?

**Comment by matthewleon** [comment]
> Manager comes with a function for modifying Requests on the fly before sending them: managerModifyRequest

Missed that trick! Thanks @alpmestan.
