### ISSUE TITLE
Multiple "Set-Cookie" Headers

### ISSUE THREAD

**Issue by jsermeno** [haskell-servant/servant#396]
The server should be allowed to set multiple "Set-Cookie" headers in order to conform with the way browsers accept cookies. In general, you wouldn't want this. There is code in `ResponseHeader.hs` that prevents duplicate headers.

```
type family Contains x xs where
    Contains x ((Header x a) ': xs) = 'True
    Contains x ((Header y a) ': xs) = Contains x xs
    Contains x '[]                  = 'False
```

A quick hack that adds

```
type family Contains x xs where
    Contains "Set-Cookie" ((Header a b) ': xs) = 'False
    ...
```

fixes the problem, though maybe a more general solution would be better.

**Comment by jsermeno** [comment]
I added a pull request here.

https://github.com/haskell-servant/servant/pull/397

As far as I know, "Set-Cookie" is the only header you would want to do this with. Maybe it makes sense to have a sole exception.

However, one strange thing with this code is that the types are case sensitive. This means even with the code as is, you can do things like

```
Get '[HTML] (Headers '[Header "Set-Cookie" ByteString, Header "Set-cookie" ByteString] LucidHtml)
```

I'm unsure if there is a way to make this check in a case-insensitive way. If not, perhaps it's better to have this logic outside of the types.

**Comment by arianvp** [comment]
I think a more general solution is in place here. Lets take a look at what the HTTP spec has to say here:

https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2


> Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma. The order in which header fields with the same field-name are received is therefore significant to the interpretation of the combined field value, and thus a proxy MUST NOT change the order of these field values when a message is forwarded.


In other words, in general duplicate header names are accepted. And are actually also used aside from cookies.    And these two are considered equivalent:

```
X-My-Header: foo
X-My-Header: bar
```
and:

```
X-My-Header: foo, bar
```
Cache-Control: no-store


Another real world example is Cache-Control:
```
Cache-Control: no-cache
Cache-Control: no-store
``` 
Or
```
Cache-Control: no-cache, no-store
```

Hence I am actually in favor to be able to have duplicate header names in general. As it's allowed by the standard.   Maybe we want to be able to squash them into one header though as a comma separated list.  But the semantics stay the same.

**Comment by arianvp** [comment]
The case insensitivity on type-level might actually be difficult as `Symbol`s aren't typelevel `[Char]`'s so we can't really define useful type families on them as far as I know.

Perhaps it would be a better solution to be able to pass a list of values to a response header?

**Comment by jsermeno** [comment]
I would be also be in favor of allowing duplicate header names in general. However, we should note that for cookies in particular, not all browsers accept the squashed comma-separated format. Chrome for example, only accepts multiple cookie headers.

http://tools.ietf.org/html/rfc6265#section-4.1.2 states multiple cookie headers should not be be folded into a single header.
```
Origin servers SHOULD NOT fold multiple Set-Cookie header fields into
   a single header field.  The usual mechanism for folding HTTP headers
   fields (i.e., as defined in [RFC2616]) might change the semantics of
   the Set-Cookie header field because the %x2C (",") character is used
   by Set-Cookie in a way that conflicts with such folding.
```

I almost feel as though there should be a good default, but that the user is allowed to choose if a header is folded, or not. I don't expect the situation to change in the near-term, but I can imagine developers running into issues depending on browser support, or communication with old clients.

Or, what if the `addHeader` function accepts a list, and that folds by default. But, you can also specify two headers, and that is respected. So you can do:

```
Get '[HTML] (Headers '[Header "Set-Cookie" ByteString] LucidHTML)
...
addHeaders ["a=x", "b=y"]
```
This results in: 

```
Set-Cookie: a=x;,b=y;
```
or 

```
Get '[HTML] (Headers '[Header "Set-Cookie" ByteString, Header "Set-Cookie" ByteString] LucidHTML)
...
addHeaders ["a=x"] $ addHeaders ["b=y"]
```
This results in:
```
Set-Cookie: a=x;
Set-Cookie: b=y;
```
And we remove the restrictions against all duplicate headers.

**Comment by jkarni** [comment]
Done in #397
