### ISSUE TITLE
`:<|>` tries subsequent `Raw`s even for bad requests

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#41]
_From @soenkehahn on April 17, 2015 10:37_

@phunehehe and I came up with a test case for this: https://github.com/haskell-servant/servant-server/compare/badRequest-bug?expand=1

I'm not sure this is a bug or wanted behaviour though.

_Copied from original issue: haskell-servant/servant-server#42_

**Comment by jkarni** [comment]
Ouch, tricky one. My intuition is that the `Raw` endpoint should be tried (any non-complete match should try other endpoints), but if the `Raw` endpoint fails, `400` should be returned. We'd have to check whether the `Raw` endpoint returned `2XX` though (not impossible, just annoying).

**Comment by phunehehe** [comment]
My intuition is a little different :)
I think the URL on its own should determine the handler. If the handler says "bad request" or throw an error, that should be the final answer. This mapping feels "clean" to me.
But of course, that's just an intuition.

**Comment by jkarni** [comment]
The problem is that it's a *feature* that `Raw` doesn't need to match on endpoints. It means one can mount an entire other web server, with its own routing, there. So we can't assume that the route doesn't in fact match just because from the outside, so to speak, it looks that way. Internally, the `Raw` endpoint may well match against the route too.

**Comment by phunehehe** [comment]
Ah I was talking about other, "normal", endpoints. Do you think Raw should still be tried if the request already matches another endpoint?

**Comment by alpmestan** [comment]
@jkarni With the new routing machinery, is this issue solved?

**Comment by jkarni** [comment]
No, I don't think so. I'm still unsure of what should be considered an appropriate solution. We've so far not had the semantics that body mismatches prevent future endpoints from being tried (so you could have the same endpoint with different `ReqBody`s and it would make sense). @phunehehe's point that this doesn't match up with how most web frameworks (where URL alone determines handlers) behave is well taken. OTOH from within the logic of servant the current behaviour also makes sense: URL match, method match, request-body match, etc. are all just predicates that stand on the same footing, and a handler is picked when all predicates are true. 

So we have to decide: with something like:

         ReqBody '[JSON] Person :> Get '[JSON] ()
         ReqBody '[JSON] Thing   :> Get '[JSON] ()

Would a request with a body that can be deserialized as a `Thing` but not `Person` get a 400 or a 204? Note that this also applies to e.g. differing content-types, and other things besides.

(By the way, this reminds me that we might need `Server Raw = Either ServantErr Application`, rather than just `Application`, but this isn't directly pertinent to the issue.)

**Comment by jkarni** [comment]
Closed in #218
