### ISSUE TITLE
Support for repeated items in QueryParam

### ISSUE THREAD

**Issue by bitemyapp** [haskell-servant/servant#417]
There's an idiom that's become more common lately where the following request:

`GET /users?id=1&id2`

Gives you a list of ids equal to `[1, 2]`.

It doesn't seem like support for this exists for `QueryParam` in 0.5. I may have missed something.

If it needs implemented, this seems like a potentially surprising feature that should be under a different name, `MultiQueryParam` perhaps?

**Comment by alpmestan** [comment]
We have [`QueryParams`](http://hackage.haskell.org/package/servant-0.5/docs/Servant-API-QueryParam.html#t:QueryParams) for this, does it suit your needs?

**Comment by bitemyapp** [comment]
Yes, derp, thank you!
