### ISSUE TITLE
Provide a minimal `servant-server` project as a template

### ISSUE THREAD

**Issue by soenkehahn** [haskell-servant/servant#420]
This should live in its own github repo and probably include:

- cabal file,
- stack file,
- `src` directory with a minimal API and a server,
- `test` directory with a minimal test-suite using either `servant-client` or `hspec-wai`.

**Comment by alpmestan** [comment]
Great idea.

**Comment by rvion** [comment]
yes, and it would be great to have it either
 - submitted to stack-templates.
 - compatible with stack templates by pointing stack new to use servant repo as template catalog repo

**Comment by alexanderkjeldaas** [comment]
There is already some support in stack-templates now:

https://github.com/commercialhaskell/stack-templates/commit/bd7b20e51e78ae70801aa63e01e7a653411ff423

What's nice about that template is that it enables letsencrypt.org by default.

Maybe this work could be merged with that template.

**Comment by arianvp** [comment]
@alexanderkjeldaas interesting. Maybe a bit offtopic. but why choose to put nginx in front of the app instead of letting warp use the letsencrypt cert directly?

**Comment by alexanderkjeldaas** [comment]
The nginx docker container has an existing sidecar for letsencrypt.

I also think it is a bad idea not to have a HTTP load balancer in front of a backend in any production setup, and SSL termination has to happen at the load balancer.

**Comment by soenkehahn** [comment]
I've opened this PR: https://github.com/commercialhaskell/stack-templates/pull/52
It's for `servant-0.4` since `stack new` doesn't support templates with stack files in it. (See a discussion here: https://groups.google.com/d/topic/haskell-stack/sOI5rY28G3E/discussion)

Once `servant-0.5` is on stackage, we can of course update the template. (https://github.com/fpco/stackage/issues/1290)

**Comment by soenkehahn** [comment]
I've created an example project here: https://github.com/haskell-servant/example-servant-minimal

**Comment by soenkehahn** [comment]
I also created a section about example projects in the documentation: #471. If we merge this, I would consider this issue solved.

**Comment by jkarni** [comment]
Closing since #471 had been merged.
