### ISSUE TITLE
Upgrading to servant-0.5:   Overlapping instances for Servant.API.ContentTypes.AllCTRender

### ISSUE THREAD

**Issue by ecognium** [haskell-servant/servant#421]
I am trying to port my `servant-0.4.*` project to 0.5 and I am not sure how to handle overlapping instance for Content Types. 

I used to have this for serving a dynamic blob (see https://github.com/haskell-servant/servant/issues/400) 

     instance Accept BLOB where
         contentType _ = "image" M.// "jpeg"
     
     instance MimeRender BLOB BlobFile where
         mimeRender _ = blobContent  
     
     instance {-# OVERLAPPING #-} (AllMimeRender xs BlobFile) => AllCTRender xs BlobFile where
       handleAcceptH _ _ (BlobFile h c) = Just (h, c)

I added the `(AllMimeRender xs BlobFile)` part for `servant-0.5`.  When I compile the above with `servant-0.5` I get this error: 

    Overlapping instances for Servant.API.ContentTypes.AllCTRender
                                '[BLOB] BlobFile
      arising from a use of ‘serve’
    Matching instances:
      instance [overlappable] Servant.API.ContentTypes.AllMimeRender
                                (ct : cts) a =>
                              Servant.API.ContentTypes.AllCTRender (ct : cts) a
        -- Defined in ‘Servant.API.ContentTypes’
      instance [overlapping] Servant.API.ContentTypes.AllMimeRender
                               xs BlobFile =>
                             Servant.API.ContentTypes.AllCTRender xs BlobFile
        -- Defined at src/JSON/JModels.hs:120:30
    In the expression: serve userAPI (readerServer cfg)
    In an equation for ‘app’:
        app cfg = serve userAPI (readerServer cfg)

This is how I am constructing the `Application`

     type AppM = ReaderT Config (ExceptT ServantErr IO)

     app :: Config -> Application
     app cfg = serve userAPI (readerServer cfg)
     
     readerServer :: Config -> Server API
     readerServer cfg = enter (readerToExcept cfg) server
     
     readerToExcept :: Config -> AppM :~> ExceptT ServantErr IO
     readerToExcept cfg = Nat $ \x -> runReaderT x cfg

**Note**:  If I remove the entire overlapping instance declaration for `AllCTRender`, my project compiles fine in `servant-0.5`.  Unfortunately, I need that declaration to serve dynamic blob files.

**Comment by soenkehahn** [comment]
Not 100% sure, but I think you shouldn't write the instance for `AllCTRender`. Just `Accept` and `MimeRender`. You say, if you remove the instance for `AllCTRender` it compiles. What is the actual error message when you do try to serve `Blobfile`s then?

**Comment by ecognium** [comment]
Hi @soenkehahn, The overlapping instance of `AllCTRender` works fine in `servant-0.4.*` but not in `0.5`.  Not sure what has changed in `0.5` that such an overlapping instance returns an error.  Maybe there is a different way to do this in `0.5` now?

The reason I need to create this overlapping instance is that I get documents from a third party service and all I get is `ByteString` and `Content-Type`. I have to pass this back to the client as-is. You can see my original question here: http://stackoverflow.com/questions/35636829/sending-generic-content-type-in-servant

> if you remove the instance for AllCTRender it compiles. What is the actual error message when you do try to serve Blobfiles then?

There is no error message, just that it will serve `image/jpeg` for everything, which is not correct. If I know it is an IMAGE or a PDF, I can generate types for those but all I get is a BLOB with content-type provided at runtime.

**Comment by ecognium** [comment]
I think I fixed the compile issue. I had to add the following to make it work:

    {-# LANGUAGE TypeOperators              #-}  
    {-# LANGUAGE DataKinds                    #-}  

I also had to change the instance definition to:

     instance {-# OVERLAPPING #-} (AllMimeRender (ct ': cts) BlobFile) => AllCTRender (ct ': cts) BlobFile where
       handleAcceptH _ _ (BlobFile h c) = Just (h, c)

I will close this issue once i am able to verify that I am getting the right content-type in the client.

**Comment by soenkehahn** [comment]
Ah, I think now I understand the issue better. You want to be able to dynamically set the `Content-Type` of the response depending on the value of the data (e.g. `ByteString`) you're sending. Is that correct?

If so, this is a use-case that isn't directly supported by `servant`. So I guess it was a bit coincidental that you managed to make that work in `servant-0.4` (kudos for that).

Hope you make it work with the new version too. I'd be interested to see the code, if you do.

**Comment by ecognium** [comment]
@soenkehahn: It took me a while to test the blob viewing functionality as we changed our document service. I have ported to the new backend and I can confirm that it now works with the updated overlapping instance definition. 

The credit goes to the person who answered my Stackoverflow question -- I just modified it to suit my needs :) 

The code is very simple:

     data BlobFile = BlobFile { blobHeader ::  LBS.ByteString, blobContent :: LBS.ByteString } deriving (Show, Generic)

The above defines the type for the blob I will receive. The service returns the ByteString along with the content-type. 

Then I define my `BLOB` type for `servant` and add the necessary MIME instances

     data BLOB
     
     instance Accept BLOB where
         contentType _ = "image" M.// "jpeg"
     
     instance MimeRender BLOB BlobFile where
         mimeRender _ = blobContent
     
     instance {-# OVERLAPPING #-} (AllMimeRender (ct ': cts) BlobFile) => AllCTRender (ct ': cts) BlobFile where
       handleAcceptH _ _ (BlobFile h c) = Just (h, c)

As you can see the `Accept` instance is there to satisfy `servant` but it gets overridden with the overlapping instance.   

My API is defined as:

       <|> "get-blob-file"      :> Capture "blobKey" BlobKey :> Get '[BLOB] BlobFile

When I get a request at `get-blob-file`, I connect to the backend, retrieve the ByteString and Content-Type. I populate my `BlobFile` type with this info. I then just return `BlobFile` from `servant`.

**Comment by soenkehahn** [comment]
@ecognium: Glad you worked it out.

One thing that I worry is that your app will not behave correctly when it comes to `Accept` headers. I guess that your handler only gets called if (and only if) the `Accept` header allows `image/jpeg`. But then the returned `content-type` can be something completely different.

- If the client sends e.g. `Accept: image/png`, `servant` will reject it. Even though the corresponding handler might return a `BlobFile` with `content-type: image/png`.
- If the client sends e.g. `Accept: image/jpeg`, `servant` will allow the request and call the handler, but it might return `content-type: image/png`, which the client doesn't want.

I'm not 100% sure whether this is how `servant` will behave. It depends on how `Accept` and `AllCTRender` are being used.

(And in practice this behavior might not be a problem at all, especially if you control the client.)

**Comment by ecognium** [comment]
@soenkehahn  Thanks. You are right that this hack is not ideal. In my case, since the response is dynamic the client does not just request the blob file with a specific Accept Header right away. 

The client first obtains a list of metadata available along with the blobKeys and then it requests the data based on the content-type.  For example, if it the metadata says it is an image, it will put the blobkey inside an `<img>` tag. If not, it may put the blob key inside `<a>`.
