### ISSUE TITLE
cannot install servant 5 

### ISSUE THREAD

**Issue by rwobben** [haskell-servant/servant#424]
Hello, 

I have this in my stack,yaml : 

    # This file was automatically generated by stack init
    # For more information, see: http://docs.haskellstack.org/en/stable/yaml_configuration/

    # Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
    resolver: lts-5.9

     # Local packages, usually specified by relative directory name
    packages:
    - '.'
    - location :
       git: git://github.com/haskell-servant/servant.git
       commit : a35aa161a67f52d93db2277858afe1f761df45bd
      extra-dep : true
      subdirs:
         - servant-blaze
        - servant-cassava
         - servant-client
         - servant-docs
         - servant-foreign
         - servant-js
         - servant-lucid
          - servant-mock
         - servant-server

    # Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
    extra-deps: []

    # Override default flag values for local packages and extra-deps
    flags: {}

    # Extra package databases containing global packages
    extra-package-dbs: []

    # Control whether we use the GHC we find on the path

    # system-ghc: true

    # Require a specific version of stack, using version ranges
    # require-stack-version: -any # Default
    # require-stack-version: >= 1.0.0

    # Override the architecture used by stack, especially useful on Windows 
    # arch: i386
    # arch: x86_64

    # Extra directories used by stack for building
    # extra-include-dirs: [/path/to/dir]
    # extra-lib-dirs: [/path/to/dir]

    # Allow a newer minor version of GHC than the snapshot specifies
    # compiler-check: newer-minor

And this is my .cabal file : 

    name:                paytime
    version:             0.1.0.0
    synopsis:            Initial project template from stack
    description:         Please see README.md
    homepage:            http://github.com/githubuser/paytime#readme
    license:             BSD3
    license-file:        LICENSE
    author:              Author name here
     maintainer:          example@example.com
     copyright:           2016 Author name here
     category:            Web
    build-type:          Simple
    -- extra-source-files:
    cabal-version:       >=1.10

    library
      hs-source-dirs:      src
      exposed-modules:     Lib
      build-depends:       base >= 4.7 && < 5
                                  , servant >= 5.0
      default-language:    Haskell2010

    executable paytime-exe
      hs-source-dirs:      app
      main-is:             Main.hs
      ghc-options:         -threaded -rtsopts -with-rtsopts=-N
      build-depends:       base
                                  , paytime
                                  , servant >= 5.0
      default-language:    Haskell2010

    test-suite paytime-test
      type:                exitcode-stdio-1.0
      hs-source-dirs:      test
      main-is:             Spec.hs
     build-depends:       base
                                , paytime
      ghc-options:         -threaded -rtsopts -with-rtsopts=-N
      default-language:    Haskell2010

    source-repository head
      type:     git
     location: https://github.com/githubuser/paytime

but when I do stack build or stack install servant ,there is no output at all.

What did I do wrong

**Comment by phadej** [comment]
It's servant `0.5` not `5.0`.

**Comment by rwobben** [comment]
Thanks, 

I changed it to servant >= 0.5 and see this error : 

    servant needed  (>=0.5) , 0.4.4.7 found (latest applicative is 0 5)
    needed for package

**Comment by phadej** [comment]
you forgot to list the `servant` (the base package) as a subdir. Still, more straightforward would be to use released version i.e. use

```yaml
extra-dep:
- servant-0.5
```

Stack reporting about the older version is usually because that version is found in Snapshot, as in this case. Note, that `servant-0.5` won't be in `lts-5`, and it probably will take some time until it's in `nightly` snapshots: https://github.com/fpco/stackage/issues/1290

**Comment by rwobben** [comment]
oke, so instead of the git stuff , add servant to the extra-deps ?

**Comment by rwobben** [comment]
Thanks, everything is working fine.
I can now experiment with the tutorial.
