### ISSUE TITLE
[servant-client-0.5] Altered encoding of `QueryParams` breaks API calls

### ISSUE THREAD

**Issue by fosskers** [haskell-servant/servant#426]
Hi, I'm wondering why `QueryParams` had its encoding changed from `arg[]=foo&arg[]=bar` to just `arg=foo&arg=bar`. An API that a library of mine calls expects the `arg[]` syntax, and returns limited results otherwise.

**Comment by fosskers** [comment]
I just rolled back to version 0.4, and for some reason I'm seeing the same behaviour.

**Comment by fosskers** [comment]
After more testing, it is definitely the difference between `arg` and `arg[]`. The tutorial for 0.4 says that `QueryParams` is precisely for this. 

Here is my `API`:

```haskell
type API = "rpc" :> QueryParam "v" String
	   :> QueryParam "type" String
	   :> QueryParams "arg" String
           :> Get '[JSON] Value
```

It was my assumption that `arg` here would automatically be expanded to `arg[]` when necessary.

**Comment by fosskers** [comment]
Fixed with this:

```haskell
type Info = "rpc" :> QueryParam "v" String
           :> QueryParam "type" String
           :> QueryParams "arg[]" String
           :> Get '[JSON] RPCResp

type Search = "rpc" :> QueryParam "v" String
           :> QueryParam "type" String
           :> QueryParam "arg" String
           :> Get '[JSON] RPCResp

type API = Info :<|> Search
```

**Comment by soenkehahn** [comment]
There's multiple ways to encode multiple query params by the same name. I've seen at least the following:

- `/?foo=a&foo=b`
- `/?foo[]=a&foo[]=b`

AFAIU there's not one right way to do it. And while `servant-server` can accept both variants as valid requests, `servant-client` has to pick one. IIRC `servant-client` always used the first variant. Are you sure this changed at some point?

**Comment by fosskers** [comment]
I suppose it didn't, because when I rolled back to 0.4, the problem was still there. I ended up using two sub-APIs as shown above.
