### ISSUE TITLE
Question : Can I have these url scheme 

### ISSUE THREAD

**Issue by rwobben** [haskell-servant/servant#431]
Hello,

I like to develop a accounting package in Servanr .

I like to have a url schema like this ;

/ accounts                                             to see all accounts
/account/accountname                           to see the data of a particular account.
./account/subaccount                             to see all subaccounts
/account/subaccount/accountname          to see all the data of a paricular subaccount. 

Is this possible and if so. how do I do this ?

**Comment by freezeboy** [comment]
you just need to declare an Api like:

``` haskell
type AccountAPI = "accounts" :> Get '[JSON] [Account]
     :<|> "account" :> Capture "accountName" String :> Get '[JSON] [AccountDetails]
     :<|> "account" :> "subaccounts" :> Get '[JSON] [SubAccount]
     :<|> "account" :> Capture "accountName" String :> Get '[JSON] [SubAccountDetails]
```

Then, define what you call Account, AccountDetails, SubAccount, SubAccountDetails

and use -server or -client to implement the service / consuming parts

**Comment by rwobben** [comment]
Thanks, 

That could be using a function like this : 

allPersons :: AppM [Person]
allPersons = do
    users <- runDb $ selectList [] []
    let people = map (\(Entity _ y) -> userToPerson y) users
    return people

**Comment by freezeboy** [comment]
yes
