### ISSUE TITLE
Question: Is this a good order for the tutorials on github

### ISSUE THREAD

**Issue by ghost** [haskell-servant/servant#433]
I like to try this tutorial :https://github.com/haskell-servant/servant/blob/master/doc/tutorial/Authentication.lhs
is it enought to do this one first : https://github.com/haskell-servant/servant/blob/master/doc/tutorial/Server.lhs

**Comment by arianvp** [comment]
Just try and see. If you get stuck or don't understand certain things. Feel free to join us in our IRC channel #servant  on Freenode. We can help you with any questions you might have.

Is it okay if I close this issue for now?
