### ISSUE TITLE
Raw gobbles up auth-protected endpoint?

### ISSUE THREAD

**Issue by 3noch** [haskell-servant/servant#440]
Using the tutorial, if I have this API:

```haskell
type Api = "users" :> BasicAuth "here" Bool :> Get '[JSON] [User]
```

Everything works as expected when browsing with my browser. It asks for creds.

However,

```haskell
type Api = "users" :> BasicAuth "here" Bool :> Get '[JSON] [User] :<|> Raw
```
(and serving a local directory) makes it impossible for me to visit the "users" endpoint. I get `404 File not found`.

Am I doing something wrong?

**Comment by 3noch** [comment]
With much more experimentation, I'm fairly confident this is a problem. Basically, if the basic auth header is not present, the routing skips to the `Raw` handler instead of responding with a `WWW-Authenticate` header.

If I add a path before `Raw` and rerun the server, the browser gives me a prompt (presumably because it saw a `WWW-Authenticate` header. Once I enter the right credentials, I can actually change the server back and rerun it and the authenticated URL will work because the browser caches the Basic auth header!

**Comment by 3noch** [comment]
@alpmestan @aaronlevin @arianvp Can anyone confirm? This seems like a somewhat serious problem and it's certainly non-intuitive.

**Comment by soenkehahn** [comment]
I think this is a bug in the basic auth implementation. I'm working on a PR.

**Comment by 3noch** [comment]
@soenkehahn Oh, wow. That was fast. Excellent! I'm sort of maybe giving a talk on servant in two days...and it's hard to give a talk when I can't get it to work! 😛

**Comment by jjmornim** [comment]
If I have a domain which is available with and without "www" and I want to setup a redirect from "without www" to "with www", is it possible to check whether a request comes from with or without "www", does Servant have access to such information? Or is Warp/wai only capable to do so? I'm using them both Servant and Warp/wai in my application.

**Comment by soenkehahn** [comment]
AFAIK this usually works through the `Host` header. I'm not sure if that header is being passed into `servant` as a normal header field though, because `wai` has `requestHeaderHost` for this. If it is passed in normally, you can access it with the `Header` combinator, but then it'll also show up in the API type, which is probably not what you want. So I'd go with `wai` for this.

**Comment by jjmornim** [comment]
Thanks.
