### ISSUE TITLE
Missing ReflectMethod instances?

### ISSUE THREAD

**Issue by gibiansky** [haskell-servant/servant#443]
In `servant-0.6` there is a `ReflectMethod` class that converts from `StdMethod` to `http-types` `Method`. It has instances for PATCH, DELETE, PUT, HEAD, GET, POST, but none of the other `StdMethod` constructors. Is there a reason for this, or is this an oversight? 

I would like Servant to export the same API for all the HTTP methods, so IMHO the `ReflectMethod` instances should be added.

**Comment by gibiansky** [comment]
Implemented this in #444

**Comment by jkarni** [comment]
Closed with #444
