### ISSUE TITLE
State monad is not shared between endpoints.

### ISSUE THREAD

**Issue by leohahn** [haskell-servant/servant#458]
I am using this monad:

```
type LoggedUsers = Map.Map Int (PG.Entity M.DUser)
type AppM = ReaderT Config (StateT LoggedUsers (ExceptT ServantErr IO))
```
The purpose is to maintain a in-memory map of the current logged in users. In a `/login` endpoint, I set the state, and after setting the state I would like to reuse this state from other endpoints. Turns out that the state is always the initial one after each request. 

- Is this supposed to be the correct behaviour?

**Comment by 3noch** [comment]
Where are you initializing your monad stack?

**Comment by leohahn** [comment]
I don't know exactly what you mean. But I think I initialize it with the enter function.
```
readerToExcept :: Config -> AppM :~> ExceptT ServantErr IO
readerToExcept cfg =
  Nat $ \appm -> evalStateT (runReaderT appm cfg) Map.empty

readerServer :: Config -> Server API'
readerServer cfg = enter (readerToExcept cfg) server
              :<|> serveDirectory "resources/public"
```
In this case it starts empty.

**Comment by 3noch** [comment]
That's what I thought. I'm hoping someone more knowledgeable can confirm, but I'm pretty sure `enter` gets run for each request so your state will be reinitialized for each request. In order to share your state you'd have to run the entire server from within a `StateT` monad which I doubt is possible (because you'd have to lift the call to `run` into `IO` anyway). There is no way for the resulting state of one request to feed into the next. My guess is that you'll need to use `IORef` or `MVar` to share a mutable state in your `ReaderT Config`. You could still run your handlers within a `StateT` but you'd need to initialize each run with the "global" state and then update it once the request was handled.

**Comment by leohahn** [comment]
I guess I will wait for a tutorial then. I am still learning haskell, and this is starting to become complicated.

**Comment by 3noch** [comment]
@leohahn Whoa, you got into some deep stuff really fast! (Servant isn't exactly easiest choice for a beginner.) Here's the easiest way to get you off the ground:

1. Get rid of `StateT`.
2. Add a new member to your `Config` like so:

```haskell
type State = Map.Map Int (PG.Entity M.DUser)

data Config = Config { ..., myState :: TVar State }
```

3. In main, initialize your `Config` by setting up a new state:

```haskell

main = do
    state <- atomically $ newTVar Map.empty
    let config = Config { ..., myState = state }
   -- Run your app like normal
```

4. In your handlers, access this state like this:

```haskell
handler = do
    Config{myState = state} <- ask
    result <- atomically $ do
        currentValue <- readTVar state
        doSomthingInteresting
        writeTVar newState
    return response
```

This is using the `STM` machinery to gain thread-safe mutation. You could also use `MVar`s with a similar effect.

It's possible to use your `StateT` setup by combining this tactic with some shenanigans in `enter`, but this is easier.

**Comment by leohahn** [comment]
Haha, I picked Servant because I saw a video and it looked cool. It is also nice when you have something challenging to learn.
 
Thanks for the reply though, I will give it a go trying to implement that.

**Comment by 3noch** [comment]
@leohahn: It *is* cool! I guess it depends on how far along "still learning Haskell" you are. I think we're all "still learning Haskell". ;)

You might want to checkout [stm-containers](https://hackage.haskell.org/package/stm-containers-0.2.10/docs/STMContainers-Map.html) for better performing `Map` type within the `STM` context.

**Comment by 3noch** [comment]
BTW, seems like you've gotten pretty far.

**Comment by leohahn** [comment]
Yeah. When I said beginner I meant: "I finally understood Monads Transformers this week". So I guess the term is relative. I think I will keep saying that term for a while, because there is always something new to learn, haha. That is why I love the language.

Thanks for the tip! :)

**Comment by leohahn** [comment]
Yes, If I manage to do it, I will write something on github, maybe it helps other people.

**Comment by alpmestan** [comment]
Indeed, running handlers in `StateT` doesn't make them share the state.

Imagine two clients hitting different endpoints at the same time, with both endpoints accessing and modifying the state. What should the resulting state be after the two clients are done? Updates of the first then updates of the second endpoint? The reverse? A bit of both interleaved? Given that there's no right answer (unless the said updates "commute", i.e the order in which you perform them doesn't matter, you always end up in the same final state), if you really want to have shared state between handlers, you have to use some concurrency-friendly shared variable abstraction (MVar, STM, ...).

**Comment by arianvp** [comment]
Shall we close this issue then?  Maybe we can put an example of shared state in the tutorial with STM. As it's a question that comes up quite a lot.

**Comment by alpmestan** [comment]
Yeah. I've also been thinking about using the github wiki to group some useful combinators that are not in servant, provide links to open-source projects that use servant, and give various tips and tricks that don't really fit into the tutorial.

**Comment by leohahn** [comment]
I think it would be a good idea, since it is a common use case.

**Comment by soenkehahn** [comment]
This could also be put into the `doc` directory, e.g. into a new chapter outside of the tutorial. Wiki seems also fine to me though.

**Comment by soenkehahn** [comment]
@leohahn: Can this issue be closed then?

**Comment by leohahn** [comment]
Oops, sure.
