### ISSUE TITLE
Rename ClientM to Client

### ISSUE THREAD

**Issue by 3noch** [haskell-servant/servant#467]
In #434 we added an alias called `Handler` for `ExceptT ServantErr IO`. We already have a similar client-side alias called `ClientM`. It seemed people agreed we should change `ClientM` to `Client` to be consistent with `Handler`.

**Comment by soenkehahn** [comment]
IIRC there was a consensus that `ClientM` should be renamed to something better.

`Client` doesn't really work, because we already have the type family `Client`.

**Comment by jkarni** [comment]
Are there any concrete proposals, given that `Client` doesn't work, or should we close this?

**Comment by 3noch** [comment]
1. `Requester`
2. `ClientApp`
3. `WebClient`

**Comment by soenkehahn** [comment]
I'd like to throw in `ClientAction` and `ClientCommand`. Generally I'm very un-opinionated about this. I'd be fine with closing this too.

**Comment by jkarni** [comment]
I myself prefer `ClientM`, but also don't have strong opinions.

**Comment by jkarni** [comment]
`ClientM` is actually a monad now - should we close?

**Comment by fizruk** [comment]
Closing this, feel free to reopen if I missed something.
