### ISSUE TITLE
How to deploy Servant on a server?

### ISSUE THREAD

**Issue by taakazazzz** [haskell-servant/servant#469]
I haven't found any information about the following topic. 

How can I deploy a servant 0.5 application on a server, is it enough to compile it locally and then run the executable file on a server as an ordinary executable file? Or should I compile it on a server? And should I use nginx or apache or, again, just run the executable file as-is?

**Comment by alpmestan** [comment]
If you compile the application by linking everything statically (which is done by default), then you can just copy the executable on your server and launch it there. Note that this is not specific to `servant` and is true of any program compiled with GHC. People sometimes use nginx or some other HTTP server as a proxy for various reasons (port forwarding, SSL termination, load balancing, ...), but again nothing servant specific here. It's true though that we do not have any documentation about this, but anything you'll see about Yesod, Snap and other frameworks regarding deployment will apply just fine to a servant application.

Feel free to ask for more information if that doesn't really answer your questions.

**Comment by jjmornim** [comment]
Is it a recommended and good enough approach to just copy an executable file to a server and run it?  Or does it depend on traffic? I'm thinking of running it as an executable file first and then, maybe, I'll add nginx there.

**Comment by freezeboy** [comment]
If is runs in an internal network, with a average load, I think the basic binary can do the job, in an open environment (public ip/API), I would personnally add an nginx/apache/varnish brick in front to benefit from all the security/monitoring/caching features that are easily enabled

**Comment by soenkehahn** [comment]
Generally Haskell web apps using `warp` are meant to be running in their own, stand-alone process. You can put `apache` or `nginx` in front of them, but you don't need to to use them. This is different from e.g. python or php. There are other good reasons to use e.g. `nginx` -- @alpmestan pointed some out -- but as long as you don't need any functionality from `nginx` there's no strong reason to add it.

One note about scaling: Haskell (and `warp`) scale up very well inside one process. So having more than one process running on the same machine behind a load balancer is not likely to give you better throughput. Only if the processes are running on different machines, you would see an increase in throughput.

Some very general advice:
- Solve the problem at hand. I imagine at this stage you don't have problems with traffic. So defer that until later.
- Consider using some form of configuration management.

**Comment by jjmornim** [comment]
Thank you.

**Comment by jjmornim** [comment]
Also I'm planning on installing ssl certificate.  Will I have to change the code of my app somehow to make it work? Does a Servant app know if it's running as http or https application?

**Comment by alpmestan** [comment]
A servant app doesn't care whether it's running over HTTP or HTTPS. It's only when you actually run the app with warp (or warp-tls, but the most recent warp includes support for HTTP2 which supports TLS, if I understand correctly) that this matters.

**Comment by freezeboy** [comment]
Either you handle SSL from the nginx/* reverse proxy, or simply use warp-tls's runTLS instead of run (from warp)

**Comment by alexanderkjeldaas** [comment]
@jjmornim I've created https://github.com/commercialhaskell/stack-templates/blob/master/servant-docker.hsfiles which is a stack template with nginx as a front-end, automatic ssl certificate generation, and running in docker, so you can easily deploy it in production.

A reasonable setup is to have nginx do the SSL termination and use HTTP from warp.

In most cases you will want a load balancer in front of warp, whether it is Amazon ELB, GCE load balancer or nginx.  This is so you can upgrade, have canary traffic, add backends, handle DoS, and do load shedding.  It doesn't matter whether warp is "good enough" - if the processing it does is heavier than what a load balancer does, you want a load balancer with spare CPU to be able to deal with the above issues.

IMO of course :-)

**Comment by jjmornim** [comment]
Thanks.

**Comment by jjmornim** [comment]
Thanks.

**Comment by arianvp** [comment]
I'l close this for now then.

**Comment by 3noch** [comment]
I'll just throw this resource into the mix. It's nice for deployment. You can combine it with much of the other advice here: https://github.com/snoyberg/keter

**Comment by jwaldmann** [comment]
Re: keter. Yes. I found that `keter` also has ` - type: background` for applications where keter does the deployment (watch the incoming dir, and the running process) but not the proxying. I am using this for a local servant process (client is on the same machine)
