### ISSUE TITLE
an isCompatibleWith property for servant-comock

### ISSUE THREAD

**Issue by arianvp** [haskell-servant/servant#480]
the `isCompatibleWith` function would do the following for two APIs `V1` and `V2`

* Check if all routes in `V1` still exist in `V2`
* Check if those routes behave the same in `V2` as in `V1`

It would allow for setting up quick fuzz tests to check if API compatibility isn't broken

**Comment by jkarni** [comment]
Neat idea, and very easy to implement!

**Comment by jkarni** [comment]
Closing since `-comock` related stuff won't live in this repo (but thanks!)
