### ISSUE TITLE
[servant-client] Force ipv4?

### ISSUE THREAD

**Issue by fosskers** [haskell-servant/servant#486]
For myself and many of my users, we're finding that requests made to a certain API via IPV6 almost always time out. However, if you force the same call via ipv4 via curl, etc, it always succeeds:

```
curl -6 "https://aur.archlinux.org/rpc?v=5&type=search&arg=foobar"  # Times out most times
curl -4 "https://aur.archlinux.org/rpc?v=5&type=search&arg=foobar"  # Always succeeds
```
Is there a way to force ipv4 use with `servant-client`? Or is that the purview of lower libraries?

**Comment by phadej** [comment]
The recent version of `servant-client` take a `Manager`. It can be constructed with a manual connection creation function: http://haddock.stackage.org/lts-5.14/http-client-0.4.28/Network-HTTP-Client.html#t:ManagerSettings, by tweaking that one, I guess it's possible to force IPV4.

**Comment by fosskers** [comment]
https://github.com/vincenthz/hs-connection/issues/18

**Comment by phadej** [comment]
@fosskers Most likely you want to fork the implementation of https://github.com/snoyberg/http-client/blob/10ec467c5acc47277c6598d1732a2a51f6d70a11/http-client/Network/HTTP/Client/Connection.hs#L156, which uses primitives from http://haddock.stackage.org/lts-5.13/network-2.6.2.1/Network-Socket.html 

Unfortunately I don't remember low-level details, so I don't know what exactly you have to do to force IPV4. Yet the API is very close to C, so you'll probably find info by googling.

**Comment by fosskers** [comment]
Odd, I'm not seeing that module used by `http-client-tls`. The goal is to alter the IP settings through `tlsManagerSettings`, which seems to be using `Network.Connection` from the old `connection` package.

**Comment by 3noch** [comment]
It's a hack, but you could also look up the IP for that domain first and then specifically make the request to the IPv4 host.

**Comment by joshproehl** [comment]
I still haven't had any error trying to `curl -6` aur, works perfectly every time. If IPv6 is still suspected as an issue I'm happy to disable my IPv6 tunnel and see if the issue persists via ipv4 only. Like I said, haven't seen a failure yet though on the manual attempts.

**Comment by fosskers** [comment]
@3noch That isn't a terrible idea in the interim.

**Comment by fosskers** [comment]
Odd, when inspecting the IP of `aur.archlinux.org` through firefox, I see: 5.9.250.164

If you reenter that IP in your search bar, it resolves to `bbs.archlinux.org`.

**Comment by soenkehahn** [comment]
Both domains are probably hosted on the same IP address which resolves what to serve based on the `Host` header (`aur.archlinux.org` or `bbs.archlinux.org`).

**Comment by jkarni** [comment]
I don't think there's much we can do in `servant-client` about this - the fix would have to come in `http-client` or further down. Sorry!

**Comment by fosskers** [comment]
No problem, thanks.
