### ISSUE TITLE
Minor notes about the official tutorial

### ISSUE THREAD

**Issue by mrkkrp** [haskell-servant/servant#487]
I'm not sure, but here:

https://haskell-servant.readthedocs.io/en/stable/tutorial/Server.html#case-studies-servant-blaze-and-servant-lucid

the tutorial says we need:

```haskell
type PersonAPI = "persons" :> Get '[JSON, HTMLLucid] [Person]
```

With version 0.7 of `servant` (and companion packages) this does not seem to work, it should be:

```haskell
type PersonAPI = "persons" :> Get '[JSON, HTML] [Person]
```

…and we also need the following import (at least for `lucid`):

```haskell
import Servant.HTML.Lucid
```

----

Also, numeration of `app`s (`app2`, `app3`) is confusing (IMO):

```haskell
people :: [Person]
people =
  [ Person "Isaac"  "Newton"
  , Person "Albert" "Einstein"
  ]

personAPI :: Proxy PersonAPI
personAPI = Proxy

server4 :: Server PersonAPI
server4 = return people

app2 :: Application
app2 = serve personAPI server4
```

Would it be OK if application for `server4` would be `app4` and so forth? (I was defining an app per server anyway while working through the tutorial.)

**Comment by jkarni** [comment]
Right. I think we called it `HTMLLucid` in the tutorial because it's a literate file, and because it makes clear that `Servant.HTML.Lucid.HTML` and `Servant.HTML.Blaze.HTML` are distinct. There's a note in the tutorial:

```haskell
-- For this tutorial to compile 'HTMLLucid' and 'HTMLBlaze' have to be
-- distinct. Usually you would stick to one html rendering library and then
-- you can go with one 'HTML' type.

```
But if you can think of a more confusing way of doing this, it'd be much appreciated!

> Would it be OK if application for server4 would be app4 and so forth? (I was defining an app per server anyway while working through the tutorial.)

That sounds reasonable.

**Comment by mrkkrp** [comment]
Oh, I somehow missed that comment about `HTMLLucid` and `HTMLBlaze` (maybe because I used `lucid` and this is in `blaze`-related section).

**Comment by jkarni** [comment]
If you have any suggestion about how to make this clear, they'd be very welcome. Otherwise, should we close this?

**Comment by mrkkrp** [comment]
I could probably propose something, but right now I don't have much time. Let's close for now, maybe I'll come up with a PR later.
