### ISSUE TITLE
0.7.1 release

### ISSUE THREAD

**Issue by arianvp** [haskell-servant/servant#490]
https://github.com/haskell-servant/servant/issues/488 is already resolved in master and is holding back a release on Stackage.  There are not any major breaking changes in master currently, so I think we can create a minor version bump release.

**Comment by arianvp** [comment]
@haskell-servant/maintainers I haven't gone through the process of a release yet (upload to hackage etc) so if someone could guide me through that'd be great.

**Comment by soenkehahn** [comment]
@arianvp: I'd be happy to show you how to do a release. Feel free to ping me on irc. (I'll be online today for most of the day, probably.)

I can also release `0.7.1` myself if we don't manage to do this together in the coming days. However, I think it would be great if there were more people who know how to do it.

**Comment by jkarni** [comment]
Done
