### ISSUE TITLE
hackage doc points to the wrong website

### ISSUE THREAD

**Issue by rvion** [haskell-servant/servant#494]
https://hackage.haskell.org/package/servant-docs points to http://haskell-servant.github.io/ instead of http://haskell-servant.readthedocs.io/en/stable/

**Comment by soenkehahn** [comment]
This is fixed in `master`. (Should I leave this open until released to hackage?)

**Comment by rvion** [comment]
oups, didn't see, thanks.
let I close it now not to pollute the tracker
