### ISSUE TITLE
Typesafe error types

### ISSUE THREAD

**Issue by dredozubov** [haskell-servant/servant#500]
I don't know if it was discussed before, but here's my five cents.

Errors are currently produced by the `ServantErr` record and it would be nice to parametrize it with and error type(and possibly type-level http codes with `Nat`!) to expose them in an API types:

```
-- `body` could be constrained by something like `ConformsTo contentType body`
data ServantErr httpCodes body = ServantErr
   { errHTTPCode :: httpCodes
   , errReasonPhrase :: String
   , errBody :: body
   , errHeaders :: [HTTP.Header]
   }
```

I think it makes a lot of sense, because you can have nice structured errors this way(imagine you have some validation errors which result in the nested json structure). Of course it'll be necessary to add some type-level combinators to make this kind of declarations. For those of you who'll think "just use a sum type for the result API type" - i don't think it captures the http semantics well. You'll have to answer with a error and http code 200 OK this way.

It'll force the changes in one of the two directions: 
1. Handlers will return a sum type `ExceptT (ServantErr ErrorTypeExample) IO ResultType`
2. It'll have to run in a slightly different monad

 But if it comes this way, it'll be possible to infer all possible(tbh except the parse errors) http codes and error types from the API type.

**Comment by dredozubov** [comment]
found this afterwards https://github.com/haskell-servant/servant/issues/349

**Comment by jkarni** [comment]
If we can have API-type syntax that everyone agrees on and isn't too onerous, I'm all for this.

**Comment by jkarni** [comment]
Closing and copying your original comment to #349.
