### ISSUE TITLE
Shouldn't  `MkLink (Verb m s ct a) = Link`  ?

### ISSUE THREAD

**Issue by vwwv** [haskell-servant/servant#527]
Sorry if I'm missing something obvious, but shouldn't it ?

The type `Link` is opaque making it safe, but none of the base cases produce it (the 2 base cases, yield `URI` instead). Again sorry if I'm missing something obvious, but wouldn't this make the `Link` type unusable ?

Is there a reason it is not implemented like: 

``` haskell
instance HasLink (Verb m s ct a) where
    type MkLink (Verb m s ct a) = Link
    toLink = id
```

?

**Comment by jkarni** [comment]
@vwwv yes, nice catch.

**Comment by vwwv** [comment]
Ok, then, (unless somebody do it first) once I have some minutes for it, I'll write a PR for this change, I might to change some code elsewhere to pass the tests as this change the type (Haven't read the test code yet).
