### ISSUE TITLE
Write TechEmpower benchmarks

### ISSUE THREAD

**Issue by phadej** [haskell-servant/servant#529]
at least
- Test type 1: JSON serialization
- Test type 6: Plaintext
should be trivial to do, would be good to have `servant` mentioned there.

https://www.techempower.com/benchmarks/#section=code

**Comment by jkarni** [comment]
Initial work here: https://github.com/haskell-servant/FrameworkBenchmarks/commit/5f31b5293ffd434ff4817fc7d7705a2ff3e51af8

**Comment by 3noch** [comment]
Please tell me we're doing better than "snap" and "wai" on that benchmark! 😫

**Comment by kosmikus** [comment]
In theory, it should be impossibe to do better than wai, because servant builds on wai. But I don't know much about the benchmark and have no idea how good the wai benchmark code is.

**Comment by 3noch** [comment]
"wai" really should be called "Warp"...but I don't think their benchmark is good or well tuned.

**Comment by jkarni** [comment]
`wai` is doing great! It just doesn't happen to have more than plaintext and JSON, I think.

**Comment by 3noch** [comment]
Maybe that's the problem I'm thinking of then.

**Comment by jkarni** [comment]
@kosmikus are you getting round 13 numbers by running the VM yourself? I only see up to 12 on the site.

**Comment by kosmikus** [comment]
@jkarni It was a mistake. I've edited my comment.

**Comment by jkarni** [comment]
http://termbin.com/1fno for benchmark results compared with some other frameworks on the first test. (I ran this on a pretty quiet dedicated server, so it should be acceptably reliable.) `wai` beating `openresty`, which is impressive, though to be fair that particular benchmark skews in our favour.

**Comment by jkarni** [comment]
http://termbin.com/q51l for the second test. I'm pretty happy with the results for that too.

**Comment by jkarni** [comment]
http://termbin.com/8tqc for the third. Ahead of all except `openresty` again, though `openresty` and `compojure` didn't do that well on this on round 12 (but erhaps the code has been updated). I'll run it against some more frameworks to check.

**Comment by jkarni** [comment]
http://termbin.com/dq6l for the 6th test (plaintext). `servant` is behind `openresty` and `wai`, and ahead of all others (`snap`, `spock`, `compojure`, `nodejs`, `flask`, `django`) as usual, and the results would seem good, except that the `wai` results are almost an order of magnitude better (indeed, 5 times better than `openresty`, which is pretty amazing), so there might be room for improvement.

**Comment by jkarni** [comment]
For fortune (4th test):
http://termbin.com/f0jb for servant, http://termbin.com/wgo9 for everything else (I screwed up a little in the testing commands). `servant` is kicking ass. One more test to go.

As soon as the last test passes CI, I'm going to do a full run (all tests) with a number of frameworks, and make it slightly easier to read than long JSON. What would people like to see? At least:

- servant
- snap
- spock
- wai (for what's available)
- openresty
- django
- elixir-cowboy
- flask
- rails
- finch
- phoenix

**Comment by phadej** [comment]
Is there some scala frameworks, e.g. Scalatra and Play2?

**Comment by srhb** [comment]
You can filter by language:

https://www.techempower.com/benchmarks/#section=data-r12&hw=peak&test=plaintext&l=6bk

The source repository is grouped by language:

https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Scala

**Comment by codedmart** [comment]
What about nodejs (express, hapi) if available. Express is the most popular. 

Thanks!

--
Brandon Martin

**Comment by codedmart** [comment]
Sorry just saw nodejs in the list.

**Comment by jkarni** [comment]
servant on all tests: http://termbin.com/wvtl
everything else on all tests: http://termbin.com/si0s

(I keep forgetting to run with the appropriate flags, so the benchmark refuses to run `servant` together with the rest because of left-over test results).

In short, `servant` is doing great. `openresty` beats it on all tests, but that's no embarrassment. `undertow` beats in `json`, `go` beats it in `query`, and `wai` beats in the tests that it implements, but `servant` is ahead of every other framework tested. 

I haven't yet profiled the code or tried optimizing it, but I think I'm happy enough to send a PR already, and more PRs with optimizations if I or anyone else comes up with them.

**Comment by jkarni** [comment]
https://github.com/TechEmpower/FrameworkBenchmarks/pull/2138 <- closing this.

**Comment by soenkehahn** [comment]
Very nice!

**Comment by jkarni** [comment]
Some improvements to `plaintext`: http://termbin.com/cqcd

**Comment by flip111** [comment]
> Some improvements to plaintext: http://termbin.com/cqcd

@jkarni this page does no longer exist

I tried upgrading the benchmark to lts-10.0 see https://github.com/TechEmpower/FrameworkBenchmarks/pull/3153 compilation went fine but i ran into the following problems:

```
Accessing URL http://TFB-server:7041/db:
  Response (trimmed to 40 bytes): ""
   FAIL for http://TFB-server:7041/db

     Empty response
     See http://frameworkbenchmarks.readthedocs.org/en/latest/Project-Information/Framework-Tests/#specific-test-requirements
```

```
Accessing URL http://TFB-server:7041/queries?queries=:
  Response (trimmed to 40 bytes): "Error parsing query parameter queries fa"
   FAIL for http://TFB-server:7041/queries?queries=2

     Empty response
     See http://frameworkbenchmarks.readthedocs.org/en/latest/Project-Information/Framework-Tests/#specific-test-requirements
```

```
   FAIL for http://TFB-server:7041/queries?queries=0

     Empty response
     See http://frameworkbenchmarks.readthedocs.org/en/latest/Project-Information/Framework-Tests/#specific-test-requirements
```

```
   FAIL for http://TFB-server:7041/queries?queries=foo

     Invalid JSON: No JSON object could be decoded
     See http://frameworkbenchmarks.readthedocs.org/en/latest/Project-Information/Framework-Tests/#specific-test-requirements
```

```
   FAIL for http://TFB-server:7041/queries?queries=501

     Empty response
     See http://frameworkbenchmarks.readthedocs.org/en/latest/Project-Information/Framework-Tests/#specific-test-requirements
```

```
   FAIL for http://TFB-server:7041/queries?queries=

     Invalid JSON: No JSON object could be decoded
     See http://frameworkbenchmarks.readthedocs.org/en/latest/Project-Information/Framework-Tests/#specific-test-requirements
```

These are the failures i get on my own laptop. Travis also shows failures https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/319339929
