### ISSUE TITLE
unix sockets

### ISSUE THREAD

**Issue by legrostdg** [haskell-servant/servant#537]
Is there a way I could use unix sockets with servant? I'm developing a server/cli client application and I was wondering if it was possible...

**Comment by freezeboy** [comment]
Thanks to warp, it looks easily doable yes:

http://stackoverflow.com/questions/22621623/warp-binding-to-unix-domain-sockets#22621624

**Comment by legrostdg** [comment]
I've seen that, but I didn't see how to adapt client code, which seems to need a BaseUrl...

**Comment by arianvp** [comment]
For the client the answer is currently no afaik.

**Comment by legrostdg** [comment]
consider this bug a feature request :-)

**Comment by phadej** [comment]
In theory `http-client` could parse `unix://` scheme, but I'm not sure about the practical things...

**Comment by arianvp** [comment]
maybe related discussion : https://curl.haxx.se/mail/lib-2008-04/0279.html

**Comment by phadej** [comment]
so `curl`, the command line tool uses
```
curl --unix-socket /var/run/docker.sock http://example.com/images/json
```

**Comment by phadej** [comment]
... which got me think, so i found:
[`v:managerRawConnection`](http://hackage.haskell.org/package/http-client-0.5.0/docs/Network-HTTP-Client.html#v:managerRawConnection), which you can use to open unix sockets. And as now you can specify your own `Manager` to `servant-client`, I guess this is solved cons example.

**Comment by legrostdg** [comment]
how do you get a Manager from managerRawConnection?

**Comment by phadej** [comment]
@legrostdg read the tutorial part about the client: http://haskell-servant.readthedocs.io/en/stable/tutorial/Client.html

```hs

position :: Manager -> BaseUrl -> ExceptT ServantError IO Position
position :<|> ... = client api

run :: IO ()
run = do
  manager <- newManager defaultManagerSettings {
  	managerRawConnection = createUnixConnection
  }
  res <- runExceptT (queries manager (BaseUrl Http "localhost" 8081 ""))
  case res of
    Left err -> putStrLn $ "Error: " ++ show err
    Right pos -> print pos

createUnixConnection :: IO (Maybe NS.HostAddress -> String -> Int -> IO Connection)
createUnixConnection = -- default definition is: return $ openSocketConnection (const $ return ())
```

See: [`Connection`](http://hackage.haskell.org/package/http-client-0.5.0/docs/Network-HTTP-Client-Internal.html#t:Connection)

for starting points how to implement unix-socket `Connection`.

`http-streams` knows how to work with unix sockets, the implementation could be adopted: https://hackage.haskell.org/package/http-streams-0.8.3.3/docs/src/Network-Http-Connection.html#openConnectionUnix

**Comment by phadej** [comment]
I put together a quick example, seems to work, but I give no guarantees:
https://gist.github.com/phadej/b78d95b4107e4828119f33cebf38912f

**Comment by arianvp** [comment]
Can we close this @legrostdg ?

**Comment by linventifatelier** [comment]
@phadej thanks a lot for the gist, it was useful :)

I'm still unsure about how to connect servant-client with your gist, though...

> 
 res <- runExceptT (queries manager (BaseUrl Http "localhost" 8081 ""))

this `BaseUrl Http "localhost" 8081 ""` does not seem right, does it?

**Comment by phadej** [comment]
why not? port is probably unused, but the server is still free to use `Host: ` header to do stuff (not that `warp` does, but it could).

**Comment by alpmestan** [comment]
Could we stick the example app somewhere? In case someone else needs this in the future, we really should make it easy for people to find out about this.

**Comment by phadej** [comment]
@alpmestan I'm planning to write not-very-complicated daemon & console client. I need something like that at work, and it's not much of additional effort to package the core as a demo repository.

**Comment by alpmestan** [comment]
Great, keep us posted! Thanks

**Comment by soenkehahn** [comment]
I'll close this as the initial problem seems to be solved.
