### ISSUE TITLE
How BasicAuthCheck is supposed to be useful?

### ISSUE THREAD

**Issue by mrkkrp** [haskell-servant/servant#540]
[The definition](https://www.stackage.org/haddock/nightly-2016-07-07/servant-server-0.7.1/Servant-Server.html#t:BasicAuthCheck) of `BasicAuthCheck`:

```haskell
-- | Datatype wrapping a function used to check authentication.
newtype BasicAuthCheck usr = BasicAuthCheck
  { unBasicAuthCheck :: BasicAuthData
                     -> IO (BasicAuthResult usr)
  }
  deriving (Generic, Typeable, Functor)
```

This means that the check can be only in `IO` monad, which is not realistic at all. For example, I have a connection pool to access my database. This means that in this check I want to have access to that connection pool (at least). Or else I need to use some ugly hack (because with this type I need to hardcode things anyway) and open new connection on every request.

How `BasicAuthCheck` is supposed to be useful? Should it be used in any real project or it's there just for demo purposes and I should use something else (that works)?

**Comment by mrkkrp** [comment]
Resolved this by adding `Connection Pool` argument to `authCheck` and partiall applying it when starting the app, this seems to be the only way.

**Comment by arianvp** [comment]
I agree that parameterizing it further would be prettier

**Comment by jkarni** [comment]
> Resolved this by adding Connection Pool argument to authCheck and partially applying it when starting the app, this seems to be the only way.

That's how it's intended to be used. Can you explain a bit more why that is unsatisfactory?

**Comment by mrkkrp** [comment]
I just somehow thought that it should live in the handler monad.

**Comment by mrkkrp** [comment]
I can close if you wish.
