### ISSUE TITLE
Charset for serving JSON

### ISSUE THREAD

**Issue by koterpillar** [haskell-servant/servant#559]
When serving JSON with non-ASCII characters in it, `hspec-wai-json` requires the `Content-Type` header to be `application/json; charset=utf-8` (see https://github.com/hspec/hspec-wai/blob/master/hspec-wai-json/src/Test/Hspec/Wai/JSON.hs#L67).

The JSON RFC says that it may be represented using UTF-8, UTF-16 or UTF-32, and the default is UTF-8: https://www.ietf.org/rfc/rfc4627.txt. _However_, the HTTP spec, which governs the `Content-Type` header, says the default is ISO-8859-1, and the charset _should_ be specified: https://www.w3.org/International/articles/http-charset/index

**Comment by soenkehahn** [comment]
@koterpillar: Could you elaborate a bit more, please? It's not entirely clear what this issue is about. How does `servant` behave currently? How would you want it to behave?

**Comment by koterpillar** [comment]
Sorry I was unclear. Currently when serving `JSON`, Servant sets `Content-Type` to `application/json`, and I believe it should be `application/json; charset=utf-8`.

**Comment by koterpillar** [comment]
I am now convinced that Servant's behavior is correct:

- [JSON Interchange format](https://tools.ietf.org/html/rfc7159) says `charset` isn't needed.
- The w3.org link I posted earlier only applies to `text/` content, not to JSON.
