### ISSUE TITLE
Volunteering to help with proof reading

### ISSUE THREAD

**Issue by seanhess** [haskell-servant/servant#56]
Ping me when you have something to read over.

**Comment by jkarni** [comment]
We just merged #57, which contains a number of changes that might not all have corresponding doc updates. If you're willing to, checking the output of `cabal haddock` for the different packages for mistakes as well as lack of clarity would be very welcome! I'll soon be doing that too

**Comment by alpmestan** [comment]
I'm also **completely** rewriting the getting started, it will cover much more and will be a good old HTML page. If you want to take a look / proofread as the text gets in, it's [here](https://github.com/haskell-servant/haskell-servant.github.io/blob/hakyll/pages/getting-started.md). I'll probably push the beginning of the servant-server section this evening.

**Comment by seanhess** [comment]
Sounds good, I'll take a look!​

**Comment by jkarni** [comment]
Closing since there's nothing for us to do here, but do send a PR if you have something, or re-open if you have further questions (or hop onto #servant on freenode)
