### ISSUE TITLE
AuthHandlers with no return type?

### ISSUE THREAD

**Issue by jhickner** [haskell-servant/servant#562]
Hello,

I've just finished an implementation of HTTP Signature using the AuthHandler machinery, and it was quite fun to write! I really like the approach you took to generalized authentication. Very clean.

I ran into one question: AuthHandlers currently always need to return a type, but in the case of HTTP Signature, there's really nothing to return. We want to throw an exception if authentication fails but otherwise just proceed. There's nothing to pass down to the server implementation. So I ended up with a type of `AuthHandler Request ()`. The issue is that all of the server handlers now need to accept `()` as the first argument. Is there a way around that?

Thanks!

**Comment by jkarni** [comment]
Cool! Is this open source?

There isn't any technique that's already in `servant` to do what you want, that I know of. But it is possible with a few type classes. The type class would be very similar to `Enter`, but without the `arg` type (or the natural transformation argument). Something like:

```
{-# LANGUAGE OverlappingInstances #-}
class PlugUnits orig plugged where
   plugUnits :: orig -> plugged

instance PlugUnits val (() -> val) where
   plugUnits = const

instance PlugUnits val new => PlugUnits (a -> val) (a -> new) where
  plugUnits f x = plugUnits $ f x 
instance PlugUnits val val where
   plugUnits = id
instance (PlugUnits a b, PlugUnits c d) => PlugUnits (a :<|> b) (c :<|> d) where 
   plugUnits (x :<|> y) = plugUnits x :<|> plugUnits y
```
And then just call `plugUnits` over the entire sub-api that's protected by auth.

I *think* something along these lines would work, but I haven't tried it and the first attempt always runs into overlapping or ambiguity issues. If so, you can probably have tighter types if you assume `plugUnits` will only be applied where the *first* arg is unit.

**Comment by jkarni** [comment]
Cool! Is this open source?

There isn't any technique that's already in `servant` to do what you want, that I know of. But it is possible with a few type classes. The type class would be very similar to `Enter`, but without the `arg` type (or the natural transformation argument). Something like:

```
{-# LANGUAGE OverlappingInstances #-}
class PlugUnits orig plugged where
   plugUnits :: orig -> plugged

instance PlugUnits val (() -> val) where
   plugUnits = const

instance PlugUnits val new => PlugUnits (a -> val) (a -> new) where
  plugUnits f x = plugUnits $ f x 
instance PlugUnits val val where
   plugUnits = id
instance (PlugUnits a b, PlugUnits c d) => PlugUnits (a :<|> b) (c :<|> d) where 
   plugUnits (x :<|> y) = plugUnits x :<|> plugUnits y
```
And then just call `plugUnits` over the entire sub-api that's protected by auth.

I *think* something along these lines would work, but I haven't tried it and the first attempt always runs into overlapping or ambiguity issues. If so, you can probably have tighter types if you assume `plugUnits` will only be applied where the *first* arg is unit.

**Comment by jhickner** [comment]
Thanks @jkarni. Yes, I'll open-source it once we finish testing. Is that something you'd potentially add to core, or should I make a servant-httpsignature package?

I ran into an additional issue when composing multiple AuthHandlers that have `()` as their type. The Context machinery can't differentiate them, so I ended up having to newtype the `()`. So then the `PlugUnits` solution doesn't work :/. At least the placeholder arg to the server handler has a name now though :)

**Comment by phadej** [comment]
@jhickner you can use `Proxy :: Proxy "arbitrary text"` for "light weight tagged ()"

**Comment by soenkehahn** [comment]
@jhickner: Anything you'd want to happen before closing this issue?

**Comment by pkapustin** [comment]
@jhickner Were you able to open source this? Couldn't find it, but would be really grateful if you could share it.

**Comment by pkapustin** [comment]
@jhickner Were you implementing only the server part or the client part too?
