### ISSUE TITLE
Servant.Client.client variants with baked in Manager and/or BaseUrl

### ISSUE THREAD

**Issue by runeksvendsen** [haskell-servant/servant#563]
I have an API that exports 7 endpoints/resources. So, `Servant.Client.client` returns 7 functions that I can use to query the server, all of which require both a Manager and BaseUrl as the last two parameters.

It would be extremely helpful for me to be able to "bake in" either just a BaseUrl or both a Manager and a BaseUrl into the returned functions, such that I would call `client` like so:

```
api = Proxy :: Proxy HugeApi
manager <- newManager defaultManagerSettings
let baseUrl = BaseUrl Http "localhost" 8000 ""
firstFunc :<|> secondFund :<|> [..] = client api $ manager baseUrl
```

And then have all the client/query functions (`firstFunc`, `secondFunc`, ...) only take the API-specified argument(s) (if any). So that we get universally reusable functions that can be evaluated from anywhere by themselves (without reading the right BaseUrl from a config and applying this plus a Manager to all the functions returned by `client`).

**Comment by soenkehahn** [comment]
Thanks for the report.

Note that we don't want to change how `client` works, because lots of the time we want to be able to bind the client functions at the top-level. Then we need to be able to pass in the `Manager` and often-times also the `BaseUrl` to the individual client functions.

But this is definitely something that would be nice to have *in addition* to how `client` currently works. @amarpotghan and I spent some time trying to get this working, but in the end didn't come up with a very nice solution. This is the current state of our efforts: https://github.com/haskell-servant/servant/pull/484.

I actually like the sketched solution in that discussion: Let `ClientM` be some kind of `Reader` over `BaseUrl` and `Manager` and then use `Enter` to implement `staticClient`. (And probably rename `staticClient` to something better.)

**Comment by chkl** [comment]
Apparently it was discussed once to change ClientM to be Reader, but it got discarded. See this thread:
https://github.com/haskell-servant/servant/pull/432#issuecomment-202701482

**Comment by jkarni** [comment]
Anyone want to take this up?

**Comment by chkl** [comment]
So basically we would change ClientM from

```haskell
 ClientM = ExceptT ServantError IO                                                              
```
to
```haskell
ClientM = ReaderT Manager (ReaderT BaseUrl (ExceptT ServantError IO))                      
```
or
```haskell
ClientM = ReaderT (Manager, BaseUrl) (ExceptT ServantError IO)
```

I would be interested in doing that, although I might need some help as I'm a bloody beginner.

**Comment by jkarni** [comment]
@chkl cool. I would say we should wrap it in a newtype. And it should probably be the latter

Steps:
  
  - Give `ClientM` it's new definition
  - Make instances of it for a bunch of classes (Functor, Applicative, Monad, MonadIO, MonadReader, MonadError, at least). Almost all of these should be derivable with `GeneralizedNewTypeDeriving`
   - Make all the functions that take a Manager, BaseUrl, and ClientM only take a ClientM, and use `fst <$> ask` and `snd <$> ask` to get the manager and baseurl.
  - See if it compiles!

**Comment by jkarni** [comment]
@runeksvendsen PR #599 which was just merged into master should allow you to do this with `enter` (something like `enter (client api) (Nat $ \x ->  runClientM x (ClientEnv defaultManagerSettings (BaseUrl Http "localhost" 8081 ""))`). Can you confirm?

**Comment by runeksvendsen** [comment]
Hi guys

First of all, thanks for implementing this!

It totally works if I change a couple of things. [This diff](https://github.com/runeksvendsen/restful-payment-channel-server/commit/91b8e51215fae819f5f0afd6e0a55c08ab101ddc) makes https://github.com/runeksvendsen/restful-payment-channel-server/tree/master build (and work) using servant 040db21152ebe0da106e08550e7c11983453918a.

So it seems the interface for `client` has changed, because https://github.com/runeksvendsen/restful-payment-channel-server/tree/master builds fine using servant `0.8.1` from Hackage. I'm letting you know since @soenkehahn mentioned that the behavior of `client` shouldn't change, although I'm not sure whether this is just preliminary code (to see if it works). In any case, it does work. @jkarni So I haven't even started looking at the `enter` stuff yet, since `client` now returns what I wanted originally.

**Comment by jkarni** [comment]
Can I close this? It seems to be resolved.
