### ISSUE TITLE
[discussion] Switch travis CI to stack?

### ISSUE THREAD

**Issue by soenkehahn** [haskell-servant/servant#565]
I wonder whether we should switch our CI over to `stack`. We went with `tinc` so far, mainly because it helped us catch hackage breakage. But now we have lots of upper bounds (since #546), at least in `servant`, `servant-server` and `servant-client`. So for most of our dependencies our CI doesn't even detect whether there are new versions on hackage, that are excluded by the bounds. Additionally it'd be nice to have CI for the `stack` files.

Any opinions?

**Comment by fizruk** [comment]
Personally, I like Stack for CI. For every new Stackage snapshot build we usually get a notification on GitHub from Stackage team if any bounds are too low or anything breaks. Stack is also what I believe most of us use for our own projects and it is how we build servant locally.

**Comment by phadej** [comment]
Breakdown:
- `tinc` does test against *newer versions inside the bounds*
- `tinc` allows each package to pick  different version of dependencies
    - e.q. in `QuickCheck-2.9` PR, `servant` tests pick `2.8` as there was some transitive dependency restricting it, yet `servant-mock` pick `2.9.1` as its tests weren't restricted by `servant`'s tests.
    - with `stack` we'll be forced to pin dependencies across all packages, which may or may not be restrictful.
- leaving bounds for the sake that CI would detect when they are too loose is just *bad*
    - proper way is to have a job with `--allow-newer`, dunno if `tinc` can do it (`stack` can btw).
    - yet the upper-bounds job should be triggered periodically, not on push

OTOH:
- with `stack` one could use solver to pick an install plan within specified bounds, in *addition* to using pinned version builds in `stack.yaml`s.

I'm +/- 0 on this, as far as implications of stack are understood. IMHO it's great development tool, but not so great CI tool.

**Comment by soenkehahn** [comment]
@phadej: Could you elaborate how to use `stack` with `--allow-newer`, please? I can't find any command that has that flag.

I would also prefer if we could have a periodic build for checking hackage breakage and running `packdeps`, independent of pushes. Is there a CI service that allows to do something like this? I don't really want to start to maintain our own CI server.

I've tried `stack init --force --resolver ghc-7.10.3` in an attempt to let `stack` invoke `cabal-install` and write an install-plan into a stack file. `cabal-install` didn't terminate (for like 5 minutes or so). @phadej: Is there another way to let `stack` come up with a non-snapshot install plan?

**Comment by soenkehahn** [comment]
Update: `stack init --force --resolver ghc-7.10.3` does terminate. (I had a dirty working directory, that's why it didn't work.)

**Comment by phadej** [comment]
@soenkehahn `allow-newer: true` in the `stack.yaml`, unfortunately there is no way to generate the `stack.yaml` with `extra-deps` using `stack`, so it's a bit of a bummer. OTOH if that's what we want, it is easy to add to `stack solver` command, can be done in an evening.

https://docs.haskellstack.org/en/stable/yaml_configuration/#allow-newer

I don't know "periodic" CI services, unfortunately. I'm interesting in one as well myself.

---

BTW. just now leaned that `allow: newer` makes stack ignore all bounds, so you can just list the package versions, and their flags, and `stack` will try to build that.

**Comment by soenkehahn** [comment]
@phadej: Thanks for the reply.

So, what we would ideally want from our CI:

1) Build and test every new commit against a trusted set of (cached) dependencies with all supported compilers. This should be done on push.
2) Let `cabal-install` come up with an install plan based on the newest hackage index and try to build and test using those dependencies. This should be done periodically. Caching is not crucial. Ideally, the install plan would be created in isolation for every `servant-...` package.
3) Run `packdeps` on the cabal files. Also periodically.

For 1) `stack` seems ideal.

For 2) and 3): I've found this: https://docs.travis-ci.com/user/cron-jobs/. I've sent travis a mail and hopefully we will have cron jobs there soon. :)

**Comment by soenkehahn** [comment]
Done in #568.
