### ISSUE TITLE
Create a script to test for newer, disallowed packages on hackage

### ISSUE THREAD

**Issue by soenkehahn** [haskell-servant/servant#566]
There's this tool: http://hackage.haskell.org/package/packdeps. It allows to check whether there are newer versions of dependencies on hackage that are disallowed by upper bounds in the cabal file of a project. We should add a script to the `scripts` directory that allows to perform that check for all included projects.

**Comment by phadej** [comment]
```hs
packdeps */*.cabal
```

**Comment by soenkehahn** [comment]
I see. :)
