### ISSUE TITLE
Broken "Edit on GitHub" link

### ISSUE THREAD

**Issue by Blaisorblade** [haskell-servant/servant#567]
The "Edit on GitHub" link on http://haskell-servant.readthedocs.io/en/stable/ is broken, because it assumes sources are written in Markdown rather than RST, and uses an .md extension.

It points to
https://github.com/haskell-servant/servant/blob/8eb412ff23edf83baa7978587e71791fd9498b5a/doc/index.md
rather than
https://github.com/haskell-servant/servant/blob/8eb412ff23edf83baa7978587e71791fd9498b5a/doc/index.rst.

**Comment by soenkehahn** [comment]
Thanks for the report. Certainly true. I'm not entirely sure, how to fix it at first glance...

**Comment by soenkehahn** [comment]
Maybe it's this bug: https://github.com/rtfd/readthedocs.org/issues/2130

**Comment by soenkehahn** [comment]
Following the advice from https://github.com/rtfd/readthedocs.org/issues/2130 hopefully #571 fixes this.

**Comment by soenkehahn** [comment]
Yes, #571 fixes this. Will only land on readthedocs once we cut a new release.

**Comment by Blaisorblade** [comment]
Thanks a lot for your diligent investigation and fix!
