### ISSUE TITLE
split FromFormUrlEncoded and ToFormUrlEncoded out into a separate package

### ISSUE THREAD

**Issue by cdepillabout** [haskell-servant/servant#575]
It would be nice if [`FromFormUrlEncoded`]( https://hackage.haskell.org/package/servant/docs/Servant-API-ContentTypes.html#t:FromFormUrlEncoded) and [`ToFormUrlEncoded`](https://hackage.haskell.org/package/servant/docs/Servant-API-ContentTypes.html#t:ToFormUrlEncoded) could be pulled out into a separate package.

There is nothing particularly Servant-specific with `FromFormUrlEncoded` and `ToFromUrlEncoded`.  They could be helpful in any web framework (just like `FromJSON` and `ToJSON`, or `FromHttpApiData` and `ToHttpApiData`).

I've wanted typeclasses like `FromFormUrlEncoded` and `ToFromUrlEncoded` when working on Yesod-based projects (as well as Servant-based projects).

**Comment by fizruk** [comment]
I guess https://github.com/fizruk/http-api-data/issues/23 and https://github.com/fizruk/http-api-data/pull/25 are relevant.

**Comment by cdepillabout** [comment]
@fizruk Thanks for the heads up!  I'll close this issue in favor of https://github.com/fizruk/http-api-data/issues/23 and https://github.com/fizruk/http-api-data/pull/25.
