### ISSUE TITLE
How to get client IP?

### ISSUE THREAD

**Issue by mrkkrp** [haskell-servant/servant#577]
It's not obvious to me how to get client's IP in a handler. Is there a way to do it?

**Comment by fizruk** [comment]
Did you try [`RemoteHost`](http://hackage.haskell.org/package/servant-0.8/docs/Servant-API-RemoteHost.html)?

**Comment by mrkkrp** [comment]
Somehow missed that. It should do the trick, thanks!

**Comment by mrkkrp** [comment]
BTW, the docs are rendered with the pipe `|`, perhaps it's better to remove it?

**Comment by fizruk** [comment]
@mrkkrp yeah, that looks like a typo.
