### ISSUE TITLE
put `servant-mock` in its own package

### ISSUE THREAD

**Issue by soenkehahn** [haskell-servant/servant#578]
@jkarni, @alpmestan: What do you think?

**Comment by jkarni** [comment]
:+1:

**Comment by soenkehahn** [comment]
@phadej: You did this for other packages before. Interested in carrying on that work? :)

**Comment by phadej** [comment]
@soenkehahn I can split it tomorrow, will ping when I get my-repo in the shape.

**Comment by soenkehahn** [comment]
Awesome! Do you want me to create an empty repo in this organization and give you access to that? Or would you prefer creating the repo yourself first and then transferring it?

**Comment by alpmestan** [comment]
I'm not in favor of this but my opinion isn't popular it seems, so go ahead =)

**Comment by phadej** [comment]
I did a repo: https://github.com/phadej/servant-mock, the build is failing:
```
src/Servant/Mock.hs:118:79:
    Not in scope: type constructor or class ‘CaptureAll’
    Perhaps you meant ‘Capture’ (imported from Servant)
```

I guess we need a release of parent `servant` package?

**Comment by soenkehahn** [comment]
Yes, true. I wanted to do a release anyways.
