### ISSUE TITLE
Move `servant-foreign` and `servant-js` into separate repos?

### ISSUE THREAD

**Issue by soenkehahn** [haskell-servant/servant#579]
@dredozubov, @arianvp, @MaxOw, @freezeboy: What do you think about that? (Trying to ping the people that have put most work into these packages. Please CC anyone I might have forgotten.)

This would hopefully give you more control over the package and get it a bit out of the way when working on the other core packages (e.g. when adding a new combinator).

I would put rather tight version bounds on the dependency on `servant` and would then not expect more breakage than now.

**Comment by dredozubov** [comment]
I feel like `servant-foreign` belongs to the main repo, it's easier to support it and all client generator should depend on it by now. Am i missing anything?

> This would hopefully give you more control over the package and get it a bit out of the way when working on the other core packages (e.g. when adding a new combinator).

I'm not sure, but isn't it supposed to be in the way if we want to make consistent changes?

**Comment by alpmestan** [comment]
+1 with @dredozubov here. If we are to keep at least two packages in a "central" repo, I don't see the point of splitting too much, especially packages that are important. If one of the two we're interested in here has to go, it's -js but -foreign ought to support all the combinators from servant IMO.

**Comment by freezeboy** [comment]
+1 with others, I didn't find much time till near one year to play with servant (and I'm really sorry about that) but most packages are in the same repo, and as I feel it, it's easier to check combinator's implementation this way.

I don't really the advantage of splitting it right now (or we have to split everything...)

**Comment by phadej** [comment]
FTW, I'm strong :+1: to move  `servant-js` out. Neutral about `servant-foreign`. (please vote for OP, not complement comment, it's confusing!)

**Comment by arianvp** [comment]
Personally, I'm in favor of keeping both it.  `servant-js` is kind of the 'test bed'  or the 'example' of how to correctly use `servant-foreign`. I think it is important to keep it in lockstep with the rest of the servant combinators and semantics.

**Comment by fizruk** [comment]
I'm in favor of moving `servant-js` out while keeping `servant-foreign`.

Personally, I think that for a 'test bed' `servant-js` has too many backends (vanilla, Angular, Axios, jQuery).

**Comment by jkarni** [comment]
Also +1 on `servant-foreign` staying, `servant-js` going.

**Comment by arianvp** [comment]
Well if somebody can make a quick PR. we can do this change.

**Comment by phadej** [comment]
I could do it, but I guess it will the same problem as https://github.com/haskell-servant/servant/issues/578, i.e. need fresh releases of parent packages.

**Comment by jkarni** [comment]
Ok, a *little* unclear what the tally is on `servant-js` (`servant-foreign` is staying for now, it seems).

In favor of moving: @jkarni @fizruk @phadej 
In favor of not: @arianvp  and, I think, @freezeboy  and @alpmestan 

Further votes or confirmations?

**Comment by codedmart** [comment]
I agree that `servant-foreign` should stay, but in favor of `servant-js` moving.

**Comment by arianvp** [comment]
Okay servant-js is out
