### ISSUE TITLE
Make a type alias for  /   to :>

### ISSUE THREAD

**Issue by arianvp** [haskell-servant/servant#584]

**Comment by fizruk** [comment]
The idea is roughly this

```haskell
type (/) = (:>)
```

This might make APIs nicer for captures:

```haskell
type Endpoint = "some" / "endpoint" :> Get '[JSON] SomeData
```

**Comment by 3noch** [comment]
😕  Except now you can write

```haskell
type Endpoint = "some" / "endpoint" / Get '[JSON] SomeData
```

which is confusing. I think the `:>` is only confusing to newcomers, but quickly makes sense. Adding more variance to the mix seems like it would make it even *more* confusing to newcomers and oldcomers alike.

**Comment by codedmart** [comment]
I agree with @3noch. I don't have strong feelings against this, but I just don't think it is needed.

**Comment by alpmestan** [comment]
+1 with the last 2 comments. This synonym is enough to define for people to use it in their own projects, I think. Unless a few newcomers pop by to say they would actually like to have this, I think we should not include it.

**Comment by jkarni** [comment]
:+1: on -1 on it :). It's a nice realization that we can teach it that way, but it's sort of a pedagogical stepping stone (define it somewhere when teaching `servant`, then reveal it was a type synonym).

**Comment by fycth** [comment]
At least, would be nice to show this example in the documentation/tutorial.

**Comment by 3noch** [comment]
In fact my main argument against this is ironically a pedagogical one. I actually think this is *bad* for teaching.

**Comment by kosmikus** [comment]
I would actually like if we'd enforce a syntactic difference between items such as plain symbols or captures that match against a single path component and strip it vs items that do not. But that's more difficult to do, and would be a breaking change.

Just making `(/)` a synonym will just make things more difficult to understand, because different people will use it differently, and things will look more complicated than they are.

**Comment by 3noch** [comment]
I think @kosmikus hit the nail on the head. 👍

**Comment by soenkehahn** [comment]
I'm also against this, for the sake of simplicity. I hope everyone's fine with closing this. If not, please, speak up. :)
