### ISSUE TITLE
Auth redesign

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#589]
# Intro

Let's take a look at BasicAuth:

```
-- | The result of authentication/authorization
data BasicAuthResult usr
  = Unauthorized
  | BadPassword
  | NoSuchUser
  | Authorized usr
  deriving (Eq, Show, Read, Generic, Typeable, Functor)

-- | Datatype wrapping a function used to check authentication.
newtype BasicAuthCheck usr = BasicAuthCheck
  { unBasicAuthCheck :: BasicAuthData
                     -> IO (BasicAuthResult usr)
  }
  deriving (Generic, Typeable, Functor)
```

Let's tweak it

```
-- | The result of authentication
data AuthResult usr
  = -- removing Unauthorized because it probably shouldn't have been 
   --- here to begin with - handler's do authorization, this just does
   --- authentication
    BadPassword
  | NoSuchUser
  | Indeterminate  -- this is the new bit
  | Authorized usr
  deriving (Eq, Show, Read, Generic, Typeable, Functor)

-- which allows us to do this
instance Monoid (AuthResult usr) where
  mempty = Indeterminate
  Indeterminate `mappend` x = x
  x `mappend` _ = x

-- | Datatype wrapping a function used to check authentication.
newtype AuthCheck usr = AuthCheck
  { unBasicAuthCheck :: Request  -- data may be coming from elsewhere.
                     -> IO (AuthResult usr)
  }
  deriving (Generic, Typeable, Functor)
```

Now we can do this:

```
login :: AuthCheck User
login = ...

cookie :: AuthCheck User
cookie = ...

jwt :: AuthCheck User
jwt = ...

openID :: AuthCheck User
openID = ...

type MyAPI = Auth User :> ProtectedAPI

context :: Context ...
context = (login <> cookie <> jwt <> openID) :. EmptyContext
```

Interesting thing is, there is no requirement that there be a `login` *endpoint* (true of basic auth, useful for SPAs). What I realized is that conceptually, there isn't really a difference between logging in and continuing to browse while already logged in; they just (tend to) be different forms of authentication. In this scheme, even OpenID connect fits neatly - we just look at the code and state in the appropriate GET params, send a request to the ID provider, and decode the response as a `User`. 

This is much easier to compose than the general auth we have now. 

# Putting more info in the types

If we decide that we want to reflect authentication in the types, which I think we should, then we can go the content-types route:

```
type MyAPI = Auth [Cookie, OpenID, JWT, Login] User :> ProtectedAPI
```

Where each element of the list gets to say it needs stuff from the context:

```
class IsAuth a inCtx v where   --- inCtx comes from context
  isAuth :: Proxy a -> inCtx -> AuthCheck v

-- e.g.
instance IsAuth BasicAuth (BasicAuthCheck usr) usr where
  isAuth _ = ...
```

# Cookies

We need cookies when the client is a browser. My proposal for that is simple: a cookie combinator that takes from the context a cookie value, plus some cookie configuration about e.g. how long it lasts for, and adds it to the response. This works without the auth stuff above. *But*: the auth combinator can insert into the context a cookie value. So:

```
type API = AuthCheck '[Login, Cookie, JWT, OpenID] User :> SetCookie User :> Protected
``` 

Would work (note the `SetCookie` combinator has to appear *after* the `AuthCheck` one).

Cookie policies are actually somewhat limited - we don't need the entire world of value-level programming. So we could reflect everything in the types:

```
data SetCookie (s :: Symbol) expiry v

data CurrentTime
data a :+: b
data a :-: b
data Seconds s
data Minutes s  -- or type synonyms - I find this easier
data Date (s :: Symbol)

-- e.g. :
-- type Expiry = CurrentTime :+: Minutes 15
-- SetCookie "servant-cookie" Expiry User
```

And then only require the `User` from the context. It's a *little* nice to be able to document even the expiration of cookies, but not really that significant one way or the other to my mind.

# Conclusion

An illustration of why this is neat: think about how cookies are refreshed. Generally you'd have two (at *least) code paths: one is setting the cookie in the first place after login, another is refreshing the cookie after every request. Here, on the other hand, they're the same.

Another illustration of why this is neat: think about using a different combinator than `SetCookie`, which instead puts a `code` in a GET param of a redirect, and stores that code as the key in a map from codes to JWTs. That, friends, is an OpenID Connect identity provider. Not only do auth sources (login, basic, open id) compose in the sense of being to pick any, but uses (setting cookie, preparing for stage 2 of open ID identity providing, and presumably others) are easily swappable.

I think this is a pretty elegant way of doing auth! It composes well, allowing parts to abstracted, and jives well with the servant way of doing things (it *looks* like `ReqBody` and `Verb`). 

@haskell-servant/core 

(@aaronlevin by the way, while writing this I discovered Ghédalia Tazartès - thank you!)

**Comment by alpmestan** [comment]
I like this approach. Not sure it's worth the trouble to put cookies params in types, but other than that :+1:

**Comment by jkarni** [comment]
Closing - work going on in [`servant-auth`](https://github.com/plow-technologies/servant-auth)
