### ISSUE TITLE
Wrong route being matched.

### ISSUE THREAD

**Issue by jsdw** [haskell-servant/servant#597]
I have been having an odd issue with my servant powered app, which I thought  was a JSON parsing oddity but turns out is something going awry in the route matching. I have documented some of my findings here so far:

http://stackoverflow.com/questions/39343471/haskell-servant-400-bad-request-when-using-array-of-custom-data-type-in-reqbody

Essentially, my routes are defined like so

```
type Routes = "core"    :> CoreRoutes
         :<|> "entries" :> EntryRoutes
         :<|> "users"   :> UserRoutes
         :<|> "days"    :> DayRoutes

routes = coreRoutes
    :<|> entryRoutes
    :<|> userRoutes
    :<|> dayRoutes

type CoreRoutes = Login :<|> Logout
coreRoutes      = login :<|> logout

type EntryRoutes = GetEntries :<|> GetEntry :<|> SetEntry :<|> SetEntryOrder :<|> AddEntry :<|> RemoveEntry
entryRoutes      = getEntries :<|> getEntry :<|> setEntry :<|> setEntryOrder :<|> addEntry :<|> removeEntry

type UserRoutes = GetCurrentUser :<|> GetUsers :<|> GetUser :<|> SetUser :<|> AddUser :<|> RemoveUser
userRoutes      = getCurrentUser :<|> getUsers :<|> getUser :<|> setUser :<|> addUser :<|> removeUser

type DayRoutes = GetDays :<|> GetDay :<|> SetDay :<|> AddDay :<|> RemoveDay
dayRoutes      = getDays :<|> getDay :<|> setDay :<|> addDay :<|> removeDay
```

with each route getting a more specific definition. the two I'm interested in are:

```
type SetEntryOrder = HasSession :> "order" :> ReqBody '[JSON] [Id] :> Post '[JSON] [Id]

type AddEntry = HasSession :> ReqBody '[JSON] AddEntryInput :> Post '[JSON] Entry
```

Which appear next to eachother in the list of routes.

Strangely, it seems that requests to SetEntryOrder end up hitting AddEntry instead. In curl for instance:

```
curl -v -b TEMP_COOKIES -H "Content-Type: application/json" -X POST --data-binary '{ "name":"blah", "duration":12 }' http://localhost:9090/entries/orders
```

leads to a very specific error only found in my AddEntry route! In fact, all of these paths also match my AddEntry route:

```
http://localhost:9090/entries/orders12121
http://localhost:9090/entries/d
http://localhost:9090/entries/orders/
```

# Reproducing

The app can be found at [https://github.com/jsdw/talklicker/tree/60b116f4a1cd479cd7f7d5ff6f56857679369100](https://github.com/jsdw/talklicker/tree/60b116f4a1cd479cd7f7d5ff6f56857679369100) (the commit after this, I implement the workaround myself)

cloning, building and running the app via stack (scripts/run_server.sh does the end part too):

```
git clone https://github.com/jsdw/talklicker
cd talklicker
# checkout the last bad commit before workaround implemented:
git checkout 60b116f4a1cd479cd7f7d5ff6f56857679369100
cd server
stack install
cd ..
~/.local/bin/talklicker --static client/build --db server/talklicker.json --port 9090
```

When running, these commands (assuming curl installed) reproduce the issue:

```
curl -c TEMP_COOKIES -H "Content-Type: application/json" -X POST --data-binary '{"name":"james","pass":"password"}' http://localhost:9090/core/login
curl -v -b TEMP_COOKIES -H "Content-Type: application/json" -X POST --data-binary '["hello"]' http://localhost:9090/entries/order
```

First, we log in using test credentials (saving the cookies), then we make a test request to the offending route using said cookies. (One can also remove the HasSession stuff to avoid needing to auth for these routes and the error still occurs)

# Workaround

I have worked around this issue by adding another path piece to SetEntryOrder, so it becomes:

```
type SetEntryOrder = HasSession :> "order" :> "order" :> ReqBody '[JSON] [Id] :> Post '[JSON] [Id]
```

Obviously this is a rather ugly work around, but since I control both sides it's easy enough to do for the time being.

I also tried rearranging the order that the routes were listed but that did not work.

(tested on servant 0.8.1 and 0.7.1, GHC 7.10.3)

**Comment by jkarni** [comment]
Thanks for the report. I don't have time to look too deeply into this tonight, but one thing you can do that might help debug is add signatures at every stage:

```
type Routes = "core"    :> CoreRoutes
         :<|> "entries" :> EntryRoutes
         :<|> "users"   :> UserRoutes
         :<|> "days"    :> DayRoutes
routes :: Server Routes
routes = coreRoutes
    :<|> entryRoutes
    :<|> userRoutes
    :<|> dayRoutes

type CoreRoutes = Login :<|> Logout
coreRoutes :: Server CoreRoutes
coreRoutes      = login :<|> logout
```
And so on.

That may show some unexpected mismatch (though you have laid them out quite neatly, helping forestall that!).

Can you let me know if that points to anything? If not, I'll take a longer look tomorrow.

Thanks again!

**Comment by jsdw** [comment]
Ah, I have figured it out (though one aspect of it still confuses me)! I distilled my Routes.hs down to

```
{-# LANGUAGE DeriveGeneric, RecordWildCards, DataKinds, TypeOperators, FlexibleContexts, GeneralizedNewtypeDeriving, TypeFamilies #-}
{-# OPTIONS_GHC -fno-warn-missing-signatures #-}

module Routes (routes, Routes) where

import Types
import Servant
import Application

--
-- Our routing contents table.
--

type Routes = SetEntry :<|> SetEntryOrder
routes = setEntry :<|> setEntryOrder


--
-- SET ONE ENTRY
--

type SetEntry = "entries" :> Capture "entryId" Id :> ReqBody '[JSON] EntryInput :> Post '[JSON] Entry

setEntry :: Id -> EntryInput -> Application Entry
setEntry = error "setentry"

--
-- SET ENTRY ORDER
--

type SetEntryOrder = "entries" :> "order" :> ReqBody '[JSON] [Id] :> Post '[JSON] [Id]

setEntryOrder :: [Id] -> Application [Id]
setEntryOrder = error "setentryorder"
```

at which point it became clear what I was doing wrong - the `Capture` in SetEntry basically accepts any string, so it'll always win over setentryorder. I swapped them around and things are fine!

It didn't help that EntryInput is a record full of Maybes, so it would match most things without issue!

I imagine if I make my parsing of Id more strict (don't just accept anything!) it'll work again without swapping.

Anyway, sorry to waste your time :)

**Comment by jkarni** [comment]
Careful with relying on order - I don't think we make promises that it'll always work!

**Comment by jsdw** [comment]
Thanks for the heads up - that's useful to know! As it happens I felt uncomfortable relying on it anyway so I make certain there would be no such problem ☺
