### ISSUE TITLE
Add Secure Combinator to enforce the access to certain routes *only* via HTTPS

### ISSUE THREAD

**Issue by bollmann** [haskell-servant/servant#603]
Consider the following API:

```
type API = PublicAPI :<|> IsSecure :> BasicAuth "some realm" User :> ProtectedAPI

type PublicAPI    = ...
type ProtectedAPI = ...
```
The intuition behind the above `API` is that `PublicAPI` is accessible by everyone, but `ProtectedAPI` should only be accessible via HTTPS by users that could successfully authenticate themselves.

For the above `API`, one could naively try to devise a safe server (e.g.) as follows:

```
server :: Server API
server = publicHandler :<|> adminHandler
  where 
    publicHandler :: Server PublicAPI
    publicHandler = ... -- serve the public API.

    adminHandler :: IsSecure -> User -> Server ProtectedAPI
    adminHandler Secure user | isAdmin user = ... -- allow access to the protected API.
    adminHandler _      _                   = ... -- deny access to ProtectedAPI with a 403.
```
However, using the `IsSecure` combinator followed by the `BasicAuth` combinator now leaks a user's sensitive information on insecure connections. That is, when a user connects to an endpoint inside `ProtectedAPI` via just HTTP, the `BasicAuth` dialog prompting for a user's password pops up anyway hereby leaking the user's username and password.

I haven't been able to use `IsSecure` in conjunction with `BasicAuth` to prevent the `BasicAuth` user interaction from happening on insecure connections. My first question is therefore is there a way to do this in servant at the moment?

If not, I'd propose to add a `Secure` combinator that would restrict access to its protected sub-api only to HTTPS, so that we can safely use the `BasicAuth` combinator afterwards without having to worry about user data leakage. 

I think such a `Secure` combinator can easily be defined as follows:

```
{-# LANGUAGE OverloadedStrings     #-}
{-# LANGUAGE TypeFamilies          #-}
{-# LANGUAGE FlexibleInstances     #-}
{-# LANGUAGE TypeOperators         #-}
{-# LANGUAGE DataKinds             #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE ScopedTypeVariables   #-}
module Secure (Secure) where

import Control.Monad
import Network.Wai
import Servant
import Servant.Server.Internal

data Secure

instance HasServer api context => HasServer (Secure :> api) context where
  type ServerT (Secure :> api) m = ServerT api m

  route Proxy context subserver =
    route (Proxy :: Proxy api) context (subserver `addMethodCheck` check)
    where
      check = withRequest $ \req ->
        unless (isSecure req) $ delayedFailFatal (err403 { errBody = errMsg })
      errMsg = "403: You need to use HTTPS!"
```
Thoughts or comments on the usefulness of adding such a thing to (e.g.) `Servant.API.Secure`?

**Comment by jkarni** [comment]
I'm in favor of the idea. Three things I'd propose are: 

  1) Having this combinator be a HTTP Strict Transport Security combinator too. After all, if we are insisting on secure connections, we may as well use the standard mechanism for doing so.
  2) Perhaps redirect to https rather than 403
  3) Perhaps add a new field to `Delayed` rather than re-use `methodCheck`

**Comment by jkarni** [comment]
(This could also be WAI middleware, though...)

**Comment by bollmann** [comment]
@jkarni: Ahh, I hadn' seen this, Thanks! I agree, redirecting to HTTPS is better than throwing an error. Yes, `forceSSL` from ***wai-extra*** almost solves my issue. The only thing I'm still missing is how to apply it only on the `ProtectedAPI`, while not doing so on the `PublicAPI`.

I suppose , I'd have to create two servers which would ultimately give rise to two different **WAI** applications, that I'd then somehow compose and execute via warp (the first one without and the second one with `forceSSL`). But this would mean, I'd have to leave the servant world and do this task in the WAI world. Or am I thinking incorrectly?

**Comment by jkarni** [comment]
What's the downside of using `forceSSL` over `PublicAPI`?

**Comment by bollmann** [comment]
say, I have only a self-signed certificate that only my friends trust (who incidentally will be able to access `ProtectedAPI` via https), but I still want to serve a web page's `PublicAPI` to the entire world.

I know this is kind of special, but still :-)

**Comment by jkarni** [comment]
I'm inclined to say it anyhow should be served from to `Application`s, since `PublicAPI` doesn't *really* have HTTPS support (as in, the clients are not supposed to be using it) - it would just happen to kind of get it by the accident of being served in the same `Application`. 

This is, as you say, a pretty peculiar use-case, and one that anyhow has another sensible solution, so I myself would prefer not to have a combinator just for it. But of course the combinator could live in an external library (or as part of your application).

**Comment by bollmann** [comment]
I think you're right, I should probably just split the whole application into two sub-applications and serve one of them just via HTTPS (using `forceSSL`) hereby avoiding all other hassels of needing new combinators. Thanks for the quick thoughts and insights! 

I think we can close this one here then.
