### ISSUE TITLE
Improve documentation of addHeader

### ISSUE THREAD

**Issue by thoughtpolice** [haskell-servant/servant#608]
Recently in the Twitt-o-sphere, I described some frustration with Response Headers, and how to send multiple headers at once, while working on a new donation site for Haskell.org. This is because I am a huge whiner (and twitter is where I vent).

But I also found the documentation quite poor, honestly! The only example I ever found was in the test suite, of how to add two headers at once - and that's not great! And it's especially nasty because if you ask me, the way you do it isn't immediately obvious.

Here's an example of why. Let's say I want to add one header. Easy enough:

```haskell
type CorsHeader v = Headers '[ Header "Access-Control-Allow-Origin" String ] v

addCors :: String -> v -> CorsHeader v
addCors origin v = addHeader origin v
```

Now, you have to return `CorsHeader` as part of the type, something like:

```haskell
"foo" :> Get '[PlainText] (CorsHeader String)
```

for example. Then do `return (addCors str)` or something.

OK, so now I want to add multiple headers. My initial intuition was that, despite the fact `Headers` uses an HList, I should have threaded the request something like this:

```haskell
type CorsHeader2 v = Headers '[ Header "Access-Control-Allow-Origin" String ] (Headers [ ... ] v)
```

Why would I think this? Well, because in the documentation the type of `addHeader` isn't explained (I'll get to that in a moment) very much. So I got the impression "Well, clearly this is just some kind of data structure wrapping the final return result. So I should wrap multiple times to make it all work". It's like how if I had `Maybe a` and extended that to `Maybe (Maybe a)`.

OK, so under the assumption I keep "nesting" them, I would then do:

```haskell
addCors2 :: String -> String -> v -> CorsHeader2 v
addCors2 domain next v = addHeader domain $ addHeader next v
```

Except this is totally wrong! Because `addHeader` is built on a type class using an `HList`, this is *the correct definition*, but it absolutely *has the wrong type*.

The proper type of `addCors2` would be something like:

```haskell
type CorsHeader2 v = Headers '[ Header "Access-Control-Allow-Origin" String, Header "Access-Control-..." String ] v
```

That is, because the HList contains the list of headers, the type class instances for `addHeader` "folds" over the HList, adding header entries based on the list position.

This took me like +15 minutes to figure out, *most* of it searching for an example (by frantically searching for `addHeader` in every project using Servant). Why? Because the type of `addHeader` is totally impenetrable!

![](https://pbs.twimg.com/media/CtnRTgqVUAAfrRi.jpg)

Thus, I really, really think you should go through a few examples and at least *explain* this mechanism. I'd suggest adding an example in the Haddocks, and in the user guide.

I talked with @alpmestan about this privately on IRC, and he admitted this was one of the less clean parts of Servant. I just want to say, that's totally OK! And I apologize for my whiney twitter rants about such good stuff. :) Everything else has been exceptionally easy to grok, despite all the masterful, amazing type-level magic. But this stumbling block was *especially* frustrating, because adding response headers should conceptually be very easy, and it's very vital!

Thus, even if it's not super clean, that just means it's even *more* important to document!

I'd be willing to open a patch with examples from my actual use case, since they're not entirely theoretical.

**Comment by thoughtpolice** [comment]
Here's my use case, which I think could serve as a real example of some sort. I need to do a cross-domain (XHR) request to a REST API, with an `application/json` input to a `POST` endpoint. Because I will be doing a cross-domain `POST` and the XHR specifies a `Content-Type: application/json` for the post body, the browser does a preflight `OPTIONS` check against the URL.

This means I also must have an endpoint of type `Verb 'OPTIONS 200` along with the `POST` endpoint. The `OPTIONS` endpoint responds to the browser preflight check by replying with a response, containing multiple headers an an empty body. Headers specify whether the cross domain request should be allowed.

So. I need to send back multiple headers in my request to the browser preflight check - 4, actually. How would I do this?

I'd first suggest - **every time you need to add headers, and especially multiple ones, always create a `type` for it**:

```haskell
type CorsOptHeaders v = Headers '[ Header "Access-Control-Allow-Origin" String
                                 , Header "Access-Control-Allow-Methods" String
                                 , Header "Access-Control-Allow-Headers" String
                                 , Header "Access-Control-Max-Age" Int
                                 ] v
```

Now we have the header type. To go along with the type, **always write a wrapper utility to create those headers**:

```haskell
-- | Add the @'CorsOptHeaders'@ to a response.
corsOptHeaders :: String
               -> String
               -> String
               -> Int
               -> v
               -> CorsOptHeaders v
corsOptHeaders origin method headers age
  = addHeader origin
  . addHeader method
  . addHeader headers
  . addHeader age
```

This encapsulates all these needs quite nicely. Then simply use the type and function where needed on your endpoints. Example (from my donation form):

```haskell
type ChargeOptionsAPI = "charge" :> Options '[PlainText] (CorsOptHeaders NoContent)

chargeOpts :: String
           -> Handler (CorsOptHeaders NoContent)
chargeOpts dom = pure (corsOptHeaders dom method headers age NoContent) where
  method  = "POST"
  headers = "Content-Type"
  age     = 86400
```

This means the browser can only make the request if it's a `POST`, only the `Content-Type` header is allowed, and it must come from the specified domain.

Some important things to highlight in the docs, I think:

 - Always encapsulate your header types, at least giving them a short name. It makes using them much more ergonomically feasible to use and cleaner to read.
 - Always add a utility to wrap that up as well, and keep `addHeader` encapsulated, away from actual code if possible.
 - Emphasize that `addHeader` has an advanced type that allows this kind of trick to work, where the HList allows you to "nest" calls in such a manner. This is important! It highlights that while it's advanced, it has a very regular usage pattern, and the above guidelines should make it much less intimidating, even for large amounts of headers.

And, of course, provide a minimal example of something like this. I'd be willing to write up a shorter form example for the Haddocsk and possibly the user manual if this sounds OK.

**Comment by soenkehahn** [comment]
@thoughtpolice: Thanks for the report and sorry it caused you trouble.

It'd be great to have this documented better in the haddocks, the tutorial or both. If you find the time, please open a PR.

(Here's the manual on how to build the tutorial docs: https://github.com/haskell-servant/servant/blob/master/doc/building-the-docs)
