### ISSUE TITLE
Use `natural-transformation`

### ISSUE THREAD

**Issue by phadej** [haskell-servant/servant#616]
The [`natural-transformation`](https://hackage.haskell.org/package/natural-transformation) defines the very same type as used in `Servant.Utils.Enter`: [`:->`](https://hackage.haskell.org/package/servant-0.9.0.1/docs/Servant-Utils-Enter.html#t::-126--62-)

The other packages where natural transformations are used, like `free` or `mmorph` get a way with Rank2Type, so they don't have a `newtype` wrapper.

I'd like to use the same type, I have need for natural transformation newtype in own project, and now struggling which one to use. The one in "right place", i.e. own package, or the one in `servant` (I already depend upon).

**Comment by jkarni** [comment]
I didn't know about this package. I'm always +1 on using existing libraries; moreover, in this case, there are no dependencies, and it may even be backwards compatible!

**Comment by soenkehahn** [comment]
It may be backwards compatible, because it's using the same identifiers. This is still a breaking change, and should be communicated very visibly.

The change itself sounds good to me. :+1:

**Comment by phadej** [comment]
I can prepare a PR, you can merge it before there is other breaking change going too. I'm not sure whether it's worth introducing bc just for this, and keeping it up to date with master shouldn't be a problem.

**Comment by soenkehahn** [comment]
I'd be in favor of just merging this. We shouldn't be afraid of breaking changes and I want to keep the release process as simple as possible.
