### ISSUE TITLE
How to implement Role-Based Access Control ?

### ISSUE THREAD

**Issue by abailly** [haskell-servant/servant#617]
I have started using experimental `Auth` support to handle authentication, using [servant-auth-cookie](https://github.com/zohl/servant-auth-cookie/) implementation to manage cookie's content. I am now scratching my head on how I could implement RBAC. I would like to write something like:

```
type MyAPI  = "foo" :> UserInRole 'SomeRole :> GET [Product]
```
This would work much like `AuthProtect ...` but without adding a parameter.

I suspect I need to add something in the `Context` that would intercept the request and do the necessary checks but not sure about it. 

I had a look at how I could implement instance for `HasServer` but the implementation of `route` seemed a bit daunting. Help would be greatly appreciated as I could contribute this back to servant, in this repository or as an add-on.

**Comment by abailly** [comment]
I had a deeper look at `Auth` code and implementing something to handle RBAC seems actually less daunting than I initially thought.

**Comment by alpmestan** [comment]
Glad to know it seems less daunting =) Feel free let us know if there's something that could be documented better.
