### ISSUE TITLE
Can't do IO while preparing a Req (servant-client) ?

### ISSUE THREAD

**Issue by alpmestan** [haskell-servant/servant#624]
Hi folks,

I've recently been working on [servant-multipart](https://github.com/haskell-servant/servant-multipart), which provides `form/multipart-data` support to servant, mostly interesting for supporting file uploads.

While the server side of things required only a very minor change to Delayed to do things properly (#622), I got started thinking about client derivation. This should be possible in theory, given that `http-client` provides [this module](https://www.stackage.org/haddock/lts-7.3/http-client-0.4.31.1/Network-HTTP-Client-MultipartFormData.html) which does the hard work for us. However, adding multipart content to a request involves some IO: indeed, whenever you want to upload a local file, you have to go and read it to add its content to the request body.

As far as I can tell, this is not something we can do at the moment, and it would require us to "delay" the IO (a bit like we do in servant-server) until the point where the corresponding client function gets run. Or add a field that stores `Part`s in a list and simply fill that, instead of the request body field. This makes us have 2 fields for a single thing, that's not really satisfactory. That's why I'm opening this ticket -- I don't have any good idea to make this possible _and_ reasonably nice. Does anyone? =)

Particularly interested in hearing @soenkehahn's thoughts.

**Comment by phadej** [comment]
I'm partly interested in it, as e.g. providing streaming (i.e. conduit based) is a similar issue.

**Comment by jkarni** [comment]
This doesn't seem relevant anymore (both multipart and streaming work now, at least), so closing.
