### ISSUE TITLE
Perform basic auth on the client side without expressing it in the type?

### ISSUE THREAD

**Issue by adnelson** [haskell-servant/servant#627]
I'm writing an API which may or may not use basic auth (username/password). The API itself has no knowledge of basic auth; however, a server running the API might be running on a server which authenticates every request with basic auth. (For example, the server is proxied via nginx, and nginx handles the HTTPS termination and basic auth). The API could also be running on a server without any auth, and in any case the authentication does not affect the semantics of any of the routes, just (potentially) whether or not the service is accessible.

As such, it doesn't make sense to put authentication in the API type itself. But a client might need to add basic auth to all of the requests it performs. So, TL;DR, is there a way to *optionally* add basic auth to every request a servant client performs, without expressing it in the API type? For example, there might be a way to modify the `Manager` to insert the appropriate headers for basic auth?

**Comment by jkarni** [comment]
You can do this:

```
type API = ...

-- these don't do auth
fn1 :<|> fn2 :<|> ... = client (Proxy :: Proxy API)

-- these do
fn1' :<|> fn2' :<|> ... = client (Proxy :: Proxy (BasicAuth :> API)
```

But as mentioned, you could also use `managerModifyRequest` to add the authentication header. Adding the header isn't too complicated, and you can use the `HasClient` implementation for `BasicAuth` as guidance.

**Comment by adnelson** [comment]
Yeah, I discovered `managerModifyRequest` shortly after posting this, which addresses my particular use case. Thanks a bunch!
