### ISSUE TITLE
There is no information to start a servant project with stack

### ISSUE THREAD

**Issue by Miguelme** [haskell-servant/servant#631]
I think there are no instructions for starting a servant project with stack, it would be nice even including it in the tutorial for beginners users that try to start developing but there are no instructions of how to start with stack.

**Comment by lethom** [comment]
I am not sure there is anything specific to servant when it comes to use stack, actually.

**Comment by alpmestan** [comment]
There's [an example project](https://github.com/haskell-servant/example-servant-minimal) that you can get some inspiration from, as well as a stack template if I remember correctly.

**Comment by Miguelme** [comment]
No there are no stack template for servant. Something like that would be useful, don't you think ?

**Comment by 3noch** [comment]
@Miguelme It would only be useful if someone was trying to use servant who didn't know how to make *anything* in Haskell. In such a scenario, I would argue they probably don't want to start with servant. However, as has been said, simply having a stack file with `resolver: lts-7.9` is enough to get going with servant.
