### ISSUE TITLE
Resource management in ExceptT stacks

### ISSUE THREAD

**Issue by 3noch** [haskell-servant/servant#632]
I would like some feedback from the "horse's mouth" so to speak: 

http://stackoverflow.com/questions/40372087/what-is-the-best-way-to-manage-resources-in-an-monad-stack-like-exceptt-a-io

What do you guys do?

**Comment by jkarni** [comment]
Relates to #641

**Comment by jkarni** [comment]
Relates to #641

**Comment by phadej** [comment]
@3noch have you tried e.g. `enter (Nat runResourceT) yourHandlers`? The #676 would solve it from the inside of `servant`, but AFAICS `enter (Nat runResourceT)` should work?

Also `Handler` is now `MonadBaseControl IO`, so you can always use that (already with current servant, as there is `MonadBaseControl b (ExceptT e b)`

**Comment by phadej** [comment]
Both old `type` and `newtype` `Handler`'s are instance of `MonadBaseControl IO`, so you can use `lifter-base`'s [`bracket`](https://hackage.haskell.org/package/lifted-base-0.2.3.8/docs/Control-Exception-Lifted.html#v:bracket)

**Comment by 3noch** [comment]
@phadej Thanks. That's how I ended up doing it.
