### ISSUE TITLE
Add Lift

### ISSUE THREAD

**Issue by dmjio** [haskell-servant/servant#637]
Sometimes it's beneficial to have only concrete types expressed inside your servant DSL. 

Example:
```haskell
handlers :: String :<|> String
handlers = "foo" :<|> "bar"

type API = "foo" :> Get '[JSON] String :<|> "bar" :> Get '[JSON] String
```

Serving this DSL will obviously fail since it's not operating inside of `ExceptT ServantErr IO`.

```haskell
main :: IO ()
main = run 3000 $ serve (Proxy :: Proxy API) handlers

{--
Main.hs:125:46-51: error: …                                                                                                                                                       
    • Couldn't match type ‘[Char]’ with ‘ExceptT ServantErr IO [Char]’                                                                                                            
      Expected type: Server API                                                                                                                                                   
        Actual type: String :<|> String                                                                                                                                           
    • In the second argument of ‘serve’, namely ‘things’                                                                                                                          
      In the second argument of ‘($)’, namely                                                                                                                                     
        ‘serve (Proxy :: Proxy API) things’                                                                                                                                       
      In the expression: run 3000 $ serve (Proxy :: Proxy API) things                                                                                                             
Compilation failed.    
--}
```

An initial attempt to transform this DSL into `ExceptT ServantErr IO` using `Nat` and `Enter`'s instance for `(:~>)` will also fail since `String` is a concrete type of kind `*`. `Nat` requires the type it's transforming to be at least `* -> *`.

For reference, `Nat` and its `Enter` instance are defined as: 
```haskell
newtype m :~> n = Nat { unNat :: forall a. m a -> n a }
instance Enter (m a) (m :~> n) (n a) where enter (Nat f) = f    
```

```haskell
main :: IO ()
main = run 3000 $ serve (Proxy :: Proxy API) (enter (Nat return) handlers)

{--
Main.hs:125:58-63: error: …                                                                                                                                                       
    • Couldn't match type ‘a’ with ‘m0 a’                                                                                                                                         
      ‘a’ is a rigid type variable bound by                                                                                                                                       
        a type expected by the context:                                                                                                                                           
          forall a. m0 a -> n0 a                                                                                                                                                  
        at /Users/dmj/Desktop/falad/Main.hs:125:54                                                                                                                                
      Expected type: m0 a -> n0 a                                                                                                                                                 
        Actual type: a -> n0 a                                                                                                                                                    
    • In the first argument of ‘Nat’, namely ‘return’                                                                                                                             
      In the first argument of ‘enter’, namely ‘(Nat return)’                                                                                                                     
      In the second argument of ‘serve’, namely                                                                                                                                   
        ‘(enter (Nat return) things)’                                                                                                                                             
Compilation failed.       
--}
```

If we introduce a type `Lift` with it's own `Enter` instance we can allow arbitrary types to be lifted into `ExceptT ServantErr IO`.

```haskell
newtype x :^ n = Lift { unLift :: forall a. a -> n a }
instance Enter a (a :^ n) (n a) where enter (Lift f) = f    

main :: IO ()
main = run 3000 $ serve (Proxy :: Proxy API) (enter (Lift pure) handler)  

{-- 
λ Davids-MacBook-Pro-3 → curl localhost:3000/bar
"bar"% 
--}
```

For reference, here is the `(->)` instance for `Enter`

```haskell
instance (Enter b arg ret) => Enter (a -> b) arg (a -> ret) where
    enter arg f a = enter arg (f a)
```

It should be possible to map `Identity` (or simply pure) over each `String`, and then use `Nat`, but the `(->)` instance for `Enter` did not allow this.

```haskell
handle :: Identity String :<|> Identity String
handle = enter Identity handlers

-- Main.hs:132:7-27: error: …                                                                                                                                                     
--     • No instance for (Enter [Char] (a0 -> Identity a0) (Identity String)) arising from a use of ‘enter’
--         (maybe you haven't applied a function to enough arguments?) 
--     • In the expression: enter Identity
--       In an equation for ‘foo’: foo = enter Identity handlers
-- Compilation failed. 
```

**Comment by ElvishJerricco** [comment]
Don't you need to do `enter (Lift Identity) handlers`?

**Comment by dmjio** [comment]
@ElvishJerricco we could, but then we'd need to run `Nat` on that to transform it. `Lift` should be able to bypass that and put the `a` directly into `ExceptT IO ServantErr a`.

**Comment by ElvishJerricco** [comment]
Then what's wrong with `enter (Lift pure) handlers`?

**Comment by dmjio** [comment]
Nothing, this is what's happening.
```haskell
enter (Lift pure) :: (String :<|> String) -> (ExceptT ServantErr IO String :<|> ExceptT ServantErr IO String)
enter (Lift Identity) :: (String :<|> String) -> (Identity String :<|> Identity String)
```

**Comment by dmjio** [comment]
So in theory you should be able to do:
```haskell
(\handlers -> enter (Nat . pure . runIdentity) $ enter (Lift Identity) handlers)
  :: (String :<|> String) -> (ExceptT ServantErr IO String :<|> ExceptT ServantErr IO String)
```

**Comment by jkarni** [comment]
Is there a big downside to having the handlers be polymorphic over monad?

```
handlers :: forall m. Monad m =>  m String :<|> m String
```

Or alternatively concretely using `Identity`? In both cases you're indicating that the function is pure. In the former, you don't even need `enter`.

Adding another instance for `enter` makes the whole story a little less coherent, to my mind. If it turns out to make sense to `lift`, to my mind this should be a separate set of typeclasses (which however could use `Enter` internally).

**Comment by dmjio** [comment]
@jkarni,

> Is there a big downside to having the handlers be polymorphic over monad?

The example I provided (`"foo" :<|> "bar"`)  was a bit trivial, so let me provide some context.
In this scenario I have a client-side `View` type (that isn't higher-kinded) that looks something like:
```haskell
type ElementType = String
type Attrs = [(String, String)]
type Kids a = [ View a ]
data View a  -- here
  = View ElementType Attrs (Kids a)
  | TextNode String
```

I'm constructing client-side pages for this using `servant`. So a typical "Page API" looks like: 
```haskell
data Action = Add | Subtract -- sample actions
type HomePage = View Action
type AboutPage = "about" :> View Action

-- | like this
type PageAPI = AboutPage :<|> HomePage 

-- with the handlers
handlers :: View Action :<|> View Action
handlers = aboutPage :<|> homePage
  where
    aboutPage, homePage :: View Action
    aboutPage = div_ [] [ text_ "about page" ]
    homePage  = div_ [] [ text_ "home page"  ]
    -- helpers
    div_ = View "div"
    text_ = TextNode
```

To require users to instead write `Identity (View Action)` (for both type and value-level) is very unnecessary and verbose imo. `View action` is not a `Monad` and I don't believe it should be treated as such. 

These `View`'s can be delivered on the server if we transform them correctly into `Get '[HTML] (View Action)`. So we simply use a closed type family.

```haskell
-- Type family which goes from `View a` to anything we want (i.e. Get '[HTML] (View Action))
type family ViewTransform view r where
   ViewTransform (a :<|> b) r = ViewTransform a r :<|> ViewTransform b r
   ViewTransform (a :> b) r = ViewTransform b r
   ViewTransform view r = r

-- Usage
type ServerPageAPI = ViewTransform PageAPI (Get '[HTML] (View Action))
```

The only thing left to do now is to transform the value-level using `enter`, and this is what inspired the creation of `Lift`. `View Action` is not eligible to be used with `(:~>)` since it's not higher-kinded. To my knowledge there is no other way lift these types into a `Monad` nor `Identity` without requiring the user's to first specify it, which in this case doesn't make sense.

> Or alternatively concretely using Identity?

If there was a way to apply `Identity` to `String :<|> String`, to get `Identity String :<|> Identity String`, by using `enter` I would be ok disregarding this, but at present there is not as far as I can tell.

> Adding another instance for enter makes the whole story a little less coherent, to my mind.

It seems like `Enter` is very nicely abstracted from `Nat`. Sure `Lift` would bring another instance into `Enter`, but that instance would only be used if `Lift` was being used, so type inference wouldn't change for users not using `Lift` afaik.

I think it would be beneficial to allow concrete types of kind star to be lifted into `ExceptT IO ServantErr` (using `Lift`) along with the higher-kinded types (using `Nat`) being transformed into `ExceptT IO ServantErr`, not just have the "monads only" club, etc.

**Comment by alpmestan** [comment]
+1 from me. Asking users to sprinkle `Identity` everywhere is not a good solution and the current `Nat` machinery does not apply, so I'm in favor of including this. It won't hurt anyone and will be there for those who need it, like @dmjio. While `Nat` is the main motivation for `Enter`, unlike you @jkarni I feel better knowing that we are making it more broadly applicable instead of having to define other typeclasses that do the very same thing but over other kinds.

**Comment by jkarni** [comment]
Here's an explanation for `enter` that is simple and concise:

> `enter (x :: M :~> N)` converts a `ServantT API M` to `ServantT API N`. 

One can't even *describe* a non-`Identity` API with `Servant`/`ServantT, much less give this explanation. So the documentation gets more verbose, and everyone is more confused. 

Here's a law that we could give:

```haskell
import Control.Category as C
enter f1 C.. enter f2 == enter (f1 C.. f2)
```

Which also doesn't work with `Lift`.

If we treat `enter` as this magic "do whatever you can to make what I wrote fit what `servant` expects" (which I think is quite tempting), things are going to get ugly. 

Another point is that I think `Enter` is actually a little bit carelessly defined. It should have been:

```haskell
class Enter arg from to ret | arg from to -> ret, arg ret -> to, arg ret -> from, ret from to -> arg   where
     enter :: from :~> to -> arg -> ret
```

Because in theory we *should* be able to deduce the natural transformation from the original and final versions. This wouldn't work with `Lift`. So we'd be tying our hands against this change.

Ultimately, though, I just think the use-case seems very specialized (and to admit of several other adequate solutions) for `servant` itself to include it.

**Comment by dmjio** [comment]
@jkarni,

Certainly, and the last thing I want to do is introduce a datatype into `servant` that is not law-abiding. With that being said, I think it's a good idea for to formalize `Enter` and the laws it expects to be upheld. 

> One can't even describe a non-Identity API with Server/ServerT, much less give this explanation. So the documentation gets more verbose, and everyone is more confused.

This is true, but this assumes that `Enter` and `(:~>)`'s sole purpose is to work with the `servant-server` package, which requires all web handlers to be monads (not just values). I see both `Enter` and `(:~>)` defined in `servant`, which seems their use can be more general, and not solely for `servant-server`. 

> Here's a law that we could give:
> import Control.Category as C
> enter f1 C.. enter f2 == enter (f1 C.. f2)

I can see how a natural transformation forms a category, but I'm unsure if `Lift` not forming a `Category` is really problematic. I think `Lift` is problematic only if it does not uphold the laws of `Enter`. Which would be true if we redefined `Enter` to include `(:~>)`, as you suggested.

> If we treat enter as this magic "do whatever you can to make what I wrote fit what servant expects" (which I think is quite tempting), things are going to get ugly.

I agree with this. So it seems we have 2 options. 

1) Put `(:~>)` and `enter` into the `servant-server` package, and assume all usage of them should be in the context of working with web handlers that are at least `Functor`s and define `Enter` in terms of `Nat` to gain the `Category` law (as you've suggested). This way people won't be tempted.

2) Don't include `(:~>)` into `Enter`, but introduce some other formalisations / laws to `Enter` so that if we can extend it, we'll do so correctly. Otherwise, I don't see any inherent problem with `Lift` as the code stands. 

IMO requiring users to annotate their types with `Identity TypeA :<|> Identity TypeB` isn't a good solution, from an aesthetics point of view.

Otherwise, if we don't want `Lift`, then we need some way of transforming all values in `(:<|>)` into `Identity`. I guess I could just use `coerce` for now, seems to work well with the `Identity` newtype. I still think `Lift` would be more direct. 

```haskell
module Main where                                                                                                                                                                 
                                                                                                                                                                                  
import Control.Monad.Identity                                                                                                                                                     
import Data.Coerce                                                                                                                                                                
                                                                                                                                                                                  
data a :<|> b = a :<|> b                                                                                                                                                          
 deriving (Show)                                                                                                                                                        
                                                                                                                                                                                  
value :: Int :<|> String                                                                                                                                                          
value = 1 :<|> "foo"                                                                                                                                                              
                                                                                                                                                                                  
lifted :: Identity Int :<|> Identity String                                                                                                                                       
lifted = coerce value                                                                                                                                                             
                                                                                                                                                                                  
main :: IO ()                                                                                                                                                                     
main = print lifted                                                                                                                                                               
-- Identity 1 :<|> Identity "foo" 
```

**Comment by ElvishJerricco** [comment]
I agree with formalizing the laws. Laws are the best way for us to provide substantial meaning to an abstraction. `Enter` as it stands is substantially unmeaningful =P

**Comment by dmjio** [comment]
@jkarni 

Here's a full example, I'm just saying aesthetically, if we could serve `values` instead of `lifted`, it would look better imo. Normally we'd have `Handler` there. But `Identity` in `lifted` just doesn't seem like it matches the `API` description like unwrapped `value`. `Lift` would help with that.

```haskell
{-# LANGUAGE DataKinds #-}                                                                                                                                                        
{-# LANGUAGE DeriveGeneric #-}                                                                                                                                                    
{-# LANGUAGE FlexibleInstances #-}                                                                                                                                                
{-# LANGUAGE MultiParamTypeClasses #-}                                                                                                                                            
{-# LANGUAGE TypeOperators #-}                                                                                                                                                    
                                                                                                                                                                                  
module Main where                                                                                                                                                                 
                                                                                                                                                                                  
import Control.Monad.Identity                                                                                                                                                     
import Data.Coerce                                                                                                                                                                
import Data.Proxy                                                                                                                                                                 
import Servant.API                                                                                                                                                                
import Servant.Server                                                                                                                                                             
import Network.Wai.Handler.Warp                                                                                                                                                   
                                                                                                                                                                                  
type API = "foo" :> Get '[JSON] Int                                                                                                                                               
      :<|> "bar" :> Get '[JSON] String                                                                                                                                            
                                                                                                                                                                                  
value :: Int :<|> String                                                                                                                                                          
value = 1 :<|> "foo"                                                                                                                                                              
                                                                                                                                                                                  
lifted :: Identity Int :<|> Identity String                                                                                                                                       
lifted = coerce value                                                                                                                                                             
                                                                                                                                                                                  
main :: IO ()                                                                                                                                                                     
main = do                                                                                                                                                                         
  putStrLn "running on 3000..."                                                                                                                                                   
  run 3000 $ serve (Proxy :: Proxy API) (enter nat lifted)                                                                                                                        
  where                                                                                                                                                                           
    nat :: Identity :~> Handler                                                                                                                                                   
    nat = Nat $ \(Identity x) -> pure x  
```

**Comment by fizruk** [comment]
@jkarni 

> Here's an explanation for enter that is simple and concise:
> > `enter (x :: M :~> N)` converts a `ServantT API M` to `ServantT API N`.
> 
> One can't even describe a non-Identity API with `Servant`/`ServantT`, much less give this explanation. So the documentation gets more verbose, and everyone is more confused.

I guess you meant `Server`/`ServerT`. And although currently those do not allow pure handlers, I don't see why we can't have it in principle. Pure handlers is actually something we might want to have, especially since we can move the impure stuff into combinators such as `AuthProtect`.

> Here's a law that we could give:
> ```haskell
import Control.Category as C
enter f1 C.. enter f2 == enter (f1 C.. f2)
```
> Which also doesn't work with `Lift`.

Although it doesn't typecheck for `Lift m` in Haskell, it does work in theory. Just consider `Lift m` a wrapper around `forall a. Kleisli m a a`. And you can even fix it in Haskell by just adding two phantom parameters to `Lift`:

```haskell
newtype Lift m a b = Lift { unLift :: forall x. x -> m x }

instance Monad m => Category (Lift m) where
  id = Lift pure
  Lift f . Lift g = Lift (f <=< g)

instance Enter x (Lift m a b) (m x) where
  enter (Lift f) = f
```

And now `enter (Lift f) . enter (Lift g) == enter (Lift f . Lift g)` works just fine!
Alternatively we can just not give a `Category` instance for `Lift` at all and the law would just not make sense because RHS would not typecheck.

By the way, if you also include this law:

```
enter id = id
```

Then it stops working for `Lift m` (because there's no `id :: a -> m a`).

> Another point is that I think Enter is actually a little bit carelessly defined. It should have been:
>
> ```haskell
class Enter arg from to ret | arg from to -> ret, arg ret -> to, arg ret -> from, ret from to -> arg   where
     enter :: from :~> to -> arg -> ret
```
> Because in theory we should be able to deduce the natural transformation from the original and final versions. This wouldn't work with Lift. So we'd be tying our hands against this change.

The problem with `:~>` is that it does not capture every natural transformation we might be interested in. In fact `forall a. a -> f a` is one such transformation and `forall a. f a -> a` is another one (although I don't have a use case for that one).

That said, I am neutral on adding `Lift` to `servant` directly. In my opinion, this issue is just another echo of `ServerT` being a hard-to-deal-with type family and not a proper (possibly indexed) monad transformer.

**Comment by jkarni** [comment]
> Then it stops working for Lift m (because there's no id :: a -> m a).

What about `Control.Category.id`?

> I guess you meant Server/ServerT. And although currently those do not allow pure handlers, I don't see why we can't have it in principle. Pure handlers is actually something we might want to have, especially since we can move the impure stuff into combinators such as AuthProtect.

It's not a question of my not wanting to express pure handlers or operations on them (in some other way than `ServerT API Identity`). It's just that Haskell doesn't allow it. Similarly, theoretically we might want this:

```haskell
fmap (+ 1) (5 :: Int)

eg = do
   x <- (5 :: Int)
   (x + 1)
```

To work, but it can't. I think `ServerT` is exactly in the same situation as a monad transformer here, and with monad transformers you also have this awkward extra `Identity` (which is however hidden away in type synonyms and functions that use `runIdentity/Identity`). Relatedly:

> The problem with :~> is that it does not capture every natural transformation we might be interested in. In fact forall a. a -> f a is one such transformation and forall a. f a -> a is another one (although I don't have a use case for that one).

 I think we have to come to terms with the fact that `functor` in our context (Haskell) means `Functor`, even if conceptually `Either` is a functor in both arguments, it is not a `Functor` in both arguments (though it is a `Bifunctor`). Similarly, in our context it may be said natural transformation is `Nat` or `forall a. f a -> g a` - not also `a -> f a` or `f a -> a`. 

Here's another way of seeing it. `ServerT API` is "like" a functor one level up (where instead of functions you have natural transformations). `enter` is "like" `fmap`. In this world, perhaps `Lift` could be seen as `Unit :~> m` (where `Unit` is "like" `()` but one level up - i.e. `Proxy`). I don't know. 

There are perhaps other things that can be said about what `ServerT API` is "like" (in this sense). For example:

```haskell
class MonadLike from a b to where
  bindLike :: from -> a :-> b -> to

-- Not really this but conceptually:
instance (MonadTrans t, Monad m, Monad n) => MonadLike (ServerT api (t m)) m n (ServerT api (t n)
```

(Although I can't for the life of me imagine a use-case for this.)

But *there is* the solution that @dmjio found (of `coerce`) - which is anyhow more efficient. While I think this *discussion* has been very helpful (to me, at least) in clarifying `enter`, I still don't see why we should include more functionality that isn't needed, especially when it is at least not *obvious* that adding a `Lift` instance doesn't muddle the semantics of `enter`.

**Comment by dmjio** [comment]
@jkarni,

One issue with `coerce` is that the type you want to coerce into cannot be inferred unless you write out the entire type first due to ambiguity with `Enter`. So if your API is large, that would be *very* tedious. If we had:
```haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}

module Main where

import Control.Monad.Identity
import Data.Coerce
import Data.Proxy
import Servant.API
import Servant.Server
import Network.Wai.Handler.Warp

type API = "foo" :> Get '[JSON] Int
      :<|> "bar" :> Get '[JSON] String

handlers :: Int :<|> String
handlers = 1 :<|> "foo"

main :: IO ()
main = do
  putStrLn "running on 3000..."
  run 3000 $ serve (Proxy :: Proxy API) (enter nat (coerce handlers))
  where
    nat :: Identity :~> Handler
    nat = Nat $ \(Identity x) -> pure x
```

This will fail since `enter` has no idea what to `coerce` something into. `Nat` doesn't help either since the type we'd care about coercing into is an existential. 
```bash
Main.hs:22:42-68: error: …                                                                                                                                                        
    • Ambiguous type variable ‘typ0’ arising from a use of ‘enter’                                                                                                                
      prevents the constraint ‘(Servant.Utils.Enter.Enter                                                                                                                         
                                  typ0                                                                                                                                            
                                  (Identity :~> Handler)                                                                                                                          
                                  (Control.Monad.Trans.Except.ExceptT ServantErr IO Int                                                                                           
                                   :<|> Control.Monad.Trans.Except.ExceptT                                                                                                        
                                          ServantErr IO [Char]))’ from being solved.                                                                                              
      Probable fix: use a type annotation to specify what ‘typ0’ should be.                                                                                                       
      These potential instance exist:                                                                                                                                             
        instance (Servant.Utils.Enter.Enter typ1 arg1 ret1,                                                                                                                       
                  Servant.Utils.Enter.Enter typ2 arg2 ret2, arg1 ~ arg2) =>                                                                                                       
                 Servant.Utils.Enter.Enter (typ1 :<|> typ2) arg1 (ret1 :<|> ret2)                                                                                                 
          -- Defined in ‘Servant.Utils.Enter’                                                                                                                                     
    • In the second argument of ‘serve’, namely                                                                                                                                   
        ‘(enter nat (coerce handlers))’                                                                                                                                           
      In the second argument of ‘($)’, namely                                                                                                                                     
        ‘serve (Proxy :: Proxy API) (enter nat (coerce handlers))’                                                                                                                
      In a stmt of a 'do' block:                                                                                                                                                  
        run 3000 $ serve (Proxy :: Proxy API) (enter nat (coerce handlers))                                                                                                       
Main.hs:22:53-67: error: …                                                                                                                                                        
    • Couldn't match representation of type ‘typ0’                                                                                                                                
                               with that of ‘Int :<|> String’                                                                                                                     
        arising from a use of ‘coerce’                                                                                                                                            
    • In the second argument of ‘enter’, namely ‘(coerce handlers)’                                                                                                               
      In the second argument of ‘serve’, namely                                                                                                                                   
        ‘(enter nat (coerce handlers))’                                                                                                                                           
      In the second argument of ‘($)’, namely                                                                                                                                     
        ‘serve (Proxy :: Proxy API) (enter nat (coerce handlers))’                                                                                                                
Compilation failed.                 
```

I still think there is a place for something that uses `enter` and lifts into an `m a`. Before we can say this causes ambiguity with `Enter`, it might be best to define what is 'expected behavior' first, and this is hard without laws. I'm under the impression that if a user doesn't use `Lift`, then that instance will be not be chosen, and there won't be ambiguity.

**Comment by jkarni** [comment]
The coerce issue is, I think, fixed by @phadej's `hoistServer`, so closing. But please re-open if this was a mistake.
