### ISSUE TITLE
When parsing a ReqBody there is no way to set optional params in the json request

### ISSUE THREAD

**Issue by Miguelme** [haskell-servant/servant#639]
I think there is no way to set a parameter of a haskell object to be used in the ReqBody as optional. 

Let's say in this case :

```
data User = User
  { userId        :: Int
  , userFirstName :: String
  , userLastName  :: String
  , userFullName  :: String 
  } deriving (Eq, Show)

```

I would like the userFullName to be an optional param in the req body. How can I achieve this ?

Thanks in advance

**Comment by 3noch** [comment]
This is something you would handle in your deserialization code. For example, if you're accepting JSON for this datatype, you would change your `FromJSON` instance to allow `userFullName` to be optional. You can do this generically by making `userFullName :: Maybe String` and allowing the generic JSON derivations take care of it. If you don't like `Maybe String`, you'll have to manually write a `FromJSON` instance to provide a default value for that field.

**Comment by jkarni** [comment]
@Miguelme does @3noch 's answer help? I'll close this since I assume it does, but if not, feel free to reopen.
