### ISSUE TITLE
Abstract Handler

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#641]
@kosmikus suggested this a while back, but: is everyone okay with making `Handler` it's own abstract monad (rather than a type synonym)? This will make it easier to add more instances without breaking backwards compatibility.

Currently I'm thinking of making it a `MonadResource` (as part of the work on file uploads, I'd be using `MonadResource` anyhow, and it seems reasonable to allow handlers to also register cleanup actions). I've also thought about adding functions:

```haskell
etagIs :: Etag -> Handler ()
lastModifiedAt :: DateTime -> Handler ()
```

With the functionality that if there is a `If-Match`/`If-None-Match` (or `If-Modified-Since`/`If-Unmodified-Since`) header in the request that doesn't/does match the mentioned `Etag`/`DateTime`, and appropriate `throwError` is thrown. (This seems like a nice API for servers, but I still haven't figured out how it would work for clients.)

**Comment by phadej** [comment]
I'm :+1:, and let's make `ClientM` a newtype as well!

**Comment by jkarni** [comment]
`ClientM` already [is](https://github.com/haskell-servant/servant/pull/599)!

**Comment by phadej** [comment]
Oh, I didn't even realised that. I'd say the `Handler` change should follow.

**Comment by kosmikus** [comment]
Unsurprisingly, I support this change. I still don't like the `M` in `ClientM`, but that's unrelated ...

**Comment by 3noch** [comment]
Yes please!
