### ISSUE TITLE
How to set headers for all exit paths?

### ISSUE THREAD

**Issue by 3noch** [haskell-servant/servant#642]
I have several endpoints that configure CORS headers. However I just stumbled upon the fact that `throwError err400` does *not* include those headers. Is there an easy way to share headers between the API endpoint and the exceptional cases?

**Comment by dmjio** [comment]
You could extract the headers out of the type level list in the happy path, and add them to the `ServantError` headers.

```haskell
err :: ServantError 
err = ServantError { 
   headers = getHeaders $ addHeader 5 "hi" :: Headers '[Header "someheader" Int] String;
   ...
}
```
https://hackage.haskell.org/package/servant-0.9.1.1/docs/Servant-API-ResponseHeaders.html#v:getHeaders

**Comment by phadej** [comment]
@3noch does @dmjio's solution work for you?

**Comment by 3noch** [comment]
Yes it works. Thanks. Is this supposed to be the normal approach to this?

**Comment by dmjio** [comment]
Yes. I'd make a separate type for your headers, include that type in your API, and then here in your natural transformation. This way you don't have to update it in 2 places.

**Comment by 3noch** [comment]
Thanks.
