### ISSUE TITLE
Routing conflict with `Capture` parameter 

### ISSUE THREAD

**Issue by abailly** [haskell-servant/servant#647]
I have the following (fragment of) API:

```
:<|> "predefined" :> Capture "queryId" UUID :> Delete '[JSON] (Maybe PredefinedQuery)
:<|> "predefined" :>                        :> Delete '[JSON] [PredefinedQuery]
```

The intent is that in one case, we `Delete` one object and in the other case all the objects. While writing tests for that API, I got stuck with the fact the second endpoint is never called. I thought this was related to the fact that the `UUID` type could be converted from an empty string, which I fixed but to no avail.

Am I misunderstanding something about the way routing works in servant?

**Comment by fizruk** [comment]
@abailly did you try referring to the second endpoint with or without a trailing slash?
Does `servant-client` distinguish the two endpoints correctly?

**Comment by abailly** [comment]
I am using servant client, so URI construction is transparent and maybe it is the client which is not distinguishing the endpoints. I removed the "clear all" endpoint and use a `QueryParam`  instead and now I am stuck with an even weirder behaviour: The only remaining handler for deletion is not called at all

**Comment by fizruk** [comment]
@abailly which version of servant are you using?
