### ISSUE TITLE
Question : Combining wai middleware in servant

### ISSUE THREAD

**Issue by reygoch** [haskell-servant/servant#648]
So, I want to add two wai middlewares to my servant server. One middleware for serving static files, and one for logging.

I have my api defined (`router`) and this is how I start my server :

```
webServer :: IO ()
webServer = run 80 (middleware $ router)
```

And here is how I defined my middleware :

```
middleware :: Application -> Application
middleware = do
  logStdoutDev
  staticPolicy $ addBase "static"
```
Now, if I put `logStdoutDev` first than I can't serve static files, but if I put `staticPolicy` first, than I can serve static files but I loose ability to log events (basically they get ignored).

Question is really, how to properly combine wai middleware in servant?

**Comment by jkarni** [comment]
I imagine you're getting a warning (with `-Wall`) about the result of a do notation statement being discarded, no? Try:

```haskell
middleware :: Application -> Application
middleware =  logStdoutDev . staticPolicy (addBase "static")
```

By using the `((->) Application)` monad, each statement is producing an `Application`, but you are really only using the second.

**Comment by reygoch** [comment]
@jkarni thanks, that did the trick. I was expecting some monadic syntax since it would be much cleaner to define middleware in that way.

Thanks!
