### ISSUE TITLE
Write own ReqBody combinator?

### ISSUE THREAD

**Issue by nd2s** [haskell-servant/servant#650]
Is it possible to write my own `ReqBody` combinator?

I want to parse the request body myself and validate it using `json-schema`. Unfortunately I couldn't find out how. The current `ReqBody` implementation is just a single data type with `Typeable` instance which doesn't seem to do anything on its own.

**Comment by alpmestan** [comment]
@nd2s Absolutely. `ReqBody`, like all other combinators, is just an empty type, it doesn't have any meaning by itself but is given one by all the "interpretations" (servant-server, servant-client, servant-docs, etc). If you want to write your own variant, it's easy: define a similar empty type and give it the meaning you want by instantiating `HasServer` and friends in a similar way to what's done for `ReqBody`.

Are you sure however that what you want can't be done within a `FromJSON` instance? Is the problem that you'd have to pull the schema out of thin air? In that case, could you maybe instead define an alternative to our `JSON` content type that gets a JSON schema attached to it somehow?

**Comment by nd2s** [comment]
Ah, I see. Thanks I will try that! My problem was that I hadn't seen the already existing `HasServer` instance.

I'm not sure if there is a better way: `persistent` is generating the `FromJSON`/`ToJSON` instances for me, and I am adding the `JSONSchema` manually, specifying how long each text string is allowed to be and so on. (I don't want to make special types for normal `Text` fields like "name" or "description").
I now just want to validate the input objects before they are passed to my handler functions.

Seems like a very common thing to do, so maybe there is already a standard solution for that?

**Comment by jkarni** [comment]
Use a newtype?
