### ISSUE TITLE
Custom handler monad for AuthHandler for db connection

### ISSUE THREAD

**Issue by reygoch** [haskell-servant/servant#652]
I want to have simple db access in all of my handlers, for that purpose I've created new monad e.g. :

```
newtype Controller a = Controller
    { runController :: ReaderT ServerEnvironment Handler a
    } deriving ( Functor, Applicative, Monad, MonadReader ServerEnvironment, MonadError ServantErr, MonadIO )
```

Problem is that `mkAuthHandler` requires my handler function to be `Request -> Handler a` instead of `Request -> Controller a` and I'm not sure how to make that transformation.

I also can't pass db connection to my authentication handler because of it speciffic signature.

**Comment by 3noch** [comment]
@reygoch You need to use `enter` to tell Servant how to run handlers in your monad: http://haskell-servant.readthedocs.io/en/stable/tutorial/Server.html#using-another-monad-for-your-handlers

**Comment by reygoch** [comment]
@3noch sure, I'm doing this for all other handlers, but I can't do it for authentication handler since types simply don't match.

**Comment by 3noch** [comment]
Oh sorry I misread your question.

**Comment by reygoch** [comment]
@3noch no problem, but do you possibly have any idea how to achieve this?

**Comment by VyacheslavHashov** [comment]
@reygoch Supposing you have the transformation
`natController :: Controller a -> Handler a`

and the auth handler
`authHandler :: Request -> Controller a`

then just use
 `mkAuthHandler (natController . authHandler)`
