### ISSUE TITLE
Question about text encoding

### ISSUE THREAD

**Issue by rikvdkleij** [haskell-servant/servant#654]
I'm confused by all information about String, ByteString and Text (and all encodings, strictnes) in Haskell.

If my data type contains `Text` fields and are converted by Aeson's `ToJSON` to json. What is the encoding of these text fields in json result? Do I have to set to encoding explicitly in json response? Many thanks for answering.

**Comment by rikvdkleij** [comment]
Hmm, I think I already found answer: http://stackoverflow.com/questions/14080659/why-do-library-designers-use-bytestring-where-text-seems-to-be-appropriate

**Comment by arianvp** [comment]
Aeson encodes Text as  UTF-8.  Im not sure if it is configurable.  The JSON Standard says   JSON should always be Unicode, and the default should be UTF-8 unless stated otherwise. https://www.ietf.org/rfc/rfc4627.txt

**Comment by arianvp** [comment]
Furtermore I think haskells's internal format is UTF-16  (Either LE, or BE according to the architecture) and thus is not portable. When serializing you should always   use one of these funtions: https://www.stackage.org/haddock/lts-7.14/text-1.2.2.1/Data-Text-Encoding.html

Of course, Aeson already takes care of that for you

**Comment by alpmestan** [comment]
Let us know if @arianvp's answer is enough and solves your problem (therefore allowing us to close this issue) :)

**Comment by rikvdkleij** [comment]
@arianvp Thank you very much for answering my question. 

So Servant's json response does not need an encoding header because it's using the default encoding.

Question about your second comment. What data type do you mean by  Haskell's internal format? Do you mean Char by that?

**Comment by christian-marie** [comment]
@rikvdkleij you may also like to read through https://github.com/haskell-servant/servant/issues/263

In this ticket, we see that it's not always that simple when you take into account misbehaving clients. That said, utf-8 *should* be implied. In my experience Aeson does the right thing here.

As for what @arianvp meant, perhaps this helps: https://hackage.haskell.org/package/base-4.9.0.0/docs/Data-Char.html#t:Char

**Comment by christian-marie** [comment]
@rikvdkleij does this clear everything up for you?

**Comment by rikvdkleij** [comment]
@christian-marie yes, thanks all
