### ISSUE TITLE
Memory leak in servant-client

### ISSUE THREAD

**Issue by edsko** [haskell-servant/servant#656]
Although the `Req` type uses a lazy bytestring for the `reqBody`, this lazy bytestring is fully evaluated in memory. Here's a test case against servant 0.9.1.1:

``` haskell
{-# LANGUAGE DataKinds             #-}
{-# LANGUAGE FlexibleInstances     #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings     #-}
{-# LANGUAGE ScopedTypeVariables   #-}
{-# LANGUAGE TypeFamilies          #-}
{-# LANGUAGE TypeOperators         #-}

module Main (main) where

import Control.Monad.Except
import Network.HTTP.Media
import Network.Wai
import System.Environment
import qualified Data.ByteString          as Strict
import qualified Data.ByteString.Lazy     as Lazy
import qualified Network.Wai.Handler.Warp as Warp
import qualified Network.HTTP.Client      as Client

import Servant
import Servant.Client
import Servant.Common.Req (setRQBody)
import Servant.Server.Internal.RoutingApplication

{-------------------------------------------------------------------------------
  Large request bodies

  This allows clients to explicitly provide a lazy bytestring
-------------------------------------------------------------------------------}

data LargeBody

instance HasClient sub => HasClient (LargeBody :> sub) where
  type Client (LargeBody :> sub) = Lazy.ByteString -> Client sub

  clientWithRoute Proxy req bs =
      clientWithRoute
        (Proxy :: Proxy sub)
        (setRQBody bs genericMediaType req)
    where
      genericMediaType :: MediaType
      genericMediaType = "application"//"octet-stream"

instance HasServer sub ctxt => HasServer (LargeBody :> sub) ctxt where
  type ServerT (LargeBody :> sub) m = IO Strict.ByteString -> ServerT sub m

  route Proxy ctxt sub =
      route
        (Proxy :: Proxy sub)
        ctxt
        (addBodyCheck sub (withRequest (return . requestBody)))

{-------------------------------------------------------------------------------
  Test API
-------------------------------------------------------------------------------}

type API = LargeBody :> Post '[JSON] NoContent

testServer :: Server API
testServer getChunk = liftIO dumpChunks
  where
    dumpChunks :: IO NoContent
    dumpChunks = do
      bs <- getChunk
      if Strict.null bs
        then return NoContent
        else Strict.putStr bs >> dumpChunks

testClient :: Client API
testClient = client (Proxy :: Proxy API)

{-------------------------------------------------------------------------------
  Test executables
-------------------------------------------------------------------------------}

runServer :: IO ()
runServer = Warp.run 22089 $ serve (Proxy :: Proxy API) testServer

runClient :: FilePath -> IO ()
runClient file = do
    bs      <- Lazy.readFile file
    manager <- Client.newManager Client.defaultManagerSettings
    result  <- runClientM (testClient bs) (ClientEnv manager baseUrl)
    case result of
      Left  err       -> putStrLn $ "Error " ++ show err
      Right NoContent -> return ()
  where
    baseUrl :: BaseUrl
    baseUrl = BaseUrl Http "localhost" 22089 ""

{-------------------------------------------------------------------------------
  Top-level application
-------------------------------------------------------------------------------}

main :: IO ()
main = do
    args <- getArgs
    case args of
      ["server"]       -> runServer
      ["client", file] -> runClient file
      _otherwise       -> putStrLn "invalid arguments"
```

When we then start the server and use the client to upload a largeish file (64M) to the server, the server behaves itself:

```
       5,809,272 bytes allocated in the heap
         433,440 bytes copied during GC
         101,848 bytes maximum residency (2 sample(s))
          18,672 bytes maximum slop
               1 MB total memory in use (0 MB lost due to fragmentation)
```

but the client does not:

```
      71,456,344 bytes allocated in the heap
         577,064 bytes copied during GC
      41,057,560 bytes maximum residency (7 sample(s))
       8,380,424 bytes maximum slop
              77 MB total memory in use (2 MB lost due to fragmentation)
```

Incidentally, in our code base we use servant 0.8.1, which suffers from the same problem.

**Comment by alpmestan** [comment]
Hmm, interesting.

For reference, this is where we turn a `Req` into an http-client `Request`: https://github.com/haskell-servant/servant/blob/master/servant-client/src/Servant/Common/Req.hs#L133

From a quick look at it, I don't see anything there that could cause the leak. I'm wondering though if we could entirely eliminate this class of problems by using another constructor than `RequestBodyLBS`, e.g one of the streaming ones (see [here](https://hackage.haskell.org/package/http-client-0.5.5/docs/Network-HTTP-Client.html#g:10)).

If you don't have time to investigate, I'll get around to it eventually but I have many items on my TODO.

**Comment by kosmikus** [comment]
@alpmestan Yes, I think you're right and we should allow the streaming request bodies. I suggest to just allow setting any `RequestBody`. The current implementation of servant-client is already very specific to the http-client package, so exposing implementation details of http-client should not be a huge issue.

I've created PR #661 as a basis for discussion. With this, @edsko 's example can be changed to say:
```
runClient :: FilePath -> IO ()
runClient file = do
    b       <- Client.streamFile file
    manager <- Client.newManager Client.defaultManagerSettings
    result  <- runClientM (testClient b) (ClientEnv manager baseUrl)
    case result of
      Left  err       -> putStrLn $ "Error " ++ show err
      Right NoContent -> return ()
  where
    baseUrl :: BaseUrl
    baseUrl = BaseUrl Http "localhost" 22089 ""
```

It seems to run in constant space for me then.

**Comment by phadej** [comment]
@kosmikus just a note: OTOH it would be great to have servant-client actual http-lib agnostic (or at least not to make it too hard to generalise later)

**Comment by kosmikus** [comment]
@phadej Yes, I think it'd be good to separate out the backend-agnostic parts from the backend-specific parts in the longer term. But I don't think we can ever hope to be fully backend-agnostic. Specific libraries (such as now, wai and http-request) will always offer rather specific features that users also want to make use of. If we want to be fully compatible between a wide range of low-level libraries, we always have to limit ourselves to the common subset of functionality. So I think the only thing we can reasonably strive for is to make it easy/easier to switch between low-level libraries by separating as clearly as possible from features that are specific to one and features that we expect to be agnostic.

**Comment by alpmestan** [comment]
Right, this doesn't have to happen in the next release though, this will require a lot of time and thought given to it. However we do want to allow constant-time request body sending, in all circumstances, as it otherwise very much limits the usefulness of servant-client (only small request bodies).

**Comment by kosmikus** [comment]
@alpmestan Ok. We should wait for @edsko to confirm that this does indeed fix his situation, too, and not just the simplified example he created. Also, we should then agree on the actual name(s) being exposed. I chose `setReqBody` for the new function because it was free and because `setRQBody` is a naming scheme I cannot completely explain anyway. But having both function, especially without comments, is not very nice. Any better suggestions?

**Comment by alpmestan** [comment]
So we should make it clear that one is specific to constructing an request body as a lazy bytestring while the other is a generalization that allows any request body type. Maybe `setRQBodyLBS` vs `setRQBody`? I'd probably like `setReqBodyLBS`/`setReqBody` better, actually.

**Comment by edsko** [comment]
So I can confirm that this does indeed solve the memory leak in the larger project as well. 

However, if the current HEAD is released as the new servant-client, it will also need a new release of servant because it uses some functionality not available in the released version of servant; but the current HEAD of servant has a backwards incompatible change with the released version of servant as it now uses `:~>` from `natural-transformation`, where the constructor is called `NT` rather than `Nat`.

**Comment by kosmikus** [comment]
Hm, if the version number synchronization between the different packages is kept, this then means that the new servant-client should be released as 0.10 probably, and the `@since` annotations I added in the Haddock comments should be changed again as well.

**Comment by phadej** [comment]
@kosmikus, we can correct them before publishing the release

**Comment by alpmestan** [comment]
Yeah I think we'll just go with 0.10 for all the core packages. Glad to know this fixed the issue in your program @edsko :)

**Comment by jkarni** [comment]
Can we close this now that #661 has been merged?

**Comment by phadej** [comment]
Yes we can :muscle:!
