### ISSUE TITLE
Clarify serveDirectory indexing

### ISSUE THREAD

**Issue by Crote** [haskell-servant/servant#657]
`Servant.Utils.StaticFiles.serveDirectory` currently uses WAI's `defaultFileServerSettings`, which mean that a directory index is automatically served when no `index.html` exists. This behaviour may be undesirable for many users and is not documented form `serveDirectory`.

As most applications using servant's `serveDirectory` will be webapps, the behaviour of `defaultWebAppSettings` would seem more appropriate: no directory indices and aggressive caching.

I'd like to suggest adding a second method which uses `defaultWebAppSettings` and clearly documenting which behaviour one should expect from each.

**Comment by alpmestan** [comment]
How about [this commit](https://github.com/haskell-servant/servant/commit/66455f7dfe99f17bdd0aa1e43fadba0ee3a3b10f) ?

**Comment by Crote** [comment]
Yeah, that's pretty much exactly what I had in mind.

Just one small thing: this completely removes `serveDirectory`. Wouldn't it be better to leave it in, albeit deprecated, to avoid breaking existing software?

**Comment by alpmestan** [comment]
Yeah, I guess it can't hurt to give users a bit of time to switch over =) Will do this and open a PR.

**Comment by alpmestan** [comment]
@Crote PR got merged (see #658). Do you think we can close this issue?

**Comment by Crote** [comment]
Yes, many thanks!
