### ISSUE TITLE
How can i keep back the old file in server when update a new file?

### ISSUE THREAD

**Issue by cp1319421** [haskell-servant/servant#662]
like below picture, when i update the BOM file, i want to keep back the old BOM file in server folder, the database can be changed

![default](https://cloud.githubusercontent.com/assets/19610257/21917220/3fdd99ec-d981-11e6-98a1-527928f652ff.PNG)

**Comment by phadej** [comment]
Is this issue to the right repository? How it's related to the `servant` (the haskell web framework?)

**Comment by jkarni** [comment]
Closing - please reopen if you feel like this was a mistake.
