### ISSUE TITLE
Missing MonadBase instance for ClientM

### ISSUE THREAD

**Issue by edsko** [haskell-servant/servant#663]
It's easily defined

``` haskell
instance MonadBase IO ClientM where
  liftBase = ClientM . liftBase
```

but I don't know if this will cause an additional unwanted dependency.

Incidentally, why is the `ClientM` monad hardcoded? It would be nicer if we could define our own, just like we can for the server.

**Comment by phadej** [comment]
For the record, `transformers-base` doesn't bring in anything else than itself. Also `monad-control` adds only itself (and `transformers-base`). I'm ok with defining instances for classes in these packages.

**Comment by phadej** [comment]
Hmm. Maybe it can be made so `client` returns `forall m. (MonadIO m, MonadError e m) => m ...`, but will it gain *anything* (I know we will lose things)

**Comment by edsko** [comment]
I was thinking something more along the line of `ClientT ... m`, just like for `ServerT`.

**Comment by phadej** [comment]
@edsko On the other hand, I'm not sure there is that many applications having

```hs
client HasServer CustomCombinator :> api where
    type ServerT (CustomCombinator :> api) m = ServerT api (CustomT m)
```

as in practice you have to run the `CustomT` in the `route` implementation. But if you have some cool tricks, please share. We are looking for "advanced examples" for the tutorial.

In fact, all combinators in `servant-server` (AFAICS) could be rewritten with more simple:

```hs
class HasServer api where
  type ServerM api :: *

  route ::
       Proxy api
    -> Context context
    -> Delayed env (ServerM api)
    -> Router env
```

Also if you want to do something like that for `Client` (i.e. have a use case in mind), please open another issue.

**Comment by phadej** [comment]
And to return to this issue: @alpmestan I'm very lenient with adding "not far from Haskell Platform"  upto `lens` -dependencies, as we use e.g. `swagger2` so it's all there anyway (later or sooner).  What is  `servant`'s policy?

**Comment by edsko** [comment]
No, but in the server it's easy to replace the underlying monad completely (which I do all the time since `EitherT` does not play nice with exceptions as it does not and cannot implement `MonadMask`). But in the client I cannot use a application specific client monad at all.

**Comment by edsko** [comment]
While we're at it, this instance is also missing (and it wrecks my head every time I have to define it :)

``` haskell
type ClientM' = ReaderT ClientEnv (ExceptT ServantError IO)

instance MonadBaseControl IO ClientM where
  type StM ClientM a = StM ClientM' a

  liftBaseWith :: (RunInBase ClientM IO -> IO a) -> ClientM a
  liftBaseWith f = ClientM (liftBaseWith (\g -> f (g . runClientM')))

  restoreM :: StM ClientM a -> ClientM a
  restoreM st = ClientM (restoreM st)
```

**Comment by edsko** [comment]
That one relies on `monad-control`.

**Comment by alpmestan** [comment]
To be entirely honest, I don't feel like it's appropriate to reject instances that "force" us to bring in 2 more small deps, when our transitive dependency chain is so large already. I mean, we should not be looking to double the number of transitive deps for servant, but sensible instances that are needed and that don't make us pull another 20 deps should be accepted IMO.

Regarding the policy itself, I think that's pretty close to what we've been doing so far, but it's not set in stone :)

**Comment by phadej** [comment]
@edsko do you want to make a PR?

**Comment by edsko** [comment]
Thanks @phadej !
