### ISSUE TITLE
Out-of-the-box configurable server

### ISSUE THREAD

**Issue by alpmestan** [haskell-servant/servant#689]
This is mostly to act as a summary of a discussion that I had with @dcoutts this week, though if we consider that this proposal makes sense, we can certainly go ahead and implement it in servant-server.

Note that this is in the same alley (but generalizes a fair bit) as @jkarni's https://github.com/haskell-servant/servant/issues/685. Duncan and I thought of the same thing sometimes this week independently to address the same problem.

# Problem

Currently, the behavior of the routing machinery as well as that of all existing combinators is fixed and we have no way whatsoever to tweak any of it. What if we'd like to add some "hooks" to be called here and there instead?

Examples:
- what if we're not happy with the standard error responses and instead would like JSON errors all the time, for all the HTTP errors _thrown by the router_? (see #685)
- what if we'd like to see some debugging output to figure out which endpoint a given request is routed to (see https://github.com/haskell-servant/servant/issues/449)?
- what if we'd like to allow the server to be more lenient with respect to content types, e.g make checks on the request's `Content-Type` header optional, because of some existing clients that don't follow the HTTP RFCs?
- etc

# Solution

Augment the default context with either:
- a bunch of entries for each configurable bit at the toplevel, or
- a named subcontext with a bunch of entries in it, one for each configurable bit, or
- a single context entry of some `ServerCfg` data type, with a field for each configurable bit.

(I'd go for 2, 3, 1, in that order, I think)

By "augment", here, I mean that the `serve*` functions would now require that the context contains at least our server configuration (whatever its final form is), and `serve` would just use some default behavior (e.g the current one).

We could alternatively do lookups in the context and do some standard thing if no "hook" is provided by the user, allowing us to still be able to work with an empty `Context`. I don't like this idea though because the default config would be "implicit", spread accross all the `HasServer` instances, instead of in one place.

It's important to notice that, while this would be a pervasive change, it would provide us with a definitive solution to "I'd like to make combinator X do Y instead of what it currently does", most of the time forcing people to duplicate an existing combinator, only to override the behavior of one bit of the `HasServer` instance. They would only have to find the right config entry to tweak some particular behavior, override it in their code, done.

This is similar (but broader) to #685, but Duncan and I came up with this "feature request" independently, initially to address the same problem as Julian, but we then realized we probably want to go further down that road. There are many excellent reasons to write custom combinators & `HasServer` instances, but tweaking the behavior of one line or two in an existing combinator's `HasServer` instance is not one of them in my opinion.

I do not have (yet) the list of configuration entries, but if we decide that this proposal makes sense, we can work on that and then decide by looking at all the `HasServer` instances what should be made configurable and what should not. We could go pretty far, as virtually anything but the actual "shape"/"structure" of the `HasServer` instances can be made configurable. We could however start small and address the few questions in the **Problem** section above and see where that leads us.

A disadvantage of this proposal is that we'd spend more time doing `Context` lookups. We could however (probably quite easily) switch to an heterogeneous vector/map. Not without making sure it's worth it, as there might only be a dozen lookups in a small list during the routing of some request. This could be a good occasion to go over the `Context` module and offer a more extensive (e.g context lookups that can fail, that I implemented [here](https://github.com/haskell-servant/servant-multipart/blob/master/src/Servant/Multipart.hs#L374), as well as maps/traversals, etc) & user-friendly API to manipulate `Context`s.

Note that we could probably define a combinator for "overriding" the configuration only in some part of an API. Its `HasServer` instance would recurse into the subapi but with a "modified context", using some user supplied function or another mechanism. This, along with the rest of this proposal, would give a pretty solid answer to the "configuration problem" that many users have encountered.

**Comment by phadej** [comment]
I'm :+1: to solving the problem. 

---

But before I have to ask, why whole context thing is looking like *extensible-records*, why we don't have e.g.

```haskell
class HasAuthInfo ctx where
    getAuthInfo :: ctx -> AuthInfo -- or Lens', or ...

instance HasAuthInfo AuthInfo where
    getAuthInfo = id

instance (HasAuthInfo ctx, HasServer api ctx) => HasServer (Auth :> api) ctx where
   ....
```

IMHO having direct `Has*` classes would be less opinionated choice: you could still use your favourite extensible records lib to avoid boilerplate, but you could use something else as well.

---

In that light, I'd rather change `route` to take yet another `Reader` argument (so we don't use context).

---

IMHO how we present error messages could and maybe should be solved separately. E.g. `ServantErr` could be changed to sum, where to current "final" variant, we could have more high level errors, which `servant` user could provide presenters for. I have to thing about this more.

**Comment by jkarni** [comment]
It wasn't clear to me - is there anything essentially different about the
proposal here? If not, I'd rather have separate issues for each problem we
actually want to solve with Context rather than one big one for the general
idea.

**Comment by alpmestan** [comment]
Well, that's the point. I want us to avoid redoing the very same kind of work just for another problem, over and over. Let's give them a decent number of configuration knobs out of the box, with some easy to use machinery for adding other knobs.

**Comment by jkarni** [comment]
Why redoing? It seems like a pretty easily separated task.

 This was part of the idea behind Context all along (that it could be used
for further configuration - indeed, that's exactly what Context is), and
one of the things that seemed appealing was how orthogonal each piece of
configuration would be. Sönke and I then didn't go beyond auth for this
reason, and because we're generally in favour of smaller tasks.

That said, if you want to write all of it in one go, I don't oppose! It'll
involve a lot more design discussion and review time (just think of how
much thought is involved in just the task of well-designed custom errors!),
but if someone is willing to do the work of writing it all I'm happy to do
the reviewing and discussion.

**Comment by alpmestan** [comment]
Yes, but if we leave everything for the user to do then we're not doing anything. Whereas I'm suggesting that we offer a few such config knobs out of the box.

**Comment by jkarni** [comment]
Hm, maybe I'm misunderstanding. I don't see how it'd be leaving everything to the user. I was just suggesting splitting up the task, and try to understand each problem and application separately.

**Comment by phadej** [comment]
@jkarni: I'd separate the "configuring API combinators" and "presenting errors". Latter could be done as an instance of the former, but then you'd always need to

```haskell
throwError $ amendError (getContextEntry errorAmander) err418 { errBody = "Do you ask me to make coffee?" }
```

Where i'd rather continue having
```haskell
throwError err418 { errMsg = "Do you ask me to make coffee?" }
```
and have `ServantErr -> Response` function separately.

---

I'd rather not to use `Context`, as I'm not convinced having yet-another *extensible-record* like construct in `servant` is good idea. With `class HasConfigFor ctx where fooConfig :: Lens' ctx FooConfig` would also solve 

> Note that we could probably define a combinator for "overriding" the configuration only in some part of an API

I haven't found a PR / discussion about implementation of Context. Why it's own implementation, and not e.g `labels` or `vinyl` or `fclabels`. Kind of the same issue as with `resourcet`. Maybe I'll should open separate issue about this.

**Comment by sboosali** [comment]
I agree with @phadej about using an existing record library. `vinyl`'s "each field is in the same functor" might be able to help with linking up routes with types, but any record library (especially ones with support for lenses over `Symbol`-named fields) should work.

**Comment by jkarni** [comment]
Can this be closed? `Context` now has many of these things.

**Comment by gdeest** [comment]
Agreed, context and named contexts seem to fit the original purpose sufficiently well.
