### ISSUE TITLE
Permit zero content types for empty response

### ISSUE THREAD

**Issue by rimmington** [haskell-servant/servant#69]
The instances for `HasClient` match on the type-level cons eg.

```haskell
instance HasClient (Delete (ct ': cts) ())
```

For empty responses, there isn't a need for any content types; in fact, `ct` and `cts` aren't used in the instance body.

**Comment by rimmington** [comment]
I tried writing a simple PR for this but ran into overlapping instances issues; I'm hoping someone will have a better idea than writing a bunch of `HasClient (Method '[] ())` instances.

**Comment by rimmington** [comment]
This also crops up when writing documentation:

```
Could not deduce (Servant.API.ContentTypes.IsNonEmpty '[])
      arising from a use of ‘docs’
```

**Comment by jkarni** [comment]
Good call, and thanks. For the client, it should be as simple as changing, e.g.:
```
instance
#if MIN_VERSION_base(4,8,0)
         {-# OVERLAPPING #-}
#endif
  HasClient (Delete (ct ': cts) ()) where
  type Client (Delete (ct ': cts) ()) = EitherT ServantError IO ()
  clientWithRoute Proxy req baseurl =
    void $ performRequestNoBody H.methodDelete req [204] baseurl
```
To
```
instance
#if MIN_VERSION_base(4,8,0)
         {-# OVERLAPPING #-}
#endif
  HasClient (Delete cts ()) where
  type Client (Delete cts ()) = EitherT ServantError IO ()
  clientWithRoute Proxy req baseurl =
    void $ performRequestNoBody H.methodDelete req [204] baseurl
```

I'd have to look into servant-docs - it might involve further overlapping instances.

**Comment by codedmart** [comment]
@jkarni I will take another stab at this in the morning if you haven't got to it.
