### ISSUE TITLE
how to properly handle enums

### ISSUE THREAD

**Issue by joaomilho** [haskell-servant/servant#695]
So I have an API definition that gets a locale in the ReqBody. I have defined a type called Locale, so I don't need to accept all kind of string (a common thing to do in swagger/json-schema). Something like:

```hs
data Locale = EnUS | SvSE | ...
  deriving (Eq, Enum, Generic)
```

Then I implement both `Read` and `Show` for `Locale`, mapping it to "en-US", "sv-SE" ...

But when I try to post it via curl I get...

```sh
$ curl -H "Content-Type: application/json" \
     -X POST \
     -d '{"locale": "sv-SE"}' \
     http://localhost:8080/endpoint

Error in $: The key "sv-SE" was not found%
```

Using "EnUS" and "SvSE" work 'though. Maybe I'm not getting how it's supposed to work, but I expected servant would try to convert a received value to my defined type.

Any tip?

**Comment by jkarni** [comment]
Can you post your API type and relevant FromJSON instance?

**Comment by fizruk** [comment]
This part of the error message:

```
The key "sv-SE" was not found
```

Suggests that you probably have one of the constructors non-nullary. That is some constructor of `Locale` needs arguments. This changes JSON representation for all the nullary constructors from just `"sv-SE"` to `{"sv-SE": []}` (if you're using `ObjectWithSingleField` sum encoding).

Can you show the entire `Locale` data type and `FromJSON` instance?

**Comment by joaomilho** [comment]
Yes, it was late at night and I wasn't thinking straight. While I was about to sleep I realized that what I have to do is to have a custom FromJSON implementation (I was using Generics). I'll give it a try and let you know.

**Comment by joaomilho** [comment]
Yeap

```
instance FromJSON Locale where
   parseJSON (String "en-US") = return EnUS
   parseJSON (String "sv-SE") = return SvSE
   parseJSON _ = error "Locale must be one of en-US/sv-SE"
```

Does the trick 😃

**Comment by fizruk** [comment]
@joaomilho please, use `fail` in place of `error` so that your server will result in a `400 Bad request` error, not `500 Internal server error`.

I'm not sure if it was implemented yet, but using `fail` should propagate the error message to the response body, so when your client sends invalid request he/she knows what was wrong.

**Comment by phadej** [comment]
This is `aeson` not `servant`s issue.

The `Read` and `Show` aren't related to `ToJSON` / `FromJSON` anyhow.

You should read about `Options:` http://hackage.haskell.org/package/aeson-1.1.0.0/docs/Data-Aeson-Types.html#t:Options

```haskell
>>> data Locale = EnUS | SvSE deriving (Eq, Show, Generic)
>>> instance ToJSON Locale where toJSON = genericToJSON defaultOptions { constructorTagModifier = map toLower } 
>>> encode EnUS
"\"enus\""
```

(I'm using simpler constructor name mangling here)
