### ISSUE TITLE
Custom error responses

### ISSUE THREAD

**Issue by thsutton** [haskell-servant/servant#7]
It would be useful if servant supported custom HTTP error responses in addition to `NotFound`, `WrongMethod`, and `InvalidBody`.

I'd be happy to add such support, but would like confirmation this feature would actually be merged before spending the time. Is this a contribution you would accept in servant?

**Comment by jkarni** [comment]
If you return a `left` with an `(Int,String)` from your handle (in the `EitherT` monad)r, the endpoint will respond with that status code and message. Is that not sufficient for your use case?

**Comment by thsutton** [comment]
I'm doing it in the `HasServer(route)` implementation for a custom type rather than in a handler.

I'm currently just using `succeedWith` in these cases, but would like to have a similar API for my "401 Unauthorized", etc. responses as with the existing `NotFound`, `BadBody`, etc.

**Comment by jkarni** [comment]
I see. We can definitely support more error responses in that case, and would welcome a PR.

**Comment by thsutton** [comment]
Great! I'll open a PR first thing tomorrow morning (GMT+1100).
