### ISSUE TITLE
Details on `Context`, and using it in place of Reader?

### ISSUE THREAD

**Issue by freckletonj** [haskell-servant/servant#700]
While trying to figure out how to pass in a pool of DB connections, I considered using `Context`, and came across the following, in `Context.hs`. Could you help me understand what Contexts are, and why they're not fit to replace a Reader monad in this context?

```
-- (They are __not__ meant
-- to be used to pass parameters to your handlers, i.e. they should not replace
-- any custom 'Control.Monad.Trans.Reader.ReaderT'-monad-stack that you're using
-- with 'Servant.Utils.Enter'.)
```

**Comment by phadej** [comment]
`Context` is used to pass stuff to combinators (e.g. `Capture`, or `QueryParam`, though these don't use context, the only build ones are authentication related). `Reader` / *partial-application* is OTOH much simpler way to pass stuff to your `Handler`s.

Another way to see it, is that in the `API` type like:

```haskell
type API => UsesDBConnection :> "foo" :> Get '[JSON] Payload
```

the `UsesDBConnection` is little use for `servant-docs` or `servant-client`.
