### ISSUE TITLE
Dead link in servant-docs description

### ISSUE THREAD

**Issue by Xandaros** [haskell-servant/servant#703]
The link to the runnable example in the [description of servant-docs](https://github.com/haskell-servant/servant/blob/master/servant-docs/servant-docs.cabal#L7) points to a non-existent repo.
I assume that `servant-docs` used to be in its own repo and was recently moved into the main `servant` repo. The link still points to the old repo.

**Comment by cjnickel** [comment]
This looks like it was fixed in https://github.com/haskell-servant/servant/commit/2d271dc1276f5fab09687e04b5e041730f56b373.

**Comment by alpmestan** [comment]
Wow, thanks for checking, I'm closing the issue then.
