### ISSUE TITLE
servant-foreign rewriting "." in path with "_"

### ISSUE THREAD

**Issue by chris-kahn** [haskell-servant/servant#707]
When deriving client code with `servant-js`, it seems to erroneously rewrite `.` into `_` even though it's valid to appear within the path component. For example many restful APIs include a version number using a `.`, like Twitter: `https://api.twitter.com/1.1/statuses/home_timeline.json`

`/1.1/statuses/home_timeline.json` is a valid path but it will be rewritten to `/1_1/statuses/home_timeline.json` which we don't want.

**Comment by chris-kahn** [comment]
Perhaps this was done for the JavaScript function names? 

The function will be named like `function get1_1StatusesHomeTimeline`, so we want to rewrite the function name, but not the actual URL path.

**Comment by phadej** [comment]
IIRC the `servant-foreign` doesn't mangle the names anymore, are you sure it's not the code in `servant-js`. Please provide a failing test case.

**Comment by chris-kahn** [comment]
Oh, you're right, my bad! I see it was just recently fixed in 0.10... I'll close this for now
