### ISSUE TITLE
XML Content Types

### ISSUE THREAD

**Issue by ivan-m** [haskell-servant/servant#711]
At the top of [Servant.API.ContentTypes](https://github.com/haskell-servant/servant/blob/master/servant/src/Servant/API/ContentTypes.hs) the Haddock documentation references an example usage of an XML content type.

Does such an instance exist (or did so in the past)?  The only other mention of XML I can find is in generation of Markdown documentation.

**Comment by phadej** [comment]
AFAIK there isn't. It's simple to add, see e.g. http://hackage.haskell.org/package/servant-lucid-0.7.1/docs/src/Servant-HTML-Lucid.html, but one have to find a library doing all the heavy lifting, i.e. xml serialization (and parsing).

**Comment by ivan-m** [comment]
That's what I thought; the closest I've come across is HXT's Pickling support, but it's typeclass is very limited in terms of data types covered (and with no in-built Generics/DefaultSignatures support either, making instances more verbose).

**Comment by fizruk** [comment]
We use [`xml-picklers`](https://hackage.haskell.org/package/xml-picklers) for our very limited use of XML (together with `xml-conduit`, `xml-conduit-writer` and `xml-types`).

**Comment by phadej** [comment]
`xml-picklers` doesn't seem to provide type-classes to do conversions, do you have your own, @fizruk? Does it make sense to create `servant-xml-picklers` ?

**Comment by ivan-m** [comment]
If I were to write `servant-xml-picklers`, would it be worth putting a type class (+ instances) into that library or trying to get one upstream?

**Comment by ivan-m** [comment]
(My interest in this is I have to write a server to receive data from a third party that are only starting to consider using this new-fangled JSON technology and thus want to provide XML data, even though it's simple enough to be JSON.)

**Comment by phadej** [comment]
@ivan-m It depends. As you, I'd start small and implement everything needed in your app. With experience it's much easier to make design decisions, what works and what not. Sorry, but you are a bit on your own with XML stuff.

**Comment by fosskers** [comment]
Am I late to the party? Here's some simple XML support: https://hackage.haskell.org/package/servant-xml

**Comment by alpmestan** [comment]
@fosskers There's no such thing as being late to the servant party... whatever that means. 

Cheers for putting that package together. Feel free (if you want to) to send PRs to the tutorial or cookbook etc if you want to document this library further (e.g a cookbook recipe about dealing with XML in request/response bodies?) as well as I guess make it a little more discoverable.

**Comment by fosskers** [comment]
> The limitation of this library is that it only supports MimeRender, not MimeUnrender.

At least for the first release I followed the model of `Servant.HTML.Lucid`. Luckily `xmlbf` does also have a `FromXml` typeclass, so I could add support for `MimeUnrender`. Do people send XML in request bodies?

**Comment by fosskers** [comment]
I updated `servant-xml` to include a `MimeUnrender` instance.
