### ISSUE TITLE
Pull out BaseUrl (etc.) into Servant or another core library

### ISSUE THREAD

**Issue by 3noch** [haskell-servant/servant#712]
Right now `BaseUrl` (etc.) is baked into servant-client which is a very *particular* implementation of an API client. However, `BaseUrl` is useful for almost all client implementations. I've seen the code duplicated and now I am tempted to duplicate it myself. Since it's nothing more than a simple data type it might be worth just putting it in `servant` directly. By itself it won't add any meaningful cost to dependencies that don't use it.

**Comment by phadej** [comment]
There is a plan to make `servant-client` implementation agnostic. The `BaseUrl` would be shared during that naturally.

But for now, I don't think `BaseUrl` belongs to `servant`. It's clients' type. But it's too early to make
- `servant`
- `servant-client-commons`
- `servant-http-client`
split.

**Comment by 3noch** [comment]
Is this done now that #803 is merged?

**Comment by jkarni** [comment]
Yeah, it now exists in `servant-client-core`, which seems more sensible. (Whether we should be using `BaseUrl`, or something like `uri-bytestring`, it to my mind a separate question.)

**Comment by 3noch** [comment]
Great! I'll close this then.
