### ISSUE TITLE
servant-client's ConnectionError wraps itself in SomeException

### ISSUE THREAD

**Issue by 3noch** [haskell-servant/servant#714]
Using Servant 0.9.1.1, when I deconstruct a `ServantError` to see a `ConnectionError`, I've found that the `SomeException` inside `ConnectionError` contains, surprisingly, a `ServantError`!

```haskell
tryTlsOrDegrade :: (Scheme -> IO (Either ServantError a)) -> IO (Either ServantError a)
tryTlsOrDegrade req = do
  secureResponse <- req Https
  case secureResponse of
    Left (ConnectionError connE) -> case fromException connE of
      Just (ConnectionError connE2) -> print "Found it" >> pure secureResponse
      _ -> print connE >> pure secureResponse
    _ -> pure secureResponse
```

Both `connE` and `connE` are `SomeException`.

Perhaps I'm doing this wrong.

**Comment by 3noch** [comment]
This is what I ended up with:

```
tryTlsOrDegrade :: (Scheme -> IO (Either ServantError a)) -> IO (Either ServantError a)
tryTlsOrDegrade req = do
  secureResponse <- req Https
  case secureResponse of
    Left (ConnectionError connE) -> case fromException connE of
      Just (ConnectionError connE2) -> case fromException connE2 of
        Just (HttpExceptionRequest _ TlsNotSupported) -> req Http
        Nothing -> pure secureResponse
      Nothing -> pure secureResponse
    _ -> pure secureResponse
```

**Comment by jkarni** [comment]
The `ConnectionError` now only contains `Text`. Less informative, but we wanted to not depend on `http-client`-specifics. 

If it feels like that's insufficient (i.e., you need to distinguish `TlsNotSupported` in a more reliable way than text parsing), please open a new issue!

**Comment by 3noch** [comment]
@jkarni Yes that's unfortunate. What should my new issue be exactly?

**Comment by 3noch** [comment]
Could the error type be parameterized somehow instead?

**Comment by jkarni** [comment]
Agreed - my fault! Maybe we can get this fixed before ever releasing `master`. How about "More informative `ConnectionError`"?

**Comment by jkarni** [comment]
If some backend is less informative than another, there's no actual problem - we can just have as many constructors as we think make sense, and some backends can just choose less informative ones (e.g. a default `OtherConnectionError`)

**Comment by 3noch** [comment]
@jkarni Done

**Comment by ocharles** [comment]
What was the need to drop `SomeException` and the switch to `show`ing the exception and packing it as `Text`? Surely a better fix would have been fixing the actual bug that 3noch was experiencing by not double wrapping things?
