### ISSUE TITLE
linkURI adds unwanted `[]` to specified parameter names for QueryParams

### ISSUE THREAD

**Issue by mpilgrem** [haskell-servant/servant#715]
`linkURI`, in generating a `URI` from a `Link`, adds `[]` to the end of the specified parameter names for `QueryParams`, which consequently generates URIs that are inconsistent with those generated by the use of `client`.

~~~~
linkURI :: Link -> URI
...
    makeQuery (ArrayElemParam k v) = escape k <> "[]=" <> escape (Text.unpack v)
~~~~

This has been problematic for me, because I am seeking to query an API that encourages (and sometimes requires) the initial request to be digitally signed using HMAC-SHA1 in producing the final request (through the addition of a `signature=<CALCULATED_SIGNATURE>` parameter). I was expecting to be able to use `linkURI` to generate a copy of the relevant part of the URI that I could then sign, not a different URI.

If the behaviour of `linkURI` is fixed, perhaps a function `linkURI' :: Bool -> Link -> URI` could also be provided, with the `Bool` argument providing a switch between adding the `[]` or not.

**Comment by phadej** [comment]
So do I understand right, there is inconsitency between `servant-server`, `servant-client` and `servant` (`Links`) in how they handle `QueryParams`?

AFAICS `Links` and `HasServer` are consistent, aren't they?

**Comment by phadej** [comment]
I see, `HasServer`:

> Lookup the values associated to the sym query string parameter and try to extract it as a value of type [a]. This is typically meant to support query string parameters of the form param[]=val1&param[]=val2 and so on. Note that servant doesn't actually require the []s and will fetch the values just fine with param=val1&param=val2, too.

So is `servant-server` not accepting either one?

**Comment by mpilgrem** [comment]
I've not used the `server` side of `servant`, but, as far as I can see, the 'problem' (from my perspective) is limited to function `linkURI` and the `safeLink` side of things in `Servant.Utils.Links`:

* as you identify, the `server` side is tolerant of incoming requests with `[]` added on to the parameter names specified in the API (`looksLikeParam name = name == paramname || name == (paramname <> "[]")` in the instance for `HasServer`);

* the `client` side of things does not add `[]` on to specified parameter names in making requests (if you want a parameter name to end in `[]`, you have to specify that expressly) (I am looking here at `reqToRequest` in module `Servant.Common.Req`); but

* `linkURI :: Link -> URI` adds `[]` on to specified parameter names. I think `linkURI` is the only way to get an `URI` from an API specification.

As module `Servant.Utils.Links` does not export the constructors for type `Link`, it is not possible to 'fix' the problem outside of the module.

**Comment by mpilgrem** [comment]
To make things more concrete, I think if you have an API `QueryParams "markers" Markers :> Get ...`:

* the `server` side of things will be tolerant of `?markers[]=` (as well as accepting the specified `?markers=`);

* `client` will generate `?markers=` (which is what the `server` side is expecting); but

* `linkURI` will generate `?markers[]=` (which is inconsistent with what `client` will generate - my 'problem' when trying to digitally sign the URI that will be sent by `client`).

**Comment by phadej** [comment]
Ok,
- Let's have an internal module to reveal `Link`
- and more controversial, let's `client` generate the `[]` version?

@haskell-servant/maintainers opinions?

**Comment by mpilgrem** [comment]
Taking your two proposals above in reverse order:

1. I would oppose `client` adding `[]` to the specified parameter names of `QueryParams`, because it would break the use of `client` with (non-`servant`) servers that (1) did not specify parameter names ending in `[]` and (2) were not tolerant of alternative parameter names with `[]` added to the end. At the moment, if you want to use `client` with an API that does require `[]`, you can use APIs specified as such - for example, `QueryParams "markers[]" Markers :> Get ...`.

2. I don't think you need to compromise the current safety of `Link` by exposing its constructors if you either (1) fix `linkURI` to remove the adding of `[]` to specified parameter names; or (2) add and expose new function `linkURI' :: Bool -> Link -> URI` (say) that makes the adding of `[]` in generating the `URI` optional.

Option 2(1) is conceptually 'cleaner' (and would also 'fix' the instance of `ToHttpApiData` for `Link`, which uses `linkURI`), but would change the current behaviour of `linkURI`. Option 2(2) is less disruptive of some possible current use of `safeLink`, but also leaves the `ToHttpApiData` instance for `Link` unchanged.

In respect of my point 2(1) above, `linkURI` would become:
~~~~
linkURI :: Link -> URI
linkURI (Link segments q_params) =
    URI mempty  -- No scheme (relative)
        Nothing -- Or authority (relative)
        (intercalate "/" segments)
        (makeQueries q_params) mempty
  where
    makeQueries :: [Param Query] -> String
    makeQueries [] = ""
    makeQueries xs =
        "?" <> intercalate "&" (fmap makeQuery xs)

    makeQuery :: Param Query -> String
    makeQuery (ArrayElemParam k v) = escape k <> "=" <> escape (Text.unpack v) -- Changed behaviour
    makeQuery (SingleParam k v)    = escape k <> "=" <> escape (Text.unpack v)
    makeQuery (FlagParam k)        = escape k
~~~~

In respect of my point 2(2) above, `linkURI'` could be:
~~~~
linkURI' :: Bool -> Link -> URI
linkURI' addBrackets (Link segments q_params) =
    URI mempty  -- No scheme (relative)
        Nothing -- Or authority (relative)
        (intercalate "/" segments)
        (makeQueries q_params) mempty
  where
    makeQueries :: [Param Query] -> String
    makeQueries [] = ""
    makeQueries xs =
        "?" <> intercalate "&" (fmap makeQuery xs)

    makeQuery :: Param Query -> String
    makeQuery (ArrayElemParam k v) = escape k <> (if addBrackets "[]=" else "=") <> escape (Text.unpack v) -- Optional behaviour
    makeQuery (SingleParam k v)    = escape k <> "=" <> escape (Text.unpack v)
    makeQuery (FlagParam k)        = escape k
~~~~
and then `linkURI` is simply:
~~~~
linkURI :: Link -> URI
linkURI =linkURI' True -- no change in current behaviour
~~~~

**Comment by alpmestan** [comment]
I think I'd be in favor of 2.2: have another function that takes a boolean that lets a user specify whether she/he wants `[]` to follow the parameter name in the generated URI. We could alternatively tweak the `HasLink` instance for `QueryParams` (https://github.com/haskell-servant/servant/blob/master/servant/src/Servant/Utils/Links.hs#L206) to take a `([v], Bool)` instead of just a list of params (`[v]`) like now, where the user sets the boolean value to True when `[]` should be appended to the parameter name in the URI. It'd be a breaking change, yes, but it has the advantage of only needing to specify the `Bool` if you use `QueryParams` without having two functions. OTOH, for a given API, you probably want the `Bool` to be the same for all your `QueryParams` and there might not be a point in allowing a per-parameter policy.
