### ISSUE TITLE
How can I generate a random UUID for every request and make servant to include it in the logs?

### ISSUE THREAD

**Issue by sras** [haskell-servant/servant#719]
I would also like to pass it to the environment of a ReaderT in which my handlers run, so they can include the request id in any logs the write themselves.

Is this possible?

**Comment by arianvp** [comment]
Yes this is defenitely possible.  Check out the section on Natural Transformations in the tutorial: 
http://haskell-servant.readthedocs.io/en/stable/tutorial/Server.html#using-another-monad-for-your-handlers

I'm on my phone but I think this should work.   Using  Identity as base monad now, but any monad transformer stack should work:
```haskell
import Data.UUID
readerToHandler' :: forall a. Reader UUID a -> ExceptT SevantErr IO a
readerToHandler'  reader = do
    uuid  <- nextRandom
    return (runReader uuid reader)

readerToHandler :: Reader UUID :~> ExceptT ServantErr IO
readerToHandler = NT readerToHandler'

```

**Comment by axman6** [comment]
I have written a middleware in the past which added a UUID to the Vault, which could then be accessed by other parts of apps, including a modified logging middleware if you wanted. It was less than half an hour's time.

**Comment by sras** [comment]
@axman6 

Yes, did it via vault. Found a post later that describe this process [here](http://www.yesodweb.com/blog/2015/10/using-wais-vault). Might be helpful for any one who stumbles across this in the future...  

@arianvp 

My problem was not getting a different monad to work with servant. I am already using the process you outlined. It was how to generate the random id for every request and share the id between the logging middle ware and the function that runs the application monad.

I had to implement it via the 'Vault' that is attached to every request, as @axman6 has mentioned above..

**Comment by arianvp** [comment]
Ahhhh I see...  I misinterpreted.  If you want to share it with the logging middlware you'll have to use the Vault I think.

**Comment by alpmestan** [comment]
@sras Is this issue solved for you?

**Comment by sras** [comment]
@alpmestan Yes. It was a while back, but I did solve the issue using the Vault. I followed the process that is described in here https://www.yesodweb.com/blog/2015/10/using-wais-vault

**Comment by cbeav** [comment]
Yo @sras, doing something similar to your Vault solution and had a question. Adding WAI middleware to populate the Vault is great. The annoying part is then modifying an API with `:> Vault` and forcing handlers to explicitly have a Vault in their signature. Did you ever come up with a nice way of getting vault access from the `Handler` monad stack?

For context, my goal here is to wrap `runDB` executions with timing and logging "middleware" tying an ID from the overarching WAI `Request` onto all of its DB dependencies. Not sure if there's a more idiomatic way to do that.

**Comment by saurabhnanda** [comment]
> The annoying part is then modifying an API with :> Vault and forcing handlers to explicitly have a Vault in their signature. Did you ever come up with a nice way of getting vault access from the Handler monad stack?

Don't do that. If you are you using your own `AppM` monad, add the UUID as a field in your Reader environment. In the function that converts `AppM a -> ExcepT ServantErr IO a`, you will need to construct your Reader environment. Only in that function, access the Vault to get the UUID out, and construct your Reader environment with it.

Let me know if you need a simplified code snippet.

**Comment by saurabhnanda** [comment]
@cbeav and that will lead to a different question - if the UUID is going into the Reader environment, why put it in the Vault in the first place? This is because the Vault outlives the Reader environment and can be used for other purposes, like logging, and error reporting.

**Comment by cbeav** [comment]
Thanks for the quick response @saurabhnanda.

Right now my `Reader` access is straightforward enough:

```haskell
type ApiHandler = ReaderT AppState Handler

runApp :: AppState -> ApiHandler a -> Handler a
runApp = flip runReaderT
```
Right now it's kind of nice that `AppState` can be brought up and constructed once before starting up the server and never needs to be touched again. I guess I could add a non-strict `UUID` field and have middleware populate that. Is that what you're suggesting?

**Comment by cbeav** [comment]
Ah, think I got what you meant. A reasonable option here seems to be to change
```haskell
type ApiHandler = ReaderT (AppState, RequestState) Handler
```
and populate that in my `runApp`. Then all of my handlers can access both the fixed global state that never needs to be reallocated after startup, and some request state initialized per request at that `run` boundary.

**Comment by cbeav** [comment]
Hm. Still one problem. I think I do need to use `Vault` because I want Middleware-level logging that outlives the `Reader` state. Ideally I could set the `requestId` in the `Vault` and pull that somehow in my `runApp` to make that available in the `Reader`. But I'm lost on how to ever get access to the raw `Request` in the Servant `Handler`.

Thanks once more for the help.

**Comment by cbeav** [comment]
Here's the solution I've got right now. Is the answer ever not partial function application?

```haskell
middleware :: (UUID -> Application) -> Application
middleware app req sendResponse = do
  requestId <- nextRandom
  app requestId req $ \resp -> ...
```

Then in `Main`, expect this wacky middleware to give you just what you need:

``` haskell
middleware $ \requestStateId ->
  serveWithContext (Proxy :: Proxy Api) cfg $
  hoistServerWithContext
    (Proxy :: Proxy Api)
    (Proxy :: Proxy '[CookieSettings, JWTSettings)
    (runApp state RequestState{..})
    (server jwtCfg)
```

Open to further suggestions for cleanup, but this offers a nice mechanism for never having to touch the `Vault` if you're only looking at the `Request` in one piece of middleware, while still dishing the rock to the Servant `Reader` for subsequent use in your `Handler` stack.

**Comment by axman6** [comment]
Unless I'm missing something here, I don't think it's possible to do this for an app which is using ReaderT, since the natural transformation which is applied to your app is already finished by the time any requests are handled. the ReaderT can only contain information which was available to it before producing the Handlers.

IMO, the better solution here is to have a custom combinator for request IDs, something like:

```haskell
data ReqID

instance HasServer api context => HasServer (ReqID :> api) where
  type ServerT (ReqID :> api) m = Maybe UUID -> ServerT api m

  route = ... -- Retrieve the request UUID from the Vault of the request
              -- and pass it to the handler function
```

For a more fully developed system, it could pass in `[UUID]` which would allow for tracing between services, where any service which makes requests another service's endpoints would append its request UUID to those it's been passed.

**Comment by cbeav** [comment]
Thanks for the response @axman6. Does the combinator approach get you much that the `Vault` combinator doesn't offer out-of-the-box? My main aversion would be that this is something that I'll want present in all handlers in the API, so modifying the stack feels like the more natural place to put this.

**Comment by axman6** [comment]
All the combinator approach gets you is a little more type safety I think, and better semantics; your App doesn't care about the Vault, it cares about a (possibly non-existent) request ID, so `Maybe UUID` is nicer, imo, than requiring the App to know how to handle the Vault. I'm not sure what you mean by _so modifying the stack feels like the more natural place to put this_, though looking at what you have it feels like you're executing things in an order I've never seen before; interesting idea. Calling runReaderT for every request feels odd but I guess it works.

**Comment by saurabhnanda** [comment]
@cbeav the approach mentioned at https://github.com/haskell-servant/servant/issues/719#issuecomment-476465681 is similar to what we use in production.

The advantage of shoving the uuid into your reader env is that, it is potentially available throughout your app without having to manually pass it around. It can be used for multiple things, eg. adding to the DB based audit logs, or added it as a prefix to text-based logs.

> My main aversion would be that this is something that I'll want present in all handlers in the API

I also don't like the combinator-based approach for this reason, coupled with the fact that you have to manually pass around the requestId when you have an "Environment" (ReaderT) exactly for this purpose. However, to be fair, you can abstract out the repetitive parts while defining the API signature.

**Comment by cbeav** [comment]
Really appreciate the discussion. I'm using this to build a Microsoft ApplicationInsights library that I hope to contribute back, so input on all of this is greatly appreciated.

For further context, I want to capture both request-level logs, and DB- and HTTP-outbound dependencies, and tie all of these back to the same request ID. The former is naturally done at the middleware level as discussed. The latter require modifying respectively `runDB` and `http*` library functions in my monad stack to `forkIO` non-blocking logging requests. Does this pattern seem sane so far or is there something cleaner I've missed?

> Calling runReaderT for every request feels odd but I guess it works.

@axman6 Is there any performance-driven concern for avoiding executing `runReaderT` per request? I really do enjoy that my approach doesn't require modifying handler signatures, while still giving access to the `RequestState` needed by my `runDB` function. 

> I'm not sure what you mean by so modifying the stack feels like the more natural place to put this...

I just meant that semantically I preferred going towards `MyHandler :: ModifiedApiHandler a` over `MyHandler :: UUID -> ApiHandler a` to not pollute all handler signatures.

> However, to be fair, you can abstract out the repetitive parts while defining the API signature.

@saurabhnanda Do you mean partially applying the handlers in the `Server` definition so that they never have to see the `ReqID ->` coming through? The problem is I would need this ID in every handler every time I call `runDB reqId ...` with my current approach :)

**Comment by darrell-roberts** [comment]
Was there ever an agreed upon solution to this? I'm looking to do the same thing. That is have my handlers run in my Reader Monad that has the initial application scope environment and a per request environment (Unique correlation ID). Having a handler run with an application scope environment works as documented but a per request environment would be needed as well.

**Comment by tchoutri** [comment]
In production we had the ID generated at the reverse-proxy level (Kong, nginx).
See https://docs.konghq.com/hub/kong-inc/correlation-id.
Then in your servant/wai natural transform/middlewares, just extract the content of the header and put it in your ReaderT. :)

**Comment by darrell-roberts** [comment]
I have wai middleware that looks up the correlation id from a header and stores it in Request Vault. The challenging part has been making it available to the ReaderT setup for servant handlers. This is not per request. I used the approach @cbeav had however I'm wondering if there is a performance issues with this approach. I have a prototype of this approach. It works but I'm not sure if it is adding unnecessary overhead on how servant is initialized.

https://github.com/darrell-roberts/servant-ms-proto/blob/master/user-ms/app/Main.hs#L112
https://github.com/darrell-roberts/servant-ms-proto/blob/master/user-ms/app/UserService/Server.hs#L53
https://github.com/darrell-roberts/servant-ms-proto/blob/master/ms-framework/app/MSFramework/Middleware.hs#L196
