### ISSUE TITLE
Broken MonadCatch instance on ClientM monad

### ISSUE THREAD

**Issue by ondrap** [haskell-servant/servant#723]
Something seems to be broken in the `ClientM` monad from `servant-client`.

```
import Control.Monad.Catch (onException)

snapshotSave :: ClientM ()
snapshotSave  = do
  liftIO (putStrLn "init")
  void apiCall `onException` liftIO (putStrLn "exception")
  liftIO (putStrLn "done")
```

The `onException` (and `catch` and all the others) just seems to be ignored. I tried this on servant 0.9.1.1 quite thoroughly, it seems not to work with 0.10 either (the MonadBaseControl doesn't seem to help, I haven't tested this a lot). 

The `MonadCatch` is automatically derived, so this might be an error somewhere else.

**Comment by phadej** [comment]
Are you sure that error doesn't go into `MonadError ServantError`, most expected errors go there.

http://hackage.haskell.org/package/servant-client-0.10/docs/Servant-Client.html#t:ServantError

**Comment by ondrap** [comment]
It does, sorry, my fault. It's somewhat confusing having both...

**Comment by phadej** [comment]
At least in my usage where web-server uses servant-client to make further requests I never catch unchecker (`MonadCatch`) exceptions, they are rare and unrecoverable (and framework fails original request with 500 internal error), so far I never seen. Based on our monitoring 500 "never' happens.
(Disclaimer: `Data.Binary.decode` throws impure exceptions, and those I do sometimes catch, I have mixed feelings about that impurity though).

OTOH, if you think there is some recoverable error, than IMO we should extend `ServantError`. Please open another issue if it's so.
