### ISSUE TITLE
Allow failures in arbitrary order

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#73]
This is something we've discussed quite a bit before, but I just realized there's no ticket for it. We're stuck in this position where failures (from `failWith`) happen without trying matches further down the `:>` chain, resulting in some bad error messages (e.g. `Bad Request` instead of `Method Not Found`), hard to implement authentication ( #70 ), and inefficiency (it's better not to try decoding a body if there's no matching route anyhow).

This relates to #48. It also likely relates to improved routing. 

# Design issues

Do we want only the leaves of the tree (the methods) to be able to adjudicate error messages? Or do we want combinator instances to be *allowed* (but not required) to adjudicate between failure and continuation as well? I think the former would be sufficient to conform to the behaviour of most frameworks, but the second may also allow for room for interesting possibilities (what comes to mind immediately is auth-protecting a set of endpoints without even allowing non-authenticated clients to figure out what the endpoints being protected are - not a crucial feature, but also almost certainly not the only one).

# Implementation ideas

?

**Comment by aaronlevin** [comment]
I think the latter (*combinator instances to be* allowed *(but not required) to adjudicate between failure and continuation as well*) is preferable from an authentication standpoint. It makes sense to wrap sets of endpoints under a specific authentication scheme. 

Something to consider: authentication (and other combinators) may introduce `IO` and other effects *during* the routing process. Therefore, whatever new process is introduced for routing it's important that authors of a web-service are able to reason about the effects that happen during matching. This is why I think the latter choice is a good one.

**Comment by thsutton** [comment]
I have the start of a thing which constructs a traditional check-the-predicate-then-call-the-handler router from an API type in https://github.com/anchor/servant-route.

It has an overlapping instances problem I haven't managed to resolve yet, but I think that an approach like this is more likely to be a "correct" approach than mixing all these success-but-failure responses in with backtracking search.

**Comment by jkarni** [comment]
@thsutton come to the servant channel on freenode, we're discussing just this.

**Comment by jkarni** [comment]
Fixed in #111
