### ISSUE TITLE
Support Logging in servant-client

### ISSUE THREAD

**Issue by gmalecha** [haskell-servant/servant#731]
Has there been much thought to adding logging to servant-client? In particular, I would like to log (using a custom logger) the exact request that is sent to the URL and the raw (unparsed) response that I get from the server. I was able to hack the first part of this together using a similar technique to #241. The basic idea of the code is the following:

```haskell
data LogRequest
  deriving Typeable

instance (ToHttpApiData a, HasLink sub)
      => HasLink (LogRequest :> sub) where
  type MkLink (LogRequest :> sub) = MkLink sub
  toLink _ = toLink (Proxy @sub)

instance {-# OVERLAPPABLE #-}
     (MimeUnrender ct a, ReflectMethod method, cts' ~ (ct ': cts))
  => HasClient (LogRequest :> Verb method status cts' a) where
  type Client (LogRequest :> Verb method status cts' a) =
    Client (Verb method status cts' a)
  clientWithRoute Proxy req = do
    reqHost <- asks baseUrl
    reqToRequest req reqHost >>= liftIO . Log.info ("Constructed request: " % shown)
    clientWithRoute (Proxy @(Verb method status cts' a)) req
```

There are also other instances for `Verb`. The `HasServer` class simply ignores `LogRequest` (in my application I have both clients and servers sharing the same servant spec, yay for reuse).

While this works to some extent, I don't find it very nice. It seems like a better solution would be to generalize the monad that performs the requests. Essentially make [`performRequest`](https://github.com/haskell-servant/servant/blob/25110fefe430fb7767835700252c5e07fed080ff/servant-client/src/Servant/Common/Req.hs#L227) a typeclass function and generalize the client code over any monad that supports this method. The idea seems similar to [this library](https://hackage.haskell.org/package/kawhi-0.2.1/candidate/docs/Control-Monad-Http.html).

I'm happy to implement a PR for this functionality, I'd just like to get an idea if there is a simple solution that I'm seeing, or if there a better design for the implementation.

Thanks.

**Comment by alpmestan** [comment]
The closest I remember is https://gist.github.com/proger/271f1e1d479c7a7678f2. It would be useful to have _some_ debugging capability in servant-client indeed. I'm however not fond of having something in the API type that is only the business of the client side of things. It's fine if you just add it while debugging an issue, but I'm wondering whether anyone can come up with an approach that does not require a user to change the API type, but rather toggle a switch when deriving the client functions or even call another function. I do not have any particular opinion on how this should be implemented behind the scenes though.

@gmalecha Thoughts?

**Comment by phadej** [comment]
There is [`managerModifyRequest`](http://hackage.haskell.org/package/http-client-0.5.6.1/docs/Network-HTTP-Client.html#v:managerModifyRequest) and `managerModifyResponse` which you can (ab-)use for logging.

**Comment by gmalecha** [comment]
I 100% agree with the idea that adding logging to the API spec isn't a good idea.

I think my actual proposal (not the quick-and-dirty code that I posted) would address what you're saying. The proposal is something like the following:

```haskell
class Monad m => MonadHTTP m where
  performRequest :: Method -> Req -> m ( Int, ByteString, MediaType , [HTTP.Header], Response ByteString)
  -- ... other special case functions here, e.g. @performRequestNoBody@ ...

class HasClient api where
  type Client api (m :: * -> *) :: *
  clientWithRoute :: MonadHTTP m => Proxy api -> Req -> Client api m
```

With this, the `client` function would look like:

```haskell
client :: (HasClient api, MonadHTTP m) => Proxy api -> Client api m
```

This would allow the caller of the API to specify their own type that implements `MonadHTTP` and insert logging inside the `performRequest` function if they would like. Something like:

```haskell
newtype RequestWithLogging a = RequestWithLogging { getRequestWithLogging :: IO a }

instance MonadHTTP RequestWithLogging where
  performRequest meth req = RequestWithLogging $ do
    -- log the request
    resp <- performRequest meth req -- the @IO@ instance of @MonadHTTP@
    -- log the response
    return resp
```

**Comment by gmalecha** [comment]
Thanks @phadej. That looks like it would work pretty well for logging.

**Comment by phadej** [comment]
FWIW, I was thinking about some kind of `MonadHttp` for `servant-client` (I have one `MonadHttp` at work), but it needs a bit of work.

Side-note: we want still to allow making `http-client` specific combinators for example, if that's the client lib you'll end up using. E.g. we shouldn't make streaming impossible.

**Comment by alpmestan** [comment]
I would be happy with the suggested generalization of `client`.

**Comment by gmalecha** [comment]
@phadej Perhaps a way to generalize `MonadHTTP` and leave the door open for further extension is to parameterize over this constraint. I'm thinking something like:

```haskell
class HasClient api where
  type C api :: (* -> *) -> Constraint -- TODO: This needs a better name
  type Client api (m :: * -> *) :: *
  clientWithRoute :: C api m => Proxy api -> Req -> Client api m
```

For most `HasClient` instances, we construct `C` by combining the lower-level `C`s until we get to something like a `Verb` where we will require, e.g. `MonadHTTP` or `MonadHTTPStream` or just `MonadIO`.

Under this, the type of `client` would become:

```haskell
client :: (HasClient api, C api m) => Proxy api -> Client api m
```

**Comment by phadej** [comment]
That could work: Or `class HasClient m api where`, then for `Verb` it could be `HasHttp m => HasClient m (Verb ...)`.

**Comment by phadej** [comment]
I'm closing this in favor of generalisation issue.
