### ISSUE TITLE
http library independent servant-client

### ISSUE THREAD

**Issue by phadej** [haskell-servant/servant#733]
See #731 for explanation of one approach (thru `MonadHTTP`).

Successful outcome would give us:
- servant-client
- servant-http-client
- servant-http-streams

Having two client "backends" is essential, to verify that generalisation actually works (and not only adds one indirection layer).

**Comment by gmalecha** [comment]
Either version of the proposed `HasClient` changes seems reasonable to me. The one @phadej proposed is a bit simpler so it be preferred. It might also mirror servant-server a bit more.

What is the plan for implementing? Should I work on a PR?

**Comment by phadej** [comment]
**ZuriHac note:** This is expert task, but if someone wants to start tacking this, it would be great!

**Comment by abailly** [comment]
Some work towards this in #800

**Comment by jkarni** [comment]
Done in #803
