### ISSUE TITLE
Suppress headers in generated documentation

### ISSUE THREAD

**Issue by rikvdkleij** [haskell-servant/servant#735]
Is it possible to not generate header information in output of `markdown`?

Reason: the header is added by proxy between client and server. So it's not send by client but added by proxy. It's used on server for authentication based on IP-address.

**Comment by phadej** [comment]
Is this related to `servant-docs`, I don't understand.

**Comment by rikvdkleij** [comment]
Yes, it's related to `servant-docs`. It's about generating documentation with `markdown` of `servant-docs`.  I have read this: http://haskell-servant.readthedocs.io/en/stable/tutorial/Docs.html

**Comment by alpmestan** [comment]
I don't think we have anything yet that allows us to drop some bits and pieces from the API type. One solution would be to generate the docs for a slightly different API type, which would be the image of the actual API type through some type family maybe?

Do you want to drop _request_ headers or _response_ headers from the API type? Sounds like it's the former, in which case the type family might look something like:

``` haskell
type family DropHeaders api where
  DropHeaders (Header name ty :> api) = DropHeaders api
  DropHeaders (a :<|> b) = DropHeaders a :<|> DropHeaders b
  DropHeaders (a :> b) = a :> DropHeaders b
  DropHeaders a = a
```

with a little helper to turn a `Proxy api` into a `Proxy (DropHeaders api)`:

``` haskell
dropHeaders :: Proxy api -> Proxy (DropHeaders api)
dropHeaders Proxy = Proxy
```

Which you would then use as follows:

``` haskell
-- given yourApi :: Proxy SomeAPIType

myAPIDocs = docs (dropHeaders yourApi)
```

**Comment by fizruk** [comment]
@rikvdkleij on a side note, if you were to use `servant-swagger` you would be able to modify generated documentation as you please with lots of optics available to dig into any part of an API spec and modify it :)

**Comment by rikvdkleij** [comment]
@alpmestan I have tried to create 2 different API's based on each other but did not succeed because `Header` combinator can not be on the head or tail of endpoint.

I also tried your solution with type family but that does not work. It compiles but the generated markdown is not changed.

@fizruk Thanks for your note. I'll try that.

**Comment by alpmestan** [comment]
> I also tried your solution with type family but that does not work. It compiles but the generated markdown is not changed.

@rikvdkleij Hmm, that sounds wrong, maybe I overlooked something but I did a quick experiment in ghci and I do get the expected result, could you share your code (or a minimal repro extracted from it) ?

``` haskell
Prelude> :set -XTypeOperators
Prelude> :set -XTypeFamilies
Prelude> data (:>) a b
Prelude> data (:<|>) a b = a :<|> b
Prelude> data Get
Prelude> data Header s ty
Prelude> :{
Prelude| type family DropHeaders api where
Prelude|   DropHeaders (Header s ty :> api) = DropHeaders api
Prelude|   DropHeaders (a :<|> b) = DropHeaders a :<|> DropHeaders b
Prelude|   DropHeaders (a :> b) = a :> DropHeaders b
Prelude|   DropHeaders a = a
Prelude| :}
Prelude> type API = (Header () () :> Get) :<|> (Get :<|> (Header () () :> Get))
Prelude> :kind! DropHeaders API
DropHeaders API :: *
= Get :<|> (Get :<|> Get)
```

**Comment by rikvdkleij** [comment]
@alpmestan I think it's because my API type has combinators before the `Header`. 

Some extract:
```
type XFFHeader = Header "X-Forwarded-For" XFF
type Unprotected = "authenticate" :> ReqBody '[ JSON] Credentials :> XFFHeader :> Post '[ JSON] LoginResponse
```

**Comment by alpmestan** [comment]
That should not be a problem. Maybe the type family should explicitly say that it can handle things with kind other than `*`, as I suspect it's the `"authenticate"` bit, with kind `Symbol`, that's getting in the way. Could you maybe try replacing:

``` haskell
DropHeaders (a :> b) = a :> DropHeaders b
```

with

``` haskell
DropHeaders ((a :: k) :> b) = a :> DropHeaders b
```

?

**Comment by rikvdkleij** [comment]
Yes, that works! Many thanks!

**Comment by rikvdkleij** [comment]
@fizruk Can you give some example about how to modify in the same way with `servant-swagger`? I have read the haddocks documentation and the example but I see only simple ways how to add more documentation/samples. Not how to change the API and my `lens` knowledge is minimal.
