### ISSUE TITLE
BasicAuthentication has no documentation for client-side use

### ISSUE THREAD

**Issue by alexanderkjeldaas** [haskell-servant/servant#752]
The following is the documentation, but this is actually no documentation without an example.

<img width="759" alt="skarmavbild 2017-05-16 kl 06 12 10" src="https://cloud.githubusercontent.com/assets/339369/26089511/b703c32e-39fe-11e7-999e-f11326d899d5.png">

**Comment by alpmestan** [comment]
We should (and will) indeed add a little example here. That sentence is saying that if you see a `BasicAuth` combinator in the API, it gets "translated" to having client functions take an argument of type `BasicAuthData`. I'm again not disputing the need for an example, just clarifying in case you did not get this working because of the sloppy docs.

**Comment by jhb563** [comment]
@phadej I think I can do this if I find a little time this weekend. Might need a little help finding my way around the repo, but I've used Basic Auth a few times before so I should be able to provide an example.

**Comment by phadej** [comment]
@jhb563 great!

**Comment by jhrcek** [comment]
@phadej Is this issue still relevant? It's true there's a backend basic-auth example in the cookbook section, but the tutorial is still missing "client only" example. I could cook up one using external https://httpbin.org/basic-auth as a target endpoint and submit a PR..

**Comment by alpmestan** [comment]
Note that we have a basic auth example in the cookbook: https://haskell-servant.readthedocs.io/en/stable/cookbook/basic-auth/BasicAuth.html (server _and_ client)

**Comment by alexanderkjeldaas** [comment]
Seems like it's covered.

I'll open a separate ticket for the Bearer token authentication which is even more important to document client side as it's what's typically used in all APIs.

**Comment by jhrcek** [comment]
Since client-side authentication section of the tutorial doesn't have any example, I at least added a link to the cookbook example here https://github.com/haskell-servant/servant/pull/928

If you merge this in my opinion this issue can be closed.

**Comment by alpmestan** [comment]
Done, thanks for tthe PR! I'm closing the issue, but if someone disagrees let us know :-)
