### ISSUE TITLE
Lower infix precedence for Sub (:>)

### ISSUE THREAD

**Issue by fizruk** [haskell-servant/servant#761]
There's a discussion about parameter descriptions in https://github.com/haskell-servant/servant-swagger/issues/62. It's becoming obvious that there needs to be a support for them in servant. However, it can take a while before we solve design problems for it.

In any case, it is highly probable that we want to use infix operator to attach descriptions:

```haskell
-- style I like
type FooEndpoint
  = "foo"
 :> Capture "foo-id" FooId      --^ "The identifier"
 :> QueryParam "canonical" Bool --^ "Normalise the representation"
 :> Get '[JSON] Foo             --^ "Why not annotate the result too"
```

```haskell
-- style @phadej proposed
type FooEndpoint =
   "foo" :>
   Capture "foo-id" FooId      :? "The identifier" :>
   QueryParam "canonical" Bool :? "Normalise the representation" :>
   Get '[JSON] Foo             :? "Why not annotate the result too"
```

Unfortunately, none of these is currently possible to implement (even locally), because

```haskell
infixr 9 :>
```

9 is the highest available priority and I guess it should never be used in a library.
So I propose we decrease it to at least 8.

**Comment by phadej** [comment]
IHMO we can lower `:<|>` to 3, and `:>` to 4. Because:

```haskell
Prelude Control.Applicative> :i *>
...
infixl 4 *>

Prelude Control.Applicative> :i <|>
...
infixl 3 <|>
```

(let's not care that `Applicative` operators are `infixl`)

**Comment by alpmestan** [comment]
@phadej sounds good to me!

**Comment by phadej** [comment]
@fizruk feel free to make a PR

**Comment by fizruk** [comment]
You can actually work around this current limitation with a little re-export:

```haskell
module MyServant (
  module Servant.API,
  (:>), (:<|>),
) where

import qualified Servant.API as Servant
import Servant.API hiding ((:>), (:<|>))

type (:>) = (Servant.:>)
infixr 4 :>

type (:<|>) = (Servant.:<|>)
infixr 3 :<|>
```

But I hope next release would be soon after ZuriHac, so perhaps few would need this sort of hack.
