### ISSUE TITLE
Auth handling tutorial - confusion over cookie/header

### ISSUE THREAD

**Issue by JoeMShanahan** [haskell-servant/servant#776]
I think that the wording of the example could be improved for the tutorial, particularly for the provided auth handler:

```haskell
authHandler :: AuthHandler Request Account
authHandler =
  let handler req = case lookup "servant-auth-cookie" (requestHeaders req) of
        Nothing -> throwError (err401 { errBody = "Missing auth header" })
        Just authCookieKey -> lookupAccount authCookieKey
  in mkAuthHandler handler
```
The pattern match `Just authCookieKey` implies that we've retrieved a value from the cookie, where in reality all we've done is retrieved the _header value_ of `servant-auth-cookie`.

Using `Web.Cookie`, the following achieves what is implied:

```haskell
authHandler :: AuthHandler Request Account
authHandler =
  let handler req = case lookup "cookie" (requestHeaders req) of
        Nothing -> throwError (err401 { errBody = "Missing cookie header" })
        Just cookie -> case lookup "servant-auth-cookie" $ parseCookies cookie of
          Nothing -> throwError (err401 { errBody = "Missing token in cookie"})
          Just authCookieValue -> lookupAccount authCookieValue
  in mkAuthHandler handler
```
.. which I think is a little convoluted. I'd (personally) instead write it like:

```haskell
authHandler :: AuthHandler Request Account
authHandler = mkAuthHandler handler
  where
  maybeToEither e = maybe (Left e) Right
  throw401 msg = throwError $ err401 { errBody = msg }
  handler req = either throw401 lookupAccount $ do
    cookie <- maybeToEither "Missing cookie header" $ lookup "cookie" $ requestHeaders req
    maybeToEither "Missing token in cookie" $ lookup "servant-auth-cookie" $ parseCookies cookie
```

Of course it's much easier just to change the wording of the tutorial but I'd prefer to see a fully worked example that likely better represents a typical situation.

**Comment by JoeMShanahan** [comment]
Happy to do the PR if needed once feedback has been received!

**Comment by alpmestan** [comment]
I too think that implementing the actual cookie retrieval is nicer. I'd definitely be in favor of a PR that makes that change, if you feel like putting it together :)

**Comment by JoeMShanahan** [comment]
Will add something hopefully later today!

**Comment by JoeMShanahan** [comment]
PR in!
