### ISSUE TITLE
Axiomatic way to catch and do some computation for all errors in an application

### ISSUE THREAD

**Issue by t3hmrman** [haskell-servant/servant#779]
Hey servant team, as always thanks for the library, I'm really having a blast using it. I've been struggling with how to **add logging (in my case, but it's general) to all my routes**, particularly when they fail.

Some background:
- Right now my app fails (without going down) just about 2 ways, either with a `ServantError` (that I threw myself), or a `SQLError` (ignoring completely unexpected exceptions right now)

- While it makes sense that `ServantError`s didn't bring the server down, I was surprised at how the `SQLError`s didn't either -- they just get printed (I am happy it works this way), and I found my answer [in the code @ RoutingApplication.hs](https://github.com/haskell-servant/servant/blob/master/servant-server/src/Servant/Server/Internal/RoutingApplication.hs#L376)

- I want to log all the errors (at the very least the two classes of error above) in the application to Graylog

There are a few ways I can think of that servant could have supported this functionality:
- Including post-route handlers in `DelayedIO` (this would make it possible to build combinators)
- Adding a way to specify a handler for `Fail`/`FailFatal` routes

But, I figure it's not supported in these ways because it can just be supported with other approaches, a few of which are:

1. Wrapping all computations in handlers to make sure they don't error/fail (seems hacky, even if I wrapped the whole server in some `handle` like contraption it still doesn't feel great as a clean way to add functionality)

2. Implementing a monad stack whose `bind` function does the necessary check by reaching down the monad stack 

I chose 2 -- and I just finally got to something that compiles (I still haven't written the `NT` for it so I can use it with Enter):

```haskell
-- The WithLoggedErrorsT expects to be wrapped over a MonadState ApplicationGlobals with an ExceptT under it
instance (MonadState ApplicationGlobals (ExceptT e m), MonadIO m) => Monad (WithLoggedErrorsT (StateT ApplicationGlobals (ExceptT e m))) where
    return a = WithLoggedErrorsT $ return a

    x >>= f = WithLoggedErrorsT $ do
                -- Get state that will be used for re-construction & actual logic
                state <- get
                logger <- fmap globalLogger get

                -- Journey down the monad stack by pattern-match disassembling the monads
                let res@(StateT m0) = (runWithLoggedErrorsT x)
                let except@(ExceptT m1) = (m0 state)

                -- After 2 levels, when we know we're going to get an either, perform the computation and do stuff with the result
                let newM = m1 >>= \res -> return $ case res of
                                            Left err -> do -- Error case, this is where the logging would happen... Right now a `let` is there
                                                     let a = 1
                                                     res
                                            Right _ -> res

                -- Re-wrap the computation in two levels of monads it came from
                let rewrapped = WithLoggedErrorsT $ withStateT (\_ -> state) (StateT (\_ -> (ExceptT newM)))
                runWithLoggedErrorsT rewrapped >>= runWithLoggedErrorsT . f

    fail err = WithLoggedErrorsT $ fail err

instance (MonadState ApplicationGlobals (ExceptT e m), MonadIO m) => Applicative (WithLoggedErrorsT (StateT ApplicationGlobals (ExceptT e m))) where
    pure = return
    (<*>) = ap

instance (MonadState ApplicationGlobals (ExceptT e m), MonadIO m) => Functor (WithLoggedErrorsT (StateT ApplicationGlobals (ExceptT e m))) where
    fmap = liftM

instance MonadTrans WithLoggedErrorsT
```

**Am I making this too hard for myself?** I have only seen examples of pre-action-handle monad stacks, and none that try to reach down to get at the `Either` that is returned by the route... I'm not sure how I should be doing this.

**Comment by t3hmrman** [comment]
sorry accidental close

**Comment by phadej** [comment]
- For proper exceptions: Use `warp`'s [`setOnException`](http://hackage.haskell.org/package/warp-3.2.13/docs/Network-Wai-Handler-Warp.html#v:setOnException)
- I suspect you mean [`ServantErr`](http://hackage.haskell.org/package/servant-server-0.11/docs/Servant-Server.html#t:ServantErr), that one you shouldn't `throwM`, but `throwError`.
    - IIRC there isn't a way to process the last `ServantErr` though, one would need to somehow plug into https://github.com/haskell-servant/servant/blob/265b4276db908d01130532ace098a881794afc69/servant-server/src/Servant/Server/Internal/RoutingApplication.hs#L93

**Comment by t3hmrman** [comment]
Hey @phadej thanks for the response!

- Ahhh, so that's why, it's `warp` doing the magic and keeping the server up, that should take care of the `SQLError` case, I have no reason to think it magically became a `ServantErr`, so it must be another case

- Yeah, I saw the lines in `RoutingApplication.hs` and see why it works that way, but there isn't a way to plug in there right? 

As far as `ServantErr`s go, I'm perfectly happy implementing some `doSomethingAndErr` and using that instead, there's no need to add that to servant (since if I'm calling `throwError` I might as well do the other stuff as well).

**Comment by phadej** [comment]
FWIW, you most likely don't want unexpected errors to crash the server. It's a bit like faulty `servlet` would crash whole servlet container in Java World. Bad idea.

**Comment by t3hmrman** [comment]
hey @phadej agreed -- that's what I want to happen but was confused I just thought servant did the catching so I was very confused everything didn't come crashing down since any exception will stop Haskell. I didn't even think of Warp when I was trying to find the code that was handling the error.

To fix my mental model -- `ServantErr`s get handled by Servant but any other exception gets handled directly by warp (`Server`/`Handler` monad(s) `fail`, and the underlying `Warp` application catches the failure in the fiber and handles it.

BTW, I just confirmed that it works. For anyone who might run into this, all I needed to do was:

```haskell
... in app set up code ...
  -- Set the default application-wide on-exception handler
  let appSettings = (setOnException (appOnExceptionHandler appLogger) . setPort port) defaultSettings

  runSettings appSettings app
.....

... somewhere later ...
appOnExceptionHandler :: Logger -> Maybe Request -> SomeException -> IO ()
appOnExceptionHandler logger _ e = logL logger ERROR (show e)
                                   >> when (defaultShouldDisplayException e) (TIO.hPutStrLn stderr packedErrStr)
    where
      packedErrStr = T.pack $ show e
...

**Comment by t3hmrman** [comment]
thanks for your help @phadej , turns out I was 1000% making it harder than it needed to be

**Comment by leptonyu** [comment]
I'm using the following function to translate Exception to ServantErr
```haskell
exceptionHandler :: SomeException -> ServantErr
```
and then, write a wai Middleware with this function.

**Comment by t3hmrman** [comment]
Thanks for the suggestion @leptonyu , another good way to handle this would have been to tack a middleware on to the Warp serveer
