### ISSUE TITLE
Should servant-pandoc still be referenced?

### ISSUE THREAD

**Issue by ivan-m** [haskell-servant/servant#782]
The [documentation tutorial](https://github.com/haskell-servant/servant/blob/master/doc/tutorial/Docs.lhs) says that the [servant-pandoc](http://hackage.haskell.org/package/servant-pandoc) package can be used to convert the generated Markdown to other formats.  However, that package hasn't been updated for quite a while and will not work with current versions of servant _or_ pandoc.  As such, should that recommendation be removed?

**Comment by phadej** [comment]
@mpickering, do you intent to maintain `servant-pandoc`?

**Comment by mpickering** [comment]
No I don't really plan to maintain it.

**Comment by alpmestan** [comment]
@phadej Is there that much work to bring it up to date? If not, we could have it as an open task for anyone interested, or one of us can get around to updating it in the upcoming weeks.

**Comment by ivan-m** [comment]
@alpmestan: the biggest issue IMO is that it basically duplicates the markdown function from servant-docs; I'd be willing to send a PR to update servant-pandoc but to an extent it's a losing battle unless a more flexible model is found to avoid duplication (maybe use a typeclass to create a document?).

**Comment by alpmestan** [comment]
@ivan-m Good point. I guess the first question we should ask is: who uses servant-pandoc? how do they use it? I suppose that ideally we should target pandoc's document representation, for maximal flexibility, and basically obsolete servant-docs?

**Comment by ivan-m** [comment]
pandoc is GPL, so some people might prefer not to use it.

**Comment by lethom** [comment]
I don’t see the point here, especially because we are talking about an API endpoint. Of course, it means the client package cannot depends on `servant-pandoc`, which shouldn’t be an issue in practice.

**Comment by ivan-m** [comment]
Some people prefer not to use GPL software at all. Also, I'm currently using servant-docs in my server with an endpoint to generate the documentation (like with swagger).

**Comment by ivan-m** [comment]
Actually, pandoc-types is BSD3, so just depending on that should be fine  (possibly with a simple markdown writer implementation as a default).

**Comment by alpmestan** [comment]
To be entirely honest, my main use for -docs (which is quite rare) is for generating an in-repository API documentation that can be handed over to frontend people or whoever is going to consume my API, so -docs is enough. If anyone is however interested in maintaining/revamping servant-pandoc, and possibly  making it share code with servant-docs and maybe even offer a BSD3-ish alternative, I'm definitely not opposed to that. It's really up to what you folks need. Feel free to use the issue tracker (this issue and possibly new ones) for organising that work.

**Comment by ivan-m** [comment]
It appears that just bumping the dependencies on servant-pandoc suffices.

My thinking is as follows:

* Implement the current documentation-generation functionality using the `Pandoc` type
* Add a manual `markdown :: Pandoc -> String` function duplicating the current behaviour of servant-docs (thus not requiring the GPL pandoc library to do so)
* Have another library `servant-pandoc-types` that uses pandoc for content types of the various documents.

**Comment by ivan-m** [comment]
servant-pandoc-0.4.1.3 has been released which supports servant-docs-0.10.

I'll make another point release for servant-docs-0.11.

I think any discussion about merging servant-docs and servant-pandoc should take place in a separate thread.
