### ISSUE TITLE
servant-docs breaks PVP

### ISSUE THREAD

**Issue by ivan-m** [haskell-servant/servant#784]
In 0.10.0.1, servant-docs changed the type of the `_rqbody` field in the `Action` type (specifically in [this commit](https://github.com/haskell-servant/servant/commit/d8dd1cb90a887e2a235179a03069c9552f6ba8e0)).

This is an API-breaking change and hence should have required a major version bump, but it instead received a patch-level bump; this means that it isn't viable to just put `servant-docs == 0.10.*` as a dependency in a `.cabal` file if you use the `rqbody` lens.

As such, it would probably be a good idea to at least deprecate one of 0.10 or 0.10.0.1 on Hackage just in case.

**Comment by phadej** [comment]
The `Action` is defined in `Internal.` (well, I should bumped at least third digit).

@haskell-servant/maintainers How to deal with `Internal` modules. Also in `servant` we have a lot of `Internal` which are re-exported as such, which makes them not really internal.

For next major release I'd rather drop `Internal` from them naming.

Internal in a name to mean "you don't need to use/import this while writing servant applications" is IMHO confusing, if it was the intention.

**Comment by ivan-m** [comment]
Except that `rqbody` is exported from `Servant.Docs`, _not_ just `.Internal`.

**Comment by phadej** [comment]
bummer. I'll make `servant-docs-0.11` and deprecated `0.10.0.1`.

**Comment by ivan-m** [comment]
Ta!

**Comment by ivan-m** [comment]
@phadej maybe release 0.10.0.2 as a duplicate of 0.10 just in case someone ignores the deprecation flags on Hackage and tries to get the newest version?

**Comment by phadej** [comment]
@ivan-m than that's their problem. Unfortunately `0.10.0.1` got into Stackage nightly, but I don't want to spam Hackage just for that. Nightly will "fix" itself eventually anyway.

**Comment by phadej** [comment]
https://hackage.haskell.org/package/servant-docs-0.11

**Comment by alpmestan** [comment]
I agree that our "internal" modules should be dealt with. We did that until we found something better, which we never did so far. Suggestions welcome.

**Comment by ivan-m** [comment]
I think it's fine that the data structure is internal; you just need to remember that the lenses are exported and thus affect the API :)

**Comment by ivan-m** [comment]
So it looks like the new [LTS Haskell 9.0](https://www.stackage.org/lts-9.0) includes the deprecated servant-docs-0.10.0.1 ...
