### ISSUE TITLE
Optional request body

### ISSUE THREAD

**Issue by zudov** [haskell-servant/servant#793]
It's sometimes useful to have an endpoint, that can either take the content as a body, or as query parameter (e.g. in the form of id that can be used to resolve that content).

A couple of examples:
- A `search` endpoint that can either take a simple query through parameters or a more complex query as json (elasticsearch does it)
- An endpoint that allows to submit a file can read a file from the body or download it from the url specified in the `url` paramater

I've been using the following combinator for my needs:

```haskell
data OptionalReqBody cts a

instance
  ( AllCTUnrender cts a
  , HasServer api context
  , reqBodyApi ~ (ReqBody cts a :> api)
  )
  => HasServer (OptionalReqBody cts a :> api) context where
  type ServerT (OptionalReqBody cts a :> api) m =
    Maybe a -> ServerT api m
  route _ context subserver =
    route @api Proxy context
      $ addBodyCheck subserver
          (withRequest contentTypeCheck)
          bodyCheck
    where
      contentTypeCheck
        :: Wai.Request
        -> DelayedIO (Maybe (LByteString -> Either String a))
      contentTypeCheck request =
        | hasMessageBody && not isEmptyMessageBody
            Just <$> getContentHandler
        | otherwise =
            pure Nothing
        where
          headers           = Wai.requestHeaders request
          hContentType      = headers & lookup Header.hContentType
          hContentLength    = headers & lookup Header.hContentLength
          hTransferEncoding = headers & lookup Header.hTransferEncoding

          -- https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html
          -- 4.3 Message body
          -- > The presence of a message-body in a request is
          -- > signaled by the inclusion of a Content-Length
          -- > or Transfer-Encoding header field in the request's
          -- > message-headers.
          hasMessageBody =
            isJust (hContentLength <|> hTransferEncoding)

          isEmptyMessageBody = fromMaybe False $ do
            contentLength <- parseContentLength =<< hContentLength
            pure $ contentLength <= 0
            where
              parseContentLength =
                (readMaybe :: String -> Maybe Double)
                  . Text.unpack . Text.decodeUtf8

          -- when Content-Type is not provided we assume it's octet-stream
          -- http://tools.ietf.org/html/rfc7231#section-3.1.1.5 RFC7231
          orOctetStream = fromMaybe "application/octet-stream"

          getContentHandler
            :: DelayedIO (LByteString -> Either String a)
          getContentHandler =
             maybe (delayedFailFatal err415) pure
               $ canHandleCTypeH (Proxy :: Proxy cts)
                   $ LByteString.fromStrict
                   $ orOctetStream hContentType

      bodyCheck
        :: Maybe (LByteString -> Either String a)
        -> DelayedIO (Maybe a)
      bodyCheck = traverse $ \contentHandler -> withRequest $ \request -> do
        body <- liftIO (Wai.lazyRequestBody request)
        case contentHandler body of
          Left e -> delayedFailFatal err400
            { errBody = LByteString.fromStrict
                      $ Text.encodeUtf8 $ Text.pack e
            }
          Right a -> pure a
```

I wanted to get some feedback on it, and I'll be happy to warp it in a PR.
Such combinator could as well go into `servant-contrib` or it's own library, but I feel like it might be wanted here, because without it you can't describe valid and occuring-in-the-wild APIs. Also `ReqBody` can be easily defined through `OptionalReqBody`.

**Comment by alpmestan** [comment]
I would not mind including it in the core servant packages (assuming it comes with tests, documentation and maybe an update of the tutorial), but could understand it if others want to see it go through servant-contrib first. Thoughts, @phadej ?

**Comment by phadej** [comment]
This is close to the "mandatory headers / query parameters" so, let's get this into core `servant`.

**Comment by alpmestan** [comment]
@zudov There you go :) We can proceed to a more detailed review once a PR is up.

**Comment by zudov** [comment]
Awesome, I'll give it a go

**Comment by phadej** [comment]
ping @zudov

**Comment by zudov** [comment]
There is a long-living branch over here (resurrected it recently): https://github.com/haskell-servant/servant/compare/master...zudov:required-parameter. It currently implements it for `ReqBody`, but supposed to be extended over `QueryParam`. Currently it just adds a parameter like `ReqBody (required :: Required) a`. But it would be a lot nicer to go with an extensible list of modifiers as in #856.

I'll gather up some context and open a WIP pull request.

**Comment by jkarni** [comment]
Done in #873.
