### ISSUE TITLE
Nesting api's

### ISSUE THREAD

**Issue by KasperJanssens** [haskell-servant/servant#794]
Hello,

More of a question than an issue. I need to consume a rather deeply nested tree-like rest api. I thought to do it more or less like this 
```
type BlehApi =
   Post '[JSON] ()
    :<|>
   Get '[JSON] ()


data BlehClient =
  BlehClient
    { 
      add::ClientM ()

    , get:: ClientM ()

    } deriving (GHC.Generics.Generic)


instance Generics.SOP.Generic BlehClient

instance (Client BlehApi ~ client) => ClientLike client BlehClient


type FooApi =
    "bleh" :> BlehApi


data FooClient =
  FooClient
    { 
    
       f ::  BlehClient

    }
  deriving (GHC.Generics.Generic)

instance Generics.SOP.Generic FooClient
```
So the top part would be the Foo Rest service's API and then underneath you could have a part handlin requests to Bar (or to Bleh). I wanted to use separate types and records and include those in the FooClient record and so on, I guess you get the drift.
However, by doing this I get a compilation error
```
   * Couldn't match type `ClientM () :<|> ClientM ()'
                     with `ClientM ()'
        arising from a functional dependency between constraints:
          `(ClientM () :<|> ClientM ()) ~ ClientM ()'
            arising from a use of `Servant.Client.Generic.$dmmkClient'
            at src/Member.hs:88:10-64
          `(ClientM () :<|> ClientM ()) ~ (ClientM () :<|> ClientM ())'
            arising from the instance declaration at src/Member.hs:88:10-64
    * In the expression:
        Servant.Client.Generic.$dmmkClient @client @FooClient
      In an equation for `mkClient':
          mkClient = Servant.Client.Generic.$dmmkClient @client @FooClient
      In the instance declaration for `ClientLike client FooClient'
```
After looking it over a bit I seems that the way I compose the BlehApi into the FooApi leads the type system to believe that I should provide two functions in the FooClient record, while I want to provide a sub record.

How would I achieve such a tree-like client, e.g. how would I be able to do this without including all the necessary functions directly inside the FooClient record (because if I do that, then this code compiles)? I have to admit that I'm unsure about why exactly the type system doesn't like my concoction. I can't really put my finger on why it doesn't compile, but I expect  a separation like this to be possible in Servant without having to include all possible functions inside the FooClient record.

Kasper

**Comment by phadej** [comment]
ping @fizruk, @fierce-katie

**Comment by fierce-katie** [comment]
@KasperJanssens 
Hello, Kasper.

The way client functions are matched with API depends on how you declare the `ClientLike` instance for `FooClient` in your case. By default, nested alternatives are expanded (that's why it compiles when you list all functions directly in `FooClient` structure). 

There's an alternative way to declare this instance:
```haskell
instance (Client FooApi ~ client) => ClientLike client FooClient where
  mkClient = genericMkClientP
```

Your example code successfully compiled with this one.

The `genericMkClientP` function does not expand nested alternatives and has been added just because of the reasons you mention: to have separate client structures for logically separated nested APIs. 

I hope this helped :)

**Comment by KasperJanssens** [comment]
Hello Catherine,

Thanks for the response, I'll close the ticket as soon as I managed to verify it (unfortunately that might take some time still).

Kasper

**Comment by KasperJanssens** [comment]
Confirmed, sorry it took so long. Thanks for the help!
