### ISSUE TITLE
how to deal with partial parseable types in FromHttpApiData

### ISSUE THREAD

**Issue by CarstenKoenig** [haskell-servant/servant#796]
not sure if this is a bug/issue at all but I wanted to have a UUID as part of the query-url and so I wrapped the type and have this:

```haskell
newtype MyId = MyId UUID

instance FromHttpApiData MyId where      
  parseUrlPiece piece = do
    s <- parseUrlPiece piece
    case UUID.fromString s of
      Nothing -> fail $ "no valid UUID-piece " ++ show piece
      Just uid -> return $ MyId uid
```
sadly the behavior of this is that the corresponding API part triggers and the hole process fails if this hits the `fail` case - **no matter what the verb is**

so if I have some thing like this:

```haskell
type API =
  "api" :> "article" :> Capture "artId" MyId :> Get '[JSON] (Maybe Article)
  :<|> "api" :> "article" :> "new" :> Post '[JSON] MyId
```

this will fail for `api/article/new` as the first part triggers and `"new"` is no valid UUID

of course it' easily fixed by reversing the order of the two parts but still it would be nice if the process would fall through to the next case/part if a `Capture` fails in the `parseUrlPiece` function

**Comment by alpmestan** [comment]
IIRC allowing "arbitrary backtracking" (not entirely arbitrary to be fair) would force us to deviate from the HTTP spec, but this is very much @jkarni's specialty so I will let him take it from here.

**Comment by jkarni** [comment]
No, I think the issue here is the use of `fail` (which for `Either` throws an exception). Can you try using `Left . T.pack` instead?

**Comment by CarstenKoenig** [comment]
@jkarni yes you are right - with `Left` it works just as expected

Thank you
