### ISSUE TITLE
Support authorization (separately from authentication)

### ISSUE THREAD

**Issue by m-renaud** [haskell-servant/servant#799]
Authentication and authorization are related but separate concepts, Servant currently conflates them though; if you're authenticated then you are authorized. There is also currently no built-in support for more complex authentication schemes such as OAuth, and if they were to be added it would be nice if they were built on top of infrastructure that differentiated authentication from authorization so they wouldn't need to be rewritten in the future.

I've spent a bit of time thinking about the problem and have some ideas for how we could achieve this. I'm putting most of my thoughts in a doc (because its easier to add to and modify than github comments), hopefully it will ready to share to get feedback by the end of the weekend.

## Current auth support

_Pros:_
* `Context` does a lot of the heavy lifting for non-request state
* `BasicAuth` is nice and easy to use
* APIs that are protected are done so in a type-safe way (I love this!)

_Cons:_
* Authentication and authorization are conflated
* `BasicAuth` and `GeneralizedAuth` look very different from one another
  - BasicAuth uses `BasicAuthData -> IO (BasicAuthResult usr)` auth check, generalized uses `AuthHandler Request Account`
  - BasicAuth specifies the authentication result type as part of the `BasicAuth` combinator, generalized auth uses type families
* No built-in support for common authentication methods

## High level design idea

* Authentication checks take credentials provided by the client ((username,password), OpenID, OAuth token, etc.) and return an authentication result (`Authenticated` _id_ | `AuthenticationError`).
* Authorization checks take an _id_ and return an authorization result (`Unauthorized` | `AuthenticationRequired` | `Authorized`)
* AuthProtect (or equivalent) combinator deals only with authorization, if the API is protected then Servant will ensure that the user is authenticated first, then pass the required data to the authorization check.
* Multiple authentication schemes can be provided

There will be a lot more detail in the doc, and there are definitely open design questions, I just wanted to get the conversation started :)

**Comment by jkarni** [comment]
Have you seen servant-auth [0]? This seems to overlap a lot with it. OpenID and
OAuth aren't yet supported, but could well be.

[0] https://github.com/plow-technologies/servant-auth

**Comment by alpmestan** [comment]
The idea looks good to me, although I definitely don't see servant as conflating authentication and authorization. I'd say it simply cares about the former, the latter is left for the user to deal with currently! So there probably is a solution that could sit on top of either (or both?) the generalized auth stuffs or the servant-auth packages that Julian points to above.

**Comment by m-renaud** [comment]
> Have you seen servant-auth

Hey Julian, I saw the name and looked at it (very briefly) when looking at auth for Servant, I'll definitely take a closer look! I think when I saw that it wasn't part of the haskell-servant repo and appeared to have a relatively small number of downloads relative to servant itself that it wasn't the recommended/common approach for doing auth. I think this may just be a byproduct of the Haskell ecosystem where libraries are usually spread across a number of packages instead of being one monolith with nothing really tying them together other than knowing that they're supposed to be used together :)

> although I definitely don't see servant as conflating authentication and authorization. I'd say it simply cares about the former ...

Yes, you're right, "conflating" is probably the wrong word. I was more thinking that authorization could/should be a first class citizen of the Servant framework instead of something you do ad-hoc in your handler. Then you can provide more separation of concerns and a structured way of dealing with what happens when a user is not authenticated or authorized; this keeps the handler itself free from that logic.

Something else I noticed (or failed to notice) is that you can't get the authentication state of a user from a non-protected API. For example, your home page may not be protected but you may still want to have custom logic if the user is logged in. I didn't see a way of doing that, let me know if I missed it though.

So, it sounds like servant-auth is the recommended way of doing authentication? Is that because you wanted to avoid committing to an official auth API until some of the kinks were worked out, or because you wanted to keep the deps small for core servant?

**Comment by abailly** [comment]
FWIW, I have written code to handle some primitive form of RBAC. If that's of interest to anyone, I could make it publicly available for scrutiny and discussions.

**Comment by m-renaud** [comment]
@abailly That would be great!

**Comment by phadej** [comment]
@m-renaud You should note that `servant` is designed to be extensible. E.g. `Capture` combinator could <sup>&dagger;</sup> live in a separate library. So does alternative authentication stuff is in `servant-auth`. So to answer to your

> I was more thinking that authorization could/should be a first class citizen of the Servant framework instead of something you do ad-hoc in your handler.

You don't need to have things in the handler, you can make first class Servant combinators, which just 
happen to live in your package, and not in `servant` & `servant-server` packages.

> So, it sounds like servant-auth is the recommended way of doing authentication? Is that because you wanted to avoid committing to an official auth API until some of the kinks were worked out, or because you wanted to keep the deps small for core servant?

It's one way. We (at least me) aren't sure which approach is the clearest. Note that core `servant` has BasicAuth, but it's an experimental API.

<sup>&dagger;</sup> There is some code in `servant-server`, but that can be used to work with other combinators related to request path segements.

**Comment by jkarni** [comment]
> Is that because you wanted to avoid committing to an official auth API until some of the kinks were worked out, or because you wanted to keep the deps small for core servant?

Both, and also to encourage experimentation and competition by not blessing one specific approach.

Given that the essential design proposed here seems to similar to `servant-auth`, should we close this and move the discussion there?

**Comment by m-renaud** [comment]
@phadej Gotcha, I wasn't sure if the plan was to continue to build out the experimental API until there was general consensus that the implementation there was good enough to promote to the recommended API, or if it was just meant to provide the building blocks necessary for people to do their own thing.

@jkarni Yes, I think you're right that this discussion is more around ideas for improvements to servant-auth. I'll open an issue there and link back to this one for posterity.

In any case, since servant-auth seems to be the most mature implementation would it be possible to link to it or mention it from the Servant auth docs? That's not to say that its the blessed approach, but its one that you could consider using if you're working with Servant and don't want to build your own combinators from scratch :)

**Comment by jkarni** [comment]
I opened #805 for moving more officially towards `servant-auth`. Closing this since between that and the issue in the `servant-auth` repo, it seems like there's nothing to do here.
