### ISSUE TITLE
ServantError instance of Exception

### ISSUE THREAD

**Issue by PierreR** [haskell-servant/servant#80]
Wouldn't make sense to make [ServantError](https://github.com/haskell-servant/servant/blob/master/servant-client/src/Servant/Common/Req.hs#L34) an instance of Control.Exception ?

**Comment by alpmestan** [comment]
I guess we could. Since (for now) we force `EitherT` down people's throats there wouldn't be any use for an `Exception` instance I think. Do you have any? I do agree that we could make an instance just because it makes to though =)

**Comment by PierreR** [comment]
I do. With the current situation I eventually need to map ServantError to a custom applicative one. Ideally I would prefer to have a function that accepts any `Control.Exception` and keep `ServantError` exposed until it reaches that function.

Generally speaking it seems that an exception would add more flexibility.

I have to say I am not convinced the `EitherT` approach is so great either ;-).

**Comment by alpmestan** [comment]
Well with 0.4 you can write handlers in oter monads, which is the first step in improving the situation.

Feel like putting a little PR together?

**Comment by PierreR** [comment]
Sure I can PR the instance for `exception` if you are ok with it. That should be quite easy ;-)

**Comment by PierreR** [comment]
I actually need another change and will PR accordingly if I have your ok.

Could `parseBaseUrl` type goes from  `String -> Either String BaseUrl` to ` String -> Either ServantError BaseUrl` ? I actually would like it to be an `Exception` to improve composability.

**Comment by alpmestan** [comment]
You could even put it in its own module. Regarding `parseBaseUrl` I think it would be ok since it's internal. So if you need to tweak the internals a bit, why not, I'm sure @jkarni won't mind either.

**Comment by PierreR** [comment]
>  So if you need to tweak the internals a bit, why not, I'm sure @jkarni won't mind either.

Is it really internal ? The whole module is [re-exported](https://github.com/haskell-servant/servant/blob/master/servant-client/src/Servant/Client.hs#L20).

**Comment by jkarni** [comment]
@PierreR can you explain a little more the reason for changing the signature of `parseBaseUrl`?

**Comment by PierreR** [comment]
My motivation is to re-conciliate exception handlings from different libraries when I build the command line of my application. Ideally I would like to use one function with this signature `checkError :: Exception e => Doc -> Either e a -> IO a`. 
Of course I could just have  `checkError :: Show  e => Doc -> Either e a -> IO a` and it would work just fine. It is just less precise.

Given `String` for exception is generally considered as a poor practice and the servant client already defined `ServantError`, I believe it makes the API generally more composable if there is only one of `Either Exception a`/`Either String a`.

As a general note, I have to say I fully agree with all the recent posts that advice against [`ExceptT IO`](https://www.fpcomplete.com/user/commercial/content/exceptions-best-practices) . So I dislike the fact that the library forces `EitherT` on us. That is another motivation for having a `Exception` instance for `ServantError`.

**Comment by jkarni** [comment]
I think having something like `(MonadError ServantError m, MonadIO m ) => m a` instead of `EitherT ServantError IO a` could be a good move, and should work. The servant-server version might be trickier (there might be too much ambiguity) and anyhow doesn't seem to me like a big deal given that it's pretty easy to work in any monad besides `EitherT`. 

I don't however like the idea of changing the signature of `parseBaseUrl` to `Either ServantError BaseUrl`. It's not a `ServantError` - it happens much before any request - and it seems to sacrifice clarity for ease-of-use in a pretty specific use-case (which, it seems to me, isn't that annoying in the first place). But I could well be wrong.

**Comment by PierreR** [comment]
Curious about `parseBaseUrl`, I have been looking around a bit. The definition given by `http-client` might be of interest: 

```
parseUrl :: MonadThrow m => String -> m Request
parseUrl s =
    case parseURI (encode s) of
        Just uri -> setUri def uri
        Nothing  -> throwM $ InvalidUrlException s "Invalid URL"
  where
    encode = escapeURIString isAllowedInURI
```

**Comment by jkarni** [comment]
Done in #89
