### ISSUE TITLE
Allow empty responses for other methods apart from DELETE when using servant-client

### ISSUE THREAD

**Issue by asilvestre** [haskell-servant/servant#801]
I've been trying to define an API like the following:

`type API = ReqBody '[JSON] ChangeCfg :> Put '[] ()`

but for instance defining a client for it,

`putCfg = client (Proxy :: Proxy API)`

fails like this:

` Couldn't match type ‘'[]’ with ‘ct0 : cts0’  arising from a use of ‘client’ `

I've also tried defining a JSON "unit" handler, like this:

`type API = ReqBody '[JSON] ChangeCfg :> Put '[JSON] ()`

And works fine as a server handler, but not so when used as a client as there is no string you can pass to Aeson.value that gets turned into ()

Maybe is there already another way of achieving this?

**Comment by alpmestan** [comment]
You probably want to use `NoContent` (`data NoContent = NoContent`, defined in servant) instead of `()` for empty response bodies.

**Comment by jkarni** [comment]
@asilvestre closing this, but if you feel like that's a mistake, feel free to re-open.

**Comment by asilvestre** [comment]
Sorry I've received the answer, which was exactly what I asked and forgot to close it later. Thanks for everything
