### ISSUE TITLE
Return JSON in throwError

### ISSUE THREAD

**Issue by vimalloc** [haskell-servant/servant#802]
Sorry in advance, I'm sure this has been answered somewhere before, but my searching is failing me and I haven't been able to find any information yet.

Is there an easy way to return JSON from a `throwError` handler (ex: `S.err404`)? I'm sure I could get it working by setting the `errBody` to JSON encoded `Data.ByteString.Lazy.Internal.ByteString` and `errHeaders` to include `Content-Type: application/json;charset=utf-8`, but this seems like a lot of hassle for something that I presume is pretty common. Am I missing something obvious here?

Thanks :)

**Comment by vimalloc** [comment]
Just on the off chance it helps some else, here is the helper function I wrote for this:

```haskell
module RestAPI.RestErrors where

import qualified Data.ByteString.Char8 as BS
import qualified Data.ByteString.Lazy.Char8 as LazyBS
import           Data.CaseInsensitive (mk)
import qualified Servant as S
import           Text.Printf (printf)

errorToJSON :: Int -> String -> String -> S.ServantErr
errorToJSON code title detail = err {S.errBody = jsonBody,
                                     S.errHeaders = [jsonHeader]}
  where
    err          = getErrorFromCode code
    jsonTemplate = "{\"status\": %d, \"title\": \"%s\", \"detail\": \"%s\"}"
    jsonBody     = LazyBS.pack $ printf jsonTemplate code title detail
    jsonHeader   = ((mk $ BS.pack "Content-Type"),
                    (BS.pack "application/json;charset=utf-8"))

-- Non-exhaustive. Trivial to add more, just only adding the ones I
-- am currently using.
getErrorFromCode :: Int -> S.ServantErr
getErrorFromCode 400 = S.err400
getErrorFromCode 404 = S.err404
```

You can obviously change the JSON to whatever your spec requires, and use it the with throwError just like normal

```haskell
S.throwError $ errorToJSON 404 "catNotFound" "The cat named 'foo' was not found"
```

**Comment by 3noch** [comment]
It's unfortunate you had to do that much work. Perhaps `servant` could (or already does) expose some helper functions that will properly set up this error type along with the headers, the same way it does for successful return types. Anyone?

**Comment by phadej** [comment]
See #732

**Comment by alpmestan** [comment]
We can definitely offer something to help with that, as virtually all our users (yeah, not exactly all of them, but surely at least 90% of our users) write applications that use JSON. #732 is indeed very relevant, as ideally we want a solution that does not require as much work as @vimalloc did. I'm still hoping we can find a way of specifying errors and handling them that 1/ is not too cumbersome to use/write code against 2/ can be used by client derivation for returning clients that hand you errors as values of the same error type used by the server, instead of the very annoying and almost unusable `ServantError`. At least whenever the user is using an error type that's not servant-server's `ServantErr`.

**Comment by vimalloc** [comment]
#732 has some neat ideas. The ambitious approach in particular, on top of being easier to use, would open the door for documenting the error cases of your application as well. It will be interesting to see what happens there.  👍

**Comment by jkarni** [comment]
Closing in favor of #732.

**Comment by jkarni** [comment]
Also, note that there's now `servant-check-exceptions`.

**Comment by domenkozar** [comment]
I have simplified a bit the snippet from @vimalloc and created a simple cookbook entry https://github.com/haskell-servant/servant/pull/947 - feedback welcome.
