### ISSUE TITLE
More informative ConnectionError in servant-client-core

### ISSUE THREAD

**Issue by 3noch** [haskell-servant/servant#807]
`servant-client-core` now has an opaque `ConnectionError` type that just stores text. In order to make any sort of reliable decision based on client errors this type needs to preserve as much information as possible. Perhaps it can be parameterized so that underlying client backends can use their native error types. C.f. #714  for an example use-case where we try to examine TLS-not-supported error and downgrade to HTTP connections.

**Comment by domenkozar** [comment]
Another consequence is that exception is printed as-is with newline characters visible instead of being pretty-printed. This makes reasoning about these errors harder :)

**Comment by heroin-moose** [comment]
Bump? This is really annoying. If everyone is busy I'll write the patches, no problem.

**Comment by alpmestan** [comment]
We would be delighted to take a patch :-) The servant devs (the 2-3 ones that are somewhat active these days) indeed have been a bit busy lately, since the (recent) latest release.

**Comment by clementd-fretlink** [comment]
I've started to have a look at it. From what I've gathered from this issue and #714, either we could fix the issue to be `HttpException` (from `Network.HTTP.Client`) or make `ServantError` parametric on the error type. I've tried replacing `Text` with `HttpException`, it breaks a few typeclass instances (`HttpException` has no `Eq` instance), but the rest looks okay.

**Comment by domenkozar** [comment]
For posterity:

```
@phadej | servant-client-core must stay independent of http lib
@phadej | and it would be nice to not parametrise it, as it might be used as an exception
@phadej | (polymorphic exceptions are trickier to catch!)
```

**Comment by phadej** [comment]
We can use SomeException if it helps the problem

It's better than Text, you still need to know what it could be to get more info: but you can. All SomeExceptions could be compared equal

**Comment by clementd-fretlink** [comment]
I've used `SomeException`, the only issues left are the `Eq` and `NFData` instances

**Comment by phadej** [comment]
Both Eq and NFData have to written manually. For Eq all exceptions can be considered equal; for NFData `rnf (show exc)` is probably best we can do

**Comment by clementd-fretlink** [comment]
I've added a test to make sure the expected exception is caught in https://github.com/divarvel/servant/commit/6fc447f3c1ec8ac5bd1ece6cdb40ec0db3041c16

**Comment by clementd-fretlink** [comment]
I've opened a PR replacing `Text` with `SomeException`, along with a text making sure there is no double wrapping. Let me know if it's ok with you
