### ISSUE TITLE
Incorrect type signature causes GHC to go into an infinite loop

### ISSUE THREAD

**Issue by saurabhnanda** [haskell-servant/servant#812]
Here's the **inferred** type signature of my function which was supposed to take a bunch of configurable settings and finally give-back an `Application`. 

```     
      mkApp :: (ServerT api Servant.Handler
                ~
                (t :<|> Tagged Servant.Handler Application),
                HasServer api '[Auth.AuthHandler Request UserId],
                Servant.Utils.Enter.Enter
                  (Entered Servant.Handler (ReaderT Env (LoggingT IO)) t)
                  (ReaderT Env (LoggingT IO))
                  Servant.Handler
                  t) =>
               Proxy api
               -> Entered Servant.Handler (ReaderT Env (LoggingT IO)) t
               -> Key LogId
               -> Pool Connection
               -> (LogStr -> IO ())
               -> Config
               -> Request
               -> (Response -> IO ResponseReceived)
               -> IO ResponseReceived
```

I had put the following, probably incorrect, type-signature manually, which caused GHC to go into an infinite loop and consume all RAM:

```
mkApp :: (HasServer api '[(Auth.AuthHandler Request UserId), ()])
      => Proxy api
      -> Server api
      -> V.Key LogId 
      -> Pool Connection 
      -> FastLogger 
      -> Config 
      -> Application
```

My application is running in the `type AppM = ReaderT Env (LoggingT IO)` monad, and the `mkApp` function is internally calling the following function (which I still don't completely understand!) to do the natural transformation magic:

```
    appmToServantM :: forall a. AppM a  -> Servant.Handler a
    appmToServantM appm = Servant.Handler $ runAppM_ appm -- TODO: what is happening here?!
    serverApplication = serveWithContext serverType ((authHandler $ getRailsCookieConfig config) :. EmptyContext) server
```

**Comment by 3noch** [comment]
Which version of GHC?

**Comment by saurabhnanda** [comment]
LTS 9.0 / GHC 8.0.2

**Comment by saurabhnanda** [comment]
I've finally managed to get things compiled with the following "simplified" type signature...

```
run :: forall (api :: *) t .
       ( Enter (Entered Servant.Handler AppM t) AppM Servant.Handler t
       , ServerT api Servant.Handler ~ (t :<|> Tagged Servant.Handler Application)
       , HasServer api '[Auth.AuthHandler Request UserId]) 
    => Proxy api
    -> Entered Servant.Handler AppM t
    -> IO ()
```

...but have absolutely no idea what any of that means. Is there any tutorial which can help me understand what's going on here?

**Comment by alpmestan** [comment]
@saurabhnanda Did you go through the servant tutorial [here](https://haskell-servant.readthedocs.io/en/stable/) ? This will provide enough to get you most of the way towards understanding that signature. I also think it's not really "the signature that you want". The `run` function above is generic in the API type (the `api` type variable above) and the server side handlers (that `Entered ...` argument), but I suspect you're working with just one API and one server?

**Comment by saurabhnanda** [comment]
> The run function above is generic in the API type (the api type variable above) and the server side handlers (that Entered ... argument), but I suspect you're working with just one API and one server?

I **want** the `run` function to be able to take APIs and handlers/servers of different types. Use-case: 

* We have 5 modules (and growing) with various logically related endpoints.
* During development, we need a quick way to fire-up Servant for any one of the modules that is under active development, eg:

```
> AppServer.run (Proxy :: Proxy Module1.Endpoints.Routes) (Module1.Endpoints.handlers)

-- or

> AppServer.run (Proxy :: Proxy Module4.Endpoints.Routes) (Module4.Endpoints.handlers)
```

> Did you go through the servant tutorial here ? This will provide enough to get you most of the way towards understanding that signature.

I've gone through that tutorial, which is how I managed to get Servant to work with our custom monad. However, there's a bunch of other complicated stuff in our use-case, namely: a context to pass-along the authentication-cookie decryption key, and that the routes being served are appended with `:<|> "assets" :> Raw` and `:<|> (serveDirectoryFileServer "assets")`

**Comment by alpmestan** [comment]
I see. I would still maybe provide smaller functions (an alias for running on a given port that you get from the config or something, something that takes an API type and a server for it and appends the file serving bits at both levels), and then simply put all of those together wherever you need them. Just to avoid that "horrible" type sig, but at least it should be nicer in the next release.

To answert:
> ...but have absolutely no idea what any of that means.

We can look at it bit by bit and give an intuition of what it means.

``` haskell
run :: forall (api :: *) t .
       -- given any API type and some type t, assuming:
       ( Enter (Entered Servant.Handler AppM t) AppM Servant.Handler t
       -- we know how to apply `enter` to t, going from AppM to Handler in all handlers,
       , ServerT api Servant.Handler ~ (t :<|> Tagged Servant.Handler Application)
       -- that a server for the API type looks exactly like `t :<|> Tagged Handler Application`,
       , HasServer api '[Auth.AuthHandler Request UserId])
       -- and that we know how to serve the API type, with an auth handler in the context, then:
    => Proxy api -- given a handle to the API type
    -> Entered Servant.Handler AppM t -- and a server that's like `t` but with handlers in the Handler monad
    -> IO () -- run the server
```

Looks like there might be a bit of potential for problems in this type indeed. Could you perhaps show the code, so that maybe someone could suggest a similar function but that will be closer to what you want to achieve, without the type inference quirks.

**Comment by utdemir** [comment]
I randomly stumbled upon this bug and I think I have a smaller example:

```
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE DataKinds #-}

module Test where

import Servant

type MyAPI = Post '[JSON] () :<|> Get '[JSON] ()

server :: Server IO
server = enter (undefined :: IO :~> Handler) (undefined :: ServerT MyAPI IO)
```
The type error is on `server :: Server IO`, it should be `server :: Server MyAPI` to be type-correct.

Here is what I have.

```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.2
$ ghc-pkg list | grep servant
    servant-0.11
    servant-server-0.11.0.1
```

Also I checked with `GHC 8.2.1` and it correctly terminates with type error.

**Comment by alpmestan** [comment]
@utdemir `enter` is gone in master, replaced by `hoistServer` which works completely differently and might therefore systematically rule out your program. Would you maybe like to try it out on your example? You can see some explanations in the `master` version of the tutorial: https://haskell-servant.readthedocs.io/en/master/tutorial/Server.html#welcome-hoistserver

**Comment by alpmestan** [comment]
More generally, anyone who's been disappointed by `enter` (that's a lot of people), feel free to try out `hoistServer` and let us know about any problem. It's pretty much a given that there will be less issues.

**Comment by utdemir** [comment]
@alpmestan Just tried `hoistServer`, and it was a much more pleasant experience, thank you :).

**Comment by alpmestan** [comment]
@saurabhnanda servant 0.12 will be uploaded soon, `hoistServer` should improve your type signatures and situation too, most likely not ending in a loop etc. Feel free to close the issue if you try it out and find that you don't have any particular problem with your example anymore.

**Comment by saurabhnanda** [comment]
Should I wait for 0.12 or you want me to try the 0.12-rc?



On Wed, Nov 8, 2017 at 3:11 PM, Alp Mestanogullari <notifications@github.com

**Comment by phadej** [comment]
`servant-0.12` is released.

**Comment by jkarni** [comment]
Closing. Please re-open if `hoistServer` is not the desired solution.
