### ISSUE TITLE
RawM data type for using Raw endpoints with Enter

### ISSUE THREAD

**Issue by cdepillabout** [haskell-servant/servant#819]
I was playing around with using [`Raw`](https://hackage.haskell.org/package/servant-0.11/docs/Servant-API-Raw.html#t:Raw) to create a file server with [`serveDirectoryWebApp`](https://hackage.haskell.org/package/servant-server-0.11/docs/Servant-Utils-StaticFiles.html#v:serveDirectoryWebApp).

However, I am not running in [`Handler`](https://hackage.haskell.org/package/servant-server-0.11/docs/Servant-Server.html#t:Handler), but instead working in my own monad using [`Enter`](https://hackage.haskell.org/package/servant-0.11/docs/Servant-Utils-Enter.html#t:Enter).  I need to get the directory path to use to serve files from my monad, so it is not possible for me to use the normal `Raw` with `serveDirectoryWebApp`.

I whipped up a `RawM` data type that gets turned into an `m Application` by the `ServerT` type family.  This let me write a more generic `serveDirectoryWebApp` function.

It basically looks like this:

```haskell
data RawM deriving Typeable

instance HasServer RawM context where
  type ServerT RawM m = m Application

  route
    :: forall env.
       Proxy RawM
    -> Context context
    -> Delayed env (Handler Application)
    -> Router' env (Request -> (RouteResult Response -> IO ResponseReceived) -> IO ResponseReceived)
  route Proxy _ rawApplication = RawRouter go
    where
      go
        :: env
        -> Request
        -> (RouteResult Response -> IO ResponseReceived)
        -> IO ResponseReceived
      go env request respond =
        runResourceT $ do
          routeRes <- runDelayed rawApplication env request
          liftIO $
            case routeRes of
              (Fail e) -> respond $ Fail e
              (FailFatal e) -> respond $ FailFatal e
              (Route handlerApp) -> do
                eitherApp <- runHandler handlerApp
                case eitherApp of
                  Left err -> respond . Route $ responseServantErr err
                  Right app -> app request (respond . Route)

serveDirectoryWebApp :: Applicative m => FilePath -> ServerT RawM m
serveDirectoryWebApp = pure . staticApp . defaultWebAppSettings . addTrailingPathSeparator

```

Here's a small example of using it:

```haskell
type Api = "serve-directory" :> RawM

serverRoot :: ServerT Api (ReaderT FilePath IO)
serverRoot = rawEndpoint

rawEndpoint :: ReaderT FilePath IO Application
rawEndpoint = do
  filePath <- ask
  serveDirectoryWebApp filePath

app :: FilePath -> Application
app filePath = serve (Proxy :: Proxy Api) apiServer
  where
    apiServer :: Server Api
    apiServer = enter naturalTrans serverRoot

    naturalTrans :: ReaderT FilePath IO :~> Handler
    naturalTrans = NT transformation

    transformation :: ReaderT FilePath IO a -> Handler a
    transformation readerT = liftIO $ runReaderT readerT filePath

main :: IO ()
main = run 8080 $ app "/var/www"
```

I also wrote a slightly more generic `HasClient` instance.  The `HasClient` instance for `Raw` is missing the `(Req -> Req)` parameter that lets you change things about the request:

```haskell
instance HasClient RawM where
  type Client RawM = Method -> (Req -> Req) -> ClientM (Int, ByteString, MediaType, [Header], Response ByteString)

  clientWithRoute :: Proxy RawM -> Req -> Client RawM
  clientWithRoute Proxy req method f = performRequest method $ f req
```

Here's an example of using the `HasClient` instance.  Notice how I'm using `appendToPath` to search for a specific file.  I don't believe this is possible with the current `HasClient` instance for `Raw`:

```haskell
getFile' :: Method -> (Req -> Req) -> ClientM (Int, ByteString, MediaType, [Header], Response ByteString)
getFile' = client (Proxy :: Proxy Api)

getFile :: String -> ClientM ByteString
getFile filePath = do
  (_, _, _, _, resp) <- getFile' methodGet $ \req -> appendToPath filePath req
  pure $ responseBody resp

main :: IO ()
main = do
  manager <- newManager defaultManagerSettings
  let clientEnv = ClientEnv manager baseUrl
  eitherRes <- runClientM (getFile "foo.txt") clientEnv
  case eitherRes of
    Left servantErr -> putStrLn $ "Got a ServantErr: " <> show servantErr
    Right fileContents -> do
      putStrLn "Successfully got file /var/www/foo.txt:\n"
      LBS.putStr fileContents

baseUrl :: BaseUrl
baseUrl = BaseUrl Http "localhost" 8080 ""
```

I put this `RawM` datatype up on hackage at [servant-rawm](https://hackage.haskell.org/package/servant-rawm-0.1.0.0/docs/Servant-RawM.html) for the time-being.  There is also a more fleshed-out example for both the [server](https://github.com/cdepillabout/servant-rawm/blob/b38333b91550a2cc3eda6c5a4b94fcf6eda691a0/example/Server.hs) and the [client](https://github.com/cdepillabout/servant-rawm/blob/b38333b91550a2cc3eda6c5a4b94fcf6eda691a0/example/Client.hs).

However, I'm wondering why the current `Raw` datatype doesn't already work like my `RawM` type?  Why does `Raw` get turned into a `Tagged m Application` instead of an `m Application`?  Is there some catch I'm overlooking?

There seems to be a couple issues talking about the interaction between `Raw` and `Enter`, but I didn't seem to run into any problems with implementing `RawM`.  Maybe `Enter` has changed with `servant-0.11`, making this possible?

-   https://github.com/haskell-servant/servant/issues/157
-   https://github.com/haskell-servant/servant/issues/765
-   https://github.com/haskell-servant/servant/issues/785

Would there be any interest in pulling this `RawM` code back into servant proper?  It seems like a pretty convenient thing to have.  If not, then would any of the current servant developers (or anyone else making heavy use of servant) like to be made a moderator/administrator for the [servant-rawm repository](https://github.com/cdepillabout/servant-rawm)?  It would be unfortunate if people started using it and I stoped updating it for whatever reason.

Note that `servant-rawm` is still a work-in-progress and things like documentation and tests are not fully fleshed-out.  I'll continue working on them after it has been decided what will happen with this `RawM` type.

**Comment by 3noch** [comment]
I've wanted this as well just recently! Thanks for the work.

**Comment by codedmart** [comment]
[`Enter`](https://hackage.haskell.org/package/servant-0.11/docs/Servant-Utils-Enter.html#t:Enter) is actually being deprecated if I am not mistaken https://github.com/haskell-servant/servant/pull/804.

**Comment by cdepillabout** [comment]
@codedmart Looking at the diff in #804, it looks like the [instance for `Raw`](https://github.com/phadej/servant/blob/822b853590974a8812d45dead7f06699f96d2d5f/servant-server/src/Servant/Server/Internal.hs#L462) hasn't really changed from its current state.

I believe something like `RawM` will still be needed, even though `hoistServer` will be used instead of `Enter`.

**Comment by codedmart** [comment]
@cdepillabout Sorry I didn't give more context. Yes that PR didn't change Raw currently. Was just more commenting that `hoistServer` is meant to replace `enter` eventually. I also am not giving an opinion as to whether `RawM` is needed or wanted by others. I just feel that it is easy enough to use `Raw` with `hoistServer` now. I am also not making use of `servant-client` with `Raw` either though currently. I don't see any harm at all in having this available on hackage. Just not sure I think this should be in servant proper. No strong or official opinion though.

**Comment by cdepillabout** [comment]
I've fixed up the [servant-rawm](https://hackage.haskell.org/package/servant-rawm) package in version 0.2.0.1.  It now is slightly more generic and provides usable `HasClient` and `HasDocs` instances.

I've also posted a short [article](https://functor.tokyo/blog/2017-10-15-servant-rawm) about it on my blog.

I'll go ahead and close this issue, but if anyone is interested in this, feel free to open issues / PRs on the [servant-rawm repository](https://github.com/cdepillabout/servant-rawm).

**Comment by afcady** [comment]
@codedmart so how do you use `Raw` with `hoistServer`?  Is there a working example anywhere?  If so it should be posted to  #785

**Comment by alpmestan** [comment]
It should just work with the latest version of servant (0.14.x). Have you tried?

**Comment by alpmestan** [comment]
Oh, this indeed requires a different combinator. Is `RawM` out of date? Or are you perhaps suggesting that we integrate `RawM` to the core servant libraries?

**Comment by afcady** [comment]
RawM is indeed out of date.  However, I just now forward ported it, and got it working on the server side, not 60 seconds ago.

However, I had to disable the client functionality because I don't understand the changes in the Servant API that broke it.

**Comment by alpmestan** [comment]
Feel free to open an issue about this, we can certainly help/guide you through porting the client support for RawM.

**Comment by afcady** [comment]
Actually it turns out not even the server actually works :(.  It compiles and runs and responds to requests, but the responses are errors and I get this runtime error:

    src/Servant/RawM/Internal/Server.hs:50:10-45: No instance nor default method for class operation hoistServerWithContext

I will try to figure out how to implement this typeclass for a bit but I think my odds of success aren't very good.  Backup plan is to go bug @cdepillabout about updating it.

**Comment by afcady** [comment]
Well actually that was easier than I thought it would be.  (I thought I'd have to understand what was going on, but it turns just blindly fitting the types together worked.)

Here's what I got:

https://github.com/cdepillabout/servant-rawm/pull/5

**Comment by alpmestan** [comment]
Nice, cheers!
