### ISSUE TITLE
How to get host without port?

### ISSUE THREAD

**Issue by saurabhnanda** [haskell-servant/servant#820]
Is there a standard way in servant to capture the `Host` header without the port? I tried `Header "Host" Text` but it seems to give `localhost:3000` in development environments which throws-off all following logic.

Use-case: Multi-tenant webapps which use the hostname (or subdomain) to select the current user/company account.

**Comment by 3noch** [comment]
That's how the `Host` header is supposed to work ([see here](https://stackoverflow.com/a/3364396/503377)). You could parse it in your handler. You could also write a custom `HostNoPort` capture type which does this for you.

**Comment by 3noch** [comment]
You'd implement an `FromHttpApiData` instance for `HostNoPort` and use it like `Header "Host" HostNoPort`.
