### ISSUE TITLE
Is HTML not a standard/default content-type?

### ISSUE THREAD

**Issue by saurabhnanda** [haskell-servant/servant#823]
I'm looking at https://www.stackage.org/haddock/lts-9.0/servant-0.11/Servant-API-ContentTypes.html where it talks about *how* to make your own `HTML` content-type, but also suggests that `HTML` isn't a standard content-type supported by servant out-of-the-box. Is this correct? Why?

**Comment by phadej** [comment]
From my POV there are various reasons contributing:
- there is no de-facto HTML generation library, so we have `servant-lucid`, and `servant-blaze`.
- servant isn't "batteries included". OTOH `servant` is open, so it's easy to extend. If you need HTML pick `servant-lucid`, or `servant-blaze`; if you need CSV check `servant-cassava`, pictures - [`servant-JuicyPixels`](http://hackage.haskell.org/package/servant-JuicyPixels)
    - On the client side in `servant-client-core-0.12`, will be HTTP client library agnostic.
    - In the future `servant-snap` will share common code with `servant-server`: We'll probably have `servant-server-core` (name is subject to change).
- `JSON` is a bit of exception: `aeson` is de-facto JSON library for Haskell, `servant` originates in API development (you always need JSON there nowadays), and last but not least: we need something to write examples with :)

**Comment by alpmestan** [comment]
@phadej's summary is very accurate and reflects the reasoning behind separate packages for HTML. Note that there even is a third option, [servant-ede](https://hackage.haskell.org/package/servant-ede) =)

**Comment by jkarni** [comment]
Closing, feel free to re-open if you think that was a mistake.
