### ISSUE TITLE
Cookie Combinator

### ISSUE THREAD

**Issue by seanhess** [haskell-servant/servant#83]
I'm using JWTs for auth. I'm implementing the logic by hand, which is fine for now, but it is slightly more convenient to have a `Cookie` combinator so I don't have to parse the header by hand. 

Here's an example. It works exactly like `Header`, doesn't assume anything about authentication, it just provides a cookie value to your code. 

https://gist.github.com/seanhess/f4cf71ea58e4483d8ee4

Is there a place for a low-level Cookie combinator like this? I think it could live side-by-side with higher-level authentication code. If so I'd be happy to clean this up and issue a PR.

**Comment by alpmestan** [comment]
Great!

Such a "dummy" Cookie combinator (dummy as in it doesn't do anything fancy) would definitely be something I would like to add support for in all servant packages. The definition would go in a `Servant.API.Cookie` module and we would have instances of all the appropriate classes in the respective packages.

Anyone could then provide a higher level auth machinery on top of `Cookie` or `Header`. This would in fact be useful for the ongoing work on auth.

**Comment by seanhess** [comment]
Sounds good! I'll close this and open a PR soon.

**Comment by seanhess** [comment]
Closed in favor of PR.

**Comment by jkarni** [comment]
Closing again since we have `servant-auth` & `servant-auth-cookie`
