### ISSUE TITLE
Should servant-doc notes be wrapped in a separate header?

### ISSUE THREAD

**Issue by ivan-m** [haskell-servant/servant#831]
Currently, servant-docs emits each note (specified using the `notes` lens as part of the actions) as its own header within the overall endpoint section.

I wonder whether it would make more sense to group them together under a combined heading.

My primary use-case for this is that with servant-pandoc, I would like some way to provide information that people can use to write a Pandoc filter to read all those notes in as Markdown and get them processed properly in the output (as there is currently no way to identify which of the various sections are Notes).

**Comment by alpmestan** [comment]
If you find a way to properly group or tag notes so that they can easily be found and post-processed while keeping not breaking too hard (or not at all ideally) existing code, that would be lovely. Even a somewhat smooth migration story would do. Feel free to research changes to servant-docs and bring up suggestions in this issue, surely we can find something that can please everyone here.

**Comment by ivan-m** [comment]
First of all, note that for some reason, servant-docs uses 2-level headers (`## ...`) for the endpoint, and 4-level headers (`#### ...`) for everything below it, when it should really be 3-level.  This should really be fixed, as these solutions will break everything that comes after the notes (which is everything) for each endpoint by unintentionally grouping them under the combined 3-level header.

The three approaches I've come up with:

1. Unconditionally add a `### Notes` (title open for bikeshedding) header before all the note fields, keeping them at 4-level headers.

    **Pros:** No API change, simple solution.

    **Cons:** Unconditional change to output, static title (which may not suit what the actual note contents are).

2. Since #829 added `RenderingOptions`, have a boolean flag indicating whether such a header should be added (defaulting to `False`).

    **Pros:** Extends current solution, configurable, defaults to current behaviour.

    **Cons:** Static title (which may not suit what the actual note contents are).

3. Rather than just a boolean flag, add a `Maybe String` option to specify the optional title, defaulting to `Nothing`.

    **Pros:** Extends current solution, even more configurable, defaults to current behaviour.

    **Cons:** Configurable title may make post-processing even more difficult as it needs to occur on a case-by-case basis.

**Comment by ivan-m** [comment]
I no longer need this (I realised that there were more categories available other than notes that this could apply to, and I've found a work-around for `servant-pandoc`) but I'm still happy for the pull request to be merged in case someone else wants this behaviour.

**Comment by alpmestan** [comment]
Sound good.
