### ISSUE TITLE
double escape when creating link

### ISSUE THREAD

**Issue by wuzzeb** [haskell-servant/servant#835]
In 54c30533425d4e9f05851df2bfbf316de80c7c56, a call to escape was added to linkURI to escape bad characters in the URL string.  The problem is that this causes a double escape sometimes because escape is also called in the HasLink instance.  That is, the HasLink instance for Capture is

```
instance (ToHttpApiData v, HasLink sub)
    => HasLink (Capture sym v :> sub) where
    type MkLink (Capture sym v :> sub) = v -> MkLink sub
    toLink _ l v =
        toLink (Proxy :: Proxy sub) $
addSegment (escape . Text.unpack $ toUrlPiece v) l
```

note the call to escape.  This causes the segment in Link to be escaped.  Then when it goes though linkURI, it gets escaped again.

For example,

```
type SomeRoute = "abc" :> Capture "email" Text :> Put '[JSON] ()
```

then

```
safeLink SomeRoute SomeRoute "test@example.com" 
   ~ Link { _segments = ["abc", "test%40example.com"]}
```

due to the escape in the HasLink instance.  But then calling linkURI turns it into

```
URI { uriPath = "abc/test%2540example.com" }
```

because the link segments are escaped again.

**Comment by fizruk** [comment]
@haskell-servant/maintainers would an `Escaped` newtype help to keep track of when we have an escaped `Text`?

**Comment by alpmestan** [comment]
I'd be in favor of a solution that makes it hard to get it wrong. Do we really want linkURI to do the escaping or is there some other, smarter way out of this problem that makes sure we escape only once?

**Comment by jekor** [comment]
What about reverting 54c3053 in the meantime?

**Comment by alpmestan** [comment]
Would make sense to me. @jekor @wuzzeb Would you like a bugfix 0.12.x release next week with just this commit reverted?

**Comment by jekor** [comment]
It would help me upgrade from 0.10.

**Comment by phadej** [comment]
Uploaded in https://hackage.haskell.org/package/servant-0.12.1
