### ISSUE TITLE
Edit on github link in docs is currently broken

### ISSUE THREAD

**Issue by andys8** [haskell-servant/servant#838]
1. Open http://haskell-servant.readthedocs.io/en/stable/tutorial/index.html
2. Click on “Edit on Github”
3. 404: https://github.com/haskell-servant/servant/blob/b460e211576bad4851794c3fb98c452fa939fcb5/doc/tutorial/index.rst

The behavior is the same for all subpages of the documentation.
The commit with this id was probably removed.

**Comment by alpmestan** [comment]
@andys8 Thanks for reporting. It might be time for us to rework the doc generation / upload scripts.

**Comment by alpmestan** [comment]
@soenkehahn Any idea of what might be going wrong? IIRC you contributed most of this infrastructure. If not I'll try and take a look and debug it sometimes this week.

**Comment by alpmestan** [comment]
It would be nice if the edit link would just pick the branch (or master, really).

**Comment by andys8** [comment]
Jap

**Comment by i-schuetz** [comment]
The general link to Github ("Read the docs" at the bottom left, then "On Github" > "View") also doesn't work.

**Comment by tchoutri** [comment]
It works now
