### ISSUE TITLE
servant-docs release?

### ISSUE THREAD

**Issue by ivan-m** [haskell-servant/servant#844]
There have been [quite a few additions](https://github.com/haskell-servant/servant/blob/0d97deada9e84b22ace60d6ce8551706586cc1ae/servant-docs/CHANGELOG.md) to the 0.11 release of servant-docs.  Would it be possible to have a 0.11.1 release please?

[`servant-pandoc`](https://github.com/mpickering/servant-pandoc/) has been updated to have the same behaviour for all except the `markdownWith` function (as that requires using `RenderingOptions` which isn't available in a released version of servant-docs); I would like to release a new version of that with all the new functionality (if not I'll just skip the `RenderingOptions` support and release as-is).

**Comment by alpmestan** [comment]
Pinging @phadej.

**Comment by phadej** [comment]
Sorry, I have a bit of a whirlpool of stuff going during this week.

I'm not sure `0.11.1` is *easy*. I don't feel super ok for making a release from a `master` branch, when everything else have moved and made breaking changes.

One option is to freeze master and push-out what we have atm as `0.12`, meaning e.g. we won't yet get `Stream` @gbaz is working on.

**Comment by phadej** [comment]
To amend: not *freeze the master*, but *cut a release branch*. Commits must flow into `master`, but I can do release preparations concurrently with that.

**Comment by alpmestan** [comment]
@phadej Maybe an isolated release of -docs?

**Comment by phadej** [comment]
done as part of 0.12
