### ISSUE TITLE
Superfluous "charset" parameter in JSON content-type

### ISSUE THREAD

**Issue by Philonous** [haskell-servant/servant#849]
https://github.com/haskell-servant/servant/commit/7793b52d232074e1305cca1227fe8ded7f417686 adds "charset=utf-8" to the content type of json responses, but the parameter isn't defined in the [media-type registration](https://www.iana.org/assignments/media-types/application/json). This causes breakage with hspec-wai (https://github.com/hspec/hspec-wai/issues/46)

Related to: https://github.com/haskell-servant/servant/issues/559

**Comment by phadej** [comment]
I'm sorry, we have ping-ponging this back and forth, and there's always some broken client.
Currently `servant-server` behaves well, as if asked for just `application/json` it will response with JSON.

The [JSON RFC](https://tools.ietf.org/html/rfc7159) says on page 10

>    Note:  No "charset" parameter is defined for this registration.
      Adding one really has no effect on compliant recipients.

So: `hspec-wai` should relax it's mime-type matching, e.g. by using [`mainType`](http://hackage.haskell.org/package/http-media-0.7.1.1/docs/Network-HTTP-Media-MediaType.html#v:mainType) from `http-media`.
