### ISSUE TITLE
tutorial sources

### ISSUE THREAD

**Issue by mf59816** [haskell-servant/servant#86]
I want to corrrect a typo in http://haskell-servant.github.io/tutorial/api-type.html.  Is there a way to do that in form of a pull request?  I searched the gh-pages branch and master but couldn't find anything.

**Comment by alpmestan** [comment]
Hello,

The website's repo is at https://github.com/haskell-servant/haskell-servant.github.io but the master branch is just the generated HTML. If you want to view and modify the sources, check out [the `hakyll` branch](https://github.com/haskell-servant/haskell-servant.github.io/tree/hakyll). This is also the branch PRs should be made against.

In particular, you can find the files for the tutorial in [`tutorial/`](https://github.com/haskell-servant/haskell-servant.github.io/tree/hakyll/tutorial), `index.md` being the tutorial's homepage.

I guess I should make the link toe the repo more proeminent, or maybe just give some instructions at the very beginning of the tutorial or something? If you couldn't find your way it means that the information isn't as accessible as I thought =)

**Comment by mf59816** [comment]
Thanks, that answers that.  If it's ok, I'll make a dual-use PR that contains both the information you just gave me and the (very few) errata.

**Comment by mf59816** [comment]
(Hum, I just found the reference to the sources on the index page.  I can't think of a way to make it any more prominent without adding too much noise.  Perhaps I was just too lazy and slow to find it?  Sorry :-)

**Comment by alpmestan** [comment]
If you think it should be at the very top of the page, using a `blockquote` (done by prefixing each line with `>` in markdown) or something, feel free to move it. That would probably stand out much more than now. Thanks by the way for reporting/fixing typos!

**Comment by mf59816** [comment]
Pleasure!  (-:
