### ISSUE TITLE
Explicit Parsing Error for Headers

### ISSUE THREAD

**Issue by KtorZ** [haskell-servant/servant#862]
Hi folks!

I am running into a simple issue: having custom headers on a request lead to have some `Maybe header` parameter in the corresponding handler function.

There are 3 scenarios resulting of parsing a header

- The header hasn't been provided
- The header didn't parse successfully
- The header is present and successfully parsed

Therefore, from within the `Handler`, I didn't find any way to know whether a header was wrongly specified or simply not specified. In the former, I want to return a clear error to the user to avoid silently swallowing the mistake. 

Headers of the response aren't accessible either, so it's not possible to lookup whether the header is provided and compare against the value of the handler's parameter to deduce whether the header didn't parse or was simply not provided.

Provided that the `FromHttpApiData` method has the following signature:

```hs
parseHeader :: ByteString -> Either Text a
```

Is there any reasons why the [Header type](http://hackage.haskell.org/package/servant-0.12/docs/Servant-API-Header.html#t:Header) isn't leveraged here since it seems to already make an explicit distinction between the 3 possible outcomes?

Thanks for helping.

**Comment by alpmestan** [comment]
I have the feeling this might be somewhat related to https://github.com/haskell-servant/servant/pull/256 and https://github.com/haskell-servant/servant/issues/241 but I'll let @phadej and @fizruk comment on this, as they have given a lot more thought to these issues.

**Comment by phadej** [comment]
Will be resolved in #873

**Comment by phadej** [comment]
solved by #873
