### ISSUE TITLE
Discussion: IsSecure visible in Link

### ISSUE THREAD

**Issue by phadej** [haskell-servant/servant#874]
While working on #873 I added `HasLink (IsSecure :> api)` instance. Should it be visible in the `Link` (currently it's fall-through)?

cc @alp, @jkarni, @fizruk

**Comment by jkarni** [comment]
I think just fall-through is fine.

**Comment by alpmestan** [comment]
I don't think `IsSecure` should affect the link either.

**Comment by phadej** [comment]
Good, then no changes are needed :)
