### ISSUE TITLE
GSoC 2018 Ideas for Haskell.org

### ISSUE THREAD

**Issue by wisn** [haskell-servant/servant#880]
Google Summer of Code will take place again in 2018. Last year, Haskell.org was not selected, and we decided to run our own program, which ended very successfully.

Currently, we are in the process of gathering ideas for the students.  I think it would be great to have a Haskell Servant project in there. Projects should be concrete and small enough in scope such that they can be finished by a student in three months. Mind to discussing the idea here? Or, just send the idea to HSoC [repository](https://github.com/haskell-org/summer-of-haskell/).

For context, Google Summer of Code is a program where Google sponsors students to work on open-source projects during the summer. Haskell.org has taken part in this program from 2006 until 2015. Many important improvements to the ecosystem have been the direct or indirect result of Google Summer of Code projects, and it has also connected new people with the existing community.

Reference: <https://summer.haskell.org/news/2017-12-25-call-for-ideas.html>
Current Ideas: <https://summer.haskell.org/ideas.html>
Repository: <https://github.com/haskell-org/summer-of-haskell/>

**Comment by jkarni** [comment]
Thanks for starting the discussion - I had just mentioned proposing something on the servant IRC channel, but this might be the better place.

Some ideas follow. I'll update this list with input from others and then we can pick one or two of them two actually submit.

# Better error messages

We have quite bad error messages during compilation, in a wide variety of contexts. With custom type errors (and to a lesser degree without) we could go from the current horror, to an Elm-like user-friendliness. Some error messages can be quite easily improved. However, the primary source of type errors - mismatches between an API type and the value provided (between description and implementation) - is a quite involved technical challenge, as it requires a type-level minimal diffing between types expected, and provided, along with enough context for the error to make sense to the user, without slowing compilation too much.

# Making servant-auth great

TODO

**Comment by saurabhnanda** [comment]
> We have quite bad error messages during compilation, in a wide variety of contexts. With custom type errors (and to a lesser degree without) we could go from the current horror, to an Elm-like user-friendliness. Some error messages can be quite easily improved. However, the primary source of type errors - mismatches between an API type and the value provided (between description and implementation) - is a quite involved technical challenge, as it requires a type-level minimal diffing between types expected, and provided, along with enough context for the error to make sense to the user, without slowing compilation too much.

What about merging servant-generic into core servant, so that solving this problem become easier AND it is possible to get named routes easily?

**Comment by 3noch** [comment]
@saurabhnanda That's not a bad idea. I would much rather use the servant-generic approach but it's not supported enough at this point.

**Comment by alpmestan** [comment]
@wisn We'd definitely be thrilled to have a student work on servant or something servant related, and using this issue to discuss interesting project ideas is perfectly fine.

As a first filter to "apply" to only retain ideas that are likely to be selected, we have to remember that votes are made by mentors of other Haskell SoC projects and therefore the project must appeal to the "wider haskell community". I'm not sure "better error messages" fits that. Having a full-featured servant-auth that seamlessly supports 5+ common auth schemes is better in that regard, but not perfect either.

If anyone has other ideas than those cited so far, please go ahead.

**Comment by jkarni** [comment]
(Adding this separately since I realized it should be made to be `servant` independent for maximum effect, but I still would love feedback!)

# A language for combining requests

One of the downsides of standard REST applications is that each endpoint must
be queried separately, and without further processing. This introduces a
problem with extra roundtrips, and therefore latency, as well as consuming
extra bandwith; or else proliferation of endpoints, which introduce burdens on
server and client developers. For example:

    a) If I (as the client) know a user's name, and want to know their address,
    and an API only exposes an endpoint to query IDs by name, and one to query
    address by ID, I need to make one request to retrieve the user's name, wait
    for the response, and only then make the second request. 

    b) If I want to delete all my photos, but the API only exposes an endpoint to
    get all photos, and one to delete photo by ID, I need to make one request,
    wait for the response, and then another N requests, where N is the number
    of photos I have.

    c) If I want only a list of the titles I gave my photos, but not the photos
    themselves, but an API only exposes an endpoint to get all photo IDs, and
    one to get the photo's title, the photo itself, as well as extra metadata,
    I will have to receive responses with a lot of data I don't need.

GraphQL addresses some of these issues, at the cost of incompatibility with
existing APIs. Instead, we'd like to try out defining a simple language to
solve the problems above with minimal modifications to existing servers. (b)
might look like:

```
for photoid in GET@photos.id:
    DELETE@photo/$photoid
```

This project would define the language, and add support for it in the form of a
proxy or Wai middleware, and client support

The language we develop ought to have static guarantees with respect to not
only termination, but indeed worst-case resource usage. This project will
therefore involve a little reading in automatic static cost analysis.

**Comment by jkarni** [comment]
> What about merging servant-generic into core servant, so that solving this problem become easier AND it is possible to get named routes easily?

I'd be okay with that, if the current `:<|>`-based system were still available (it's easier to work with for many purposes). 

Should I change the description accordingly? (Thumbs up: yes; thumbs down: no)

**Comment by alpmestan** [comment]
When's the dealdine for project ideas? In 10 days?

**Comment by wisn** [comment]
@alpmestan https://developers.google.com/open-source/gsoc/timeline

**Comment by alpmestan** [comment]
@wisn right but I'm not sure whether we really want all our big ideas ready and listed on the summer of haskell page, or whether getting that ready in time for student applications is enough.

**Comment by wisn** [comment]
@alpmestan You guys may discuss till 18th then choose several ideas to be submitted to HSoC repository. Don't forget that each idea need a mentor. I will be back on 16th.

**Comment by jkarni** [comment]
Added `empiricus` entry.

**Comment by alpmestan** [comment]
Wrote a few sentences to describe what we (well, I) have in mind for the servant-auth proposal.

**Comment by alpmestan** [comment]
@wisn Should we submit our ideas to the SoC repo or will you?

**Comment by alpmestan** [comment]
@jkarni @phadej It feels to me like the idea #1 is a bit underspecified. Should I submit only #2 and #3?

**Comment by alpmestan** [comment]
Submitted the servant-auth idea at https://github.com/haskell-org/summer-of-haskell/pull/53.
