### ISSUE TITLE
is there any way to conditionally load api

### ISSUE THREAD

**Issue by leptonyu** [haskell-servant/servant#881]
suppose i have two apis a and b, and i want to load b conditionally depends on some configuration

```Haskell
type API = aAPI :<|> bAPI

-- how can i disable bAPI and let API become following by changing configuration as disable.b.api=true

type API = aAPI

```

any ideas to solve this problem or make it not a problem? thank you.

**Comment by saurabhnanda** [comment]
Is the configuration read only at startup time? Not changed dynamically
during runtime? We had the same requirement. I'll post a code snippet from
my desktop.

**Comment by saurabhnanda** [comment]
@leptonyu if you need to conditionally load an API basic on static configuration (i.e. config that doesn't change during the runtime of the program):

```
  let
    envName_ = config ^. envName
    baseServer = enter (NT appmToServantM) combinedServer
    serverApplication = if (isDevEnv envName_)
                        then serveWithContext (Proxy :: Proxy (Routes :<|> "lambda" :> "assets" :> Raw))
                                              appContext
                                              (baseServer :<|> (serveDirectoryFileServer "dist"))
                        else serveWithContext (Proxy :: Proxy Routes)
                                              appContext
                                              (enter (NT appmToServantM) combinedServer)
```

Does the snippet give you enough context of how to solve this for use-case?

**Comment by leptonyu** [comment]
@saurabhnanda Thank you, that's what i want, at startup time, not runtime.

**Comment by alpmestan** [comment]
More generally, you can play `reflection`-style tricks to tweak the API type at the last minute, by reflecting some value to types and using it to affect the API type on which you'll actually call `serve`. An example of this is how to serve an entire API type under some arbitrary runtime-provided string prefix, and you can see one way to achieve that [here](https://github.com/alpmestan/servant-prefix/blob/master/servant-prefix.hs).

**Comment by leptonyu** [comment]
@alpmestan Thanks, `reflection`-style tricks inspired me to complete my target. 

```Haskell
type API api = (Proxy api, BaseContext -> Server api)
type MaybeAPI api = (Text, Bool, API api)
type MkApplication = BaseContext -> Application
type ApiToApplication = forall s. (HasServer s '[BaseContext], HasSwagger s) => API s -> MkApplication
type SwaggerAPI = SwaggerSchemaUI "swagger-ui" "swagger.json"
mkServe :: (HasServer api '[BaseContext], HasSwagger api) => API api -> BaseContext -> Application
mkServe ps c | isSwaggerOn c = go (swagger ps) c
             | otherwise     = go ps c
             where isSwaggerOn c = (fromMaybe True $ evalProp c "swagger.enable") && evalProp c "mode" /= Just Production
                   go :: (HasServer api '[BaseContext]) => API api -> BaseContext -> Application
                   go (p,s)    c = serveWithContext p (c :. EmptyContext) $ s c

addApi :: (HasServer api '[BaseContext], HasSwagger api, HasServer new '[BaseContext], HasSwagger new)
       => API api -> MaybeAPI new -> ApiToApplication -> MkApplication
addApi a (key, def, b) f c | fromMaybe def $ evalProp c key = f (a `ap` b) c
                           | otherwise = f a c
                           where ap :: API a -> API b -> API (a :<|> b)
                                 ap (_,a) (_,b) = (Proxy, \c -> a c:<|>b c)

mkApplication :: MkApplication
mkApplication = userModule `addApi` wechatModule $ \a -> addApi a bearychatModule mkServe
```

The key point is use `ApiToApplication` to accept any api, then i can implement `addApi` to feed `ApiToApplication` with different apis, depends on the configuration. and i also made swagger loaded conditionally on config `swagger.enable`
