### ISSUE TITLE
Add travis testing of stack configurations

### ISSUE THREAD

**Issue by mgsloan** [haskell-servant/servant#888]
I noticed that https://github.com/haskell-servant/servant/blob/master/stack.yaml is broken, and certainly has been for some time.  I find this surprising, it is broken in ways that cause the build to immediately fail, and this would always be the case.  Namely, the `aeson-compat` version specified by the snapshot is not compatible with the specified `aeson` version.

If you do not want to have CI do both stack and cabal builds, at least run `stack build --dry-run --system-ghc`.  This will usually run very quickly and will tell you if there are version constraint problems.

**Comment by phadej** [comment]
Will do. Though I will leave only single `stack.yaml` in place

**Comment by mgsloan** [comment]
I am in favor of removing old configs unless there is a strong reason to keep them :+1:  One `stack.yaml` should do.
