### ISSUE TITLE
Limitations of typeclass-based doc generation

### ISSUE THREAD

**Issue by seagreen** [haskell-servant/servant#894]
Typeclass based doc generation works well for some things, but has some limitations.

For instance, an endpoint like `addOne :: Int -> Handler Int` is never going to be well suited to typeclass based doc generation. That's just a toy example, but for some servers which have a lot of responses that depend on the input, and which need a lot of custom notes, a more explicit way of building docs might be better.

Does anyone else have thoughts on this, or know of someone who's already tried it?

**Comment by jkarni** [comment]
Closing since it's not clear what else we can do besides `Description`. Please re-open if you think this was a mistake.
