### ISSUE TITLE
ExceptT

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#91]
Now that the world is moving towards `ExceptT` (cf. the `errors` package), we probably should too.

**Comment by christian-marie** [comment]
What's the rationale for ExceptT in favor of MonadThrow?

**Comment by jkarni** [comment]
I *suspect* MonadThrow will make everything too ambiguous (for the `Nat` machinery in particular). But we should check.

**Comment by jkarni** [comment]
I actually no longer think this is the case. But we need either MonadCatch or MonadError (MonadThrow isn't enough).

**Comment by jkarni** [comment]
Just as an update - a few weeks back I did try a class constraint. It won't work without making everything else uglier.

In other news, this isn't worth losing backwards-compatibility with ghc 7.8. Closing.
