### ISSUE TITLE
Nothing is translated to null

### ISSUE THREAD

**Issue by paweln1986** [haskell-servant/servant#914]
When I have API defined like:
```haskell
type Api = "user" :> Capture "name" Text :> Get '[JSON] (Maybe User)
```
servant don't treat Nothing as 404 but return null
```
curl -H 'Content-type: application/json' localhost:3000/user/Alice

< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Date: Sat, 03 Mar 2018 16:02:32 GMT
< Server: Warp/3.2.13
< Content-Type: application/json;charset=utf-8
< 
* Connection #0 to host localhost left intact
null%                                                   
```
Is it possible to create general handlers for Maybe, now I have to manually throw ServantErrors.
It would be good if servant translate Nothing into 404.

**Comment by alpmestan** [comment]
I see the point you're making, but the response type advertised after the verb (`Maybe User` in your example) is supposed to be whatever the handler will return in the successful case, that is if we don't encounter any error. The way to achieve what you want with servant is to indeed throw an error. Usually I do this by using a custom monad which contains `ExceptT ApplicationError` in the stack, where `ApplicationError` is something like:

``` haskell
data ApplicationError
  = UserNotFound UserId
  | ProductNotFound Product
  | ...
```

and I then convert values of that type to HTTP error responses (`ServantErr` values) using `hoistServer`.

Another way to achieve what you want would also be to use [servant-checked-exceptions](https://hackage.haskell.org/package/servant-checked-exceptions). In both cases though, the library requires you to say `Get '[JSON] User` and drop the `Maybe`.

Note that this would all become a little more explicit and symmetric once we get around to executing #841.

**Comment by jkarni** [comment]
Closing, please re-open if you think this was a mistake.
