### ISSUE TITLE
make safeLink safer

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#92]
Andres pointed out that:
```
type MyAPI = Capture "id" Int :> Get '[JSON] Int
GHCI> safeLink (Proxy :: Proxy MyAPI) (Proxy :: Proxy ("foo" :> Get '[JSON] Int)
foo
```
Not good. To be truly safe, only `Capture x y` should match `Capture z y`. The `Int` should be provided as an argument.

**Comment by christian-marie** [comment]
Not sure how to regression test this without doctests, which is really nasty. Do we have any better ideas there?

**Comment by tvh** [comment]
What about `hint`?

```.haskell
runInterpreter $ do
    setImports ["Servant.API","Data.Proxy"]
    typeChecks "safeLink (Proxy :: Proxy (Capture \"id\" Int :> Get '[JSON] Int)) (Proxy :: Proxy (\"foo\" :> Get '[JSON] Int)"
````

**Comment by christian-marie** [comment]
That's certainly cleaner than the current approach.

**Comment by mpickering** [comment]
One way to write tests to make sure certain expressions don't type check is to use `-fdefer-type-errors`.

**Comment by jkarni** [comment]
:+1: on `defer-type-errors`.

**Comment by christian-marie** [comment]
Sounds good to me!

**Comment by jkarni** [comment]
Done is #95
