### ISSUE TITLE
Add path prefix in client part

### ISSUE THREAD

**Issue by s9gf4ult** [haskell-servant/servant#93]
Now 

```haskell
data BaseUrl = BaseUrl
  { baseUrlScheme :: Scheme -- ^ URI scheme to use
  , baseUrlHost :: String   -- ^ host (eg "haskell.org")
  , baseUrlPort :: Int      -- ^ port (eg 80)
  } deriving (Show, Eq, Ord, Generic)
```

and I propose to

```haskell
data BaseUrl = BaseUrl
  { baseUrlScheme :: Scheme -- ^ URI scheme to use
  , baseUrlHost :: String   -- ^ host (eg "haskell.org")
  , baseUrlPath :: [String] -- ^ api path prefix (eg "/apiv1")
  , baseUrlPort :: Int      -- ^ port (eg 80)
  } deriving (Show, Eq, Ord, Generic)
```

This would be very usable when servant service is mounted as Yesod subsite for example. Like: 

```
/apiv1 SomeApiR WaiSubsite getSomeApi
```

I beleive it is very common use case.

This is also required to add changes to `servant-jquery` package to generate right pathes in JS code.

**Comment by jkarni** [comment]
Good idea

**Comment by alpmestan** [comment]
Yup, looks good to me. I think it can go in for the next major release. I'm not saying this will be in a long time, just that we're preparing a minor release with non-breaking changes only, which should go out sometimes this week I guess.

@s9gf4ult Do you feel like putting a PR together?

**Comment by s9gf4ult** [comment]
Yes, I think I will PR this feature.

**Comment by kosmikus** [comment]
What's the problem in just adding the prefix to the API type?

**Comment by jkarni** [comment]
@kosmikus good point

**Comment by s9gf4ult** [comment]
No, it will not work, because when you mount your servant service as Yesod subsite in path 

```
/apiv1 SomeApiR WaiSubsite getSomeApi
```

And your API looks like 

```haskell
type SomeApi = "prefix" :> "users" :> Get '[JSON] [User]
```

Then full path will be 

```
/apiv1/prefix/users
```

Not 

```
/prefix/users
```

This is the case I deal with right now.

**Comment by jkarni** [comment]
But I think kosmikus' point was that you can just do `type ClientApi = "apiv1" :> SomeApi`, and call `client` on `ClientApi` instead.

**Comment by s9gf4ult** [comment]
Can I prefix all parts of `:<|>` operator somehow?

**Comment by jkarni** [comment]
Yup. `"prefix" :> (a :<|> b)` will do it.

**Comment by s9gf4ult** [comment]
Wow, I must try it.

**Comment by s9gf4ult** [comment]
You right! It works!

**Comment by Elewyth** [comment]
While @jkarni 's solution works perfectly fine if you know the path at compile-time, it doesn't seem easy to do with a dynamic prefix at runtime. In my case I am trying to write a reusable module which serves some functionality at `/foo`, but can be used in as part of any other server at e.g. `/service1/foo` or `/service2/foo`.

I found the following example: https://github.com/alpmestan/servant-prefix. Does anyone know of a simpler solution, or if this could be made into a servant feature?

**Comment by alpmestan** [comment]
You really need to do something like `servant-prefix` there if you only discover the string at runtime. You could alternatively perhaps investigate creating a `Middleware` that tweaks a servant app (or any WAI `Application really) to make it run under some prefix.
