### ISSUE TITLE
How to deal with MonadUnliftIO?

### ISSUE THREAD

**Issue by nmattia** [haskell-servant/servant#950]
`ClientM` is basically a `ReaderT` wrapped around an `ExceptT`:

``` haskell
newtype ClientM a = ClientM
  { unClientM :: ReaderT ClientEnv (ExceptT ServantError IO) a }
  deriving ( Functor, Applicative, Monad, MonadIO, Generic
           , MonadReader ClientEnv, MonadError ServantError, MonadThrow
           , MonadCatch)
```

unfortunately the latest version of `resourcet` redefines `runResourceT` to run in `MonadUnliftIO`:
``` haskell
runResourceT :: MonadUnliftIO m => ResourceT m a -> m a
```

which does not allow `ExceptT`. Basically this makes it impossible (or very hard) to have `HasClient` instances with
``` haskell
type Client foo =  ResourceT (ClientM bar)
```

Right now I'm tempted to replace the `Client` with `ResourceT (ClientM' bar)` where `ClientM'` is basically the same as `ClientM` except that it returns an `Either` directly:

``` haskell
newtype ClientM a = ClientM
  { unClientM :: ReaderT ClientEnv IO (Either ServantError a) }
```

but I might be missing an easier solution. Those who were faced with this, how did you work around it?

**Comment by alpmestan** [comment]
@nmattia Does this answer your question?

**Comment by nmattia** [comment]
@alpmestan all good, thanks!

**Comment by docmoxie** [comment]
@nmattia how did you end up solving this?

**Comment by k-bx** [comment]
This topic explains in detail how to not use ExceptT-based monad from Servant. One small addition: I recommend not using newtype, but just doing the type alias. https://harporoeder.com/posts/servant-13-reader-io/

What this had let me do was to add a `safeguard` wrapper for my handlers, which would print a relatively nice call-stack every time my handler throws an `error`-based exception.

```haskell
-- | Safeguard
sg :: HasCallStack => AppM a -> AppM a
sg act = catchAny act onErr
  where
    onErr e = do
      logError $
        display $
        "Safeguard caught an exception: " <> tshow e <> ". Call stack: " <>
        S.toText (prettyCallStack callStack)
      throwM e

accountCurrentlyReading ::
     HasCallStack => P.Entity User -> AppM AT.CurrentlyReading
accountCurrentlyReading user =
  sg $ do
    ...
```

Error looks like this:

```
Safeguard caught an exception: Couldn't find object
CallStack (from HasCallStack):
  error, called at src/MyProj/AppUtils.hs:34:20 in MyProj-0.1.0.0-74GOROh3LCnIQ02kjUtntc:MyProj.AppUtils
  mustFindE, called at src/MyProj/AppUtils.hs:38:20 in MyProj-0.1.0.0-74GOROh3LCnIQ02kjUtntc:MyProj.AppUtils
  mustFindME, called at src/MyProj/Handlers.hs:591:16 in MyProj-0.1.0.0-74GOROh3LCnIQ02kjUtntc:MyProj.Handlers
  accountCurrentlyReading, called at src/MyProj/Routes.hs:248:38 in MyProj-0.1.0.0-74GOROh3LCnIQ02kjUtntc:MyProj.Routes. Call stack: CallStack (from HasCallStack):
  sg, called at src/MyProj/Handlers.hs:570:3 in MyProj-0.1.0.0-74GOROh3LCnIQ02kjUtntc:MyProj.Handlers
  accountCurrentlyReading, called at src/MyProj/Routes.hs:248:38 in MyProj-0.1.0.0-74GOROh3LCnIQ02kjUtntc:MyProj.Routes
```

E.g. not only you can see the handler's name, you see the line where the object wasn't found.

**Comment by Profpatsch** [comment]
This issue really is a life-saver, thank you @k-bx for linking the blog post. I’ve been struggling with this so much.

**Comment by k-bx** [comment]
You're welcome!
