### ISSUE TITLE
Servant API to Server Type

### ISSUE THREAD

**Issue by RobertFischer** [haskell-servant/servant#957]
I would find it very useful to have a type-level function that took in an API and an execution monad, and generated the resulting server implementation type. When you have a composite API, the mapping between the API and the server types is both non-trivial to get right (precedence is tricky), and the resulting type is usually pretty hard to read. Even worse, when you make a change in the API, you then have to change the server type and then the server implementation, but that shouldn't be necessary -- the server type *should* be derivable from the API that the server fulfills.

I'm not sure if this is even possible (although it seems like it should be), or how to go about implementing it (PolyKinds something something?), but if I could get some guidance on how to implement the approach, I'd be happy to take a swing at implementing such a thing as both an educational and a productive exercise.

**Comment by alpmestan** [comment]
That's exactly what the `ServerT` type family does, no?

``` haskell
*Servant λ> :set -XTypeOperators -XDataKinds
*Servant λ> type API = Get '[JSON] Int :<|> Capture "id" Int :> Post '[JSON] NoContent
*Servant λ> :kind ServerT
ServerT :: k -> (* -> *) -> *
*Servant λ> :kind! ServerT API IO
ServerT API IO :: *
= IO Int :<|> (Int -> IO NoContent)
```

**Comment by alpmestan** [comment]
Note that you can use the `servant-flatten` package to get completely flat endpoint descriptions, which usually are much more readable, in case the solution above is not satisfactory.
