### ISSUE TITLE
Customized ReqBody

### ISSUE THREAD

**Issue by dawei-dev** [haskell-servant/servant#970]
I'm using servant-client to send `_bulk` API to a elasticsearch server.
The ES API requires that the final line of data must end with a newline character `\n`.

My type is:

```
type ESAPI = "testindex"
  :> "doc"
  :> ReqBody '[JSON] SomeData
  :> Put '[JSON] Value
```

My question is:
1: Will SomeData be turned into a string? Something like the `-d` flag in a `curl` command?
2: Since I have to add a newline at the end, is there a way to customize how SomeData is turned into a String?

Note: Seems like I can achieve this by customized Content-type?

**Comment by alpmestan** [comment]
Yes, you could achieve this with a custom content type that does everything like JSON but adds a newline to everything. Or you could provide a `newtype WithNewline a = WithNewline a` whose `ToJSON` instance would add that newline. Or perhaps some other way?

**Comment by phadej** [comment]
I'd do

```haskell
"endpoint" :> Get '[WithNewline JSON] MyValue
```

as then you could easily append newline to resulting `ByteString`, but that's all different variations on the same idea: use `newtype`.
