### ISSUE TITLE
Move Servant.Utils.Links -> Servant.Links

### ISSUE THREAD

**Issue by phadej** [haskell-servant/servant#997]
Leaving old module name as deprecated for few releases.

The `Servant.Utils.Enter` is (almost) gone, #996. And there aren't other `Utils` (and IMHO doesn't need to be).

:+1: / :-1: ?

**Comment by alpmestan** [comment]
Yes!!!

Servant.API, Servant.Server, Servant.Client, Servant.Links. It just makes sense. =) I was thinking about this the other day in fact.
